<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020i" Comment="DigitalInput_I1 auf DigitalOutput_Q1; E_PULSE; Impulsformend" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-10946.67" y="393.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_PULSE" Type="E_PULSE" x="-12406.67" y="573.33">
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" x="-13873.33" y="346.67">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_STOPWATCH" Type="E_STOPWATCH" x="-13833.33" y="1453.33">
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" x="-15100" y="1680">
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" x="-16380" y="1293.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="E_PULSE.CNF" Destination="DigitalOutput_Q1.REQ" dx1="406.67"/>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_PULSE.REQ" dx1="373.33"/>
			<Connection Source="DigitalInput_I2.IND" Destination="E_SWITCH.EI" dx1="273.33"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_STOPWATCH.START" dx1="286.67"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_STOPWATCH.STOP" dx1="306.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_PULSE.Q" Destination="DigitalOutput_Q1.OUT" dx1="286.67"/>
			<Connection Source="E_STOPWATCH.TD" Destination="E_PULSE.PT" dx1="326.67"/>
			<Connection Source="DigitalInput_I2.IN" Destination="E_SWITCH.G" dx1="273.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
