<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_087" Comment="Beispiel für E_DEMUX" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0&#10;   &#10;Beispiel für E_CTD&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 93" >
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IX" x="-7900" y="100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_DEMUX" Type="E_DEMUX" x="-6100" y="300">
			<Parameter Name="K" Value="UINT#3"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="E_DEMUX.EI"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
