<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_030" Comment="LED_PWM Blinkende LED" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0" >
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_DI" Type="logiBUS_8_DI" x="-3280" y="-1066.67">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="isobus::GLOBAL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="isobus::ID_NULL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I1" Value="'App.Control.functions.DigitalInput_I1'"/>
			<Parameter Name="DigitalInput_I2" Value="'App.Control.functions.DigitalInput_I2'"/>
			<Parameter Name="DigitalInput_I3" Value="'App.Control.functions.DigitalInput_I3'"/>
			<Parameter Name="DigitalInput_I4" Value="'App.Control.functions.DigitalInput_I4'"/>
			<Parameter Name="DigitalInput_I5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_PWM" Type="logiBUS_1_LED_PWM" x="-3466.67" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="LED_DO::Output_Q1"/>
			<Parameter Name="u16ObjId" Value="isobus::ID_NULL"/>
			<Parameter Name="LED_5HZ" Value="'App.Control.functions.LED_Q1_5HZ'"/>
			<Parameter Name="LED_1HZ" Value="'App.Control.functions.LED_Q1_1HZ'"/>
			<Parameter Name="LED_breathing_05HZ" Value="'App.Control.functions.LED_Q1_breathing_05HZ'"/>
			<Parameter Name="LED_ON" Value="'App.Control.functions.LED_Q1_ON'"/>
		</FB>
	</SubAppNetwork>
</SubAppType>
