<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_080c" Comment="Beispiel für E_CTU" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0&#10;   &#10;Beispiel für E_CTU&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 92" >
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-4800" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="IE" x="-10600" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_CTU" Type="E_CTU" x="-6200" y="-800">
			<Parameter Name="PV" Value="UINT#5"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="IE" x="-7700" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_PERMIT" Type="E_PERMIT" x="-8000" y="-800">
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" x="-9100" y="-800">
		</FB>
		<Comment Comment="Die Kombination von T_FF und PERMIT halbiert die Events.&#10;"  x="-9000" y="-1200" width="1500" height="300"/>
		<EventConnections>
			<Connection Source="E_CTU.CUO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_CTU.RO" Destination="DigitalOutput_Q1.REQ" dx1="286.67"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_CTU.R" dx1="273.33"/>
			<Connection Source="E_T_FF.EO" Destination="E_PERMIT.EI"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_T_FF.CLK"/>
			<Connection Source="E_PERMIT.EO" Destination="E_CTU.CU"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTU.Q" Destination="DigitalOutput_Q1.OUT" dx1="453.33"/>
			<Connection Source="E_T_FF.Q" Destination="E_PERMIT.PERMIT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
