<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_049" Comment="DigitalInput_I1-_I4 auf DigitalOutput_Q1-_Q4" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-1300" y="-700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" x="-4400" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" x="-1300" y="800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" x="-4400" y="700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="QX" x="-1300" y="2100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I3" Type="IX" x="-4400" y="2000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="QX" x="-1300" y="3300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I4" Type="IX" x="-4400" y="3200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="DigitalInput_I2.IND" Destination="DigitalOutput_Q2.REQ"/>
			<Connection Source="DigitalInput_I3.IND" Destination="DigitalOutput_Q3.REQ"/>
			<Connection Source="DigitalInput_I4.IND" Destination="DigitalOutput_Q4.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="DigitalInput_I2.IN" Destination="DigitalOutput_Q2.OUT"/>
			<Connection Source="DigitalInput_I3.IN" Destination="DigitalOutput_Q3.OUT"/>
			<Connection Source="DigitalInput_I4.IN" Destination="DigitalOutput_Q4.OUT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
