<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_049" Comment="DigitalInput_I1-_I4 auf DigitalOutput_Q1-_Q4" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-1320" y="-820">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" x="-4386.67" y="-933.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" x="-1320" y="673.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" x="-4386.67" y="560">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="QX" x="-1320" y="2060">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I3" Type="IX" x="-4386.67" y="1946.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="QX" x="-1320" y="3340">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I4" Type="IX" x="-4386.67" y="3226.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="DigitalOutput_Q1.REQ" dx1="1200"/>
			<Connection Source="DigitalInput_I2.IND" Destination="DigitalOutput_Q2.REQ" dx1="1200"/>
			<Connection Source="DigitalInput_I3.IND" Destination="DigitalOutput_Q3.REQ" dx1="1200"/>
			<Connection Source="DigitalInput_I4.IND" Destination="DigitalOutput_Q4.REQ" dx1="1200"/>
			<Connection Source="DigitalInput_I3.INITO" Destination="DigitalOutput_Q3.INIT" dx1="1200"/>
			<Connection Source="DigitalInput_I4.INITO" Destination="DigitalOutput_Q4.INIT" dx1="1200"/>
			<Connection Source="DigitalInput_I2.INITO" Destination="DigitalOutput_Q2.INIT" dx1="1200"/>
			<Connection Source="DigitalInput_I1.INITO" Destination="DigitalOutput_Q1.INIT" dx1="1200"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT" dx1="1200"/>
			<Connection Source="DigitalInput_I2.IN" Destination="DigitalOutput_Q2.OUT" dx1="1200"/>
			<Connection Source="DigitalInput_I3.IN" Destination="DigitalOutput_Q3.OUT" dx1="1200"/>
			<Connection Source="DigitalInput_I4.IN" Destination="DigitalOutput_Q4.OUT" dx1="1200"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
