<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_031" Comment="LED Strip" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_CLK_I1" Type="IE" x="-5733.33" y="626.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="IE" x="-5733.33" y="-326.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="strip_set_pixel" Type="strip_set_pixel" x="-1066.67" y="400">
			<Parameter Name="index" Value="0"/>
		</FB>
		<FB Name="hsv2rgb" Type="hsv2rgb" x="-3200" y="740">
			<Parameter Name="hue" Value="100"/>
			<Parameter Name="saturation" Value="100"/>
			<Parameter Name="value" Value="100"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="strip_set_pixel.clear" dx1="2553.33"/>
			<Connection Source="hsv2rgb.CNF" Destination="strip_set_pixel.set_pixel" dx1="1413.33"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="hsv2rgb.REQ" dx1="873.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="hsv2rgb.r" Destination="strip_set_pixel.red" dx1="746.67"/>
			<Connection Source="hsv2rgb.g" Destination="strip_set_pixel.green" dx1="746.67"/>
			<Connection Source="hsv2rgb.b" Destination="strip_set_pixel.blue" dx1="746.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
