<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_001_P2" Comment="DigitalInput_I1 auf DigitalOutput_Q1, mit Plug and Socket">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IXP" Comment="" x="-4533.333333333334" y="-933.3333333333334">
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QXP" Comment="" x="-1466.6666666666667" y="-933.3333333333334">
		</FB>
		<FB Name="AX_X_TO_BOOL" Type="AX_X_TO_BOOL" Comment="" x="-4000.0" y="0.0">
		</FB>
		<FB Name="AX_BOOL_TO_X" Type="AX_BOOL_TO_X" Comment="" x="-2133.3333333333335" y="0.0">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="1073.3333333333335" dx2="1073.3333333333335" dy="0.0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1.INITO" Destination="DigitalOutput_Q1.INIT" Comment=""/>
			<Connection Source="AX_X_TO_BOOL.IND" Destination="AX_BOOL_TO_X.REQ" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AX_X_TO_BOOL.IN" Destination="AX_BOOL_TO_X.OUT" Comment=""/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_X_TO_BOOL.AX_IN" Comment="" dx1="80.0" dx2="80.0" dy="513.3333333333334"/>
			<Connection Source="AX_BOOL_TO_X.AX_OUT" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="80.0" dx2="80.0" dy="-513.3333333333334"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
