<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020b" Comment="DigitalInput_I1 auf DigitalOutput_Q1; TON Einschaltverzögert; aufgelöst">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-3520" y="453.34">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-8726.67" y="453.34">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" Comment="" x="-7480" y="800">
		</FB>
		<FB Name="E_RS" Type="E_RS" Comment="" x="-4873.33" y="566.67">
		</FB>
		<FB Name="E_DELAY" Type="E_DELAY" Comment="" x="-6013.33" y="680">
			<Parameter Name="DT" Value="T#2S" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="200">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="3880">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1.IND" Destination="E_SWITCH.EI" Comment="" dx1="246.67"/>
			<Connection Source="E_RS.EO" Destination="DigitalOutput_Q1.REQ" Comment=""/>
			<Connection Source="E_SWITCH.EO1" Destination="E_DELAY.START" Comment="" dx1="526.67"/>
			<Connection Source="E_DELAY.EO" Destination="E_RS.S" Comment=""/>
			<Connection Source="E_SWITCH.EO0" Destination="E_DELAY.STOP" Comment=""/>
			<Connection Source="E_SWITCH.EO0" Destination="E_RS.R" Comment="" dx1="306.67" dx2="246.67" dy="-366.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="E_SWITCH.G" Comment=""/>
			<Connection Source="E_RS.Q" Destination="DigitalOutput_Q1.OUT" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
