<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020b" Comment="DigitalInput_I1 auf DigitalOutput_Q1; TON Einschaltverzögert; aufgelöst" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-3520" y="453.34">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" x="-8726.67" y="453.34">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" x="-7480" y="800">
		</FB>
		<FB Name="E_RS" Type="E_RS" x="-4873.33" y="566.67">
		</FB>
		<FB Name="E_DELAY" Type="E_DELAY" x="-6013.33" y="680">
			<Parameter Name="DT" Value="T#2S"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="E_SWITCH.EI" dx1="246.67"/>
			<Connection Source="E_RS.EO" Destination="DigitalOutput_Q1.REQ" dx1="486.67"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_DELAY.START" dx1="526.67"/>
			<Connection Source="E_DELAY.EO" Destination="E_RS.S" dx1="266.67"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_DELAY.STOP" dx1="406.67"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_RS.R" dx1="306.67" dx2="246.67" dy="-366.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="E_SWITCH.G" dx1="313.33"/>
			<Connection Source="E_RS.Q" Destination="DigitalOutput_Q1.OUT" dx1="486.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
