<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_015a" Comment="Object Pointer umschalten -- 3-fach">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_F1_UP" Type="IE" Comment="" x="-4533.33" y="-1133.33">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="SoftKey_F2_UP" Type="IE" Comment="" x="-4533.33" y="226.67">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_UINT_TO_UDINT" Type="F_UINT_TO_UDINT" Comment="" x="-2800" y="0">
			<Parameter Name="IN" Value="Button_A1" Comment=""/>
		</FB>
		<FB Name="F_SEL_E_3" Type="F_SEL_E_3" Comment="" x="-1133.33" y="-906.67">
			<Parameter Name="IN0" Value="ID_NULL" Comment=""/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" Comment="" x="800" y="-1020">
			<Parameter Name="u16ObjId" Value="ObjectPointer_P1" Comment=""/>
		</FB>
		<FB Name="SoftKey_F3_UP" Type="IE" Comment="" x="-4533.33" y="1473.33">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_UINT_TO_UDINT_1" Type="F_UINT_TO_UDINT" Comment="" x="-2833.33" y="566.67">
			<Parameter Name="IN" Value="Button_A2" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="SoftKey_F1_UP.INIT" Comment="" dx1="1113.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="SoftKey_F2_UP.INIT" Comment="" dx1="1206.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Q_NumericValue.INIT" Comment="" dx1="3733.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="F_UINT_TO_UDINT.REQ" Comment="" dx1="1933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL_E_3.CNF" Destination="Q_NumericValue.REQ" Comment=""/>
			<Connection Source="SoftKey_F1_UP.IND" Destination="F_SEL_E_3.REQ0" Comment="" dx1="1413.33"/>
			<Connection Source="SoftKey_F2_UP.IND" Destination="F_SEL_E_3.REQ1" Comment="" dx1="280"/>
			<Connection Source="INIT" Destination="SoftKey_F2_UP_1.INIT" Comment="" dx1="2133.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_F2_UP_1.IND" Destination="F_SEL_E_3.REQ2" Comment="" dx1="560"/>
			<Connection Source="INIT" Destination="F_UINT_TO_UDINT_1.REQ" Comment="" dx1="2946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_UINT_TO_UDINT.OUT" Destination="F_SEL_E_3.IN1" Comment="" dx1="373.33" dx2="373.33" dy="0"/>
			<Connection Source="F_SEL_E_3.OUT" Destination="Q_NumericValue.u32NewValue" Comment="" dx1="606.67"/>
			<Connection Source="F_UINT_TO_UDINT_1.OUT" Destination="F_SEL_E_3.IN2" Comment="" dx1="520"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
