<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_015a" Comment="Object Pointer umschalten -- 3-fach" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_F1_UP" Type="IE" x="-4533.33" y="-1133.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="SoftKey_F2_UP" Type="IE" x="-4533.33" y="226.67">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_UINT_TO_UDINT" Type="F_UINT_TO_UDINT" x="-2800" y="0">
			<Parameter Name="IN" Value="Button_A1"/>
		</FB>
		<FB Name="F_SEL_E_3" Type="F_SEL_E_3" x="-1133.33" y="-906.67">
			<Parameter Name="IN0" Value="ID_NULL"/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" x="800" y="-1020">
			<Parameter Name="u16ObjId" Value="ObjectPointer_P1"/>
		</FB>
		<FB Name="SoftKey_F3_UP" Type="IE" x="-4533.33" y="1473.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_UINT_TO_UDINT_1" Type="F_UINT_TO_UDINT" x="-2833.33" y="566.67">
			<Parameter Name="IN" Value="Button_A2"/>
		</FB>
		<EventConnections>
			<Connection Source="F_SEL_E_3.CNF" Destination="Q_NumericValue.REQ" dx1="613.33"/>
			<Connection Source="SoftKey_F1_UP.IND" Destination="F_SEL_E_3.REQ0" dx1="1413.33"/>
			<Connection Source="SoftKey_F2_UP.IND" Destination="F_SEL_E_3.REQ1" dx1="280"/>
			<Connection Source="SoftKey_F3_UP.IND" Destination="F_SEL_E_3.REQ2" dx1="446.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_UINT_TO_UDINT.OUT" Destination="F_SEL_E_3.IN1" dx1="360"/>
			<Connection Source="F_SEL_E_3.OUT" Destination="Q_NumericValue.u32NewValue" dx1="606.67"/>
			<Connection Source="F_UINT_TO_UDINT_1.OUT" Destination="F_SEL_E_3.IN2" dx1="520"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
