<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="eio_ueb" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2025-07-29">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="EInit" Comment="Initialization Request">
			</SubAppEvent>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="INITO" Type="EInit" Comment="Initialization Confirm">
			</SubAppEvent>
			<SubAppEvent Name="CNF" Type="Event" Comment="Execution Confirmation">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="QI" Type="BOOL" Comment="Input event qualifier"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="QO" Type="BOOL" Comment="Output event qualifier"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="eIX" Type="eIX" x="120" y="-546.67">
		</FB>
		<FB Name="eIXconfig" Type="eIXconfig" x="2100" y="300">
			<Parameter Name="FE" Value="TRUE"/>
			<Parameter Name="RE" Value="TRUE"/>
		</FB>
		<AdapterConnections>
			<Connection Source="eIX.eCONF" Destination="eIXconfig.eIX" dx1="366.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
