<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="page" Comment="Subapplication Type">
	<Identification Standard="61499-2"/>
	<VersionInfo Version="1.0" Author="franz" Date="2025-07-11"/>
	<CompilerInfo packageName="MyLib::sys::page"/>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF" Type="Event" Comment="Execution Confirmation"/>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="CbVtStatus" Type="isobus::UT::status::CbVtStatus" x="300" y="1400"/>
		<FB Name="E_D_FF" Type="iec61499::events::E_D_FF" x="1900" y="1500"/>
		<EventConnections>
			<Connection Source="CbVtStatus.IND" Destination="E_D_FF.CLK" dx1="480"/>
			<Connection Source="E_D_FF.EO" Destination="CNF" dx1="2653.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="CbVtStatus.qWsActive" Destination="E_D_FF.D" dx1="426.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
