<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_071b" Comment="WBSD auf UT ausgeben, Q1 Schalten wenn Speed &amp;gt;0">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="I_WBSD" Type="I_WBSD" Comment="" x="-5213.33" y="453.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="Q_NumericValue_WBSD" Type="Q_NumericValue" Comment="" x="-680" y="453.33">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_speed" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="1400" y="2300">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="GEN_PULSE_DIST" Type="signalprocessing::distance::GEN_PULSE_DIST" Comment="" x="-1600" y="2400">
			<Parameter Name="DIST_HIGH" Value="5000" Comment=""/>
			<Parameter Name="DIST_LOW" Value="5000" Comment=""/>
		</FB>
		<FB Name="E_D_FF" Type="E_D_FF" Comment="" x="300" y="2400">
		</FB>
		<EventConnections>
			<Connection Source="I_WBSD.IND" Destination="Q_NumericValue_WBSD.REQ" Comment=""/>
			<Connection Source="INIT" Destination="I_WBSD.INIT" Comment="" dx1="1760">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Q_NumericValue_WBSD.INIT" Comment="" dx1="4026.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="3473.33" dx2="3473.33" dy="0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="I_WBSD.IND" Destination="GEN_PULSE_DIST.REQ" Comment="" dx1="1086.67" dx2="1086.67" dy="0"/>
			<Connection Source="E_D_FF.EO" Destination="DigitalOutput_Q1.REQ" Comment=""/>
			<Connection Source="GEN_PULSE_DIST.CNF" Destination="E_D_FF.CLK" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="I_WBSD.WHEELBASEDMACHINESPEED" Destination="Q_NumericValue_WBSD.u32NewValue" Comment="" dx1="806.67"/>
			<Connection Source="I_WBSD.WHEELBASEDMACHINEDISTANCE" Destination="GEN_PULSE_DIST.DIST_IN" Comment="" dx1="786.67" dx2="786.67" dy="0"/>
			<Connection Source="E_D_FF.Q" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="280"/>
			<Connection Source="GEN_PULSE_DIST.Q" Destination="E_D_FF.D" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
