<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039b" Comment="Spiegelabfolge V2 mit Schrittkette" >
	<Identification Standard="61499-2" Description="Spiegelabfolge V2 mit Schrittkette  &#10;geeignet für hydraulisches Ringsystem 3/2 Wege Ventile  (z.B. Claas) &#10;oder pneumatische 5/2 Wege Ventile  &#10;" >
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-11293.33" y="-986.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" x="-11333.33" y="1066.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey_F1" Type="IX" x="-14000" y="-1066.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_TP_Q1" Type="E_TP" x="-12620" y="-800">
			<Parameter Name="PT" Value="T#8s"/>
		</FB>
		<FB Name="E_TP_Q2" Type="E_TP" x="-12620" y="1180">
			<Parameter Name="PT" Value="T#4s"/>
		</FB>
		<FB Name="E_TON" Type="E_TON" x="-13866.67" y="1200">
			<Parameter Name="PT" Value="T#2s"/>
		</FB>
		<EventConnections>
			<Connection Source="E_TP_Q1.CNF" Destination="DigitalOutput_Q1.REQ" dx1="366.67"/>
			<Connection Source="E_TP_Q2.CNF" Destination="DigitalOutput_Q2.REQ" dx1="420"/>
			<Connection Source="E_TP_Q1.CNF" Destination="E_TON.REQ" dx1="300" dx2="66.67" dy="913.33"/>
			<Connection Source="E_TON.CNF" Destination="E_TP_Q2.REQ" dx1="233.33"/>
			<Connection Source="SoftKey_F1.IND" Destination="E_TP_Q1.REQ" dx1="613.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_TP_Q2.Q" Destination="DigitalOutput_Q2.OUT" dx1="273.33"/>
			<Connection Source="E_TP_Q1.Q" Destination="DigitalOutput_Q1.OUT" dx1="66.67"/>
			<Connection Source="E_TP_Q1.Q" Destination="E_TON.IN" dx1="66.67" dx2="413.33" dy="293.33"/>
			<Connection Source="E_TON.Q" Destination="E_TP_Q2.IN" dx1="200"/>
			<Connection Source="SoftKey_F1.IN" Destination="E_TP_Q1.IN" dx1="613.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
