<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_042" Comment="Scaling Function Block Testing" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1_CLK" Type="IE" x="-4986.67" y="-460">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SCALE" Type="signalprocessing::SCALE" x="-2606.67" y="-226.67">
			<Parameter Name="IN" Value="10.0"/>
			<Parameter Name="MAX_IN" Value="20.0"/>
			<Parameter Name="MIN_IN" Value="4.0"/>
			<Parameter Name="MAX_OUT" Value="100.0"/>
			<Parameter Name="MIN_OUT" Value="0.0"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="SCALE.REQ" dx1="846.67"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
