<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_042" Comment="Scaling Function Block Testing">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I2_CLK" Type="IE" Comment="" x="-4986.67" y="-460">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="SCALE" Type="signalprocessing::SCALE" Comment="" x="-2606.67" y="-226.67">
			<Parameter Name="IN" Value="10.0" Comment=""/>
			<Parameter Name="MAX1" Value="20.0" Comment=""/>
			<Parameter Name="MIN1" Value="4.0" Comment=""/>
			<Parameter Name="MAX2" Value="100.0" Comment=""/>
			<Parameter Name="MIN2" Value="0.0" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I2_CLK.INIT" Comment="" dx1="1920">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="SCALE.REQ" Comment=""/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
