<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AuxPic" Comment="Bild- und Farbumschaltung für AUX-N und VT Objekte">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Organization="HR Agrartechnik" Version="1.1" Author="Christoph Behr" Date="2026-04-09" Remarks="Inits verbunden und REQ angeschlossen">
	</VersionInfo>
	<VersionInfo Version="1.0" Author="franz" Date="2025-06-12">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="logiBUS::utils::sequence::schieber::SchieberAuxOutStruct"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EO" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="Auxiliary" Type="logiBUS::utils::sequence::schieber::SchieberAuxOutStruct"/>
			<VarDeclaration Name="Picture" Type="UINT" Comment="Object ID of the ObjectPointer to the Picture"/>
			<VarDeclaration Name="Color" Type="UINT" Comment="Object ID of the AuxFunction"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="PictureVT" Type="isobus::UT::Q::Q_NumericValue" x="1673.33" y="1113.33">
		</FB>
		<FB Name="ColorAux" Type="isobus::UT::Q::Q_BackgroundColourAux" x="1673.33" y="2193.33">
		</FB>
		<FB Name="PictureAux" Type="isobus::UT::Q::Q_NumericValueAux" x="1673.33" y="33.33">
		</FB>
		<FB Name="ColorVT" Type="isobus::UT::Q::Q_BackgroundColour" x="1606.67" y="3273.33">
		</FB>
		<FB Name="STRUCT_DEMUX_1" Type="eclipse4diac::convert::STRUCT_DEMUX" x="-2000" y="900">
			<Attribute Name="StructuredType" Type="STRING" Value="logiBUS::utils::sequence::schieber::SchieberAuxOutStruct"/>
		</FB>
		<EventConnections>
			<Connection Source="EO" Destination="STRUCT_DEMUX_1.REQ" dx1="2120"/>
			<Connection Source="STRUCT_DEMUX_1.CNF" Destination="PictureAux.REQ" dx1="820"/>
			<Connection Source="PictureAux.CNF" Destination="PictureVT.REQ" dx1="80" dx2="80" dy="540"/>
			<Connection Source="PictureVT.CNF" Destination="ColorAux.REQ" dx1="80" dx2="80" dy="540"/>
			<Connection Source="ColorAux.CNF" Destination="ColorVT.REQ" dx1="80" dx2="80" dy="540"/>
			<Connection Source="PictureAux.INITO" Destination="PictureVT.INIT" dx1="80" dx2="80" dy="540">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="PictureVT.INITO" Destination="ColorAux.INIT" dx1="80" dx2="80" dy="540">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="ColorAux.INITO" Destination="ColorVT.INIT" dx1="80" dx2="80" dy="540">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="Color" Destination="ColorAux.u16ObjId" dx1="3200">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Color" Destination="ColorVT.u16ObjId" dx1="3200">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Picture" Destination="PictureAux.u16ObjId" dx1="3153.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Picture" Destination="PictureVT.u16ObjId" dx1="3173.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Auxiliary" Destination="STRUCT_DEMUX_1.IN" dx1="1973.33"/>
			<Connection Source="STRUCT_DEMUX_1.u8Colour" Destination="ColorVT.u8Colour" dx1="893.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="STRUCT_DEMUX_1.u8Colour" Destination="ColorAux.u8Colour" dx1="920">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="STRUCT_DEMUX_1.Picture" Destination="PictureAux.u32NewValue" dx1="920">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="STRUCT_DEMUX_1.Picture" Destination="PictureVT.u32NewValue" dx1="920">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
