<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Button_IXA_TO_logiBUS_QXA_BG_OPC" Comment="Konvertierung Button IXA zu logiBUS QXA und Background">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-07-20" Remarks="Background">
	</VersionInfo>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-01-15" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO_S"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID" InitialValue="ID_NULL"/>
			<VarDeclaration Name="Output" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Invalid"/>
			<VarDeclaration Name="ID" Type="WSTRING"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="logiBUS_QXA" Type="logiBUS::io::DQ::logiBUS_QXA" x="700" y="-2100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Button_IXA" Type="isobus::UT::io::Button::Button_IXA" x="-5900" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-1800" y="-1200">
		</FB>
		<SubApp Name="GreenWhiteBackground1_AX" Type="MyLib::sys::GreenWhiteBackground1_AX" x="400" y="-1000">
		</SubApp>
		<FB Name="SUBSCRIBE_1" Type="iec61499::net::SUBSCRIBE_1" x="-5900" y="-1800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_BOOL_TO_X" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="-4200" y="-1600">
		</FB>
		<FB Name="AX_OR_2" Type="adapter::booleanOperators::AX_OR_2" x="-3100" y="-1300">
		</FB>
		<EventConnections>
			<Connection Source="SUBSCRIBE_1.IND" Destination="AX_BOOL_TO_X.REQ" dx1="473.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="Button_IXA.u16ObjId" dx1="1580">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Output" Destination="logiBUS_QXA.Output" dx1="4113.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground1_AX.u16ObjId" dx1="3126.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="ID" Destination="SUBSCRIBE_1.ID" dx1="1580">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="SUBSCRIBE_1.RD_1" Destination="AX_BOOL_TO_X.OUT" dx1="473.33"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="Button_IXA.IN" Destination="AX_OR_2.IN2" dx1="246.67"/>
			<Connection Source="AX_SPLIT_2.OUT1" Destination="logiBUS_QXA.OUT" dx1="273.33"/>
			<Connection Source="AX_SPLIT_2.OUT2" Destination="GreenWhiteBackground1_AX.DI1" dx1="240"/>
			<Connection Source="AX_BOOL_TO_X.AX_OUT" Destination="AX_OR_2.IN1" dx1="126.67"/>
			<Connection Source="AX_OR_2.OUT" Destination="AX_SPLIT_2.IN" dx1="340"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
