<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Button_IXA_TO_logiBUS_QXA_BG_OPC" Comment="Konvertierung Button IXA zu logiBUS QXA und Background">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-07-20" Remarks="Background">
	</VersionInfo>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-01-15" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO_S"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID" InitialValue="ID_NULL"/>
			<VarDeclaration Name="Output" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Invalid"/>
			<VarDeclaration Name="ID_READ" Type="WSTRING"/>
			<VarDeclaration Name="ID_WRITE" Type="WSTRING"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="logiBUS_QXA" Type="logiBUS::io::DQ::logiBUS_QXA" x="1700" y="-2200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Button_IXA" Type="isobus::UT::io::Button::Button_IXA" x="-7400" y="-1300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_SPLIT_3" Type="adapter::events::unidirectional::AX_SPLIT_3" x="-800" y="-1300">
		</FB>
		<SubApp Name="GreenWhiteBackground1_AX" Type="MyLib::sys::GreenWhiteBackground1_AX" x="1400" y="-1100">
		</SubApp>
		<FB Name="AX_SUBSCRIBE_1" Type="adapter::net::AX_SUBSCRIBE_1" x="-7300" y="-2200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_PUBLISH_1" Type="adapter::net::AX_PUBLISH_1" x="2000" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_RF_TRIG_BT" Type="adapter::events::unidirectional::AX_RF_TRIG" x="-4600" y="-1000">
		</FB>
		<FB Name="AX_SR" Type="adapter::events::unidirectional::AX_SR" x="-2900" y="-1600">
		</FB>
		<FB Name="AX_RF_TRIG_OPC" Type="adapter::events::unidirectional::AX_RF_TRIG" x="-4600" y="-1600">
		</FB>
		<EventConnections>
			<Connection Source="AX_SUBSCRIBE_1.INITO" Destination="AX_PUBLISH_1.INIT" dx1="3800">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="AX_RF_TRIG_OPC.ER" Destination="AX_SR.S"/>
			<Connection Source="AX_RF_TRIG_BT.ER" Destination="AX_SR.S" dx1="380"/>
			<Connection Source="AX_RF_TRIG_OPC.EF" Destination="AX_SR.R"/>
			<Connection Source="AX_RF_TRIG_BT.EF" Destination="AX_SR.R" dx1="546.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="Button_IXA.u16ObjId" dx1="1546.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Output" Destination="logiBUS_QXA.Output" dx1="4113.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground1_AX.u16ObjId" dx1="3126.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="ID_READ" Destination="AX_SUBSCRIBE_1.ID" dx1="760">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="ID_WRITE" Destination="AX_PUBLISH_1.ID" dx1="5026.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="Button_IXA.IN" Destination="AX_RF_TRIG_BT.QI" dx1="1580"/>
			<Connection Source="AX_SPLIT_3.OUT1" Destination="logiBUS_QXA.OUT" dx1="273.33"/>
			<Connection Source="AX_SPLIT_3.OUT2" Destination="GreenWhiteBackground1_AX.DI1" dx1="800"/>
			<Connection Source="AX_SR.Q" Destination="AX_SPLIT_3.IN" dx1="840"/>
			<Connection Source="AX_SUBSCRIBE_1.OUT" Destination="AX_RF_TRIG_OPC.QI" dx1="1580"/>
			<Connection Source="AX_SPLIT_3.OUT3" Destination="AX_PUBLISH_1.IN" dx1="460"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
