<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenBlueBackground1_AXSC" Comment="Hintergrundfarbe (TRUE -&gt; Blau, FALSE -&gt; Weiß) für 1 Objekt (AX-Adapter) (Kompakt)">
	<Identification Standard="61499-2"/>
	<VersionInfo Version="1.0" Author="Franz Höpfinger" Date="2022-11-10"/>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="isobus::UT::Q::types::s1ObjectID"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="u16ObjIds" Type="isobus::UT::Q::types::s1ObjectID" Comment="Object ID" InitialValue="(u16ObjId := ID_NULL)"/>
		</InputVars>
		<Sockets>
			<AdapterDeclaration Name="DI1" Type="adapter::types::unidirectional::AX" Comment="Selector"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenBlueBackground" Type="MyLib::sys::GreenBlueBackground1_AXS" x="1700" y="-800"/>
		<DataConnections>
			<Connection Source="u16ObjIds" Destination="GreenBlueBackground.u16ObjIds" dx1="900"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="DI1" Destination="GreenBlueBackground.DI1" dx1="660"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
