<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground3C" Comment="Hintergrundfarbe (TRUE -&gt; Grün, FALSE -&gt; Weiß) für 3 Objekte (Kompakt)">
	<Identification Standard="61499-2"/>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-06"/>
	<CompilerInfo packageName="MyLib::sys"/>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EO" Type="Event" />
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="DI" Type="BOOL"/>
			<VarDeclaration Name="u16ObjId" Type="UINT"/>
			<VarDeclaration Name="u16ObjIdA" Type="UINT"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenWhiteBackground" Type="MyLib::sys::GreenWhiteBackground3" x="-2533.33" y="-3466.67"/>
		<EventConnections>
			<Connection Source="EO" Destination="GreenWhiteBackground.REQ" dx1="246.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground.u16ObjId" dx1="733.33"/>
			<Connection Source="u16ObjIdA" Destination="GreenWhiteBackground.u16ObjIdA" dx1="833.33"/>
			<Connection Source="DI" Destination="GreenWhiteBackground.DI1" dx1="466.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
