<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground3C" Comment="Hintergrundfarbe (TRUE -> Grün, FALSE -> Weiß) für 3 Objekte (Kompakt)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-06">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EO" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="272"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="Q" Type="BOOL">
				<Attribute Name="YPOSITION" Type="INT" Value="139"/>
			</VarDeclaration>
			<VarDeclaration Name="u16ObjId" Type="UINT"/>
			<VarDeclaration Name="u16ObjIdA" Type="UINT"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenWhiteBackground" Type="GreenWhiteBackground3" x="-2533.33" y="-3466.67">
			
			
		</SubApp>
		<EventConnections>
			<Connection Source="EO" Destination="GreenWhiteBackground.REQ" dx1="573.33" dx2="573.33" dy="0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Q" Destination="GreenWhiteBackground.DI1" dx1="680" dx2="680" dy="0"/>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground.u16ObjId" dx1="733.33" dx2="733.33" dy="0"/>
			<Connection Source="u16ObjIdA" Destination="GreenWhiteBackground.u16ObjIdA" dx1="833.33" dx2="833.33" dy="0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
