<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="logiBUS_IXA_BG_OPC" Comment="logiBUS_IXA auf logiBUS_QXA (generisch)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_S"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID" InitialValue="ID_NULL"/>
			<VarDeclaration Name="Input" Type="logiBUS::io::DI::logiBUS_DI_S" Comment="Identify the Input Input_I1..I8" InitialValue="logiBUS_DI::Invalid"/>
			<VarDeclaration Name="ID" Type="WSTRING"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="logiBUS_IXA" Type="logiBUS::io::DI::logiBUS_IXA" x="-4600" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<SubApp Name="GreenWhiteBackground1_AX" Type="MyLib::sys::GreenWhiteBackground1_AX" x="-2200" y="-1000">
		</SubApp>
		<FB Name="PUBLISH_I1" Type="iec61499::net::PUBLISH_1" x="200" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-3300" y="0">
		</FB>
		<FB Name="AX_X_TO_BOOL" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-1700" y="200">
		</FB>
		<EventConnections>
			<Connection Source="AX_X_TO_BOOL.CNF" Destination="PUBLISH_I1.REQ" dx1="473.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Input" Destination="logiBUS_IXA.Input" dx1="2926.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground1_AX.u16ObjId" dx1="2680">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="AX_X_TO_BOOL.IN" Destination="PUBLISH_I1.SD_1" dx1="473.33"/>
			<Connection Source="ID" Destination="PUBLISH_I1.ID" dx1="4280">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="logiBUS_IXA.IN" Destination="AX_SPLIT_2.IN" dx1="420"/>
			<Connection Source="AX_SPLIT_2.OUT1" Destination="GreenWhiteBackground1_AX.DI1" dx1="173.33"/>
			<Connection Source="AX_SPLIT_2.OUT2" Destination="AX_X_TO_BOOL.AX_IN" dx1="420"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
