<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="RedWhiteBackground2C" Comment="Hintergrundfarbe (TRUE -&gt; Rot, FALSE -&gt; Weiß) für 2 Objekte (Kompakt)">
	<Identification Standard="61499-2"/>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-06"/>
	<CompilerInfo packageName="MyLib::sys"/>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EO" Type="Event" />
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="DI" Type="BOOL"/>
			<VarDeclaration Name="u16ObjIdA" Type="UINT"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="RedWhiteBackground" Type="MyLib::sys::RedWhiteBackground2" x="-2400" y="-2100"/>
		<EventConnections>
			<Connection Source="EO" Destination="RedWhiteBackground.REQ" dx1="260"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjIdA" Destination="RedWhiteBackground.u16ObjIdA" dx1="833.33"/>
			<Connection Source="DI" Destination="RedWhiteBackground.DI1" dx1="653.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
