<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_007" Comment="Blinker mit E_CYCLE und E_T_FF" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-400" y="-906.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_CYCLE" Type="E_CYCLE" x="-2933.33" y="-566.67">
			<Parameter Name="DT" Value="T#1s"/>
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" x="-1600" y="-566.67">
		</FB>
		<EventConnections>
			<Connection Source="E_CYCLE.EO" Destination="E_T_FF.CLK"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ" dx1="333.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="333.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
