<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_007" Comment="Blinker mit E_CYCLE und E_T_FF">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-400" y="-906.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_CYCLE" Type="E_CYCLE" Comment="" x="-2933.33" y="-566.67">
			<Parameter Name="DT" Value="T#1s" Comment=""/>
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" Comment="" x="-1600" y="-566.67">
		</FB>
		<EventConnections>
			<Connection Source="E_CYCLE.EO" Destination="E_T_FF.CLK" Comment=""/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="333.33"/>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="1813.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="E_CYCLE.START" Comment="" dx1="533.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
