<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_072c" Comment="GBSD auf UT ausgeben">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="I_GBSD" Type="I_GBSD" Comment="" x="-5200" y="500">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="Q_NumericValue_GBSD" Type="Q_NumericValue" Comment="" x="-400" y="500">
			<Parameter Name="u16ObjId" Value="NumberVariable_Ground_based_machine_speed" Comment=""/>
		</FB>
		<FB Name="Q_NumberVariable_Wheel_based_machine_distance" Type="Q_NumericValue" Comment="" x="3300" y="1400">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_distance" Comment=""/>
		</FB>
		<FB Name="INTEGRAL" Type="utils::math::INTEGRAL" Comment="" x="1200" y="2800">
		</FB>
		<FB Name="OFFSET" Type="utils::math::OFFSET" Comment="" x="-1000" y="1900">
		</FB>
		<FB Name="CYCLE_TIME" Type="utils::timing::CYCLE_TIME" Comment="" x="-2800" y="3000">
		</FB>
		<FB Name="F_UINT_TO_REAL" Type="F_UINT_TO_REAL" Comment="" x="-800" y="2900">
		</FB>
		<FB Name="F_REAL_TO_UDINT" Type="F_REAL_TO_UDINT" Comment="" x="3500" y="2900">
		</FB>
		<FB Name="F_SUB" Type="F_SUB" Comment="" x="8800" y="2300">
		</FB>
		<FB Name="F_UDINT_TO_LINT" Type="F_UDINT_TO_LINT" Comment="" x="6000" y="2000">
		</FB>
		<FB Name="F_UDINT_TO_LINT_1" Type="F_UDINT_TO_LINT" Comment="" x="6000" y="2500">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="I_GBSD.INIT" Comment="" dx1="1766.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="I_GBSD.IND" Destination="Q_NumericValue_GBSD.REQ" Comment=""/>
			<Connection Source="INIT" Destination="Q_NumericValue_GBSD.INIT" Comment="" dx1="4013.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Q_NumberVariable_Wheel_based_machine_distance.INIT" Comment="" dx1="5053.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="I_GBSD.IND" Destination="OFFSET.REQ" Comment="" dx1="1206.67" dx2="1206.67" dy="0"/>
			<Connection Source="OFFSET.CNF" Destination="Q_NumberVariable_Wheel_based_machine_distance.REQ" Comment="" dx1="760"/>
			<Connection Source="I_GBSD.IND" Destination="CYCLE_TIME.REQ" Comment="" dx1="460"/>
			<Connection Source="CYCLE_TIME.CNF" Destination="F_UINT_TO_REAL.REQ" Comment="" dx1="373.33"/>
			<Connection Source="F_UINT_TO_REAL.CNF" Destination="INTEGRAL.REQ" Comment="" dx1="480"/>
			<Connection Source="INTEGRAL.CNF" Destination="F_REAL_TO_UDINT.REQ" Comment="" dx1="820"/>
			<Connection Source="F_REAL_TO_UDINT.CNF" Destination="F_UDINT_TO_LINT_1.REQ" Comment="" dx1="760"/>
			<Connection Source="OFFSET.CNF" Destination="F_UDINT_TO_LINT.REQ" Comment="" dx1="2666.67"/>
			<Connection Source="F_UDINT_TO_LINT_1.CNF" Destination="F_SUB.REQ" Comment="" dx1="306.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="I_GBSD.GROUNDBASEDMACHINESPEED" Destination="Q_NumericValue_GBSD.u32NewValue" Comment="" dx1="2813.33"/>
			<Connection Source="I_GBSD.GROUNDBASEDMACHINEDISTANCE" Destination="OFFSET.IN" Comment="" dx1="986.67" dx2="986.67" dy="0"/>
			<Connection Source="OFFSET.OUT" Destination="Q_NumberVariable_Wheel_based_machine_distance.u32NewValue" Comment="" dx1="1553.33"/>
			<Connection Source="I_GBSD.timestamp_data" Destination="CYCLE_TIME.TM" Comment="" dx1="460"/>
			<Connection Source="CYCLE_TIME.CYCLE" Destination="INTEGRAL.TM" Comment=""/>
			<Connection Source="F_UINT_TO_REAL.OUT" Destination="INTEGRAL.IN" Comment=""/>
			<Connection Source="I_GBSD.GROUNDBASEDMACHINESPEED" Destination="F_UINT_TO_REAL.IN" Comment="" dx1="2413.33"/>
			<Connection Source="INTEGRAL.OUT" Destination="F_REAL_TO_UDINT.IN" Comment=""/>
			<Connection Source="OFFSET.OUT" Destination="F_UDINT_TO_LINT.IN" Comment="" dx1="3220"/>
			<Connection Source="F_REAL_TO_UDINT.OUT" Destination="F_UDINT_TO_LINT_1.IN" Comment="" dx1="760"/>
			<Connection Source="F_UDINT_TO_LINT_1.OUT" Destination="F_SUB.IN2" Comment="" dx1="306.67"/>
			<Connection Source="F_UDINT_TO_LINT.OUT" Destination="F_SUB.IN1" Comment="" dx1="420"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
