<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_072c" Comment="GBSD auf UT ausgeben" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0" >
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="I_GBSD" Type="I_GBSD" x="-5200" y="500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_GBSD" Type="Q_NumericValue" x="-400" y="500">
			<Parameter Name="u16ObjId" Value="DefaultPool_TECU::NumberVariable_Ground_based_machine_speed"/>
		</FB>
		<FB Name="Q_NumberVariable_Wheel_based_machine_distance" Type="Q_NumericValue" x="3300" y="1400">
			<Parameter Name="u16ObjId" Value="DefaultPool_TECU::NumberVariable_Wheel_based_machine_distance"/>
		</FB>
		<FB Name="INTEGRAL" Type="utils::math::INTEGRAL" x="1200" y="2800">
		</FB>
		<FB Name="OFFSET_UDINT" Type="utils::math::OFFSET_UDINT" x="-1000" y="1900">
		</FB>
		<FB Name="CYCLE_TIME" Type="utils::timing::CYCLE_TIME" x="-2800" y="3000">
		</FB>
		<FB Name="F_UINT_TO_REAL" Type="F_UINT_TO_REAL" x="-800" y="2900">
		</FB>
		<FB Name="F_REAL_TO_UDINT" Type="F_REAL_TO_UDINT" x="3500" y="2900">
		</FB>
		<FB Name="F_SUB" Type="F_SUB" x="8800" y="2300">
		</FB>
		<FB Name="F_UDINT_TO_LINT" Type="F_UDINT_TO_LINT" x="6000" y="2000">
		</FB>
		<FB Name="F_UDINT_TO_LINT_1" Type="F_UDINT_TO_LINT" x="6000" y="2500">
		</FB>
		<EventConnections>
			<Connection Source="I_GBSD.IND" Destination="Q_NumericValue_GBSD.REQ"/>
			<Connection Source="I_GBSD.IND" Destination="OFFSET_UDINT.REQ" dx1="1206.67"/>
			<Connection Source="OFFSET_UDINT.CNF" Destination="Q_NumberVariable_Wheel_based_machine_distance.REQ" dx1="446.67"/>
			<Connection Source="I_GBSD.IND" Destination="CYCLE_TIME.REQ" dx1="460"/>
			<Connection Source="CYCLE_TIME.CNF" Destination="F_UINT_TO_REAL.REQ" dx1="373.33"/>
			<Connection Source="F_UINT_TO_REAL.CNF" Destination="INTEGRAL.REQ" dx1="480"/>
			<Connection Source="INTEGRAL.CNF" Destination="F_REAL_TO_UDINT.REQ" dx1="820"/>
			<Connection Source="F_REAL_TO_UDINT.CNF" Destination="F_UDINT_TO_LINT_1.REQ" dx1="760"/>
			<Connection Source="OFFSET_UDINT.CNF" Destination="F_UDINT_TO_LINT.REQ" dx1="2666.67"/>
			<Connection Source="F_UDINT_TO_LINT_1.CNF" Destination="F_SUB.REQ" dx1="306.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="I_GBSD.GROUNDBASEDMACHINESPEED" Destination="Q_NumericValue_GBSD.u32NewValue" dx1="2813.33"/>
			<Connection Source="I_GBSD.GROUNDBASEDMACHINEDISTANCE" Destination="OFFSET_UDINT.IN" dx1="986.67"/>
			<Connection Source="OFFSET_UDINT.OUT" Destination="Q_NumberVariable_Wheel_based_machine_distance.u32NewValue" dx1="1553.33"/>
			<Connection Source="I_GBSD.timestamp_data" Destination="CYCLE_TIME.TM" dx1="460"/>
			<Connection Source="CYCLE_TIME.CYCLE" Destination="INTEGRAL.TM"/>
			<Connection Source="F_UINT_TO_REAL.OUT" Destination="INTEGRAL.IN"/>
			<Connection Source="I_GBSD.GROUNDBASEDMACHINESPEED" Destination="F_UINT_TO_REAL.IN" dx1="2413.33"/>
			<Connection Source="INTEGRAL.OUT" Destination="F_REAL_TO_UDINT.IN"/>
			<Connection Source="OFFSET_UDINT.OUT" Destination="F_UDINT_TO_LINT.IN" dx1="3220"/>
			<Connection Source="F_REAL_TO_UDINT.OUT" Destination="F_UDINT_TO_LINT_1.IN" dx1="760"/>
			<Connection Source="F_UDINT_TO_LINT_1.OUT" Destination="F_SUB.IN2" dx1="306.67"/>
			<Connection Source="F_UDINT_TO_LINT.OUT" Destination="F_SUB.IN1" dx1="420"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
