<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_016" Comment="Background Colour umschalten" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_F1_UP" Type="IE" x="-4533.33" y="-1133.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey_F2_UP" Type="IE" x="-4533.33" y="266.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SR" Type="E_SR" x="-2833.33" y="-906.67">
		</FB>
		<FB Name="F_SEL" Type="F_SEL" x="-1020" y="-906.67">
			<Parameter Name="IN0" Value="COLOR_WHITE"/>
			<Parameter Name="IN1" Value="COLOR_GREEN"/>
		</FB>
		<FB Name="Q_BackgroundColour" Type="Q_BackgroundColour" x="793.33" y="-1020">
			<Parameter Name="u16ObjId" Value="SoftKey_F7"/>
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_F1_UP.IND" Destination="E_SR.S" dx1="506.67"/>
			<Connection Source="SoftKey_F2_UP.IND" Destination="E_SR.R" dx1="473.33"/>
			<Connection Source="E_SR.EO" Destination="F_SEL.REQ"/>
			<Connection Source="F_SEL.CNF" Destination="Q_BackgroundColour.REQ" dx1="646.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="F_SEL.G" dx1="633.33"/>
			<Connection Source="F_SEL.OUT" Destination="Q_BackgroundColour.u8Colour" dx1="673.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
