<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_016" Comment="Background Colour umschalten">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_F1_UP" Type="IE" Comment="" x="-4533.33" y="-1133.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="SoftKey_F2_UP" Type="IE" Comment="" x="-4533.33" y="266.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_SR" Type="E_SR" Comment="" x="-2833.33" y="-906.67">
		</FB>
		<FB Name="F_SEL" Type="F_SEL" Comment="" x="-1020" y="-906.67">
			<Parameter Name="IN0" Value="COLOR_WHITE" Comment=""/>
			<Parameter Name="IN1" Value="COLOR_GREEN" Comment=""/>
		</FB>
		<FB Name="Q_BackgroundColour" Type="Q_BackgroundColour" Comment="" x="793.33" y="-1020">
			<Parameter Name="u16ObjId" Value="SoftKey_F7" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="SoftKey_F1_UP.INIT" Comment="" dx1="1113.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="SoftKey_F2_UP.INIT" Comment="" dx1="1206.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_F1_UP.IND" Destination="E_SR.S" Comment=""/>
			<Connection Source="SoftKey_F2_UP.IND" Destination="E_SR.R" Comment="" dx1="473.33"/>
			<Connection Source="E_SR.EO" Destination="F_SEL.REQ" Comment=""/>
			<Connection Source="INIT" Destination="Q_BackgroundColour.INIT" Comment="" dx1="4760">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL.CNF" Destination="Q_BackgroundColour.REQ" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="F_SEL.G" Comment="" dx1="633.33"/>
			<Connection Source="F_SEL.OUT" Destination="Q_BackgroundColour.u8Colour" Comment="" dx1="673.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
