<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_034a1_Q2" Comment="Numeric Value Input auf PWM Ausgang">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_DWORD_TO_UDINT" Type="F_DWORD_TO_UDINT" Comment="" x="1360" y="2386.66">
		</FB>
		<FB Name="PWMOutput_Q2" Type="QD" Comment="" x="1733.33" y="1053.34">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="PWM_Value" Type="ID" Comment="" x="-3966.67" y="940">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<Comment Comment="ACHTUNG !! &amp;#10;IND erscheint erst, &amp;#10;wenn man die Numeric Value mit OK Bestätigt. &amp;#10;nicht bei Button Druck. &amp;#10;" x="-5800" y="1000" width="1480" height="800"/>
		<EventConnections>
			<Connection Source="INIT" Destination="PWM_Value.INIT" Comment="" dx1="2666.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="PWMOutput_Q2.INIT" Comment="" dx1="5233.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="PWM_Value.IND" Destination="PWMOutput_Q2.REQ" Comment="" dx1="2500"/>
			<Connection Source="PWM_Value.IND" Destination="F_DWORD_TO_UDINT.REQ" Comment="" dx1="3013.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="PWM_Value.IN" Destination="F_DWORD_TO_UDINT.IN" Comment="" dx1="2286.67"/>
			<Connection Source="PWM_Value.IN" Destination="PWMOutput_Q2.OUT" Comment="" dx1="2500"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
