<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="SubApp_PC_B" Comment="Geraet B (Station 12, 192.168.1.12): schaltet Output_Q1 basierend auf einem lokal ueberwachten OPC-UA-Knoten (AX_SUBSCRIBE_1), der von Geraet A per CLIENT_1_0 remote beschrieben wird - &apos;SUB style&apos;: das Protokoll steckt im MyLib::sys-Composite (logiBUS_QXA_FROM_SUBSCRIBE_OPC), nicht in der Resource des Geraets">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-02" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="subapp::Training_01_OPC_UA_SUB">
		<Import declaration="VV::const::OPC_UA::myOpcUaAddresses::Q1_LOCAL_READ"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="OUTPUT_Q1" Type="MyLib::sys::logiBUS_QXA_FROM_SUBSCRIBE_OPC" x="0" y="0">
			<Parameter Name="Output" Value="Output_Q1"/>
			<Parameter Name="ID" Value="Q1_LOCAL_READ"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
