<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004a" Comment="Toggle Flip-Flop mit IE" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-3900" y="-300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="IE" x="-7300" y="-300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" x="-5600" y="0">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_T_FF.CLK" dx1="453.33"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ" dx1="400"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
