<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_HystereseVertikal_AX_simple" Comment="MID/DEAD/HYSTERESIS-Eingabefelder bewegen live die 5 Schwellwert-Dreiecke im vertikalen Bargraph (Type=1 BottomToTop, Pixelposition gespiegelt: hoher Wert = kleiner Top)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-09-27" Remarks="AR_TO_AI, Zero, QPos zu MyLib::sys::Q_ChildPosition_AR_Vertikal SubApp ausgelagert">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::HystereseVertikal::DefaultPool_Numeric::InputNumber_MID_N"/>
		<Import declaration="Uebungen::const::UT::HystereseVertikal::DefaultPool_Numeric::InputNumber_DEAD_N"/>
		<Import declaration="Uebungen::const::UT::HystereseVertikal::DefaultPool_Numeric::InputNumber_HYSTERESIS_N"/>
		<Import declaration="Uebungen::const::UT::HystereseVertikal::DefaultPool::Polygon_MID"/>
		<Import declaration="Uebungen::const::UT::HystereseVertikal::DefaultPool::Polygon_MID_PLUS_DEAD"/>
		<Import declaration="Uebungen::const::UT::HystereseVertikal::DefaultPool::Polygon_MID_MINUS_DEAD"/>
		<Import declaration="Uebungen::const::UT::HystereseVertikal::DefaultPool::Polygon_MID_PLUS_DEAD_HYST"/>
		<Import declaration="Uebungen::const::UT::HystereseVertikal::DefaultPool::Polygon_MID_MINUS_DEAD_HYST"/>
		<Import declaration="Uebungen::const::UT::HystereseVertikal::DefaultPool::Container_Schwellwerte"/>
		<Import declaration="Uebungen::const::UT::HystereseVertikal::DefaultPool_Bargraph::Bargraph_Hysterese_ScalePx"/>
		<Import declaration="Uebungen::const::UT::HystereseVertikal::DefaultPool_Bargraph::Bargraph_Hysterese_LengthPx"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="MID_N" Type="isobus::UT::io::NumericValue::NumericValue_PHYSA" x="-12000" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="stObj" Value="InputNumber_MID_N"/>
		</FB>
		<FB Name="DEAD_N" Type="isobus::UT::io::NumericValue::NumericValue_PHYSA" x="-12000" y="1200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="stObj" Value="InputNumber_DEAD_N"/>
		</FB>
		<FB Name="HYST_N" Type="isobus::UT::io::NumericValue::NumericValue_PHYSA" x="-12000" y="2400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="stObj" Value="InputNumber_HYSTERESIS_N"/>
		</FB>
		<FB Name="Split_MID" Type="adapter::events::unidirectional::AR_SPLIT_3" x="-10500" y="0">
		</FB>
		<FB Name="Split_DEAD" Type="adapter::events::unidirectional::AR_SPLIT_2" x="-10500" y="1200">
		</FB>
		<FB Name="Split_HYST" Type="adapter::events::unidirectional::AR_SPLIT_2" x="-10500" y="2400">
		</FB>
		<FB Name="Add_MidDead" Type="adapter::iec61131::arithmetic::AR_ADD_2" x="-9000" y="300">
		</FB>
		<FB Name="Sub_MidDead" Type="adapter::iec61131::arithmetic::AR_SUB_2" x="-9000" y="900">
		</FB>
		<FB Name="Split_AddResult" Type="adapter::events::unidirectional::AR_SPLIT_2" x="-7500" y="300">
		</FB>
		<FB Name="Split_SubResult" Type="adapter::events::unidirectional::AR_SPLIT_2" x="-7500" y="900">
		</FB>
		<FB Name="Add_MidDeadHyst" Type="adapter::iec61131::arithmetic::AR_ADD_2" x="-6000" y="600">
		</FB>
		<FB Name="Sub_MidDeadHyst" Type="adapter::iec61131::arithmetic::AR_SUB_2" x="-6000" y="1500">
		</FB>
		<SubApp Name="QPos_MID" Type="MyLib::sys::Q_ChildPosition_AR_Bargraph_BottomToTop" x="2000" y="0">
			<Parameter Name="u16ObjId" Value="Polygon_MID"/>
			<Parameter Name="u16ObjIdParent" Value="Container_Schwellwerte"/>
			<Parameter Name="xScale" Value="TRUE"/>
			<Parameter Name="ScalePx" Value="Bargraph_Hysterese_ScalePx"/>
			<Parameter Name="LengthPx" Value="Bargraph_Hysterese_LengthPx"/>
		</SubApp>
		<SubApp Name="QPos_MID_PLUS_DEAD" Type="MyLib::sys::Q_ChildPosition_AR_Bargraph_BottomToTop" x="2000" y="2200">
			<Parameter Name="u16ObjId" Value="Polygon_MID_PLUS_DEAD"/>
			<Parameter Name="u16ObjIdParent" Value="Container_Schwellwerte"/>
			<Parameter Name="xScale" Value="TRUE"/>
			<Parameter Name="ScalePx" Value="Bargraph_Hysterese_ScalePx"/>
			<Parameter Name="LengthPx" Value="Bargraph_Hysterese_LengthPx"/>
		</SubApp>
		<SubApp Name="QPos_MID_MINUS_DEAD" Type="MyLib::sys::Q_ChildPosition_AR_Bargraph_BottomToTop" x="2000" y="4400">
			<Parameter Name="u16ObjId" Value="Polygon_MID_MINUS_DEAD"/>
			<Parameter Name="u16ObjIdParent" Value="Container_Schwellwerte"/>
			<Parameter Name="xScale" Value="TRUE"/>
			<Parameter Name="ScalePx" Value="Bargraph_Hysterese_ScalePx"/>
			<Parameter Name="LengthPx" Value="Bargraph_Hysterese_LengthPx"/>
		</SubApp>
		<SubApp Name="QPos_MID_PLUS_DEAD_HYST" Type="MyLib::sys::Q_ChildPosition_AR_Bargraph_BottomToTop" x="2000" y="6600">
			<Parameter Name="u16ObjId" Value="Polygon_MID_PLUS_DEAD_HYST"/>
			<Parameter Name="u16ObjIdParent" Value="Container_Schwellwerte"/>
			<Parameter Name="xScale" Value="TRUE"/>
			<Parameter Name="ScalePx" Value="Bargraph_Hysterese_ScalePx"/>
			<Parameter Name="LengthPx" Value="Bargraph_Hysterese_LengthPx"/>
		</SubApp>
		<SubApp Name="QPos_MID_MINUS_DEAD_HYST" Type="MyLib::sys::Q_ChildPosition_AR_Bargraph_BottomToTop" x="2000" y="8800">
			<Parameter Name="u16ObjId" Value="Polygon_MID_MINUS_DEAD_HYST"/>
			<Parameter Name="u16ObjIdParent" Value="Container_Schwellwerte"/>
			<Parameter Name="xScale" Value="TRUE"/>
			<Parameter Name="ScalePx" Value="Bargraph_Hysterese_ScalePx"/>
			<Parameter Name="LengthPx" Value="Bargraph_Hysterese_LengthPx"/>
		</SubApp>
		<AdapterConnections>
			<Connection Source="MID_N.rPhys" Destination="Split_MID.IN" dx1="186.67"/>
			<Connection Source="DEAD_N.rPhys" Destination="Split_DEAD.IN" dx1="186.67"/>
			<Connection Source="HYST_N.rPhys" Destination="Split_HYST.IN" dx1="186.67"/>
			<Connection Source="Split_MID.OUT2" Destination="Add_MidDead.IN1" dx1="373.33"/>
			<Connection Source="Split_DEAD.OUT1" Destination="Add_MidDead.IN2" dx1="373.33"/>
			<Connection Source="Split_MID.OUT3" Destination="Sub_MidDead.IN1" dx1="373.33"/>
			<Connection Source="Split_DEAD.OUT2" Destination="Sub_MidDead.IN2" dx1="373.33"/>
			<Connection Source="Add_MidDead.OUT" Destination="Split_AddResult.IN"/>
			<Connection Source="Sub_MidDead.OUT" Destination="Split_SubResult.IN"/>
			<Connection Source="Split_AddResult.OUT2" Destination="Add_MidDeadHyst.IN1" dx1="380"/>
			<Connection Source="Split_HYST.OUT1" Destination="Add_MidDeadHyst.IN2" dx1="1880"/>
			<Connection Source="Split_SubResult.OUT2" Destination="Sub_MidDeadHyst.IN1" dx1="380"/>
			<Connection Source="Split_HYST.OUT2" Destination="Sub_MidDeadHyst.IN2" dx1="1880"/>
			<Connection Source="Split_MID.OUT1" Destination="QPos_MID.rPhys" dx1="3620"/>
			<Connection Source="Split_AddResult.OUT1" Destination="QPos_MID_PLUS_DEAD.rPhys" dx1="2153.33"/>
			<Connection Source="Split_SubResult.OUT1" Destination="QPos_MID_MINUS_DEAD.rPhys" dx1="2166.67"/>
			<Connection Source="Add_MidDeadHyst.OUT" Destination="QPos_MID_PLUS_DEAD_HYST.rPhys" dx1="1500"/>
			<Connection Source="Sub_MidDeadHyst.OUT" Destination="QPos_MID_MINUS_DEAD_HYST.rPhys" dx1="1513.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
