<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_100" Comment="DigitalInput_I1 auf DigitalOutput_Q1, mit Plug and Socket" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IXA" x="-4500" y="-800">
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QXA" x="-1500" y="-900">
		</FB>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT" dx1="1113.33" dx2="1113.33" dy="0"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
