<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_100" Comment="DigitalInput_I1 auf DigitalOutput_Q1, mit Plug and Socket" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IXP" x="-4533.33" y="-933.33">
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QXP" x="-1466.67" y="-933.33">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" dx1="1073.33" dx2="1073.33" dy="0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1.INITO" Destination="DigitalOutput_Q1.INIT"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
