<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_003b2" Comment="Funk 16 Tasten auf DataPanel 16">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="F1" Type="Uebung_003b2_sub" x="-100" y="600">
		</SubApp>
		<SubApp Name="F2" Type="Uebung_003b2_sub" x="-100" y="900">
		</SubApp>
		<SubApp Name="F3" Type="Uebung_003b2_sub" x="-100" y="1200">
		</SubApp>
		<SubApp Name="F4" Type="Uebung_003b2_sub" x="-100" y="1500">
		</SubApp>
		<SubApp Name="F5" Type="Uebung_003b2_sub" x="-100" y="1800">
		</SubApp>
		<SubApp Name="F6" Type="Uebung_003b2_sub" x="-100" y="2100">
		</SubApp>
		<SubApp Name="F7" Type="Uebung_003b2_sub" x="-100" y="2400">
		</SubApp>
		<SubApp Name="F8" Type="Uebung_003b2_sub" x="-100" y="2700">
		</SubApp>
		<SubApp Name="F9" Type="Uebung_003b2_sub" x="-100" y="3000">
		</SubApp>
		<SubApp Name="F10" Type="Uebung_003b2_sub" x="-100" y="3300">
		</SubApp>
		<SubApp Name="F11" Type="Uebung_003b2_sub" x="-100" y="3600">
		</SubApp>
		<SubApp Name="F12" Type="Uebung_003b2_sub" x="-100" y="3900">
		</SubApp>
		<SubApp Name="F13" Type="Uebung_003b2_sub" x="2100" y="1400">
		</SubApp>
		<SubApp Name="F14" Type="Uebung_003b2_sub" x="2100" y="1800">
		</SubApp>
		<SubApp Name="F15" Type="Uebung_003b2_sub" x="2100" y="2200">
		</SubApp>
	</SubAppNetwork>
</SubAppType>
