<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_094a" Comment="Beispiel für E_PERMIT">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0&#10;   &#10;Beispiel für E_CTD&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 93">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IX" x="2486.67" y="33.33">
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="IE" x="413.33" y="33.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" x="1613.33" y="233.33">
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QX" x="3773.33" y="133.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_T_FF.CLK"/>
			<Connection Source="DigitalInput_I1.IND" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalInput_I1.INIT" dx1="73.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="E_T_FF.Q" Destination="DigitalInput_I1.QI"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
