<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_094" Comment="Beispiel für E_PERMIT" >
	<Identification Standard="61499-2" Description="Beispiel für E_CTD&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 93" >
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IX" x="-8000" y="100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" x="-8100" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_PERMIT" Type="E_PERMIT" x="-6400" y="-600">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_PERMIT.EI"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="E_PERMIT.PERMIT" dx1="440"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
