<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="tastend_TON_5s" Comment="Subapplication Type">
	<Identification Standard="61499-2" Description="Copyright (c) 2024 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2024-10-23">
	</VersionInfo>
	<CompilerInfo packageName="FBs::Uebungen::Uebung_103::subapp">
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="OUT" Type="adapter::types::unidirectional::AX"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="IN" Type="adapter::types::unidirectional::AX"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AX_X_TO_BOOL" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-13700" y="-1200">
		</FB>
		<FB Name="AX_BOOL_TO_X" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="-9906.67" y="-1200">
		</FB>
		<FB Name="E_TON" Type="iec61499::events::timers::E_TON" x="-11600" y="-1200">
			<Parameter Name="PT" Value="t#5s"/>
		</FB>
		<EventConnections>
			<Connection Source="AX_X_TO_BOOL.CNF" Destination="E_TON.REQ" dx1="626.67"/>
			<Connection Source="E_TON.CNF" Destination="AX_BOOL_TO_X.REQ" dx1="413.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_TON.Q" Destination="AX_BOOL_TO_X.OUT" dx1="413.33"/>
			<Connection Source="AX_X_TO_BOOL.IN" Destination="E_TON.IN" dx1="626.67"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="IN" Destination="AX_X_TO_BOOL.AX_IN" dx1="2833.33"/>
			<Connection Source="AX_BOOL_TO_X.AX_OUT" Destination="OUT" dx1="7540"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
