<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004b3" Comment="Toggle Flip-Flop mit IE / Split / Verriegelt" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="0" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" x="-4500" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SR_I1" Type="E_SR" x="-1600" y="-900">
		</FB>
		<FB Name="E_SWITCH_I1" Type="E_SWITCH" x="-3000" y="-900">
		</FB>
		<FB Name="E_SWITCH_I2" Type="E_SWITCH" x="-3000" y="200">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" x="0" y="100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SR_I2" Type="E_SR" x="-1600" y="200">
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" x="-4500" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="E_SR_I1.EO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_SWITCH_I1.EI"/>
			<Connection Source="E_SWITCH_I1.EO0" Destination="E_SR_I1.S"/>
			<Connection Source="E_SWITCH_I1.EO1" Destination="E_SR_I1.R"/>
			<Connection Source="E_SWITCH_I2.EO1" Destination="E_SR_I2.R"/>
			<Connection Source="E_SWITCH_I2.EO0" Destination="E_SR_I2.S"/>
			<Connection Source="E_SR_I2.EO" Destination="DigitalOutput_Q2.REQ"/>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_SWITCH_I2.EI"/>
			<Connection Source="E_SWITCH_I2.EO0" Destination="E_SR_I1.R" dx1="173.33"/>
			<Connection Source="E_SWITCH_I1.EO0" Destination="E_SR_I2.R" dx1="473.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR_I1.Q" Destination="DigitalOutput_Q1.OUT" dx1="680"/>
			<Connection Source="E_SR_I1.Q" Destination="E_SWITCH_I1.G" dx1="80" dx2="80" dy="160"/>
			<Connection Source="E_SR_I2.Q" Destination="E_SWITCH_I2.G" dx1="80" dx2="80" dy="160"/>
			<Connection Source="E_SR_I2.Q" Destination="DigitalOutput_Q2.OUT" dx1="626.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
