<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004b3" Comment="Toggle Flip-Flop mit IE / Split / Verriegelt" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="0" y="-1133.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" x="-4533.33" y="-1140">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SR_I1" Type="E_SR" x="-1706.66" y="-906.67">
		</FB>
		<FB Name="E_SWITCH_I1" Type="E_SWITCH" x="-2946.67" y="-906.67">
		</FB>
		<FB Name="E_SWITCH_I2" Type="E_SWITCH" x="-2946.67" y="233.33">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" x="0" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SR_I2" Type="E_SR" x="-1700" y="233.33">
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" x="-4540" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1_CLK.INITO" Destination="DigitalOutput_Q1.INIT" dx1="1886.67"/>
			<Connection Source="E_SR_I1.EO" Destination="DigitalOutput_Q1.REQ" dx1="440"/>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_SWITCH_I1.EI" dx1="393.33"/>
			<Connection Source="E_SWITCH_I1.EO0" Destination="E_SR_I1.S"/>
			<Connection Source="E_SWITCH_I1.EO1" Destination="E_SR_I1.R"/>
			<Connection Source="E_SWITCH_I2.EO1" Destination="E_SR_I2.R"/>
			<Connection Source="E_SWITCH_I2.EO0" Destination="E_SR_I2.S"/>
			<Connection Source="E_SR_I2.EO" Destination="DigitalOutput_Q2.REQ" dx1="446.67"/>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_SWITCH_I2.EI" dx1="400"/>
			<Connection Source="DigitalInput_I2_CLK.INITO" Destination="DigitalOutput_Q2.INIT"/>
			<Connection Source="E_SWITCH_I2.EO0" Destination="E_SR_I1.R" dx1="86.67"/>
			<Connection Source="E_SWITCH_I1.EO0" Destination="E_SR_I2.R" dx1="406.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR_I1.Q" Destination="DigitalOutput_Q1.OUT" dx1="680"/>
			<Connection Source="E_SR_I1.Q" Destination="E_SWITCH_I1.G" dx1="80" dx2="80" dy="160"/>
			<Connection Source="E_SR_I2.Q" Destination="E_SWITCH_I2.G" dx1="80" dx2="80" dy="160"/>
			<Connection Source="E_SR_I2.Q" Destination="DigitalOutput_Q2.OUT" dx1="626.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
