<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AUDI_AUI_MUX_7_VAL" Comment="7-Wege-Multiplexer fuer AUDI-Werte mit 7 internen initval_AUDI und AUI_MUX_7 / AUDI_AUI_MUX_7. Schaltet per Event-Input (EI1..EI7) zwischen val1..val7 um.">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-10" Remarks="7-fach Variante von AUDI_AUI_MUX_3_VAL">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EI1" Type="Event" Comment="Event zur Auswahl von val1"/>
			<SubAppEvent Name="EI2" Type="Event" Comment="Event zur Auswahl von val2"/>
			<SubAppEvent Name="EI3" Type="Event" Comment="Event zur Auswahl von val3"/>
			<SubAppEvent Name="EI4" Type="Event" Comment="Event zur Auswahl von val4"/>
			<SubAppEvent Name="EI5" Type="Event" Comment="Event zur Auswahl von val5"/>
			<SubAppEvent Name="EI6" Type="Event" Comment="Event zur Auswahl von val6"/>
			<SubAppEvent Name="EI7" Type="Event" Comment="Event zur Auswahl von val7"/>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="val1" Type="UDINT" Comment="Initialer Ausgabewert bei EI1"/>
			<VarDeclaration Name="val2" Type="UDINT" Comment="Initialer Ausgabewert bei EI2"/>
			<VarDeclaration Name="val3" Type="UDINT" Comment="Initialer Ausgabewert bei EI3"/>
			<VarDeclaration Name="val4" Type="UDINT" Comment="Initialer Ausgabewert bei EI4"/>
			<VarDeclaration Name="val5" Type="UDINT" Comment="Initialer Ausgabewert bei EI5"/>
			<VarDeclaration Name="val6" Type="UDINT" Comment="Initialer Ausgabewert bei EI6"/>
			<VarDeclaration Name="val7" Type="UDINT" Comment="Initialer Ausgabewert bei EI7"/>
		</InputVars>
		<Plugs>
			<AdapterDeclaration Name="OUT" Type="adapter::types::unidirectional::AUDI" Comment="Ausgewaehlter AUDI-Adapter Output"/>
		</Plugs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AUI_MUX_7" Type="adapter::events::unidirectional::AUI_MUX_7" x="-2200" y="-1100">
		</FB>
		<FB Name="AUDI_AUI_MUX_7" Type="adapter::selection::unidirectional::AUDI_AUI_MUX_7" x="100" y="-800">
		</FB>
		<FB Name="initval_AUDI_1" Type="adapter::types::unidirectional::AUDI::initval::initval_AUDI" x="-2300" y="-400">
		</FB>
		<FB Name="initval_AUDI_2" Type="adapter::types::unidirectional::AUDI::initval::initval_AUDI" x="-2300" y="200">
		</FB>
		<FB Name="initval_AUDI_3" Type="adapter::types::unidirectional::AUDI::initval::initval_AUDI" x="-2300" y="800">
		</FB>
		<FB Name="initval_AUDI_4" Type="adapter::types::unidirectional::AUDI::initval::initval_AUDI" x="-2300" y="1400">
		</FB>
		<FB Name="initval_AUDI_5" Type="adapter::types::unidirectional::AUDI::initval::initval_AUDI" x="-2300" y="2000">
		</FB>
		<FB Name="initval_AUDI_6" Type="adapter::types::unidirectional::AUDI::initval::initval_AUDI" x="-2300" y="2600">
		</FB>
		<FB Name="initval_AUDI_7" Type="adapter::types::unidirectional::AUDI::initval::initval_AUDI" x="-2300" y="3200">
		</FB>
		<EventConnections>
			<Connection Source="EI1" Destination="AUI_MUX_7.EI1" dx1="1000"/>
			<Connection Source="EI2" Destination="AUI_MUX_7.EI2" dx1="1000"/>
			<Connection Source="EI3" Destination="AUI_MUX_7.EI3" dx1="1000"/>
			<Connection Source="EI4" Destination="AUI_MUX_7.EI4" dx1="1000"/>
			<Connection Source="EI5" Destination="AUI_MUX_7.EI5" dx1="1000"/>
			<Connection Source="EI6" Destination="AUI_MUX_7.EI6" dx1="1000"/>
			<Connection Source="EI7" Destination="AUI_MUX_7.EI7" dx1="1000"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="val1" Destination="initval_AUDI_1.INIT_VAL" dx1="1000"/>
			<Connection Source="val2" Destination="initval_AUDI_2.INIT_VAL" dx1="1000"/>
			<Connection Source="val3" Destination="initval_AUDI_3.INIT_VAL" dx1="1000"/>
			<Connection Source="val4" Destination="initval_AUDI_4.INIT_VAL" dx1="1000"/>
			<Connection Source="val5" Destination="initval_AUDI_5.INIT_VAL" dx1="1000"/>
			<Connection Source="val6" Destination="initval_AUDI_6.INIT_VAL" dx1="1000"/>
			<Connection Source="val7" Destination="initval_AUDI_7.INIT_VAL" dx1="1000"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="AUI_MUX_7.K" Destination="AUDI_AUI_MUX_7.K" dx1="946.67"/>
			<Connection Source="initval_AUDI_1.OUT" Destination="AUDI_AUI_MUX_7.IN1" dx1="320"/>
			<Connection Source="initval_AUDI_2.OUT" Destination="AUDI_AUI_MUX_7.IN2" dx1="420"/>
			<Connection Source="initval_AUDI_3.OUT" Destination="AUDI_AUI_MUX_7.IN3" dx1="573.33"/>
			<Connection Source="initval_AUDI_4.OUT" Destination="AUDI_AUI_MUX_7.IN4" dx1="700"/>
			<Connection Source="initval_AUDI_5.OUT" Destination="AUDI_AUI_MUX_7.IN5" dx1="820"/>
			<Connection Source="initval_AUDI_6.OUT" Destination="AUDI_AUI_MUX_7.IN6" dx1="940"/>
			<Connection Source="initval_AUDI_7.OUT" Destination="AUDI_AUI_MUX_7.IN7" dx1="1060"/>
			<Connection Source="AUDI_AUI_MUX_7.OUT" Destination="OUT" dx1="700"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
