<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AUI_AUI_MUX_7_VAL" Comment="7-Wege-Multiplexer fuer AUI/UINT-Werte mit 7 internen initval_AUI und AUI_MUX_7&#10;/ AUI_AUI_MUX_7. Schaltet per Event-Input (EI1..EI7) zwischen val1..val7 um.">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-10" Remarks="7-fach AUI/UINT MUX mit initval">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EI1" Type="Event" Comment="Event zur Auswahl von val1">
			</SubAppEvent>
			<SubAppEvent Name="EI2" Type="Event" Comment="Event zur Auswahl von val2">
			</SubAppEvent>
			<SubAppEvent Name="EI3" Type="Event" Comment="Event zur Auswahl von val3">
			</SubAppEvent>
			<SubAppEvent Name="EI4" Type="Event" Comment="Event zur Auswahl von val4">
			</SubAppEvent>
			<SubAppEvent Name="EI5" Type="Event" Comment="Event zur Auswahl von val5">
			</SubAppEvent>
			<SubAppEvent Name="EI6" Type="Event" Comment="Event zur Auswahl von val6">
			</SubAppEvent>
			<SubAppEvent Name="EI7" Type="Event" Comment="Event zur Auswahl von val7">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="val1" Type="UINT" Comment="Initialer Ausgabewert bei EI1"/>
			<VarDeclaration Name="val2" Type="UINT" Comment="Initialer Ausgabewert bei EI2"/>
			<VarDeclaration Name="val3" Type="UINT" Comment="Initialer Ausgabewert bei EI3"/>
			<VarDeclaration Name="val4" Type="UINT" Comment="Initialer Ausgabewert bei EI4"/>
			<VarDeclaration Name="val5" Type="UINT" Comment="Initialer Ausgabewert bei EI5"/>
			<VarDeclaration Name="val6" Type="UINT" Comment="Initialer Ausgabewert bei EI6"/>
			<VarDeclaration Name="val7" Type="UINT" Comment="Initialer Ausgabewert bei EI7"/>
		</InputVars>
		<Plugs>
			<AdapterDeclaration Name="OUT" Type="adapter::types::unidirectional::AUI" Comment="Ausgewaehlter AUI-Adapter Output"/>
		</Plugs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AUI_MUX_7" Type="adapter::events::unidirectional::AUI_MUX_7" x="-2300" y="-1600">
		</FB>
		<FB Name="AUI_AUI_MUX_7" Type="adapter::selection::unidirectional::AUI_AUI_MUX_7" x="100" y="-800">
		</FB>
		<FB Name="initval_AUI_1" Type="adapter::types::unidirectional::AUI::initval::initval_AUI" x="-2300" y="-400">
		</FB>
		<FB Name="initval_AUI_2" Type="adapter::types::unidirectional::AUI::initval::initval_AUI" x="-2300" y="200">
		</FB>
		<FB Name="initval_AUI_3" Type="adapter::types::unidirectional::AUI::initval::initval_AUI" x="-2300" y="800">
		</FB>
		<FB Name="initval_AUI_4" Type="adapter::types::unidirectional::AUI::initval::initval_AUI" x="-2300" y="1400">
		</FB>
		<FB Name="initval_AUI_5" Type="adapter::types::unidirectional::AUI::initval::initval_AUI" x="-2300" y="2000">
		</FB>
		<FB Name="initval_AUI_6" Type="adapter::types::unidirectional::AUI::initval::initval_AUI" x="-2300" y="2600">
		</FB>
		<FB Name="initval_AUI_7" Type="adapter::types::unidirectional::AUI::initval::initval_AUI" x="-2300" y="3200">
		</FB>
		<EventConnections>
			<Connection Source="EI1" Destination="AUI_MUX_7.EI1" dx1="1600"/>
			<Connection Source="EI2" Destination="AUI_MUX_7.EI2" dx1="1566.67"/>
			<Connection Source="EI3" Destination="AUI_MUX_7.EI3" dx1="1533.33"/>
			<Connection Source="EI4" Destination="AUI_MUX_7.EI4" dx1="1500"/>
			<Connection Source="EI5" Destination="AUI_MUX_7.EI5" dx1="1466.67"/>
			<Connection Source="EI6" Destination="AUI_MUX_7.EI6" dx1="1433.33"/>
			<Connection Source="EI7" Destination="AUI_MUX_7.EI7" dx1="1400"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="val1" Destination="initval_AUI_1.INIT_VAL" dx1="1366.67"/>
			<Connection Source="val2" Destination="initval_AUI_2.INIT_VAL" dx1="1333.33"/>
			<Connection Source="val3" Destination="initval_AUI_3.INIT_VAL" dx1="1300"/>
			<Connection Source="val4" Destination="initval_AUI_4.INIT_VAL" dx1="1266.67"/>
			<Connection Source="val5" Destination="initval_AUI_5.INIT_VAL" dx1="1233.33"/>
			<Connection Source="val6" Destination="initval_AUI_6.INIT_VAL" dx1="1200"/>
			<Connection Source="val7" Destination="initval_AUI_7.INIT_VAL" dx1="1166.67"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="AUI_MUX_7.K" Destination="AUI_AUI_MUX_7.K" dx1="880"/>
			<Connection Source="initval_AUI_1.OUT" Destination="AUI_AUI_MUX_7.IN1" dx1="446.67"/>
			<Connection Source="initval_AUI_2.OUT" Destination="AUI_AUI_MUX_7.IN2" dx1="506.67"/>
			<Connection Source="initval_AUI_3.OUT" Destination="AUI_AUI_MUX_7.IN3" dx1="566.67"/>
			<Connection Source="initval_AUI_4.OUT" Destination="AUI_AUI_MUX_7.IN4" dx1="693.33"/>
			<Connection Source="initval_AUI_5.OUT" Destination="AUI_AUI_MUX_7.IN5" dx1="780"/>
			<Connection Source="initval_AUI_6.OUT" Destination="AUI_AUI_MUX_7.IN6" dx1="813.33"/>
			<Connection Source="initval_AUI_7.OUT" Destination="AUI_AUI_MUX_7.IN7" dx1="846.67"/>
			<Connection Source="AUI_AUI_MUX_7.OUT" Destination="OUT" dx1="693.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
