<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AUI_AUI_MUX_4_VAL" Comment="4-Wege-Multiplexer fuer AUI/UINT-Werte mit 4 internen initval_AUI und AUI_MUX_4&#10;/ AUI_AUI_MUX_4. Schaltet per Event-Input (EI1..EI4) zwischen val1..val4 um.">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-10" Remarks="4-fach AUI/UINT MUX mit initval">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EI1" Type="Event" Comment="Event zur Auswahl von val1">
			</SubAppEvent>
			<SubAppEvent Name="EI2" Type="Event" Comment="Event zur Auswahl von val2">
			</SubAppEvent>
			<SubAppEvent Name="EI3" Type="Event" Comment="Event zur Auswahl von val3">
			</SubAppEvent>
			<SubAppEvent Name="EI4" Type="Event" Comment="Event zur Auswahl von val4">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="val1" Type="UINT" Comment="Initialer Ausgabewert bei EI1"/>
			<VarDeclaration Name="val2" Type="UINT" Comment="Initialer Ausgabewert bei EI2"/>
			<VarDeclaration Name="val3" Type="UINT" Comment="Initialer Ausgabewert bei EI3"/>
			<VarDeclaration Name="val4" Type="UINT" Comment="Initialer Ausgabewert bei EI4"/>
		</InputVars>
		<Plugs>
			<AdapterDeclaration Name="OUT" Type="adapter::types::unidirectional::AUI" Comment="Ausgewaehlter AUI-Adapter Output"/>
		</Plugs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AUI_MUX_4" Type="adapter::events::unidirectional::AUI_MUX_4" x="-2300" y="-1700">
		</FB>
		<FB Name="AUI_AUI_MUX_4" Type="adapter::selection::unidirectional::AUI_AUI_MUX_4" x="100" y="-800">
		</FB>
		<FB Name="initval_AUI_1" Type="adapter::types::unidirectional::AUI::initval::initval_AUI" x="-2300" y="-400">
		</FB>
		<FB Name="initval_AUI_2" Type="adapter::types::unidirectional::AUI::initval::initval_AUI" x="-2300" y="200">
		</FB>
		<FB Name="initval_AUI_3" Type="adapter::types::unidirectional::AUI::initval::initval_AUI" x="-2300" y="800">
		</FB>
		<FB Name="initval_AUI_4" Type="adapter::types::unidirectional::AUI::initval::initval_AUI" x="-2300" y="1400">
		</FB>
		<EventConnections>
			<Connection Source="EI1" Destination="AUI_MUX_4.EI1" dx1="1500"/>
			<Connection Source="EI2" Destination="AUI_MUX_4.EI2" dx1="1466.67"/>
			<Connection Source="EI3" Destination="AUI_MUX_4.EI3" dx1="1433.33"/>
			<Connection Source="EI4" Destination="AUI_MUX_4.EI4" dx1="1400"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="val1" Destination="initval_AUI_1.INIT_VAL" dx1="1366.67"/>
			<Connection Source="val2" Destination="initval_AUI_2.INIT_VAL" dx1="1333.33"/>
			<Connection Source="val3" Destination="initval_AUI_3.INIT_VAL" dx1="1300"/>
			<Connection Source="val4" Destination="initval_AUI_4.INIT_VAL" dx1="1266.67"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="AUI_MUX_4.K" Destination="AUI_AUI_MUX_4.K" dx1="880"/>
			<Connection Source="initval_AUI_1.OUT" Destination="AUI_AUI_MUX_4.IN1" dx1="700"/>
			<Connection Source="initval_AUI_2.OUT" Destination="AUI_AUI_MUX_4.IN2" dx1="733.33"/>
			<Connection Source="initval_AUI_3.OUT" Destination="AUI_AUI_MUX_4.IN3" dx1="766.67"/>
			<Connection Source="initval_AUI_4.OUT" Destination="AUI_AUI_MUX_4.IN4" dx1="800"/>
			<Connection Source="AUI_AUI_MUX_4.OUT" Destination="OUT" dx1="693.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
