<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AUS_AX_SEL_AUS_2_VAL" Comment="Binäre Auswahl für AUS-Werte mit 2 internen initval_AUS und AUS_AX_SEL_AUS. Schaltet per G-Adapter zwischen val0 (G=FALSE) und val1 (G=TRUE) um.">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-10" Remarks="initial implementation">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="val0" Type="USINT" Comment="Ausgabewert bei G=FALSE (IN0)"/>
			<VarDeclaration Name="val1" Type="USINT" Comment="Ausgabewert bei G=TRUE (IN1)"/>
		</InputVars>
		<Sockets>
			<AdapterDeclaration Name="G" Type="adapter::types::unidirectional::AX" Comment="Auswahlsignal G"/>
		</Sockets>
		<Plugs>
			<AdapterDeclaration Name="OUT" Type="adapter::types::unidirectional::AUS" Comment="Ausgewaehlter AUS-Adapter Output"/>
		</Plugs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_SEL" Type="adapter::iec61131::selection::AUS_AX_SEL_AUS" x="100" y="-800">
		</FB>
		<FB Name="initval_AUS_0" Type="adapter::types::unidirectional::AUS::initval::initval_AUS" x="-2300" y="-1100">
		</FB>
		<FB Name="initval_AUS_1" Type="adapter::types::unidirectional::AUS::initval::initval_AUS" x="-2300" y="-300">
		</FB>
		<DataConnections>
			<Connection Source="val0" Destination="initval_AUS_0.INIT_VAL" dx1="1000"/>
			<Connection Source="val1" Destination="initval_AUS_1.INIT_VAL" dx1="1000"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="G" Destination="F_SEL.G" dx1="1000"/>
			<Connection Source="initval_AUS_0.OUT" Destination="F_SEL.IN0" dx1="320"/>
			<Connection Source="initval_AUS_1.OUT" Destination="F_SEL.IN1" dx1="420"/>
			<Connection Source="F_SEL.OUT" Destination="OUT" dx1="700"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
