<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Button_IXA_TO_Remote_WRITE_BG_OPC" Comment="VT-Button lesen + Remote-OPC-UA-Write an Zielmodul + VT-Hintergrundfarbe aus Remote-Subscribe (generisch, ein Kanal, fuer Ausgaenge auf Modulen ohne eigene VT-Anbindung)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="franz" Date="2026-08-27">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID Button/Hintergrund (VT)" InitialValue="ID_NULL"/>
			<VarDeclaration Name="ID_SUBSCRIBE" Type="WSTRING" Comment="Remote-Subscribe-Adresse (Status/Farbe, ACTION=SUBSCRIBE)"/>
			<VarDeclaration Name="ID_WRITE_REMOTE" Type="WSTRING" Comment="Remote-Write-Adresse zum Zielmodul (Befehl, ACTION=WRITE, CLIENT)"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Button_IXA" Type="isobus::UT::io::Button::Button_IXA" x="0" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_CLIENT_1_0" Type="adapter::net::AX_CLIENT_1_0" x="1700" y="100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_SUBSCRIBE_1" Type="adapter::net::AX_SUBSCRIBE_1" x="0" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<SubApp Name="GreenWhiteBackground1_AX" Type="MyLib::sys::GreenWhiteBackground1_AX" x="1500" y="1000">
		</SubApp>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="Button_IXA.u16ObjId" dx1="80" dx2="80" dy="146.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground1_AX.u16ObjId" dx1="366.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="ID_SUBSCRIBE" Destination="AX_SUBSCRIBE_1.ID" dx1="80" dx2="80" dy="540">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="ID_WRITE_REMOTE" Destination="AX_CLIENT_1_0.ID" dx1="613.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="Button_IXA.IN" Destination="AX_CLIENT_1_0.IN" dx1="100"/>
			<Connection Source="AX_SUBSCRIBE_1.OUT" Destination="GreenWhiteBackground1_AX.DI1" dx1="280"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
