<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="IXA_TO_logiBUS_LED_strip_QXA" Comment="Taster IXA schaltet einen LED-Strip blinkend (Farbe, Strip-Nummer parametrierbar), adapter-basiert. Generisch. Schwester-Baustein zu MyLib::sys::IX_TO_logiBUS_LED_strip_QX (dort event-basiert statt AX-Adapter).">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-09" Remarks="Angelegt beim Portieren von Uebung_033 nach test_AX zur Wiederverwendung.">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="logiBUS::io::DI::logiBUS_DI_S"/>
		<Import declaration="logiBUS::io::DO_LED::LED_COLOURS"/>
		<Import declaration="logiBUS::io::DO_LED::LED_FREQ"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Invalid"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="Input" Type="logiBUS::io::DI::logiBUS_DI_S" Comment="Identify the Input Input_I1..I8" InitialValue="Invalid"/>
			<VarDeclaration Name="Colour" Type="UINT" Comment="This identify the Colour. " InitialValue="LED_COLOURS::LED_GREEN"/>
			<VarDeclaration Name="Output" Type="USINT" Comment="Identify the Output Number of Strip"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="LED" Type="logiBUS::io::DO_LED::logiBUS_LED_strip_QXA" x="1500" y="-700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="FREQ" Value="LED_FREQ::LED_1HZ"/>
		</FB>
		<FB Name="BUTTON" Type="logiBUS::io::DI::logiBUS_IXA" x="-1500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<DataConnections>
			<Connection Source="Input" Destination="BUTTON.Input" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Output" Destination="LED.Output" dx1="4406.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Colour" Destination="LED.Colour" dx1="4406.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="BUTTON.IN" Destination="LED.OUT" dx1="1126.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
