<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="logiBUS_IXA_OPC" Comment="logiBUS DI Kanal: OPC-UA-Publish (generisch, ein Kanal, ohne VT-Hintergrundfarbe - fuer Module ohne ISOBUS/VT-Anbindung)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="franz" Date="2026-08-27">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="logiBUS::io::DI::logiBUS_DI"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_S"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="Input" Type="logiBUS::io::DI::logiBUS_DI_S" Comment="Identify the Input Input_I1..I8" InitialValue="logiBUS_DI::Invalid"/>
			<VarDeclaration Name="ID_WRITE" Type="WSTRING" Comment="OPC-UA Publish-Key (lesbar)"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="logiBUS_IXA" Type="logiBUS::io::DI::logiBUS_IXA" x="0" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="AX_PUBLISH_1" Type="adapter::net::AX_PUBLISH_1" x="1500" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<DataConnections>
			<Connection Source="Input" Destination="logiBUS_IXA.Input" dx1="80" dx2="80" dy="93.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="ID_WRITE" Destination="AX_PUBLISH_1.ID" dx1="526.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="logiBUS_IXA.IN" Destination="AX_PUBLISH_1.IN"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
