<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Ramp6Buttons" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2026-08-29">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::io::Button::ButtonActivationCode::BT_PRESSED_LATCHED"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND_SWITCH" Type="Event" Comment="Kanal-Ein/Aus-Taste gedrueckt (togglet Enable-Zustand)">
			</SubAppEvent>
			<SubAppEvent Name="IND_ZERO" Type="Event" Comment="Taste &apos;0&apos; gedrueckt (RampLimitFS.ZERO)">
			</SubAppEvent>
			<SubAppEvent Name="IND_UP_SLOW" Type="Event" Comment="Taste &apos;+&apos; gedrueckt (RampLimitFS.UP_SLOW, ~1%)">
			</SubAppEvent>
			<SubAppEvent Name="IND_UP_FAST" Type="Event" Comment="Taste &apos;++&apos; gedrueckt (RampLimitFS.UP_FAST, ~10%)">
			</SubAppEvent>
			<SubAppEvent Name="IND_DOWN_SLOW" Type="Event" Comment="Taste &apos;-&apos; gedrueckt (RampLimitFS.DOWN_SLOW, ~1%)">
			</SubAppEvent>
			<SubAppEvent Name="IND_DOWN_FAST" Type="Event" Comment="Taste &apos;--&apos; gedrueckt (RampLimitFS.DOWN_FAST, ~10%)">
			</SubAppEvent>
			<SubAppEvent Name="IND_FULL" Type="Event" Comment="Taste &apos;F&apos; gedrueckt (RampLimitFS.FULL, 100%)">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="u16ObjId_SWITCH" Type="UINT"/>
			<VarDeclaration Name="u16ObjId_ZERO" Type="UINT"/>
			<VarDeclaration Name="u16ObjId_UP_SLOW" Type="UINT"/>
			<VarDeclaration Name="u16ObjId_UP_FAST" Type="UINT"/>
			<VarDeclaration Name="u16ObjId_DOWN_SLOW" Type="UINT"/>
			<VarDeclaration Name="u16ObjId_DOWN_FAST" Type="UINT"/>
			<VarDeclaration Name="u16ObjId_FULL" Type="UINT"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Button_SWITCH" Type="isobus::UT::io::Button::Button_IE" x="0" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="InputEvent" Value="BT_PRESSED_LATCHED"/>
		</FB>
		<FB Name="Button_ZERO" Type="isobus::UT::io::Button::Button_IE" x="0" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="InputEvent" Value="BT_PRESSED_LATCHED"/>
		</FB>
		<FB Name="Button_UP_SLOW" Type="isobus::UT::io::Button::Button_IE" x="0" y="2000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="InputEvent" Value="BT_PRESSED_LATCHED"/>
		</FB>
		<FB Name="Button_UP_FAST" Type="isobus::UT::io::Button::Button_IE" x="0" y="3000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="InputEvent" Value="BT_PRESSED_LATCHED"/>
		</FB>
		<FB Name="Button_DOWN_SLOW" Type="isobus::UT::io::Button::Button_IE" x="0" y="4000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="InputEvent" Value="BT_PRESSED_LATCHED"/>
		</FB>
		<FB Name="Button_DOWN_FAST" Type="isobus::UT::io::Button::Button_IE" x="0" y="5000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="InputEvent" Value="BT_PRESSED_LATCHED"/>
		</FB>
		<FB Name="Button_FULL" Type="isobus::UT::io::Button::Button_IE" x="0" y="6000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="InputEvent" Value="BT_PRESSED_LATCHED"/>
		</FB>
		<EventConnections>
			<Connection Source="Button_SWITCH.IND" Destination="IND_SWITCH" dx1="1760"/>
			<Connection Source="Button_ZERO.IND" Destination="IND_ZERO" dx1="1793.33"/>
			<Connection Source="Button_UP_SLOW.IND" Destination="IND_UP_SLOW" dx1="1826.67"/>
			<Connection Source="Button_UP_FAST.IND" Destination="IND_UP_FAST" dx1="1860"/>
			<Connection Source="Button_DOWN_SLOW.IND" Destination="IND_DOWN_SLOW" dx1="1893.33"/>
			<Connection Source="Button_DOWN_FAST.IND" Destination="IND_DOWN_FAST" dx1="1926.67"/>
			<Connection Source="Button_FULL.IND" Destination="IND_FULL" dx1="1960"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjId_SWITCH" Destination="Button_SWITCH.u16ObjId" dx1="973.33"/>
			<Connection Source="u16ObjId_ZERO" Destination="Button_ZERO.u16ObjId" dx1="940"/>
			<Connection Source="u16ObjId_UP_SLOW" Destination="Button_UP_SLOW.u16ObjId" dx1="906.67"/>
			<Connection Source="u16ObjId_UP_FAST" Destination="Button_UP_FAST.u16ObjId" dx1="873.33"/>
			<Connection Source="u16ObjId_DOWN_SLOW" Destination="Button_DOWN_SLOW.u16ObjId" dx1="840"/>
			<Connection Source="u16ObjId_DOWN_FAST" Destination="Button_DOWN_FAST.u16ObjId" dx1="806.67"/>
			<Connection Source="u16ObjId_FULL" Destination="Button_FULL.u16ObjId" dx1="773.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
