<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="SUBSCRIBE_R_TRIG" Comment="Subscribed AX-Wert (per ID) auf steigende Flanke ueberwachen und als Event ausgeben">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 HR Agrartechnik GmbH  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="HR Agrartechnik GmbH" Version="1.0" Author="Franz Höpfinger" Date="2026-08-26" Remarks="initial API and implementation">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="EO" Type="Event" Comment="Feuert bei steigender Flanke des subscribed AX-Werts"/>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="ID" Type="WSTRING" Comment="OPC-UA-Endpoint-Konstante (READ), z. B. Anlage_EIN_READ"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SUBSCRIBE" Type="adapter::net::AX_SUBSCRIBE_1" x="0" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_R_TRIG" Type="adapter::events::unidirectional::AX_R_TRIG" x="1200" y="400">
		</FB>
		<EventConnections>
			<Connection Source="AX_R_TRIG.EO" Destination="EO" dx1="693.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="ID" Destination="SUBSCRIBE.ID" dx1="800">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="SUBSCRIBE.OUT" Destination="AX_R_TRIG.QI" dx1="126.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
