<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="values_50_75_25" Comment="3 feste REAL-Konstanten (50/75/25) als AR-Adapter-Ausgaenge, fuer einen AR_AUI_MUX_3-Sollwertauswahl (K=0-&gt;50, K=1-&gt;75, K=2-&gt;25)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-08">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="OUT_50" Type="adapter::types::unidirectional::AR" Comment="Fester Wert 50.0"/>
			<AdapterDeclaration Name="OUT_75" Type="adapter::types::unidirectional::AR" Comment="Fester Wert 75.0"/>
			<AdapterDeclaration Name="OUT_25" Type="adapter::types::unidirectional::AR" Comment="Fester Wert 25.0"/>
		</Plugs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="initval_AR_50" Type="adapter::types::unidirectional::AR::initval::initval_AR" x="0" y="0">
			<Parameter Name="INIT_VAL" Value="REAL#50.0"/>
		</FB>
		<FB Name="initval_AR_75" Type="adapter::types::unidirectional::AR::initval::initval_AR" x="0" y="600">
			<Parameter Name="INIT_VAL" Value="REAL#75.0"/>
		</FB>
		<FB Name="initval_AR_25" Type="adapter::types::unidirectional::AR::initval::initval_AR" x="0" y="1200">
			<Parameter Name="INIT_VAL" Value="REAL#25.0"/>
		</FB>
		<AdapterConnections>
			<Connection Source="initval_AR_50.OUT" Destination="OUT_50" dx1="820"/>
			<Connection Source="initval_AR_75.OUT" Destination="OUT_75" dx1="1153.33"/>
			<Connection Source="initval_AR_25.OUT" Destination="OUT_25" dx1="1760"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
