<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020c" Comment="DigitalInput_I1 auf DigitalOutput_Q1; E_TON; Einschaltverzögert" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-5860" y="460">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" x="-8706.67" y="346.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_TON" Type="E_TON" x="-7193.33" y="573.33">
			<Parameter Name="PT" Value="T#5s"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="E_TON.REQ" dx1="413.33"/>
			<Connection Source="E_TON.CNF" Destination="DigitalOutput_Q1.REQ" dx1="420"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="E_TON.IN" dx1="80"/>
			<Connection Source="E_TON.Q" Destination="DigitalOutput_Q1.OUT" dx1="73.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
