<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020c2" Comment="DigitalInput_I1 auf DigitalOutput_Q1; E_TON Einschaltverzögert; Zeit eingeben und speichern." >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-5893.33" y="453.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" x="-8726.67" y="340">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_TON" Type="E_TON" x="-7193.33" y="573.33">
		</FB>
		<SubApp Name="Uebung_020c2_sub" Type="Uebung_020c2_sub" x="-10133.33" y="1733.33">
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="u16ObjId" Value="DefaultPool::InputNumber_I1"/>
		</SubApp>
		<FB Name="F_MULTIME" Type="F_MULTIME" x="-8400" y="1733.33">
			<Parameter Name="IN1" Value="T#1s"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="E_TON.REQ" dx1="460"/>
			<Connection Source="E_TON.CNF" Destination="DigitalOutput_Q1.REQ" dx1="406.67"/>
			<Connection Source="Uebung_020c2_sub.IND" Destination="F_MULTIME.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="E_TON.IN" dx1="80"/>
			<Connection Source="E_TON.Q" Destination="DigitalOutput_Q1.OUT" dx1="73.33"/>
			<Connection Source="F_MULTIME.OUT" Destination="E_TON.PT" dx1="253.33"/>
			<Connection Source="Uebung_020c2_sub.VALUEO" Destination="F_MULTIME.IN2" dx1="346.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
