<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004b2" Comment="Toggle Flip-Flop mit IE / Split">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="0" y="-1140">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" Comment="" x="-4540" y="-1140">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_SR_I1" Type="E_SR" Comment="" x="-1813.33" y="-906.67">
		</FB>
		<FB Name="E_SWITCH_I1" Type="E_SWITCH" Comment="" x="-2946.67" y="-906.67">
		</FB>
		<FB Name="E_SWITCH_I2" Type="E_SWITCH" Comment="" x="-2946.67" y="233.33">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" Comment="" x="-0" y="6.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_SR_I2" Type="E_SR" Comment="" x="-1700" y="233.33">
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" Comment="" x="-4533.33" y="6.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1_CLK.INIT" Comment="" dx1="1113.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1_CLK.INITO" Destination="DigitalOutput_Q1.INIT" Comment=""/>
			<Connection Source="E_SR_I1.EO" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="440"/>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_SWITCH_I1.EI" Comment=""/>
			<Connection Source="E_SWITCH_I1.EO0" Destination="E_SR_I1.S" Comment=""/>
			<Connection Source="E_SWITCH_I1.EO1" Destination="E_SR_I1.R" Comment=""/>
			<Connection Source="E_SWITCH_I2.EO1" Destination="E_SR_I2.R" Comment=""/>
			<Connection Source="E_SWITCH_I2.EO0" Destination="E_SR_I2.S" Comment=""/>
			<Connection Source="INIT" Destination="DigitalInput_I2_CLK.INIT" Comment="" dx1="2240">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_SR_I2.EO" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="446.67"/>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_SWITCH_I2.EI" Comment=""/>
			<Connection Source="DigitalInput_I2_CLK.INITO" Destination="DigitalOutput_Q2.INIT" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR_I1.Q" Destination="DigitalOutput_Q1.OUT" Comment=""/>
			<Connection Source="E_SR_I1.Q" Destination="E_SWITCH_I1.G" Comment="" dx1="80" dx2="80" dy="160"/>
			<Connection Source="E_SR_I2.Q" Destination="E_SWITCH_I2.G" Comment="" dx1="80" dx2="80" dy="160"/>
			<Connection Source="E_SR_I2.Q" Destination="DigitalOutput_Q2.OUT" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
