<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_073" Comment="VDS auf UT ausgeben" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="I_GBSD" Type="I_GBSD" x="-5213.33" y="453.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_GBSD" Type="Q_NumericValue" x="-680" y="453.33">
			<Parameter Name="u16ObjId" Value="NumberVariable_Ground_based_machine_speed"/>
		</FB>
		<FB Name="I_VDS" Type="I_VDS" x="-5200" y="1900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_WBSD" Type="Q_NumericValue" x="-666.67" y="1900">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_speed"/>
		</FB>
		<EventConnections>
			<Connection Source="I_GBSD.IND" Destination="Q_NumericValue_GBSD.REQ"/>
			<Connection Source="I_VDS.IND" Destination="Q_NumericValue_WBSD.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="I_GBSD.GROUNDBASEDMACHINESPEED" Destination="Q_NumericValue_GBSD.u32NewValue" dx1="1480"/>
			<Connection Source="I_VDS.NavigationBasedVehicleSpeed" Destination="Q_NumericValue_WBSD.u32NewValue" dx1="1480"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
