<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Bool8_TO_logiBUS_QX8" Comment="8 generische digitale Ausgaenge (Kanal frei waehlbar), gemeinsam getriggert durch 1 CNF-Event. Generisch fuer jede 8-Bit-Ausgangsgruppe.">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-09" Remarks="Ausgelagert aus Uebung_060_sub_Outputs (dort an TC-SC gebunden) - die 8 Ausgangskanaele waren zuvor fest importierte Output_Q1..Q8, jetzt als VarDeclaration parametrierbar zur Wiederverwendung fuer beliebige 8-Bit-Ausgangsgruppen.">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="CNF" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="Q_00" Type="BOOL"/>
			<VarDeclaration Name="Q_01" Type="BOOL"/>
			<VarDeclaration Name="Q_02" Type="BOOL"/>
			<VarDeclaration Name="Q_03" Type="BOOL"/>
			<VarDeclaration Name="Q_04" Type="BOOL"/>
			<VarDeclaration Name="Q_05" Type="BOOL"/>
			<VarDeclaration Name="Q_06" Type="BOOL"/>
			<VarDeclaration Name="Q_07" Type="BOOL"/>
			<VarDeclaration Name="Output_1" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Invalid"/>
			<VarDeclaration Name="Output_2" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Invalid"/>
			<VarDeclaration Name="Output_3" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Invalid"/>
			<VarDeclaration Name="Output_4" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Invalid"/>
			<VarDeclaration Name="Output_5" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Invalid"/>
			<VarDeclaration Name="Output_6" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Invalid"/>
			<VarDeclaration Name="Output_7" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Invalid"/>
			<VarDeclaration Name="Output_8" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Invalid"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="1953.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q7" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="4893.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="-986.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q5" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="2933.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="-6.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q6" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="3913.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q8" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="5873.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="973.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="CNF" Destination="DigitalOutput_Q4.REQ" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q7.REQ" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q1.REQ" dx1="660">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q5.REQ" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q2.REQ" dx1="873.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q6.REQ" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q8.REQ" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q3.REQ" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="Q_06" Destination="DigitalOutput_Q7.OUT" dx1="766.67"/>
			<Connection Source="Q_00" Destination="DigitalOutput_Q1.OUT" dx1="966.67"/>
			<Connection Source="Q_04" Destination="DigitalOutput_Q5.OUT" dx1="833.33"/>
			<Connection Source="Q_01" Destination="DigitalOutput_Q2.OUT" dx1="933.33"/>
			<Connection Source="Q_05" Destination="DigitalOutput_Q6.OUT" dx1="800"/>
			<Connection Source="Q_02" Destination="DigitalOutput_Q3.OUT" dx1="900"/>
			<Connection Source="Q_03" Destination="DigitalOutput_Q4.OUT" dx1="866.67"/>
			<Connection Source="Q_07" Destination="DigitalOutput_Q8.OUT" dx1="733.33"/>
			<Connection Source="Output_1" Destination="DigitalOutput_Q1.Output" dx1="966.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Output_2" Destination="DigitalOutput_Q2.Output" dx1="933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Output_3" Destination="DigitalOutput_Q3.Output" dx1="900">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Output_4" Destination="DigitalOutput_Q4.Output" dx1="866.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Output_5" Destination="DigitalOutput_Q5.Output" dx1="833.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Output_6" Destination="DigitalOutput_Q6.Output" dx1="800">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Output_7" Destination="DigitalOutput_Q7.Output" dx1="766.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Output_8" Destination="DigitalOutput_Q8.Output" dx1="733.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
