<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Button_IX_TO_logiBUS_QX_BG" Comment="Konvertierung Button IXA zu logiBUS QXA und Background">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-07-20" Remarks="Background">
	</VersionInfo>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-01-15" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO_S"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID" InitialValue="ID_NULL"/>
			<VarDeclaration Name="Output" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Invalid"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="logiBUS_QX" Type="logiBUS::io::DQ::logiBUS_QX" x="-1300" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Button_IX" Type="isobus::UT::io::Button::Button_IX" x="-5000" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<SubApp Name="GreenWhiteBackground1_AX" Type="MyLib::sys::GreenWhiteBackground1C" x="-1300" y="800">
		</SubApp>
		<FB Name="E_SPLIT_2" Type="iec61499::events::E_SPLIT_2" x="-3500" y="300">
		</FB>
		<EventConnections>
			<Connection Source="Button_IX.IND" Destination="E_SPLIT_2.EI" dx1="353.33"/>
			<Connection Source="E_SPLIT_2.EO1" Destination="logiBUS_QX.REQ" dx1="646.67"/>
			<Connection Source="E_SPLIT_2.EO2" Destination="GreenWhiteBackground1_AX.EO" dx1="646.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="Button_IX.u16ObjId" dx1="1952.94">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Output" Destination="logiBUS_QX.Output" dx1="4113.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground1_AX.u16ObjId" dx1="3126.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Button_IX.IN" Destination="GreenWhiteBackground1_AX.DI" dx1="120"/>
			<Connection Source="Button_IX.IN" Destination="logiBUS_QX.OUT" dx1="1453.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
