<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenRedBackground2S" Comment="Hintergrundfarbe (TRUE -&gt; Grün, FALSE -&gt; Rot) für 2 Objekte">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="franz" Date="2026-07-21">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="isobus::UT::Q::const::colours"/>
		<Import declaration="isobus::UT::Q::types::s2ObjectIDs"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_1" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="CNF_2" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="DI1" Type="BOOL" Comment="Selector"/>
			<VarDeclaration Name="u16ObjIds" Type="isobus::UT::Q::types::s2ObjectIDs" Comment="Object IDs" InitialValue="(u16ObjId := ID_NULL, u16ObjIdA := ID_NULL)"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="STATUS_1" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_1" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_1" Type="INT" Comment="retval see description"/>
			<VarDeclaration Name="STATUS_2" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_2" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_2" Type="INT" Comment="retval see description"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_BackgroundColour_1" Type="isobus::UT::Q::Q_BackgroundColour" x="3473.33" y="33.33">
		</FB>
		<FB Name="Q_BackgroundColour_2" Type="isobus::UT::Q::Q_BackgroundColourAux" x="3473.33" y="1146.67">
		</FB>
		<FB Name="F_SEL_I" Type="iec61131::selection::F_SEL" x="1440" y="920">
			<Parameter Name="IN0" Value="colours::COLOR_RED"/>
			<Parameter Name="IN1" Value="colours::COLOR_GREEN"/>
		</FB>
		<FB Name="F_MOVE" Type="iec61131::selection::F_MOVE" x="2320" y="420">
			<Attribute Name="DataType" Value="isobus::UT::Q::types::s2ObjectIDs"/>
			<Parameter Name="OUT.u16ObjId" Value="">
				<Attribute Name="Visible" Value="true"/>
			</Parameter>
			<Parameter Name="OUT.u16ObjIdA" Value="">
				<Attribute Name="Visible" Value="true"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="REQ" Destination="F_SEL_I.REQ" dx1="473.33"/>
			<Connection Source="Q_BackgroundColour_1.CNF" Destination="CNF_1" dx1="1253.33"/>
			<Connection Source="Q_BackgroundColour_2.CNF" Destination="CNF_2" dx1="1146.67"/>
			<Connection Source="F_MOVE.CNF" Destination="Q_BackgroundColour_1.REQ" dx1="140"/>
			<Connection Source="F_SEL_I.CNF" Destination="F_MOVE.REQ" dx1="140"/>
			<Connection Source="F_MOVE.CNF" Destination="Q_BackgroundColour_2.REQ" dx1="153.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DI1" Destination="F_SEL_I.G" dx1="2886.67"/>
			<Connection Source="F_MOVE.OUT.u16ObjIdA" Destination="Q_BackgroundColour_1.u16ObjId" dx1="186.67"/>
			<Connection Source="Q_BackgroundColour_1.s16result" Destination="result_1" dx1="1386.67"/>
			<Connection Source="Q_BackgroundColour_1.u8OldColour" Destination="u8OldColour_1" dx1="1353.33"/>
			<Connection Source="Q_BackgroundColour_1.STATUS" Destination="STATUS_1" dx1="1320"/>
			<Connection Source="F_SEL_I.OUT" Destination="Q_BackgroundColour_1.u8Colour" dx1="1273.33"/>
			<Connection Source="F_MOVE.OUT.u16ObjIdA" Destination="Q_BackgroundColour_2.u16ObjId" dx1="86.67"/>
			<Connection Source="Q_BackgroundColour_2.s16result" Destination="result_2" dx1="1346.67"/>
			<Connection Source="Q_BackgroundColour_2.u8OldColour" Destination="u8OldColour_2" dx1="1313.33"/>
			<Connection Source="Q_BackgroundColour_2.STATUS" Destination="STATUS_2" dx1="1280"/>
			<Connection Source="F_SEL_I.OUT" Destination="Q_BackgroundColour_2.u8Colour" dx1="713.33"/>
			<Connection Source="u16ObjIds" Destination="F_MOVE.IN" dx1="3326.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
