<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenRedBackground2SC" Comment="Hintergrundfarbe (TRUE -&gt; Grün, FALSE -&gt; Rot) für 2 Objekte (Kompakt)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="franz" Date="2026-07-21">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::types::s2ObjectIDs"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EO" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="u16ObjIds" Type="isobus::UT::Q::types::s2ObjectIDs"/>
			<VarDeclaration Name="DI1" Type="BOOL" Comment="Selector"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenRedBackground2" Type="MyLib::sys::GreenRedBackground2S" x="2100" y="-1000">
		</SubApp>
		<EventConnections>
			<Connection Source="EO" Destination="GreenRedBackground2.REQ" dx1="806.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjIds" Destination="GreenRedBackground2.u16ObjIds" dx1="700"/>
			<Connection Source="DI1" Destination="GreenRedBackground2.DI1" dx1="700"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
