<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="IX_TO_Aux_QX" Comment="logiBUS_IX auf isobus Aux_QX (generisch), event-basiert">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-09" Remarks="Ausgelagert aus Uebung_003c_sub zur Wiederverwendung.">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Invalid"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_S"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="Input" Type="logiBUS::io::DI::logiBUS_DI_S" Comment="Identify the Input Input_I1..I8" InitialValue="Invalid"/>
			<VarDeclaration Name="iInpNr" Type="USINT" Comment="Number of auxiliary array - corresponds with the order in the pool that means first aux input in pool is iInpNr = 0 etc." InitialValue="0"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="QX" Type="isobus::UT::io::Auxiliary::OUT::Aux_QX" x="-2500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="IX" Type="logiBUS::io::DI::logiBUS_IX" x="-4600" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="IX.IND" Destination="QX.REQ" dx1="773.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="IX.IN" Destination="QX.OUT"/>
			<Connection Source="Input" Destination="IX.Input" dx1="2813.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="iInpNr" Destination="QX.iInpNr" dx1="3906.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
