<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="NumericValue_ID_TO_INI" Comment="Numerischer VT-Wert (ID-Variante) einlesen und in INI speichern (generisch).">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-09" Remarks="Ausgelagert aus Uebung_012c_sub zur Wiederverwendung.">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="KEY" Type="STRING" Comment="Key name."/>
			<VarDeclaration Name="SECTION" Type="STRING" Comment="Section name."/>
			<VarDeclaration Name="u16ObjId" Type="UINT" InitialValue="ID_NULL"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="VALUEO" Type="UDINT"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="ID" Type="isobus::UT::io::NumericValue::NumericValue_ID" x="-1300" y="300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="400" y="500">
		</FB>
		<FB Name="INI" Type="eclipse4diac::storage::INI" x="2100" y="100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#0"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="4100" y="300">
		</FB>
		<EventConnections>
			<Connection Source="ID.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="353.33"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="INI.SET" dx1="380"/>
			<Connection Source="INI.SETO" Destination="IND" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INI.GETO" Destination="Q_NumericValue.REQ" dx1="546.67"/>
			<Connection Source="INI.GETO" Destination="IND" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INI.INITO" Destination="INI.GET" dx1="80" dx2="80" dy="-580"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="ID.IN" Destination="F_DWORD_TO_UDINT.IN" dx1="186.67"/>
			<Connection Source="u16ObjId" Destination="Q_NumericValue.u16ObjId" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="KEY" Destination="INI.KEY" dx1="2066.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="INI.VALUE" dx1="333.33"/>
			<Connection Source="INI.VALUEO" Destination="Q_NumericValue.u32NewValue" dx1="486.67"/>
			<Connection Source="INI.VALUEO" Destination="VALUEO" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId" Destination="ID.u16ObjId" dx1="1793.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="SECTION" Destination="INI.SECTION" dx1="3493.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
