<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="RedWhiteBackground4SC" Comment="Hintergrundfarbe (TRUE -&gt; Rot, FALSE -&gt; Weiß) für 4 Objekte (Kompakt)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="franz" Date="2026-07-21">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::types::s3ObjectIDs"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EO" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="u16ObjIds" Type="isobus::UT::Q::types::s3ObjectIDs"/>
			<VarDeclaration Name="DI1" Type="BOOL" Comment="Selector"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="RedWhiteBackground4" Type="MyLib::sys::RedWhiteBackground4S" x="1700" y="-800">
		</SubApp>
		<EventConnections>
			<Connection Source="EO" Destination="RedWhiteBackground4.REQ" dx1="666.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjIds" Destination="RedWhiteBackground4.u16ObjIds" dx1="700"/>
			<Connection Source="DI1" Destination="RedWhiteBackground4.DI1" dx1="700"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
