<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_060_sub_Outputs" Comment="für TC-SC also Task Controller Section Control">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2024-02-29">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="93"/>
			</SubAppEvent>
			<SubAppEvent Name="CNF" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="29"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="Q_00" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="20"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_01" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_02" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_03" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_04" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_05" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_06" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_07" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_08" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_09" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_10" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_11" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_12" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_13" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_14" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_15" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q4" Type="QX" Comment="" x="-3373.33" y="1953.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q7" Type="QX" Comment="" x="-3373.33" y="4893.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-3373.33" y="-986.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q5" Type="QX" Comment="" x="-3373.33" y="2933.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" Comment="" x="-3373.33" y="-6.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q6" Type="QX" Comment="" x="-3373.33" y="3913.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q8" Type="QX" Comment="" x="-3373.33" y="5873.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="QX" Comment="" x="-3373.33" y="973.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q9" Type="QX" Comment="" x="-3373.33" y="6853.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q10" Type="QX" Comment="" x="-3373.33" y="7833.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q11" Type="QX" Comment="" x="-3373.33" y="8813.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q12" Type="QX" Comment="" x="-3373.33" y="9793.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q13" Type="QX" Comment="" x="-3373.33" y="10773.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q14" Type="QX" Comment="" x="-3373.33" y="11753.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q15" Type="QX" Comment="" x="-3373.33" y="12733.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q16" Type="QX" Comment="" x="-3373.33" y="13713.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalOutput_Q4.INIT" Comment="" dx1="940">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q4.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q7.INIT" Comment="" dx1="940">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q7.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="940">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="660">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q5.INIT" Comment="" dx1="940">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q5.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q2.INIT" Comment="" dx1="940">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="873.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q6.INIT" Comment="" dx1="940">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q6.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q8.INIT" Comment="" dx1="940">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q8.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q3.INIT" Comment="" dx1="940">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q3.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q9.INIT" Comment="" dx1="933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q9.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q10.INIT" Comment="" dx1="946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q10.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q11.INIT" Comment="" dx1="946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q11.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q12.INIT" Comment="" dx1="946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q12.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q13.INIT" Comment="" dx1="946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q13.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q14.INIT" Comment="" dx1="946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q14.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q15.INIT" Comment="" dx1="946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q15.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q16.INIT" Comment="" dx1="946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q16.REQ" Comment="" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="Q_06" Destination="DigitalOutput_Q7.OUT" Comment="" dx1="233.33"/>
			<Connection Source="Q_00" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="186.67"/>
			<Connection Source="Q_04" Destination="DigitalOutput_Q5.OUT" Comment="" dx1="266.67"/>
			<Connection Source="Q_01" Destination="DigitalOutput_Q2.OUT" Comment="" dx1="186.67"/>
			<Connection Source="Q_05" Destination="DigitalOutput_Q6.OUT" Comment="" dx1="246.67"/>
			<Connection Source="Q_02" Destination="DigitalOutput_Q3.OUT" Comment="" dx1="300"/>
			<Connection Source="Q_03" Destination="DigitalOutput_Q4.OUT" Comment="" dx1="280"/>
			<Connection Source="Q_07" Destination="DigitalOutput_Q8.OUT" Comment="" dx1="213.33"/>
			<Connection Source="Q_08" Destination="DigitalOutput_Q9.OUT" Comment="" dx1="200"/>
			<Connection Source="Q_09" Destination="DigitalOutput_Q10.OUT" Comment="" dx1="180"/>
			<Connection Source="Q_10" Destination="DigitalOutput_Q11.OUT" Comment="" dx1="166.67"/>
			<Connection Source="Q_11" Destination="DigitalOutput_Q12.OUT" Comment="" dx1="146.67"/>
			<Connection Source="Q_12" Destination="DigitalOutput_Q13.OUT" Comment="" dx1="133.33"/>
			<Connection Source="Q_13" Destination="DigitalOutput_Q14.OUT" Comment="" dx1="113.33"/>
			<Connection Source="Q_14" Destination="DigitalOutput_Q15.OUT" Comment="" dx1="100"/>
			<Connection Source="Q_15" Destination="DigitalOutput_Q16.OUT" Comment="" dx1="80"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
