<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_060" Comment="für TC-SC also Task Controller Section Control" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="20"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SETPOINT_CONDENSED_WORK_STATE_1_16" Type="ID" x="-800" y="-8900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SPLIT_DWORD_INTO_QUARTERS" Type="SPLIT_DWORD_INTO_QUARTERS" x="1300" y="-8700">
		</FB>
		<FB Name="ASSEMBLE_DWORD_FROM_QUARTERS" Type="ASSEMBLE_DWORD_FROM_QUARTERS" x="7300" y="-8700">
		</FB>
		<FB Name="ACTUAL_CONDENSED_WORK_STATE_1_16" Type="QD" x="9900" y="-8800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="BOOLS_TO_QUARTERS" Type="BOOLS_TO_QUARTERS" x="5700" y="-8700">
		</FB>
		<FB Name="QUARTERS_TO_BOOLS" Type="QUARTERS_TO_BOOLS" x="3100" y="-8700">
		</FB>
		<SubApp Name="Out" Type="Uebung_060_sub_Outputs" x="6800" y="-10700">
		</SubApp>
		<FB Name="SECTION_CONTROL_STATE_IN" Type="ID" x="-600" y="-10200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SECTION_CONTROL_STATE_OUT" Type="QD" x="900" y="-10100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="SETPOINT_CONDENSED_WORK_STATE_1_16.INIT" dx1="393.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="SETPOINT_CONDENSED_WORK_STATE_1_16.IND" Destination="SPLIT_DWORD_INTO_QUARTERS.REQ"/>
			<Connection Source="ASSEMBLE_DWORD_FROM_QUARTERS.CNF" Destination="ACTUAL_CONDENSED_WORK_STATE_1_16.REQ"/>
			<Connection Source="INIT" Destination="ACTUAL_CONDENSED_WORK_STATE_1_16.INIT" dx1="3586.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="BOOLS_TO_QUARTERS.CNF" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.REQ"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.CNF" Destination="QUARTERS_TO_BOOLS.REQ"/>
			<Connection Source="QUARTERS_TO_BOOLS.CNF" Destination="BOOLS_TO_QUARTERS.REQ"/>
			<Connection Source="INIT" Destination="Out.INIT" dx1="6433.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="QUARTERS_TO_BOOLS.CNF" Destination="Out.CNF" dx1="226.67"/>
			<Connection Source="INIT" Destination="SECTION_CONTROL_STATE_IN.INIT" dx1="3033.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="SECTION_CONTROL_STATE_OUT.INIT" dx1="3780">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="SECTION_CONTROL_STATE_IN.IND" Destination="SECTION_CONTROL_STATE_OUT.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="SETPOINT_CONDENSED_WORK_STATE_1_16.IN" Destination="SPLIT_DWORD_INTO_QUARTERS.IN" dx1="266.67"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_00" Destination="BOOLS_TO_QUARTERS.I_00"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_02" Destination="BOOLS_TO_QUARTERS.I_02"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_01" Destination="BOOLS_TO_QUARTERS.I_01"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_03" Destination="BOOLS_TO_QUARTERS.I_03"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_04" Destination="BOOLS_TO_QUARTERS.I_04"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_05" Destination="BOOLS_TO_QUARTERS.I_05"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_06" Destination="BOOLS_TO_QUARTERS.I_06"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_07" Destination="BOOLS_TO_QUARTERS.I_07"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_08" Destination="BOOLS_TO_QUARTERS.I_08"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_09" Destination="BOOLS_TO_QUARTERS.I_09"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_10" Destination="BOOLS_TO_QUARTERS.I_10"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_11" Destination="BOOLS_TO_QUARTERS.I_11"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_12" Destination="BOOLS_TO_QUARTERS.I_12"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_13" Destination="BOOLS_TO_QUARTERS.I_13"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_14" Destination="BOOLS_TO_QUARTERS.I_14"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_15" Destination="BOOLS_TO_QUARTERS.I_15"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_06" Destination="Out.Q_06" dx1="1173.33"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_00" Destination="Out.Q_00" dx1="353.33"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_04" Destination="Out.Q_04" dx1="873.33"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_01" Destination="Out.Q_01" dx1="446.67"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_05" Destination="Out.Q_05" dx1="1026.67"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_07" Destination="Out.Q_07" dx1="1260"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_02" Destination="Out.Q_02" dx1="526.67"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_03" Destination="Out.Q_03" dx1="746.67"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_08" Destination="Out.Q_08" dx1="1340"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_00" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_00"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_01" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_01"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_02" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_02"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_03" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_03"/>
			<Connection Source="ASSEMBLE_DWORD_FROM_QUARTERS." Destination="ACTUAL_CONDENSED_WORK_STATE_1_16.OUT" dx1="1133.33"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_04" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_04"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_05" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_05"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_06" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_06"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_07" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_07"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_08" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_08"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_09" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_09"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_10" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_10"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_11" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_11"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_12" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_12"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_13" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_13"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_14" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_14"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_15" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_15"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_00" Destination="QUARTERS_TO_BOOLS.IB_00"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_01" Destination="QUARTERS_TO_BOOLS.IB_01"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_02" Destination="QUARTERS_TO_BOOLS.IB_02"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_03" Destination="QUARTERS_TO_BOOLS.IB_03"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_04" Destination="QUARTERS_TO_BOOLS.IB_04"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_15" Destination="QUARTERS_TO_BOOLS.IB_15"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_14" Destination="QUARTERS_TO_BOOLS.IB_14"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_13" Destination="QUARTERS_TO_BOOLS.IB_13"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_12" Destination="QUARTERS_TO_BOOLS.IB_12"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_11" Destination="QUARTERS_TO_BOOLS.IB_11"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_10" Destination="QUARTERS_TO_BOOLS.IB_10"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_09" Destination="QUARTERS_TO_BOOLS.IB_09"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_08" Destination="QUARTERS_TO_BOOLS.IB_08"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_07" Destination="QUARTERS_TO_BOOLS.IB_07"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_06" Destination="QUARTERS_TO_BOOLS.IB_06"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_05" Destination="QUARTERS_TO_BOOLS.IB_05"/>
			<Connection Source="SECTION_CONTROL_STATE_IN.IN" Destination="SECTION_CONTROL_STATE_OUT.OUT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
