<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_002a" Comment="DigitalInput_I1/_I2 auf DigitalOutput_Q1">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-533.3333333333334" y="-800.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-4533.333333333334" y="-933.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" Comment="" x="-4533.333333333334" y="133.33333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="AND_2" Type="AND_2" Comment="" x="-2000.0" y="-400.0">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1.INITO" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="1200.0"/>
			<Connection Source="INIT" Destination="DigitalInput_I2.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I2.INITO" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="1200.0"/>
			<Connection Source="DigitalInput_I1.IND" Destination="AND_2.REQ" Comment="" dx1="920.0"/>
			<Connection Source="DigitalInput_I2.IND" Destination="AND_2.REQ" Comment="" dx1="920.0"/>
			<Connection Source="AND_2.CNF" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="486.6666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AND_2.OUT" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="486.6666666666667"/>
			<Connection Source="DigitalInput_I1.IN" Destination="AND_2.IN1" Comment="" dx1="1493.3333333333335"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AND_2.IN2" Comment="" dx1="1480.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
