<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_029" Comment="LED_DO Blinkende LED" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_DI" Type="Hutschienenmoped_XL_8_DI" x="-3280" y="-1066.67">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="GLOBAL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="ID_NULL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I1" Value="'Ventilsteuerung.functions.DigitalInput_I1'"/>
			<Parameter Name="DigitalInput_I2" Value="'Ventilsteuerung.functions.DigitalInput_I2'"/>
			<Parameter Name="DigitalInput_I3" Value="'Ventilsteuerung.functions.DigitalInput_I3'"/>
			<Parameter Name="DigitalInput_I4" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_DO" Type="Hutschienenmoped_XL_1_LED_DO" x="-3466.67" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="Output_Q1"/>
			<Parameter Name="u16ObjId" Value="ID_NULL"/>
			<Parameter Name="LED_5HZ" Value="'Ventilsteuerung.functions.LED_Q1_5HZ'"/>
			<Parameter Name="LED_1HZ" Value="'Ventilsteuerung.functions.LED_Q1_1HZ'"/>
			<Parameter Name="LED_ON" Value="'Ventilsteuerung.functions.LED_Q1_ON'"/>
		</FB>
	</SubAppNetwork>
</SubAppType>
