<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_029" Comment="LED_DO Blinkende LED" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="LED_Q1_5HZ" Type="QX" x="-1466.67" y="-833.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" x="-4533.33" y="-946.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="LED_Q1_1HZ" Type="QX" x="-1466.67" y="400">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" x="-4533.33" y="286.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="LED_Q1_ON" Type="QX" x="-1466.67" y="1566.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I3" Type="IX" x="-4533.33" y="1453.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.INITO" Destination="LED_Q1_5HZ.INIT" dx1="1200"/>
			<Connection Source="DigitalInput_I1.IND" Destination="LED_Q1_5HZ.REQ" dx1="1186.67"/>
			<Connection Source="DigitalInput_I2.IND" Destination="LED_Q1_1HZ.REQ" dx1="1186.67"/>
			<Connection Source="DigitalInput_I2.INITO" Destination="LED_Q1_1HZ.INIT" dx1="1186.67"/>
			<Connection Source="DigitalInput_I3.IND" Destination="LED_Q1_ON.REQ" dx1="1186.67"/>
			<Connection Source="DigitalInput_I3.INITO" Destination="LED_Q1_ON.INIT" dx1="1186.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="LED_Q1_5HZ.OUT" dx1="1186.67"/>
			<Connection Source="DigitalInput_I2.IN" Destination="LED_Q1_1HZ.OUT" dx1="1186.67"/>
			<Connection Source="DigitalInput_I3.IN" Destination="LED_Q1_ON.OUT" dx1="1186.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
