<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004a5" Comment="wie Uebung_004a4 aber ohne E_SPLIT">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-4266.67" y="-6.66">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" Comment="" x="-8533.33" y="-6.66">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_T_FF_Q1" Type="E_T_FF" Comment="" x="-5466.67" y="0">
		</FB>
		<FB Name="E_T_FF_Q2" Type="E_T_FF" Comment="" x="-5466.67" y="939.99">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" Comment="" x="-4266.67" y="933.33">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1_CLK.INIT" Comment="" dx1="1113.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_T_FF_Q1.EO" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="400"/>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="3780">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q2.INIT" Comment="" dx1="3613.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_T_FF_Q2.EO" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="366.67"/>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_T_FF_Q1.CLK" Comment="" dx1="1173.33"/>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_T_FF_Q2.CLK" Comment="" dx1="1173.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF_Q1.Q" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="313.33"/>
			<Connection Source="E_T_FF_Q2.Q" Destination="DigitalOutput_Q2.OUT" Comment="" dx1="366.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
