<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010b5" Comment="SoftKey_F1-10 auf DigitalOutput_Q1-10">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="F1" Type="Uebung_010b5_sub" x="-1000" y="1000">
		</SubApp>
		<SubApp Name="F2" Type="Uebung_010b5_sub" x="-1000" y="1300">
		</SubApp>
		<SubApp Name="F3" Type="Uebung_010b5_sub" x="-1000" y="1600">
		</SubApp>
		<SubApp Name="F4" Type="Uebung_010b5_sub" x="-1000" y="1900">
		</SubApp>
		<SubApp Name="F5" Type="Uebung_010b5_sub" x="-1000" y="2200">
		</SubApp>
		<SubApp Name="F6" Type="Uebung_010b5_sub" x="-1000" y="2500">
		</SubApp>
		<SubApp Name="F7" Type="Uebung_010b5_sub" x="-1000" y="2800">
		</SubApp>
		<SubApp Name="F8" Type="Uebung_010b5_sub" x="-1000" y="3100">
		</SubApp>
		<SubApp Name="F9" Type="Uebung_010b5_sub" x="-1000" y="3400">
		</SubApp>
		<SubApp Name="F10" Type="Uebung_010b5_sub" x="-1000" y="3700">
		</SubApp>
	</SubAppNetwork>
</SubAppType>
