<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039_sub_NumbAnzeig" Comment="Spiegelabfolge V2 mit Schrittkette SUB Num" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2024-03-03">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="CNF" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="20"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="STATE_NR" Type="SINT">
				<Attribute Name="YPOSITION" Type="INT" Value="75"/>
			</VarDeclaration>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_SINT_TO_UINT" Type="F_SINT_TO_UINT" x="-800" y="0">
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" x="1340" y="-873.33">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<EventConnections>
			<Connection Source="F_SINT_TO_UINT.CNF" Destination="Q_NumericValue.REQ" dx1="213.33"/>
			<Connection Source="CNF" Destination="F_SINT_TO_UINT.REQ" dx1="273.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SINT_TO_UINT.OUT" Destination="Q_NumericValue.u32NewValue" dx1="246.67"/>
			<Connection Source="STATE_NR" Destination="F_SINT_TO_UINT.IN" dx1="240"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
