<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039_sub_Outputs" Comment="Spiegelabfolge V2 mit Schrittkette SUB Out">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2024-03-03">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="46"/>
			</SubAppEvent>
			<SubAppEvent Name="REQ" Type="Event" Comment="Service Request">
				<Attribute Name="YPOSITION" Type="INT" Value="132"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="OUT" Type="BOOL" Comment="Output data to resource">
				<Attribute Name="YPOSITION" Type="INT" Value="48"/>
			</VarDeclaration>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID Softkey/Button" InitialValue="ID_NULL">
				<Attribute Name="YPOSITION" Type="INT" Value="36"/>
			</VarDeclaration>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="QX" Type="QX" Comment="" x="-853.33" y="-633.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="IX" Type="IX" Comment="" x="-3373.33" y="-986.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="OR_2" Type="OR_2" Comment="" x="-2140" y="-193.33">
		</FB>
		<SubApp Name="GreenWhiteBackground" Type="GreenWhiteBackground" Comment="" x="380" y="-260">
		</SubApp>
		<EventConnections>
			<Connection Source="OR_2.CNF" Destination="QX.REQ" Comment="" dx1="260"/>
			<Connection Source="INIT" Destination="IX.INIT" Comment="" dx1="306.67"/>
			<Connection Source="IX.INITO" Destination="QX.INIT" Comment="" dx1="900"/>
			<Connection Source="IX.IND" Destination="OR_2.REQ" Comment="" dx1="273.33"/>
			<Connection Source="REQ" Destination="OR_2.REQ" Comment="" dx1="1393.33"/>
			<Connection Source="QX.INITO" Destination="GreenWhiteBackground.INIT" Comment="" dx1="266.67"/>
			<Connection Source="QX.CNF" Destination="GreenWhiteBackground.REQ" Comment="" dx1="233.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="OUT" Destination="OR_2.IN2" Comment="" dx1="1426.67"/>
			<Connection Source="IX.IN" Destination="OR_2.IN1" Comment="" dx1="240"/>
			<Connection Source="OR_2.OUT" Destination="QX.OUT" Comment="" dx1="260"/>
			<Connection Source="OR_2.OUT" Destination="GreenWhiteBackground.DI1" Comment="" dx1="393.33" dx2="260" dy="60"/>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground.u16ObjId" Comment="" dx1="3353.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
