<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_009a" Comment="RampLimitFS" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" x="2800" y="1333.33">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<FB Name="UP_FAST" Type="IE" x="-2000" y="1466.67">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DOWN_SLOW" Type="IE" x="-2933.33" y="2133.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_DINT_TO_UDINT" Type="F_DINT_TO_UDINT" x="933.33" y="1466.67">
		</FB>
		<FB Name="ZERO" Type="IE" x="-2000" y="266.67">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DOWN_FAST" Type="IE" x="-2000" y="2540">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="UP_SLOW" Type="IE" x="-2933.33" y="933.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="RampLimitFS" Type="signalprocessing::RampLimitFS" x="-140" y="1466.67">
			<Parameter Name="VAL_ZERO" Value="DINT#0"/>
			<Parameter Name="SLOW" Value="DINT#1"/>
			<Parameter Name="FAST" Value="DINT#10"/>
			<Parameter Name="VAL_FULL" Value="DINT#100"/>
		</FB>
		<FB Name="FULL" Type="IE" x="-2933.33" y="3333.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="UP_FAST.IND" Destination="RampLimitFS.UP_FAST"/>
			<Connection Source="FULL.IND" Destination="RampLimitFS.FULL" dx1="1466.67"/>
			<Connection Source="RampLimitFS.CNF" Destination="F_DINT_TO_UDINT.REQ"/>
			<Connection Source="ZERO.IND" Destination="RampLimitFS.ZERO" dx1="546.67"/>
			<Connection Source="DOWN_SLOW.IND" Destination="RampLimitFS.DOWN_SLOW" dx1="993.33"/>
			<Connection Source="DOWN_FAST.IND" Destination="RampLimitFS.DOWN_FAST" dx1="446.67"/>
			<Connection Source="UP_SLOW.IND" Destination="RampLimitFS.UP_SLOW" dx1="1226.67"/>
			<Connection Source="F_DINT_TO_UDINT.CNF" Destination="Q_NumericValue.REQ" dx1="486.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="RampLimitFS.OUT" Destination="F_DINT_TO_UDINT.IN" dx1="266.67"/>
			<Connection Source="F_DINT_TO_UDINT.OUT" Destination="Q_NumericValue.u32NewValue" dx1="106.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
