<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_009a" Comment="RampLimitFS">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" Comment="" x="2800" y="1333.33">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1" Comment=""/>
		</FB>
		<FB Name="UP_FAST" Type="IE" Comment="" x="-2000" y="1466.67">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DOWN_SLOW" Type="IE" Comment="" x="-2933.33" y="2133.33">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_DINT_TO_UDINT" Type="F_DINT_TO_UDINT" Comment="" x="933.33" y="1466.67">
		</FB>
		<FB Name="ZERO" Type="IE" Comment="" x="-2000" y="266.67">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DOWN_FAST" Type="IE" Comment="" x="-2000" y="2540">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="UP_SLOW" Type="IE" Comment="" x="-2933.33" y="933.33">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="RampLimitFS" Type="signalprocessing::RampLimitFS" Comment="" x="-140" y="1466.67">
			<Parameter Name="VAL_ZERO" Value="DINT#0" Comment=""/>
			<Parameter Name="SLOW" Value="DINT#1" Comment=""/>
			<Parameter Name="FAST" Value="DINT#10" Comment=""/>
			<Parameter Name="VAL_FULL" Value="DINT#100" Comment=""/>
		</FB>
		<FB Name="FULL" Type="IE" Comment="" x="-2933.33" y="3333.33">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Q_NumericValue.INIT" Comment="" dx1="4986.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="UP_FAST.IND" Destination="RampLimitFS.UP_FAST" Comment=""/>
			<Connection Source="FULL.IND" Destination="RampLimitFS.FULL" Comment="" dx1="1466.67"/>
			<Connection Source="RampLimitFS.CNF" Destination="F_DINT_TO_UDINT.REQ" Comment=""/>
			<Connection Source="ZERO.IND" Destination="RampLimitFS.ZERO" Comment="" dx1="546.67"/>
			<Connection Source="DOWN_SLOW.IND" Destination="RampLimitFS.DOWN_SLOW" Comment="" dx1="993.33"/>
			<Connection Source="DOWN_FAST.IND" Destination="RampLimitFS.DOWN_FAST" Comment="" dx1="446.67"/>
			<Connection Source="UP_SLOW.IND" Destination="RampLimitFS.UP_SLOW" Comment="" dx1="1226.67"/>
			<Connection Source="F_DINT_TO_UDINT.CNF" Destination="Q_NumericValue.REQ" Comment="" dx1="486.67"/>
			<Connection Source="INIT" Destination="ZERO.INIT" Comment="" dx1="2033.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="UP_SLOW.INIT" Comment="" dx1="1566.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="UP_FAST.INIT" Comment="" dx1="2033.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DOWN_SLOW.INIT" Comment="" dx1="1566.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DOWN_FAST.INIT" Comment="" dx1="2033.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="FULL.INIT" Comment="" dx1="1566.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="RampLimitFS.OUT" Destination="F_DINT_TO_UDINT.IN" Comment="" dx1="266.67"/>
			<Connection Source="F_DINT_TO_UDINT.OUT" Destination="Q_NumericValue.u32NewValue" Comment="" dx1="106.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
