<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_009a" Comment="Stepper">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" Comment="" x="7740" y="1333.34">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1" Comment=""/>
		</FB>
		<FB Name="UP_FAST" Type="IE" Comment="" x="946.67" y="4173.34">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DOWN_SLOW" Type="IE" Comment="" x="946.67" y="5113.34">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_DINT_TO_UDINT" Type="F_DINT_TO_UDINT" Comment="" x="5080" y="1506.67">
		</FB>
		<FB Name="ZERO" Type="IE" Comment="" x="946.67" y="2306.67">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DOWN_FAST" Type="IE" Comment="" x="946.67" y="6040.01">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="UP_SLOW" Type="IE" Comment="" x="946.67" y="3240.01">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="STEPPER" Type="signalprocessing::STEPPER" Comment="" x="3746.67" y="1506.67">
			<Parameter Name="VAL_ZERO" Value="DINT#0" Comment=""/>
			<Parameter Name="SLOW" Value="DINT#1" Comment=""/>
			<Parameter Name="FAST" Value="DINT#10" Comment=""/>
			<Parameter Name="VAL_FULL" Value="DINT#100" Comment=""/>
		</FB>
		<FB Name="FULL" Type="IE" Comment="" x="940" y="6980">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Q_NumericValue.INIT" Comment="" dx1="4986.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="UP_FAST.IND" Destination="STEPPER.UP_FAST" Comment="" dx1="660" dx2="660" dy="0"/>
			<Connection Source="FULL.IND" Destination="STEPPER.FULL" Comment="" dx1="1126.67" dx2="1126.67" dy="0"/>
			<Connection Source="STEPPER.CNF" Destination="F_DINT_TO_UDINT.REQ" Comment=""/>
			<Connection Source="ZERO.IND" Destination="STEPPER.ZERO" Comment="" dx1="386.67" dx2="386.67" dy="0"/>
			<Connection Source="DOWN_SLOW.IND" Destination="STEPPER.DOWN_SLOW" Comment="" dx1="820" dx2="820" dy="0"/>
			<Connection Source="DOWN_FAST.IND" Destination="STEPPER.DOWN_FAST" Comment="" dx1="980" dx2="980" dy="0"/>
			<Connection Source="UP_SLOW.IND" Destination="STEPPER.UP_SLOW" Comment="" dx1="533.33" dx2="533.33" dy="0"/>
			<Connection Source="F_DINT_TO_UDINT.CNF" Destination="Q_NumericValue.REQ" Comment="" dx1="833.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="STEPPER.OUT" Destination="F_DINT_TO_UDINT.IN" Comment="" dx1="320" dx2="320" dy="0"/>
			<Connection Source="F_DINT_TO_UDINT.OUT" Destination="Q_NumericValue.u32NewValue" Comment="" dx1="833.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
