<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_083" Comment="Beispiel für E_CTUD_UDINT" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0&#10;   &#10;Beispiel für E_CTD&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 94" >
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-7400" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="IE" x="-10800" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_CTUD_UDINT" Type="E_CTUD_UDINT" x="-9000" y="0">
			<Parameter Name="PV" Value="UINT#5"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="IE" x="-10800" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_CLK_I3" Type="IE" x="-10800" y="700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_CLK_I4" Type="IE" x="-10800" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" x="-7400" y="800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" x="-7400" y="2100">
			<Parameter Name="u16ObjId" Value="DefaultPool::OutputNumber_N1"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_CTUD_UDINT.CU" dx1="413.33" dx2="413.33" dy="0"/>
			<Connection Source="E_CTUD_UDINT.CO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_CTUD_UDINT.LDO" Destination="DigitalOutput_Q1.REQ" dx1="393.33" dx2="393.33" dy="0"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_CTUD_UDINT.CD"/>
			<Connection Source="E_CTUD_UDINT.RO" Destination="DigitalOutput_Q1.REQ" dx1="393.33" dx2="393.33" dy="0"/>
			<Connection Source="DigitalInput_CLK_I3.IND" Destination="E_CTUD_UDINT.R" dx1="260" dx2="260" dy="0"/>
			<Connection Source="DigitalInput_CLK_I4.IND" Destination="E_CTUD_UDINT.LD" dx1="400" dx2="400" dy="0"/>
			<Connection Source="E_CTUD_UDINT.LDO" Destination="DigitalOutput_Q2.REQ" dx1="393.33" dx2="393.33" dy="0"/>
			<Connection Source="E_CTUD_UDINT.CO" Destination="DigitalOutput_Q2.REQ" dx1="393.33" dx2="393.33" dy="0"/>
			<Connection Source="E_CTUD_UDINT.RO" Destination="DigitalOutput_Q2.REQ" dx1="393.33" dx2="393.33" dy="0"/>
			<Connection Source="E_CTUD_UDINT.CO" Destination="Q_NumericValue.REQ" dx1="380"/>
			<Connection Source="E_CTUD_UDINT.RO" Destination="Q_NumericValue.REQ" dx1="380"/>
			<Connection Source="E_CTUD_UDINT.LDO" Destination="Q_NumericValue.REQ" dx1="380"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTUD_UDINT.QU" Destination="DigitalOutput_Q1.OUT" dx1="280" dx2="280" dy="0"/>
			<Connection Source="E_CTUD_UDINT.QD" Destination="DigitalOutput_Q2.OUT" dx1="313.33" dx2="313.33" dy="0"/>
			<Connection Source="E_CTUD_UDINT.CV" Destination="Q_NumericValue.u32NewValue" dx1="126.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
