<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="InputOutputTesterBt_OPC_UA" Comment="Tester">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Meins">
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_I01"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_I02"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_I03"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_I04"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_I05"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_I06"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_I07"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_I08"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_Q01"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_Q02"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_Q03"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_Q04"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_Q05"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_Q06"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_Q07"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_Q08"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_Q09"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_Q10"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_Q11"/>
		<Import declaration="Uebungen::const::UT::Tester::DefaultPool_Tester::Button_Q12"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="Input_I1" Type="MyLib::sys::logiBUS_IXA_BG_OPC" x="-1000" y="-700">
			<Parameter Name="u16ObjId" Value="Button_I01"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I1"/>
			<Parameter Name="ID" Value="&quot;opc_ua[WRITE;/Objects/I1,1:s=I1]&quot;"/>
		</SubApp>
		<SubApp Name="Input_I2" Type="MyLib::sys::logiBUS_IXA_BG_OPC" x="-1000" y="100">
			<Parameter Name="u16ObjId" Value="Button_I02"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I2"/>
			<Parameter Name="ID" Value="&quot;opc_ua[WRITE;/Objects/I2,1:s=I2]&quot;"/>
		</SubApp>
		<SubApp Name="Input_I3" Type="MyLib::sys::logiBUS_IXA_BG_OPC" x="-1000" y="900">
			<Parameter Name="u16ObjId" Value="Button_I03"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I3"/>
			<Parameter Name="ID" Value="&quot;opc_ua[WRITE;/Objects/I3,1:s=I3]&quot;"/>
		</SubApp>
		<SubApp Name="Input_I4" Type="MyLib::sys::logiBUS_IXA_BG_OPC" x="-1000" y="1700">
			<Parameter Name="u16ObjId" Value="Button_I04"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I4"/>
			<Parameter Name="ID" Value="&quot;opc_ua[WRITE;/Objects/I4,1:s=I4]&quot;"/>
		</SubApp>
		<SubApp Name="Input_I5" Type="MyLib::sys::logiBUS_IXA_BG_OPC" x="-1000" y="2500">
			<Parameter Name="u16ObjId" Value="Button_I05"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I5"/>
			<Parameter Name="ID" Value="&quot;opc_ua[WRITE;/Objects/I5,1:s=I5]&quot;"/>
		</SubApp>
		<SubApp Name="Input_I6" Type="MyLib::sys::logiBUS_IXA_BG_OPC" x="-1000" y="3300">
			<Parameter Name="u16ObjId" Value="Button_I06"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I6"/>
			<Parameter Name="ID" Value="&quot;opc_ua[WRITE;/Objects/I6,1:s=I6]&quot;"/>
		</SubApp>
		<SubApp Name="Input_I7" Type="MyLib::sys::logiBUS_IXA_BG_OPC" x="-1000" y="4100">
			<Parameter Name="u16ObjId" Value="Button_I07"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I7"/>
			<Parameter Name="ID" Value="&quot;opc_ua[WRITE;/Objects/I7,1:s=I7]&quot;"/>
		</SubApp>
		<SubApp Name="Input_I8" Type="MyLib::sys::logiBUS_IXA_BG_OPC" x="-1000" y="4900">
			<Parameter Name="u16ObjId" Value="Button_I08"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I8"/>
			<Parameter Name="ID" Value="&quot;opc_ua[WRITE;/Objects/I8,1:s=I8]&quot;"/>
		</SubApp>
		<SubApp Name="Output_Q1" Type="MyLib::sys::Button_IXA_TO_logiBUS_QXA_BG_OPC" x="-4600" y="-700">
			<Parameter Name="u16ObjId" Value="Button_Q01"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q1"/>
			<Parameter Name="ID_READ" Value="&quot;opc_ua[READ;/Objects/Q1,1:s=Q1]&quot;"/>
			<Parameter Name="ID_WRITE" Value="&quot;opc_ua[WRITE;/Objects/Q1,1:s=Q1]&quot;"/>
		</SubApp>
		<SubApp Name="Output_Q2" Type="MyLib::sys::Button_IXA_TO_logiBUS_QXA_BG_OPC" x="-4600" y="100">
			<Parameter Name="u16ObjId" Value="Button_Q02"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q2"/>
					<Parameter Name="ID_READ" Value="&quot;opc_ua[READ;/Objects/Q2,1:s=Q2]&quot;"/>
			<Parameter Name="ID_WRITE" Value="&quot;opc_ua[WRITE;/Objects/Q2,1:s=Q2]&quot;"/>
		</SubApp>
		<SubApp Name="Output_Q3" Type="MyLib::sys::Button_IXA_TO_logiBUS_QXA_BG_OPC" x="-4600" y="900">
			<Parameter Name="u16ObjId" Value="Button_Q03"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q3"/>
					<Parameter Name="ID_READ" Value="&quot;opc_ua[READ;/Objects/Q3,1:s=Q3]&quot;"/>
			<Parameter Name="ID_WRITE" Value="&quot;opc_ua[WRITE;/Objects/Q3,1:s=Q3]&quot;"/>
		</SubApp>
		<SubApp Name="Output_Q4" Type="MyLib::sys::Button_IXA_TO_logiBUS_QXA_BG_OPC" x="-4600" y="1700">
			<Parameter Name="u16ObjId" Value="Button_Q04"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q4"/>
					<Parameter Name="ID_READ" Value="&quot;opc_ua[READ;/Objects/Q4,1:s=Q4]&quot;"/>
			<Parameter Name="ID_WRITE" Value="&quot;opc_ua[WRITE;/Objects/Q4,1:s=Q4]&quot;"/>
		</SubApp>
		<SubApp Name="Output_Q5" Type="MyLib::sys::Button_IXA_TO_logiBUS_QXA_BG_OPC" x="-4600" y="2500">
			<Parameter Name="u16ObjId" Value="Button_Q05"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q5"/>
					<Parameter Name="ID_READ" Value="&quot;opc_ua[READ;/Objects/Q5,1:s=Q5]&quot;"/>
			<Parameter Name="ID_WRITE" Value="&quot;opc_ua[WRITE;/Objects/Q5,1:s=Q5]&quot;"/>
		</SubApp>
		<SubApp Name="Output_Q6" Type="MyLib::sys::Button_IXA_TO_logiBUS_QXA_BG_OPC" x="-4600" y="3300">
			<Parameter Name="u16ObjId" Value="Button_Q06"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q6"/>
					<Parameter Name="ID_READ" Value="&quot;opc_ua[READ;/Objects/Q6,1:s=Q6]&quot;"/>
			<Parameter Name="ID_WRITE" Value="&quot;opc_ua[WRITE;/Objects/Q6,1:s=Q6]&quot;"/>
		</SubApp>
		<SubApp Name="Output_Q7" Type="MyLib::sys::Button_IXA_TO_logiBUS_QXA_BG_OPC" x="-4600" y="4100">
			<Parameter Name="u16ObjId" Value="Button_Q07"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q7"/>
					<Parameter Name="ID_READ" Value="&quot;opc_ua[READ;/Objects/Q7,1:s=Q7]&quot;"/>
			<Parameter Name="ID_WRITE" Value="&quot;opc_ua[WRITE;/Objects/Q7,1:s=Q7]&quot;"/>
		</SubApp>
		<SubApp Name="Output_Q8" Type="MyLib::sys::Button_IXA_TO_logiBUS_QXA_BG_OPC" x="-4600" y="4900">
			<Parameter Name="u16ObjId" Value="Button_Q08"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q8"/>
					<Parameter Name="ID_READ" Value="&quot;opc_ua[READ;/Objects/Q8,1:s=Q8]&quot;"/>
			<Parameter Name="ID_WRITE" Value="&quot;opc_ua[WRITE;/Objects/Q8,1:s=Q8]&quot;"/>
		</SubApp>
		<SubApp Name="Output_Q9" Type="MyLib::sys::Button_IXA_TO_logiBUS_QXA_BG_OPC" x="-4600" y="5700">
			<Parameter Name="u16ObjId" Value="Button_Q09"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q9"/>
					<Parameter Name="ID_READ" Value="&quot;opc_ua[READ;/Objects/Q9,1:s=Q9]&quot;"/>
			<Parameter Name="ID_WRITE" Value="&quot;opc_ua[WRITE;/Objects/Q9,1:s=Q9]&quot;"/>
		</SubApp>
		<SubApp Name="Output_Q10" Type="MyLib::sys::Button_IXA_TO_logiBUS_QXA_BG_OPC" x="-4600" y="6500">
			<Parameter Name="u16ObjId" Value="Button_Q10"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q10"/>
					<Parameter Name="ID_READ" Value="&quot;opc_ua[READ;/Objects/Q10,1:s=Q10]&quot;"/>
			<Parameter Name="ID_WRITE" Value="&quot;opc_ua[WRITE;/Objects/Q10,1:s=Q10]&quot;"/>
		</SubApp>
		<SubApp Name="Output_Q11" Type="MyLib::sys::Button_IXA_TO_logiBUS_QXA_BG_OPC" x="-4600" y="7300">
			<Parameter Name="u16ObjId" Value="Button_Q11"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q11"/>
					<Parameter Name="ID_READ" Value="&quot;opc_ua[READ;/Objects/Q11,1:s=Q11]&quot;"/>
			<Parameter Name="ID_WRITE" Value="&quot;opc_ua[WRITE;/Objects/Q11,1:s=Q11]&quot;"/>
		</SubApp>
		<SubApp Name="Output_Q12" Type="MyLib::sys::Button_IXA_TO_logiBUS_QXA_BG_OPC" x="-4600" y="8100">
			<Parameter Name="u16ObjId" Value="Button_Q12"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q12"/>
					<Parameter Name="ID_READ" Value="&quot;opc_ua[READ;/Objects/Q12,1:s=Q12]&quot;"/>
			<Parameter Name="ID_WRITE" Value="&quot;opc_ua[WRITE;/Objects/Q12,1:s=Q12]&quot;"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
