<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_023" Comment="Spiegelabfolge (3)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_DO" Type="Hutschienenmoped_XL_8_DO" Comment="" x="-4306.67" y="-106.67">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="ID_NULL" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q1" Value="'Ventilsteuerung.functions.DigitalOutput_Q1'" Comment=""/>
			<Parameter Name="DigitalOutput_Q2" Value="'Ventilsteuerung.functions.DigitalOutput_Q2'" Comment=""/>
			<Parameter Name="DigitalOutput_Q3" Value="'Ventilsteuerung.functions.DigitalOutput_Q3'" Comment=""/>
			<Parameter Name="DigitalOutput_Q4" Value="'Ventilsteuerung.functions.DigitalOutput_Q4'" Comment=""/>
			<Parameter Name="DigitalOutput_Q5" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q6" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q7" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q8" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="UT_SoftkeyMapping_UP" Type="UT_SoftkeyMapping_UP" Comment="" x="-4306.66" y="-1253.33">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_1" Value="SoftKey_F1" Comment=""/>
			<Parameter Name="DigitalInput_1" Value="'Ventilsteuerung.functions.SoftKey_F1_UP'" Comment=""/>
			<Parameter Name="u16ObjId_2" Value="SoftKey_F7" Comment=""/>
			<Parameter Name="DigitalInput_2" Value="'Ventilsteuerung.functions.SoftKey_F7_UP'" Comment=""/>
			<Parameter Name="u16ObjId_3" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_3" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_4" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_4" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_5" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_5" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_6" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_6" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_7" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_7" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_8" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_8" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="UT_SoftkeyMapping_DOWN" Type="UT_SoftkeyMapping_DOWN" Comment="" x="-4306.67" y="-2833.33">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_1" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_1" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_2" Value="SoftKey_F2" Comment=""/>
			<Parameter Name="DigitalInput_2" Value="'Ventilsteuerung.functions.SoftKey_F2_DOWN'" Comment=""/>
			<Parameter Name="u16ObjId_3" Value="SoftKey_F3" Comment=""/>
			<Parameter Name="DigitalInput_3" Value="'Ventilsteuerung.functions.SoftKey_F3_DOWN'" Comment=""/>
			<Parameter Name="u16ObjId_4" Value="SoftKey_F8" Comment=""/>
			<Parameter Name="DigitalInput_4" Value="'Ventilsteuerung.functions.SoftKey_F8_DOWN'" Comment=""/>
			<Parameter Name="u16ObjId_5" Value="SoftKey_F9" Comment=""/>
			<Parameter Name="DigitalInput_5" Value="'Ventilsteuerung.functions.SoftKey_F9_DOWN'" Comment=""/>
			<Parameter Name="u16ObjId_6" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_6" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_7" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_7" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_8" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_8" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Hutschienenmoped_XL_8_DO.INIT" Comment="" dx1="73.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="UT_SoftkeyMapping_UP.INIT" Comment="" dx1="3600">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
