<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_051" Comment="DigitalInput_I1-_I4 auf DigitalOutput_Q1-_Q4" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_DO" Type="Hutschienenmoped_XL_8_DO" x="-3293.33" y="793.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="GLOBAL"/>
			<Parameter Name="u16ObjId" Value="ID_NULL"/>
			<Parameter Name="DigitalOutput_Q1" Value="'Ventilsteuerung.functions.DigitalOutput_Q1'"/>
			<Parameter Name="DigitalOutput_Q2" Value="'Ventilsteuerung.functions.DigitalOutput_Q2'"/>
			<Parameter Name="DigitalOutput_Q3" Value="'Ventilsteuerung.functions.DigitalOutput_Q3'"/>
			<Parameter Name="DigitalOutput_Q4" Value="'Ventilsteuerung.functions.DigitalOutput_Q4'"/>
			<Parameter Name="DigitalOutput_Q5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_8_DI" Type="Hutschienenmoped_XL_8_DI" x="-3333.33" y="-1066.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="GLOBAL"/>
			<Parameter Name="u16ObjId" Value="ID_NULL"/>
			<Parameter Name="DigitalInput_I1" Value="'Ventilsteuerung.functions.DigitalInput_I1'"/>
			<Parameter Name="DigitalInput_I2" Value="'Ventilsteuerung.functions.DigitalInput_I2'"/>
			<Parameter Name="DigitalInput_I3" Value="'Ventilsteuerung.functions.DigitalInput_I3'"/>
			<Parameter Name="DigitalInput_I4" Value="'Ventilsteuerung.functions.DigitalInput_I4'"/>
			<Parameter Name="DigitalInput_I5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
	</SubAppNetwork>
</SubAppType>
