<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_071a" Comment="WBSD auf UT ausgeben, Q1 Schalten wenn Speed &gt;0" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="I_WBSD" Type="I_WBSD" x="-5213.33" y="453.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_WBSD" Type="Q_NumericValue" x="-680" y="453.33">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_speed"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QX" x="1400" y="1900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="F_GT" Type="F_GT" x="-1500" y="2000">
			<Parameter Name="IN2" Value="UINT#0"/>
		</FB>
		<FB Name="E_D_FF" Type="E_D_FF" x="-200" y="2000">
		</FB>
		<EventConnections>
			<Connection Source="I_WBSD.IND" Destination="Q_NumericValue_WBSD.REQ"/>
			<Connection Source="I_WBSD.IND" Destination="F_GT.REQ" dx1="1006.67"/>
			<Connection Source="F_GT.CNF" Destination="E_D_FF.CLK"/>
			<Connection Source="E_D_FF.EO" Destination="DigitalOutput_Q1.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="I_WBSD.WHEELBASEDMACHINESPEED" Destination="Q_NumericValue_WBSD.u32NewValue" dx1="806.67"/>
			<Connection Source="I_WBSD.WHEELBASEDMACHINESPEED" Destination="F_GT.IN1" dx1="806.67"/>
			<Connection Source="F_GT.OUT" Destination="E_D_FF.D"/>
			<Connection Source="E_D_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="533.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
