<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_026_sub" Comment="Spiegelabfolge (6)" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2024-02-05">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="SET" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="20"/>
			</SubAppEvent>
			<SubAppEvent Name="RESET" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="29"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="EO1" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="235"/>
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_SR" Type="E_SR" x="133.33" y="-800">
		</FB>
		<FB Name="QX" Type="QX" x="1420" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" x="1333.33" y="33.33">
		</FB>
		<EventConnections>
			<Connection Source="E_SR.EO" Destination="QX.REQ" dx1="406.67"/>
			<Connection Source="E_SR.EO" Destination="E_SWITCH.EI" dx1="140"/>
			<Connection Source="SET" Destination="E_SR.S" dx1="473.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="RESET" Destination="E_SR.R" dx1="406.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_SWITCH.EO1" Destination="EO1" dx1="1453.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="QX.OUT" dx1="73.33"/>
			<Connection Source="E_SR.Q" Destination="E_SWITCH.G" dx1="73.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
