<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_039a" Comment="Spiegelabfolge V2 mit Schrittkette" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_DO" Type="Hutschienenmoped_XL_8_DO" x="-8800" y="-800">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="isobus::GLOBAL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="isobus::ID_NULL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q1" Value="'Ventilsteuerung.functions.Q1.QX'"/>
			<Parameter Name="DigitalOutput_Q2" Value="'Ventilsteuerung.functions.Q2.QX'"/>
			<Parameter Name="DigitalOutput_Q3" Value="'Ventilsteuerung.functions.Q3.QX'"/>
			<Parameter Name="DigitalOutput_Q4" Value="'Ventilsteuerung.functions.Q4.QX'"/>
			<Parameter Name="DigitalOutput_Q5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q8" Value="''">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="UT_SoftkeyMapping_UP" Type="UT_SoftkeyMapping_UP" x="-8800" y="1600">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="isobus::GLOBAL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_1" Value="SoftKey_F1"/>
			<Parameter Name="DigitalInput_1" Value="'Ventilsteuerung.functions.SoftKey_F1_UP'"/>
			<Parameter Name="u16ObjId_2" Value="SoftKey_F2"/>
			<Parameter Name="DigitalInput_2" Value="'Ventilsteuerung.functions.Q2.IE'"/>
			<Parameter Name="u16ObjId_3" Value="SoftKey_F8"/>
			<Parameter Name="DigitalInput_3" Value="'Ventilsteuerung.functions.Q1.IE'"/>
			<Parameter Name="u16ObjId_4" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_4" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_8_DI_DOWN" Type="Hutschienenmoped_XL_8_DI_DOWN" x="-12800" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="GLOBAL"/>
			<Parameter Name="u16ObjId" Value="ID_NULL"/>
			<Parameter Name="DigitalInput_I1" Value="'Ventilsteuerung.functions.DigitalInput_DOWN_I1'"/>
			<Parameter Name="DigitalInput_I2" Value="'Ventilsteuerung.functions.DigitalInput_DOWN_I2'"/>
			<Parameter Name="DigitalInput_I3" Value="'Ventilsteuerung.functions.DigitalInput_DOWN_I3'"/>
			<Parameter Name="DigitalInput_I4" Value="'Ventilsteuerung.functions.DigitalInput_DOWN_I4'"/>
		</FB>
		<FB Name="UT_SoftkeyMapping" Type="UT_SoftkeyMapping" x="-12800" y="1600">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="isobus::GLOBAL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_1" Value="SoftKey_F8"/>
			<Parameter Name="DigitalInput_1" Value="'Ventilsteuerung.functions.Q1.IX'"/>
			<Parameter Name="u16ObjId_2" Value="SoftKey_F2"/>
			<Parameter Name="DigitalInput_2" Value="'Ventilsteuerung.functions.Q2.IX'"/>
			<Parameter Name="u16ObjId_3" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_3" Value="''">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_4" Value="SoftKey_F9"/>
			<Parameter Name="DigitalInput_4" Value="'Ventilsteuerung.functions.Q3.IX'"/>
			<Parameter Name="u16ObjId_5" Value="SoftKey_F3"/>
			<Parameter Name="DigitalInput_5" Value="'Ventilsteuerung.functions.Q4.IX'"/>
			<Parameter Name="u16ObjId_6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
	</SubAppNetwork>
</SubAppType>
