<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039a" Comment="Spiegelabfolge V2 mit Schrittkette" >
	<Identification Standard="61499-2" Description="Spiegelabfolge V2 mit Schrittkette  &#10;geeignet für hydraulisches Ringsystem 3/2 Wege Ventile  (z.B. Claas) &#10;oder pneumatische 5/2 Wege Ventile  &#10;" >
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_TimeOut" Type="E_TimeOut" x="-8626.67" y="3553.33">
		</FB>
		<FB Name="DigitalInput_DOWN_I1" Type="IE" x="-12533.33" y="166.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_DOWN_I2" Type="IE" x="-12533.33" y="1146.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_DOWN_I3" Type="IE" x="-12533.33" y="2126.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_DOWN_I4" Type="IE" x="-12533.33" y="3106.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="sequence_05" Type="sequence_ET_05" x="-10726.67" y="-126.67">
			<Parameter Name="DT_S1_S2" Value="NO_TIME"/>
			<Parameter Name="DT_S2_S3" Value="NO_TIME"/>
			<Parameter Name="DT_S3_S4" Value="T#5s"/>
			<Parameter Name="DT_S4_S5" Value="NO_TIME"/>
			<Parameter Name="DT_S5_START" Value="NO_TIME"/>
		</FB>
		<SubApp Name="NumbAnzeig" Type="Uebung_039_sub_NumbAnzeig" x="-8766.67" y="-986.67">
		</SubApp>
		<FB Name="SoftKey_F1_UP" Type="IE" x="-14040" y="-353.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<SubApp Name="Q1" Type="Uebung_039a_sub_Outputs" x="-7600" y="-266.67">
			<Parameter Name="u16ObjId" Value="SoftKey_F8"/>
		</SubApp>
		<SubApp Name="Q2" Type="Uebung_039a_sub_Outputs" x="-7600" y="666.67">
			<Parameter Name="u16ObjId" Value="SoftKey_F2"/>
		</SubApp>
		<EventConnections>
			<Connection Source="DigitalInput_DOWN_I1.IND" Destination="sequence_05.S1_S2" dx1="313.33"/>
			<Connection Source="DigitalInput_DOWN_I2.IND" Destination="sequence_05.S2_S3" dx1="380"/>
			<Connection Source="DigitalInput_DOWN_I3.IND" Destination="sequence_05.S4_S5" dx1="446.67"/>
			<Connection Source="DigitalInput_DOWN_I4.IND" Destination="sequence_05.S5_START" dx1="513.33"/>
			<Connection Source="sequence_05.CNF" Destination="NumbAnzeig.CNF" dx1="73.33"/>
			<Connection Source="SoftKey_F1_UP.IND" Destination="sequence_05.START_S1" dx1="1313.33"/>
			<Connection Source="sequence_05.EO_S1" Destination="Q1.SET" dx1="986.67"/>
			<Connection Source="sequence_05.EO_S2" Destination="Q2.SET" dx1="1053.33"/>
			<Connection Source="sequence_05.EO_S4" Destination="Q2.RESET" dx1="906.67"/>
			<Connection Source="sequence_05.EO_S5" Destination="Q1.RESET" dx1="986.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="sequence_05.STATE_NR" Destination="NumbAnzeig.STATE_NR" dx1="340"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="sequence_05.timeOut" Destination="E_TimeOut.TimeOutSocket" dx1="73.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
