<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039a_sub_Outputs" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2024-03-03">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="SET" Type="Event" Comment="Set Output" >
				<Attribute Name="YPOSITION" Type="INT" Value="132"/>
			</SubAppEvent>
			<SubAppEvent Name="RESET" Type="Event" Comment="Reset Output" >
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID Softkey/Button"  InitialValue="ID_NULL">
				<Attribute Name="YPOSITION" Type="INT" Value="36"/>
			</VarDeclaration>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="QX" Type="QX" x="-853.33" y="-633.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<SubApp Name="GreenWhiteBackground" Type="GreenWhiteBackground" x="380" y="-260">
		</SubApp>
		<FB Name="E_SWITCH" Type="E_SWITCH" x="-3733.33" y="-266.67">
		</FB>
		<FB Name="E_SR" Type="E_SR" x="-2240" y="-266.67">
		</FB>
		<FB Name="IE" Type="IE" x="-5200" y="-1066.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="QX.INITO" Destination="GreenWhiteBackground.INIT" dx1="266.67"/>
			<Connection Source="QX.CNF" Destination="GreenWhiteBackground.REQ" dx1="233.33"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_SR.S"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_SR.R"/>
			<Connection Source="IE.INITO" Destination="QX.INIT" dx1="900"/>
			<Connection Source="IE.IND" Destination="E_SWITCH.EI" dx1="700"/>
			<Connection Source="E_SR.EO" Destination="QX.REQ" dx1="460"/>
			<Connection Source="SET" Destination="E_SR.S" dx1="4220"/>
			<Connection Source="RESET" Destination="E_SR.R" dx1="4306.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground.u16ObjId" dx1="6386.67"/>
			<Connection Source="E_SR.Q" Destination="E_SWITCH.G" dx1="233.33" dx2="293.33" dy="346.67"/>
			<Connection Source="E_SR.Q" Destination="QX.OUT" dx1="460"/>
			<Connection Source="E_SR.Q" Destination="GreenWhiteBackground.DI1" dx1="1073.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
