<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_038" Comment="Lauflicht 8 reine Zeitsteuerung">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-6666.666666666667" y="-2400.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_TimeOut" Type="E_TimeOut" Comment="" x="-9333.333333333334" y="2133.3333333333335">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" Comment="" x="-6666.666666666667" y="-1333.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="QX" Comment="" x="-6666.666666666667" y="-266.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="QX" Comment="" x="-6666.666666666667" y="800.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" Comment="" x="-11373.333333333334" y="-826.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I4_CLK" Type="IE" Comment="" x="-11373.333333333334" y="186.66666666666669">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q5" Type="QX" Comment="" x="-6666.666666666667" y="1866.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q6" Type="QX" Comment="" x="-6666.666666666667" y="2933.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q7" Type="QX" Comment="" x="-6666.666666666667" y="4000.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q8" Type="QX" Comment="" x="-6666.666666666667" y="5066.666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" Comment="" x="-2666.666666666667" y="-2000.0">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1" Comment=""/>
		</FB>
		<FB Name="F_SINT_TO_UINT" Type="F_SINT_TO_UINT" Comment="" x="-4906.666666666667" y="-1820.0">
		</FB>
		<FB Name="loop" Type="sequence_T_08_loop" Comment="" x="-9613.333333333334" y="-600.0">
			<Parameter Name="DT_S1_S2" Value="T#200ms" Comment=""/>
			<Parameter Name="DT_S2_S3" Value="T#100ms" Comment=""/>
			<Parameter Name="DT_S3_S4" Value="T#200ms" Comment=""/>
			<Parameter Name="DT_S4_S5" Value="T#100ms" Comment=""/>
			<Parameter Name="DT_S5_S6" Value="T#200ms" Comment=""/>
			<Parameter Name="DT_S6_S7" Value="T#100ms" Comment=""/>
			<Parameter Name="DT_S7_S8" Value="T#200ms" Comment=""/>
			<Parameter Name="DT_S8_S1" Value="T#100ms" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalOutput_Q4.INIT" Comment="" dx1="2613.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q3.INIT" Comment="" dx1="2613.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q2.INIT" Comment="" dx1="2613.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="2613.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I1_CLK.INIT" Comment="" dx1="453.33333333333337">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I4_CLK.INIT" Comment="" dx1="1453.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q5.INIT" Comment="" dx1="2346.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q6.INIT" Comment="" dx1="3346.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q7.INIT" Comment="" dx1="2680.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q8.INIT" Comment="" dx1="3346.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="F_SINT_TO_UINT.CNF" Destination="Q_NumericValue.REQ" Comment="" dx1="633.3333333333334"/>
			<Connection Source="INIT" Destination="Q_NumericValue.INIT" Comment="" dx1="4666.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="loop.START_S1" Comment=""/>
			<Connection Source="DigitalInput_I4_CLK.IND" Destination="loop.RESET" Comment="" dx1="420.0" dx2="420.0" dy="0.0"/>
			<Connection Source="loop.CNF" Destination="F_SINT_TO_UINT.REQ" Comment="" dx1="3153.3333333333335" dx2="3153.3333333333335" dy="0.0"/>
			<Connection Source="loop.EO_S1" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="820.0" dx2="820.0" dy="0.0"/>
			<Connection Source="loop.EO_S2" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="986.6666666666667" dx2="986.6666666666667" dy="0.0"/>
			<Connection Source="loop.EO_S3" Destination="DigitalOutput_Q3.REQ" Comment="" dx1="886.6666666666667" dx2="886.6666666666667" dy="0.0"/>
			<Connection Source="loop.EO_S4" Destination="DigitalOutput_Q4.REQ" Comment="" dx1="886.6666666666667" dx2="886.6666666666667" dy="0.0"/>
			<Connection Source="loop.EO_S5" Destination="DigitalOutput_Q5.REQ" Comment="" dx1="853.3333333333334" dx2="853.3333333333334" dy="0.0"/>
			<Connection Source="loop.EO_S6" Destination="DigitalOutput_Q6.REQ" Comment="" dx1="753.3333333333334" dx2="753.3333333333334" dy="0.0"/>
			<Connection Source="loop.EO_S7" Destination="DigitalOutput_Q7.REQ" Comment="" dx1="686.6666666666667" dx2="686.6666666666667" dy="0.0"/>
			<Connection Source="loop.EO_S8" Destination="DigitalOutput_Q8.REQ" Comment="" dx1="620.0" dx2="620.0" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SINT_TO_UINT.OUT" Destination="Q_NumericValue.u32NewValue" Comment="" dx1="286.6666666666667"/>
			<Connection Source="loop.STATE_NR" Destination="F_SINT_TO_UINT.IN" Comment="" dx1="953.3333333333334" dx2="953.3333333333334" dy="0.0"/>
			<Connection Source="loop.DO_S1" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="920.0" dx2="920.0" dy="0.0"/>
			<Connection Source="loop.DO_S2" Destination="DigitalOutput_Q2.OUT" Comment="" dx1="1020.0" dx2="1020.0" dy="0.0"/>
			<Connection Source="loop.DO_S3" Destination="DigitalOutput_Q3.OUT" Comment="" dx1="1053.3333333333335" dx2="1053.3333333333335" dy="0.0"/>
			<Connection Source="loop.DO_S4" Destination="DigitalOutput_Q4.OUT" Comment="" dx1="886.6666666666667" dx2="886.6666666666667" dy="0.0"/>
			<Connection Source="loop.DO_S5" Destination="DigitalOutput_Q5.OUT" Comment="" dx1="820.0" dx2="820.0" dy="0.0"/>
			<Connection Source="loop.DO_S6" Destination="DigitalOutput_Q6.OUT" Comment="" dx1="720.0" dx2="720.0" dy="0.0"/>
			<Connection Source="loop.DO_S7" Destination="DigitalOutput_Q7.OUT" Comment="" dx1="653.3333333333334" dx2="653.3333333333334" dy="0.0"/>
			<Connection Source="loop.DO_S8" Destination="DigitalOutput_Q8.OUT" Comment="" dx1="586.6666666666667" dx2="586.6666666666667" dy="0.0"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="loop.timeOut" Destination="E_TimeOut.TimeOutSocket" Comment="" dx1="80.0" dx2="80.0" dy="226.66666666666669"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
