<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004b" Comment="Toggle Flip-Flop mit IE / Split" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="0" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" x="-4300" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SR" Type="E_SR" x="-1700" y="-800">
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" x="-2600" y="-800">
		</FB>
		<EventConnections>
			<Connection Source="E_SR.EO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_SR.S"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_SR.R"/>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_SWITCH.EI"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="DigitalOutput_Q1.OUT" dx1="626.67"/>
			<Connection Source="E_SR.Q" Destination="E_SWITCH.G" dx1="80" dx2="80" dy="160"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
