<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Ventilsteuerung_Uebung_004b" Comment="Toggle Flip-Flop mit IE / Split" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="mapping" Type="mapping_Uebung_004b" x="-266.67" y="-266.67">
		</SubApp>
		<SubApp Name="functions" Type="Uebung_004b" x="-266.67" y="273.33">
		</SubApp>
	</SubAppNetwork>
</SubAppType>
