<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="SubApp_PC_B" Comment="Geraet B (Station 12, 192.168.1.12): SR/Toggle-Flipflop-Logik (ASRT_AX_T_FF_SR_2) und DigitalOutput_Q1 - 'SUB style', das Protokoll steckt im MyLib::sys-Composite (Uebung_010e_PC_B_OPC_Adapter), nicht in der Resource des Geraets - Adapter-Variante von Training_04, gleiche OPC-UA-Adressen">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-04" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="subapp::Training_06_OPC_UA_RES">
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="VV::const::OPC_UA::myOpcUaAddresses::SR1_SET_LOCAL_METHOD"/>
		<Import declaration="VV::const::OPC_UA::myOpcUaAddresses::SR1_RESET_LOCAL_METHOD"/>
		<Import declaration="VV::const::OPC_UA::myOpcUaAddresses::SR1_TOGGLE_LOCAL_METHOD"/>
		<Import declaration="VV::const::OPC_UA::myOpcUaAddresses::SR1_STATE_REMOTE_WRITE"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="Uebung_010e_PC_B_OPC_Adapter" Type="MyLib::sys::Uebung_010e_PC_B_OPC_Adapter" x="0" y="0">
			<Parameter Name="Output" Value="Output_Q1"/>
			<Parameter Name="ID_SET_METHOD" Value="SR1_SET_LOCAL_METHOD"/>
			<Parameter Name="ID_RESET_METHOD" Value="SR1_RESET_LOCAL_METHOD"/>
			<Parameter Name="ID_TOGGLE_METHOD" Value="SR1_TOGGLE_LOCAL_METHOD"/>
			<Parameter Name="ID_STATE_WRITE" Value="SR1_STATE_REMOTE_WRITE"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
