<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_022" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="REQ" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="HAND" Type="BOOL" Comment=""/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="QX" Type="QX" Comment="" x="-1466.6666666666667" y="-833.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="IX_AUTO" Type="IX" Comment="" x="-4533.333333333334" y="-933.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="IX_HAND" Type="IX" Comment="" x="-4533.333333333334" y="400.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="F_SEL" Type="F_SEL" Comment="" x="-2800.0" y="-266.6666666666667">
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="IX_AUTO.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="IX_AUTO.INITO" Destination="QX.INIT" Comment="" dx1="540.0"/>
			<Connection Source="COLD" Destination="IX_HAND.INIT" Comment="" dx1="1066.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="IX_HAND.INITO" Destination="QX.INIT" Comment="" dx1="686.6666666666667"/>
			<Connection Source="F_SEL.CNF" Destination="QX.REQ" Comment="" dx1="273.33333333333337"/>
			<Connection Source="IX_AUTO.IND" Destination="F_SEL.REQ" Comment="" dx1="520.0"/>
			<Connection Source="IX_HAND.IND" Destination="F_SEL.REQ" Comment="" dx1="520.0"/>
			<Connection Source="REQ" Destination="F_SEL.REQ" Comment="" dx1="1593.3333333333335"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="HAND" Destination="F_SEL.G" Comment="" dx1="1380.0"/>
			<Connection Source="IX_AUTO.IN" Destination="F_SEL.IN0" Comment="" dx1="366.6666666666667"/>
			<Connection Source="IX_HAND.IN" Destination="F_SEL.IN1" Comment="" dx1="393.33333333333337"/>
			<Connection Source="F_SEL.OUT" Destination="QX.OUT" Comment="" dx1="406.6666666666667"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
