<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_017" Comment="Control Audio Signal" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_F1_UP" Type="IE" x="-4533.33" y="-1066.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_CtrlAudioSignal" Type="Q_CtrlAudioSignal" x="-2400" y="-1066.67">
			<Parameter Name="u8NumOfRepit" Value="1"/>
			<Parameter Name="u16Frequency" Value="440"/>
			<Parameter Name="u16OnTimeMs" Value="150"/>
			<Parameter Name="u16OffTimeMs" Value="0"/>
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_F1_UP.INITO" Destination="Q_CtrlAudioSignal.INIT"/>
			<Connection Source="SoftKey_F1_UP.IND" Destination="Q_CtrlAudioSignal.REQ" dx1="720"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
