<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_081" Comment="Beispiel für E_CTD" >
	<Identification Standard="61499-2" Description="Beispiel für E_CTD&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 93" >
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-4886.67" y="-886.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" x="-8006.67" y="-986.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_CTD" Type="E_CTD" x="-6253.33" y="-786.67">
			<Parameter Name="PV" Value="UINT#5"/>
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" x="-8006.67" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_CTD.CD"/>
			<Connection Source="E_CTD.CDO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_CTD.LDO" Destination="DigitalOutput_Q1.REQ" dx1="406.67" dx2="406.67" dy="0"/>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_CTD.LD" dx1="460" dx2="460" dy="0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTD.Q" Destination="DigitalOutput_Q1.OUT" dx1="286.67" dx2="286.67" dy="0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
