<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010b2" Comment="Toggle Flip-Flop mit IE SoftKey_F1" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-3860" y="-346.66">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey_F1_UP" Type="IE" x="-7260" y="-346.66">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" x="-5560" y="0">
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_F1_UP.INITO" Destination="DigitalOutput_Q1.INIT"/>
			<Connection Source="SoftKey_F1_UP.IND" Destination="E_T_FF.CLK" dx1="453.33"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ" dx1="400"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="580"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
