<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_021" Comment="Spiegelabfolge (1)" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-2833.33" y="-500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey_F1_UP" Type="IE" x="-6833.33" y="-500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SR" Type="E_SR" x="-5000" y="-300">
		</FB>
		<FB Name="SoftKey_F2_DOWN" Type="IE" x="-6833.33" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<Comment Comment="START-Knopf"  x="-8500" y="-333.33" width="1373.33" height="366.67"/>
		<Comment Comment="Endlage &#10;"  x="-8500" y="1166.67" width="1373.33" height="366.67"/>
		<EventConnections>
			<Connection Source="SoftKey_F1_UP.IND" Destination="E_SR.S" dx1="573.33"/>
			<Connection Source="SoftKey_F2_DOWN.IND" Destination="E_SR.R" dx1="553.33"/>
			<Connection Source="E_SR.EO" Destination="DigitalOutput_Q1.REQ" dx1="813.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="DigitalOutput_Q1.OUT" dx1="860"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
