<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_086" Comment="Beispiel für E_SWITCH" >
	<Identification Standard="61499-2" Description="Beispiel für E_CTD&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 93" >
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IX" x="-8000" y="100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" x="-6700" y="400">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" dx1="1746.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1.IND" Destination="E_SWITCH.EI" dx1="300"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="E_SWITCH.G"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
