<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_070" Comment="DigitalInput_I1 auf DigitalOutput_Q1">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_SoftkeyMapping_DOWN" Type="UT_SoftkeyMapping_DOWN" Comment="" x="8000" y="-1000">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment=""/>
			<Parameter Name="u16ObjId_2" Value="SoftKey_F2" Comment=""/>
			<Parameter Name="DigitalInput_2" Value="'Ventilsteuerung.functions.SoftKey_F2_DOWN'" Comment=""/>
			<Parameter Name="u16ObjId_3" Value="SoftKey_F3" Comment=""/>
			<Parameter Name="DigitalInput_3" Value="'Ventilsteuerung.functions.SoftKey_F3_DOWN'" Comment=""/>
			<Parameter Name="u16ObjId_4" Value="SoftKey_F8" Comment=""/>
			<Parameter Name="DigitalInput_4" Value="'Ventilsteuerung.functions.SoftKey_F8_DOWN'" Comment=""/>
			<Parameter Name="u16ObjId_5" Value="SoftKey_F9" Comment=""/>
			<Parameter Name="DigitalInput_5" Value="'Ventilsteuerung.functions.SoftKey_F9_DOWN'" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="UT_SoftkeyMapping_DOWN.INIT" Comment="" dx1="5666.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
