<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_070" Comment="WBSD auf UT ausgeben" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="I_WBSD" Type="I_WBSD" x="-5200" y="500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" x="-700" y="500">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_speed"/>
		</FB>
		<EventConnections>
			<Connection Source="I_WBSD.IND" Destination="Q_NumericValue.REQ"/>
			<Connection Source="I_WBSD.INITO" Destination="Q_NumericValue.INIT"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="I_WBSD.WHEELBASEDMACHINESPEED" Destination="Q_NumericValue.u32NewValue" dx1="1433.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
