<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_070" Comment="DigitalInput_I1 auf DigitalOutput_Q1">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="I_WBSD" Type="I_WBSD" Comment="" x="-5213.33" y="453.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" Comment="" x="-680" y="453.33">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_speed" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="I_WBSD.IND" Destination="Q_NumericValue.REQ" Comment=""/>
			<Connection Source="I_WBSD.INITO" Destination="Q_NumericValue.INIT" Comment=""/>
			<Connection Source="INIT" Destination="I_WBSD.INIT" Comment="" dx1="1760">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="I_WBSD.WHEELBASEDMACHINESPEED" Destination="Q_NumericValue.u32NewValue" Comment="" dx1="1433.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
