<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="logiBUS_IXA_TO_CLIENT_OPC" Comment="Digitaler Eingang, aktiver Remote-OPC-UA-Write auf ein ANDERES Geraet via CLIENT_1_0 - &apos;Krauternter-Stil&apos;: das Protokoll (CLIENT_1_0) steckt IM Baustein selbst, nicht in der Resource des Geraets">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-02" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="logiBUS::io::DI::logiBUS_DI"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_S"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="Input" Type="logiBUS::io::DI::logiBUS_DI_S" Comment="Identify the Input Input_I1..I8" InitialValue="logiBUS_DI::Invalid"/>
			<VarDeclaration Name="ID" Type="WSTRING" Comment="Remote-Ziel-Adresse (BOOL, ACTION=WRITE, inkl. opc.tcp://-Endpoint des Zielgeraets)"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="logiBUS_IXA" Type="logiBUS::io::DI::logiBUS_IXA" x="-2800" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_CLIENT_1_0" Type="adapter::net::AX_CLIENT_1_0" x="-600" y="200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<DataConnections>
			<Connection Source="Input" Destination="logiBUS_IXA.Input" dx1="1460">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="ID" Destination="AX_CLIENT_1_0.ID" dx1="1400">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="logiBUS_IXA.IN" Destination="AX_CLIENT_1_0.IN" dx1="1000"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
