<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012c" Comment="String Input und Speichern (WIP)" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_DWORD_TO_UDINT" Type="F_DWORD_TO_UDINT" x="-3100" y="1300">
		</FB>
		<FB Name="InputNumber_I1" Type="ID" x="-4100" y="900">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="INI" Type="INI" x="-900" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="SECTION" Value="SECTION_S1_STORE"/>
			<Parameter Name="KEY" Value="KEY_S1_STORE"/>
			<Parameter Name="VALUE" Value="STRING#'Test'"/>
			<Parameter Name="DEFAULT_VALUE" Value="STRING#'Test'"/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_StringValue" x="1100" y="900">
			<Parameter Name="u16ObjId" Value="DefaultPool::InputNumber_I1"/>
		</FB>
		<FB Name="CbVtStatus" Type="CbVtStatus" x="-500" y="-1000">
			<Parameter Name="STATUS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8Instance" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="qWsActive" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="wPage" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="EI_TO_E" Type="EI_TO_E" x="-1900" y="0">
		</FB>
		<EventConnections>
			<Connection Source="InputNumber_I1.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="300"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="INI.SET" dx1="253.33"/>
			<Connection Source="INI.GETO" Destination="Q_NumericValue.REQ" dx1="486.67"/>
			<Connection Source="CbVtStatus.IND" Destination="Q_NumericValue.REQ" dx1="773.33"/>
			<Connection Source="EI_TO_E.OUT" Destination="INI.GET" dx1="193.33"/>
			<Connection Source="INI.INITO" Destination="EI_TO_E.IN" dx1="80" dx2="80" dy="-993.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="InputNumber_I1.IN" Destination="F_DWORD_TO_UDINT.IN"/>
			<Connection Source="INI.VALUEO" Destination="Q_NumericValue.pau8String" dx1="493.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
