<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020a" Comment="DigitalInput_I1 auf DigitalOutput_Q1" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-2673.33" y="1713.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" x="-6400" y="1600">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" x="-5160" y="1826.67">
		</FB>
		<FB Name="E_RS" Type="E_RS" x="-3960" y="1826.67">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="E_SWITCH.EI" dx1="306.67"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_RS.R"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_RS.S"/>
			<Connection Source="E_RS.EO" Destination="DigitalOutput_Q1.REQ" dx1="460"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="E_SWITCH.G" dx1="80"/>
			<Connection Source="E_RS.Q" Destination="DigitalOutput_Q1.OUT" dx1="73.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
