<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_006a2" Comment="2x SR&amp;T-Flip-Flop mit IE" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-1473.34" y="-1020">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" x="-4540" y="-913.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" x="-4540" y="113.34">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_T_FF_SR_Q1" Type="E_T_FF_SR" x="-2840" y="-913.33">
		</FB>
		<FB Name="DigitalInput_I3_CLK" Type="IE" x="-4200" y="-2380">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_T_FF_SR_Q2" Type="E_T_FF_SR" x="-2833.33" y="113.34">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" x="-1473.34" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="E_T_FF_SR_Q1.EO" Destination="DigitalOutput_Q1.REQ" dx1="346.67"/>
			<Connection Source="E_T_FF_SR_Q2.EO" Destination="DigitalOutput_Q2.REQ" dx1="340"/>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_T_FF_SR_Q1.CLK"/>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_T_FF_SR_Q2.CLK"/>
			<Connection Source="DigitalInput_I3_CLK.IND" Destination="E_T_FF_SR_Q2.R" dx1="320"/>
			<Connection Source="DigitalInput_I3_CLK.IND" Destination="E_T_FF_SR_Q1.R" dx1="320"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF_SR_Q1.Q" Destination="DigitalOutput_Q1.OUT" dx1="346.67"/>
			<Connection Source="E_T_FF_SR_Q2.Q" Destination="DigitalOutput_Q2.OUT" dx1="340"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
