<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_093" Comment="Beispiel für E_TABLE" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0" >
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-200" y="-500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_TABLE" Type="E_TABLE" x="-3100" y="-200">
			<Parameter Name="DT" Value="[T#0s, T#2s, T#3s, T#4s]"/>
			<Parameter Name="N" Value="8"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="IE" x="-5300" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" x="-1800" y="-200">
		</FB>
		<Comment Comment="E_TRAIN wird 8 Events ausgeben, das erste 1s nach dem Click, das letzte 8s nach dem Click"  x="-3400" y="700" width="1400" height="600"/>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_TABLE.START"/>
			<Connection Source="E_TABLE.EO" Destination="E_T_FF.CLK"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ" dx1="240"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
