<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_082" Comment="Beispiel für E_CTUD" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0&#10;   &#10;Beispiel für E_CTD&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 94" >
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-7600" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" x="-10800" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_CTUD" Type="E_CTUD" x="-9000" y="0">
			<Parameter Name="PV" Value="UINT#5"/>
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" x="-10800" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I3_CLK" Type="IE" x="-10800" y="700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I4_CLK" Type="IE" x="-10800" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" x="-7600" y="800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_CTUD.CU" dx1="413.33"/>
			<Connection Source="E_CTUD.CO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_CTUD.LDO" Destination="DigitalOutput_Q1.REQ" dx1="453.33"/>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_CTUD.CD"/>
			<Connection Source="E_CTUD.RO" Destination="DigitalOutput_Q1.REQ" dx1="453.33"/>
			<Connection Source="DigitalInput_I3_CLK.IND" Destination="E_CTUD.R" dx1="260"/>
			<Connection Source="DigitalInput_I4_CLK.IND" Destination="E_CTUD.LD" dx1="400"/>
			<Connection Source="E_CTUD.LDO" Destination="DigitalOutput_Q2.REQ" dx1="453.33"/>
			<Connection Source="E_CTUD.CO" Destination="DigitalOutput_Q2.REQ" dx1="453.33"/>
			<Connection Source="E_CTUD.RO" Destination="DigitalOutput_Q2.REQ" dx1="453.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTUD.QU" Destination="DigitalOutput_Q1.OUT" dx1="246.67"/>
			<Connection Source="E_CTUD.QD" Destination="DigitalOutput_Q2.OUT" dx1="260"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
