<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_032" Comment="LED Strip Blinkende LED" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_DI" Type="Hutschienenmoped_XL_8_DI" x="-3273.33" y="-933.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="GLOBAL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="ID_NULL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I1" Value="'Ventilsteuerung.functions.BUTTON_GREEN'"/>
			<Parameter Name="DigitalInput_I2" Value="'Ventilsteuerung.functions.BUTTON_YELLOW'"/>
			<Parameter Name="DigitalInput_I3" Value="'Ventilsteuerung.functions.BUTTON_RED'"/>
			<Parameter Name="DigitalInput_I4" Value="'Ventilsteuerung.functions.BUTTON_BLUE'"/>
			<Parameter Name="DigitalInput_I5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_YELLOW" Type="Hutschienenmoped_XL_1_LED_strip" x="-3600" y="933.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_YELLOW"/>
			<Parameter Name="LED_5HZ" Value="'Ventilsteuerung.functions.LED_YELLOW_5HZ'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_GREEN" Type="Hutschienenmoped_XL_1_LED_strip" x="-3600" y="133.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_GREEN"/>
			<Parameter Name="LED_5HZ" Value="'Ventilsteuerung.functions.LED_GREEN_5HZ'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_RED" Type="Hutschienenmoped_XL_1_LED_strip" x="-3600" y="1733.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_RED"/>
			<Parameter Name="LED_5HZ" Value="'Ventilsteuerung.functions.LED_RED_5HZ'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_BLUE" Type="Hutschienenmoped_XL_1_LED_strip" x="-3600" y="2533.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_BLUE"/>
			<Parameter Name="LED_5HZ" Value="'Ventilsteuerung.functions.LED_BLUE_5HZ'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
	</SubAppNetwork>
</SubAppType>
