<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_032" Comment="LED Strip Blinkende LED" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="LED_GREEN_5HZ" Type="QX" x="-1500" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="BUTTON_GREEN" Type="IX" x="-4500" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="BUTTON_YELLOW" Type="IX" x="-4500" y="100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="LED_YELLOW_5HZ" Type="QX" x="-1400" y="200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="BUTTON_RED" Type="IX" x="-4500" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="LED_RED_5HZ" Type="QX" x="-1400" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="BUTTON_BLUE" Type="IX" x="-4500" y="2600">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="LED_BLUE_5HZ" Type="QX" x="-1400" y="2700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="BUTTON_GREEN.IND" Destination="LED_GREEN_5HZ.REQ"/>
			<Connection Source="BUTTON_YELLOW.IND" Destination="LED_YELLOW_5HZ.REQ"/>
			<Connection Source="BUTTON_RED.IND" Destination="LED_RED_5HZ.REQ"/>
			<Connection Source="BUTTON_BLUE.IND" Destination="LED_BLUE_5HZ.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="BUTTON_GREEN.IN" Destination="LED_GREEN_5HZ.OUT"/>
			<Connection Source="BUTTON_YELLOW.IN" Destination="LED_YELLOW_5HZ.OUT"/>
			<Connection Source="BUTTON_RED.IN" Destination="LED_RED_5HZ.OUT"/>
			<Connection Source="BUTTON_BLUE.IN" Destination="LED_BLUE_5HZ.OUT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
