<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_032" Comment="LED Strip Blinkende LED" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="LED_GREEN_5HZ" Type="QX" x="-1466.67" y="-833.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="BUTTON_GREEN" Type="IX" x="-4533.33" y="-946.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="BUTTON_YELLOW" Type="IX" x="-4500" y="220">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="LED_YELLOW_5HZ" Type="QX" x="-1433.33" y="333.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="BUTTON_RED" Type="IX" x="-4506.67" y="1493.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="LED_RED_5HZ" Type="QX" x="-1440" y="1606.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="BUTTON_BLUE" Type="IX" x="-4533.33" y="2666.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="LED_BLUE_5HZ" Type="QX" x="-1466.67" y="2780">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="BUTTON_GREEN.INITO" Destination="LED_GREEN_5HZ.INIT" dx1="1200"/>
			<Connection Source="BUTTON_GREEN.IND" Destination="LED_GREEN_5HZ.REQ" dx1="1186.67"/>
			<Connection Source="BUTTON_YELLOW.IND" Destination="LED_YELLOW_5HZ.REQ" dx1="1186.67"/>
			<Connection Source="BUTTON_YELLOW.INITO" Destination="LED_YELLOW_5HZ.INIT" dx1="1200"/>
			<Connection Source="BUTTON_RED.IND" Destination="LED_RED_5HZ.REQ" dx1="1186.67"/>
			<Connection Source="BUTTON_RED.INITO" Destination="LED_RED_5HZ.INIT" dx1="1200"/>
			<Connection Source="BUTTON_BLUE.IND" Destination="LED_BLUE_5HZ.REQ" dx1="1186.67"/>
			<Connection Source="BUTTON_BLUE.INITO" Destination="LED_BLUE_5HZ.INIT" dx1="1193.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="BUTTON_GREEN.IN" Destination="LED_GREEN_5HZ.OUT" dx1="1186.67"/>
			<Connection Source="BUTTON_YELLOW.IN" Destination="LED_YELLOW_5HZ.OUT" dx1="1186.67"/>
			<Connection Source="BUTTON_RED.IN" Destination="LED_RED_5HZ.OUT" dx1="1186.67"/>
			<Connection Source="BUTTON_BLUE.IN" Destination="LED_BLUE_5HZ.OUT" dx1="1186.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
