<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_103" Comment="DigitalInput_I1 auf DigitalOutput_Q1, mit Plug and Socket" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IXA" x="-100" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QXA" x="6500" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_DEMUX_3" Type="io::adp::selection::AX_DEMUX_3" x="1600" y="0">
		</FB>
		<FB Name="AX_MUX_3" Type="io::adp::selection::AX_MUX_3" x="5000" y="0">
		</FB>
		<FB Name="ID" Type="ID" x="0" y="-1400">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="C1" Type="F_DWORD_TO_UDINT" x="1200" y="-1100">
		</FB>
		<FB Name="C2" Type="F_UDINT_TO_UINT" x="2600" y="-1100">
		</FB>
		<SubApp Name="rastend" Type="FBs::Uebungen::Uebung_103::subapp::rastend" x="3260" y="200">
		</SubApp>
		<SubApp Name="tastend" Type="FBs::Uebungen::Uebung_103::subapp::tastend" x="3260" y="-300">
		</SubApp>
		<SubApp Name="tastend_TON_5s" Type="FBs::Uebungen::Uebung_103::subapp::tastend_TON_5s" x="3100" y="700">
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" dx1="2986.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" dx1="6293.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="ID.IND" Destination="C1.REQ" dx1="253.33"/>
			<Connection Source="C1.CNF" Destination="C2.REQ"/>
			<Connection Source="C2.CNF" Destination="AX_DEMUX_3.REQ" dx1="80" dx2="80" dy="746.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="C2.CNF" Destination="AX_MUX_3.REQ" dx1="440">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="tastend_TON_5s.INIT" dx1="4533.33" dx2="4533.33" dy="0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="tastend.INIT" dx1="4666.67" dx2="4666.67" dy="0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="rastend.INIT" dx1="4680" dx2="4680" dy="0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="ID.INIT" dx1="2480">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="ID.IN" Destination="C1.IN" dx1="253.33"/>
			<Connection Source="C1.OUT" Destination="C2.IN"/>
			<Connection Source="C2.OUT" Destination="AX_DEMUX_3.K" dx1="80" dx2="80" dy="746.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="C2.OUT" Destination="AX_MUX_3.K" dx1="440">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="AX_MUX_3.OUT" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_DEMUX_3.IN"/>
			<Connection Source="AX_DEMUX_3.OUT0" Destination="tastend.IN" dx1="333.33" dx2="333.33" dy="0"/>
			<Connection Source="tastend.OUT" Destination="AX_MUX_3.IN0" dx1="593.33" dx2="593.33" dy="0"/>
			<Connection Source="AX_DEMUX_3.OUT2" Destination="tastend_TON_5s.IN" dx1="326.67" dx2="326.67" dy="0"/>
			<Connection Source="tastend_TON_5s.OUT" Destination="AX_MUX_3.IN2" dx1="400" dx2="400" dy="0"/>
			<Connection Source="rastend.OUT" Destination="AX_MUX_3.IN1"/>
			<Connection Source="AX_DEMUX_3.OUT1" Destination="rastend.IN"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
