<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_043" Comment="Scaling Function Block with limits Testing" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_CLK_I1" Type="IE" x="-4986.67" y="-460">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SCALE_LIM" Type="signalprocessing::SCALE_LIM" x="-2606.67" y="-226.67">
			<Parameter Name="IN" Value="50.0"/>
			<Parameter Name="MAX_IN" Value="100.0"/>
			<Parameter Name="MIN_IN" Value="0.0"/>
			<Parameter Name="MAX_IN_LIM" Value="99.0"/>
			<Parameter Name="MIN_IN_LIM" Value="1.0"/>
			<Parameter Name="MAX_OUT" Value="85.0"/>
			<Parameter Name="MIN_OUT" Value="30.0"/>
			<Parameter Name="MAX_OUT_FIX" Value="100.0"/>
			<Parameter Name="MIN_OUT_FIX" Value="0.0"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="SCALE_LIM.REQ" dx1="793.33" dx2="793.33" dy="0"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
