<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_043" Comment="Scaling Function Block with limits Testing">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1_CLK" Type="IE" Comment="" x="-4986.67" y="-460">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="SCALE_LIM" Type="signalprocessing::SCALE_LIM" Comment="" x="-2606.67" y="-226.67">
			<Parameter Name="IN" Value="50.0" Comment=""/>
			<Parameter Name="MAX_IN" Value="100.0" Comment=""/>
			<Parameter Name="MIN_IN" Value="0.0" Comment=""/>
			<Parameter Name="MAX_IN_LIM" Value="99.0" Comment=""/>
			<Parameter Name="MIN_IN_LIM" Value="1.0" Comment=""/>
			<Parameter Name="MAX_OUT" Value="85.0" Comment=""/>
			<Parameter Name="MIN_OUT" Value="30.0" Comment=""/>
			<Parameter Name="MAX_OUT_FIX" Value="100.0" Comment=""/>
			<Parameter Name="MIN_OUT_FIX" Value="0.0" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1_CLK.INIT" Comment="" dx1="1920">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="SCALE_LIM.REQ" Comment="" dx1="793.33" dx2="793.33" dy="0"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
