<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_019a" Comment="Umschalten einer Maske">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_CLK_I1" Type="IE" x="-8100" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_ActiveMask" Type="Q_ActiveMask" x="-2100" y="-300">
			<Parameter Name="u16WorkSetId" Value="DefaultPool::WorkingSet_0"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="IE" x="-8100" y="400">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="F_SEL_E_2" Type="F_SEL_E_2" x="-4800" y="-200">
			<Parameter Name="IN0" Value="DefaultPool::DataMask_M1"/>
			<Parameter Name="IN1" Value="DefaultPool::DataMask_M2"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="F_SEL_E_2.REQ0"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="F_SEL_E_2.REQ1" dx1="1253.33"/>
			<Connection Source="F_SEL_E_2.CNF" Destination="Q_ActiveMask.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SEL_E_2.OUT" Destination="Q_ActiveMask.u16NewMaskId"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
