<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_080f" Comment="Beispiel für E_CTU">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::ObjectPointer_Horse"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_00"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_01"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_02"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_03"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_04"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_05"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_06"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_07"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_08"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_09"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_10"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_11"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_12"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_13"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_14"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_15"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_16"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_17"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_18"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_19"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_20"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_21"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_22"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_23"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_24"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_25"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_26"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_27"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_28"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_29"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_30"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_31"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::ObjectPointer_Horse"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_00"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_01"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_02"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_03"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_04"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_05"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_06"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_07"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_08"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_09"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_10"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_11"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_12"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_13"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_14"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_15"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_16"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_17"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_18"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_19"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_20"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_21"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_22"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_23"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_24"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_25"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_26"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_27"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_28"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_29"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_30"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_31"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-2900" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-8000" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_CTU" Type="iec61499::events::E_CTU" x="-6200" y="-800">
			<Parameter Name="PV" Value="UINT#5"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-8000" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_MERGE_2" Type="iec61499::events::E_MERGE_2" x="-5100" y="-800">
		</FB>
		<Comment Comment="da UDINT immer einen UINT aufnehmen kann, ist hier der UINT_TO_UDINT verzichtbar&#10;" x="-5300" y="900" width="1600" height="400"/>
		<Comment Comment="E_MERGE kann man weglassen, führt hier aber zu viel saubererem Code. (sonst muss man 4 Linien kreuzen)" x="-5500" y="-1500" width="1600" height="400"/>
		<FB Name="Q_NumericValue_1" Type="isobus::UT::Q::Q_NumericValue" x="-900" y="300">
			<Parameter Name="u16ObjId" Value="ObjectPointer_Horse"/>
		</FB>
		<FB Name="F_MUX_32" Type="iec61131::selection::F_MUX_32" x="-2900" y="500">
			<Parameter Name="IN1" Value="frame_00"/>
			<Parameter Name="IN2" Value="frame_01"/>
			<Parameter Name="IN3" Value="frame_02"/>
			<Parameter Name="IN4" Value="frame_03"/>
			<Parameter Name="IN5" Value="frame_04"/>
			<Parameter Name="IN6" Value="frame_05"/>
			<Parameter Name="IN7" Value="frame_06"/>
			<Parameter Name="IN8" Value="frame_07"/>
			<Parameter Name="IN9" Value="frame_08"/>
			<Parameter Name="IN10" Value="frame_09"/>
			<Parameter Name="IN11" Value="frame_10"/>
			<Parameter Name="IN12" Value="frame_11"/>
			<Parameter Name="IN13" Value="frame_12"/>
			<Parameter Name="IN14" Value="frame_13"/>
			<Parameter Name="IN15" Value="frame_14"/>
			<Parameter Name="IN16" Value="frame_15"/>
			<Parameter Name="IN17" Value="frame_16"/>
			<Parameter Name="IN18" Value="frame_17"/>
			<Parameter Name="IN19" Value="frame_18"/>
			<Parameter Name="IN20" Value="frame_19"/>
			<Parameter Name="IN21" Value="frame_20"/>
			<Parameter Name="IN22" Value="frame_21"/>
			<Parameter Name="IN23" Value="frame_22"/>
			<Parameter Name="IN24" Value="frame_23"/>
			<Parameter Name="IN25" Value="frame_24"/>
			<Parameter Name="IN26" Value="frame_25"/>
			<Parameter Name="IN27" Value="frame_26"/>
			<Parameter Name="IN28" Value="frame_27"/>
			<Parameter Name="IN29" Value="frame_28"/>
			<Parameter Name="IN30" Value="frame_29"/>
			<Parameter Name="IN31" Value="frame_30"/>
			<Parameter Name="IN32" Value="frame_31"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_CTU.CU" dx1="453.33"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_CTU.R" dx1="273.33"/>
			<Connection Source="E_CTU.CUO" Destination="E_MERGE_2.EI1"/>
			<Connection Source="E_CTU.RO" Destination="E_MERGE_2.EI2"/>
			<Connection Source="E_MERGE_2.EO" Destination="DigitalOutput_Q1.REQ" dx1="746.67"/>
			<Connection Source="F_MUX_32.CNF" Destination="Q_NumericValue_1.REQ" dx1="420"/>
			<Connection Source="E_MERGE_2.EO" Destination="F_MUX_32.REQ" dx1="746.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTU.Q" Destination="DigitalOutput_Q1.OUT" dx1="286.67"/>
			<Connection Source="F_MUX_32.OUT" Destination="Q_NumericValue_1.u32NewValue" dx1="553.33"/>
			<Connection Source="E_CTU.CV" Destination="F_MUX_32.K" dx1="80"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
