<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012m_sub" Comment="String Input und Speichern INI mit Subapp">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-31" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="KEY" Type="STRING" Comment="Key name."/>
			<VarDeclaration Name="u16ObjId" Type="UINT" InitialValue="ID_NULL"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="VALUEO" Type="STRING"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="StringValue_IS" Type="isobus::UT::io::StringValue::StringValue_IS" x="-1600" y="100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="NVS" Type="logiBUS::storage::esp32_nvs::NVS" x="2100" y="100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="DEFAULT_VALUE" Value="STRING#''"/>
		</FB>
		<FB Name="Q_StringValue" Type="isobus::UT::Q::Q_StringValue" x="4600" y="300">
		</FB>
		<EventConnections>
			<Connection Source="StringValue_IS.IND" Destination="NVS.SET" dx1="380"/>
			<Connection Source="NVS.SETO" Destination="IND" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="NVS.GETO" Destination="Q_StringValue.REQ" dx1="546.67"/>
			<Connection Source="NVS.GETO" Destination="IND" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="NVS.INITO" Destination="NVS.GET" dx1="80" dx2="80" dy="-580"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="StringValue_IS.IN" Destination="NVS.VALUE"/>
			<Connection Source="u16ObjId" Destination="Q_StringValue.u16ObjId" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="KEY" Destination="NVS.KEY" dx1="2066.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="NVS.VALUEO" Destination="Q_StringValue.pau8String" dx1="486.67"/>
			<Connection Source="NVS.VALUEO" Destination="VALUEO" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId" Destination="StringValue_IS.u16ObjId" dx1="1793.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
