<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004b3c" Comment="Zwei gegenseitig verriegelte Toggle-Flip-Flops unter Verwendung von bidirektionalen Adaptern">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="0" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-5900" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QX" x="0" y="100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-5900" y="200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<SubApp Name="Uebung_004b3b_sub1" Type="Uebungen::Uebung_004b3c_sub" x="-4100" y="-900">
		</SubApp>
		<SubApp Name="Uebung_004b3b_sub2" Type="Uebungen::Uebung_004b3c_sub" x="-2700" y="400">
		</SubApp>
		<Comment Comment="durch den Einsatz eines Bidirektionalen Adapters: 1 Verbindung REICHT ! " x="-2600" y="1400" width="1000" height="500"/>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="Uebung_004b3b_sub2.IND" dx1="386.67"/>
			<Connection Source="Uebung_004b3b_sub1.EO" Destination="DigitalOutput_Q1.REQ" dx1="793.33"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="Uebung_004b3b_sub1.IND" dx1="440"/>
			<Connection Source="Uebung_004b3b_sub2.EO" Destination="DigitalOutput_Q2.REQ" dx1="846.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Uebung_004b3b_sub2.Q" Destination="DigitalOutput_Q2.OUT" dx1="846.67"/>
			<Connection Source="Uebung_004b3b_sub1.Q" Destination="DigitalOutput_Q1.OUT" dx1="793.33"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="Uebung_004b3b_sub1.PLUG" Destination="Uebung_004b3b_sub2.SOCKET" dx1="160"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
