<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_080" Comment="Beispiel für E_CTU">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-2900" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-8000" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_CTU" Type="iec61499::events::E_CTU" x="-6200" y="-800">
			<Parameter Name="PV" Value="UINT#5"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-8000" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="-3200" y="200">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<FB Name="E_MERGE_2" Type="iec61499::events::E_MERGE_2" x="-5100" y="-800">
		</FB>
		<Comment Comment="da UDINT immer einen UINT aufnehmen kann, ist hier der UINT_TO_UDINT verzichtbar&#10;" x="-5300" y="900" width="1600" height="400"/>
		<Comment Comment="E_MERGE kann man weglassen, führt hier aber zu viel saubererem Code. (sonst muss man 4 Linien kreuzen)" x="-5500" y="-1500" width="1600" height="400"/>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_CTU.CU" dx1="453.33"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_CTU.R" dx1="273.33"/>
			<Connection Source="E_CTU.CUO" Destination="E_MERGE_2.EI1"/>
			<Connection Source="E_CTU.RO" Destination="E_MERGE_2.EI2"/>
			<Connection Source="E_MERGE_2.EO" Destination="DigitalOutput_Q1.REQ" dx1="746.67"/>
			<Connection Source="E_MERGE_2.EO" Destination="Q_NumericValue.REQ" dx1="173.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTU.Q" Destination="DigitalOutput_Q1.OUT" dx1="286.67"/>
			<Connection Source="E_CTU.CV" Destination="Q_NumericValue.u32NewValue" dx1="80"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
