<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_203" Comment="Interlock: ILOCK_SWITCH (Umschalt-Priorität Last-Wins)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-19" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-4000" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IX" x="-4000" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="ILOCK" Type="logiBUS::signalprocessing::interlock::ILOCK_SWITCH" x="-1800" y="0">
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="400" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QX" x="400" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="ILOCK.EI_UP" dx1="200"/>
			<Connection Source="DigitalInput_I2.IND" Destination="ILOCK.EI_DOWN" dx1="200"/>
			<Connection Source="ILOCK.EO_UP" Destination="DigitalOutput_Q1.REQ" dx1="200"/>
			<Connection Source="ILOCK.EO_DOWN" Destination="DigitalOutput_Q2.REQ" dx1="200"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="ILOCK.DI_UP" dx1="100"/>
			<Connection Source="DigitalInput_I2.IN" Destination="ILOCK.DI_DOWN" dx1="100"/>
			<Connection Source="ILOCK.DO_UP" Destination="DigitalOutput_Q1.OUT" dx1="100"/>
			<Connection Source="ILOCK.DO_DOWN" Destination="DigitalOutput_Q2.OUT" dx1="100"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
