<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_080b" Comment="Beispiel für E_CTU mit E_SPLIT für Event-Verdoppelung und Terminal-Ausgabe">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-04-21" Remarks="Added terminal output for counter value and restored logiBUS_IE"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="2500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-8000" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_CTU" Type="iec61499::events::E_CTU" x="-2300" y="-800"/>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-8000" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_SPLIT" Type="iec61499::events::E_SPLIT" x="-5000" y="-1000"/>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="2500" y="800">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<FB Name="F_UINT_TO_UDINT" Type="iec61131::conversion::F_UINT_TO_UDINT" x="500" y="800"/>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_SPLIT.EI" dx1="753.33"/>
			<Connection Source="E_SPLIT.EO1" Destination="E_CTU.CU" dx1="400"/>
			<Connection Source="E_SPLIT.EO2" Destination="E_CTU.CU" dx1="400"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_CTU.R" dx1="3553.33"/>
			<Connection Source="E_CTU.CUO" Destination="DigitalOutput_Q1.REQ" dx1="100"/>
			<Connection Source="E_CTU.RO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_CTU.CUO" Destination="F_UINT_TO_UDINT.REQ" dx1="100"/>
			<Connection Source="E_CTU.RO" Destination="F_UINT_TO_UDINT.REQ" dx1="100"/>
			<Connection Source="F_UINT_TO_UDINT.CNF" Destination="Q_NumericValue.REQ" dx1="200"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTU.Q" Destination="DigitalOutput_Q1.OUT" dx1="453.33"/>
			<Connection Source="E_CTU.CV" Destination="F_UINT_TO_UDINT.IN" dx1="200"/>
			<Connection Source="F_UINT_TO_UDINT.OUT" Destination="Q_NumericValue.u32NewValue" dx1="200"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
