<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_007d2" Comment="Blinker mit E_CYCLE und E_T_FF">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="400" y="200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="E_CYCLE" Type="iec61499::events::E_CYCLE" x="-5200" y="500">
			<Parameter Name="DT" Value="T#1ms"/>
		</FB>
		<FB Name="FB_RANDOM" Type="eclipse4diac::utils::FB_RANDOM" x="-4100" y="400">
			<Parameter Name="SEED" Value="0"/>
		</FB>
		<FB Name="F_GT" Type="iec61131::comparison::F_GT" x="-2400" y="500">
			<Parameter Name="IN2" Value="REAL#0.49"/>
		</FB>
		<FB Name="E_D_FF_TMIN" Type="iec61499::events::E_D_FF_TMIN" x="-1300" y="400">
			<Parameter Name="Tmin" Value="T#3s"/>
		</FB>
		<EventConnections>
			<Connection Source="E_CYCLE.EO" Destination="FB_RANDOM.REQ" dx1="206.67"/>
			<Connection Source="FB_RANDOM.CNF" Destination="F_GT.REQ" dx1="740"/>
			<Connection Source="F_GT.CNF" Destination="E_D_FF_TMIN.CLK" dx1="260"/>
			<Connection Source="E_D_FF_TMIN.EO" Destination="DigitalOutput_Q1.REQ" dx1="446.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="FB_RANDOM.VAL" Destination="F_GT.IN1" dx1="446.67"/>
			<Connection Source="F_GT.OUT" Destination="E_D_FF_TMIN.D" dx1="313.33"/>
			<Connection Source="E_D_FF_TMIN.Q" Destination="DigitalOutput_Q1.OUT" dx1="446.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
