<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_160b" Comment="Motor Links/Rechtslauf Automatisierung IE">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q5"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q56"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q6"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_PRESS_DOWN"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_PRESS_DOWN"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_PRESS_DOWN"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q6" Type="logiBUS::io::DQ::logiBUS_QX" x="-6300" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q6"/>
		</FB>
		<FB Name="E_SR_B" Type="iec61499::events::E_SR" x="-9300" y="1400">
		</FB>
		<FB Name="OR_2_BOOL" Type="iec61131::bitwiseOperators::OR_2_BOOL" x="-7800" y="700">
		</FB>
		<FB Name="E_SR_A" Type="iec61499::events::E_SR" x="-9300" y="-800">
		</FB>
		<FB Name="DigitalOutput_Q5" Type="logiBUS::io::DQ::logiBUS_QX" x="-6300" y="-700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q5"/>
		</FB>
		<FB Name="DigitalOutput_Q56" Type="logiBUS::io::DQ::logiBUS_QX" x="-6300" y="400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q56"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-11000" y="100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_PRESS_DOWN"/>
		</FB>
		<FB Name="DigitalInput_CLK_I3" Type="logiBUS::io::DI::logiBUS_IE" x="-11000" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="InputEvent" Value="BUTTON_PRESS_DOWN"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-11000" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_DELAY" Type="iec61499::events::E_DELAY" x="-9600" y="600">
			<Parameter Name="DT" Value="T#50ms"/>
		</FB>
		<EventConnections>
			<Connection Source="E_SR_B.EO" Destination="DigitalOutput_Q6.REQ" dx1="953.33"/>
			<Connection Source="E_SR_A.EO" Destination="DigitalOutput_Q5.REQ" dx1="953.33"/>
			<Connection Source="OR_2_BOOL.CNF" Destination="DigitalOutput_Q56.REQ" dx1="393.33"/>
			<Connection Source="E_SR_B.EO" Destination="OR_2_BOOL.REQ" dx1="553.33"/>
			<Connection Source="E_SR_A.EO" Destination="OR_2_BOOL.REQ" dx1="600"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_SR_A.S" dx1="460"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_SR_A.R" dx1="460"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_DELAY.START" dx1="253.33"/>
			<Connection Source="E_DELAY.EO" Destination="E_SR_B.S" dx1="80" dx2="340" dy="500"/>
			<Connection Source="DigitalInput_CLK_I3.IND" Destination="E_SR_B.R" dx1="406.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR_B.Q" Destination="DigitalOutput_Q6.OUT" dx1="953.33"/>
			<Connection Source="E_SR_A.Q" Destination="DigitalOutput_Q5.OUT" dx1="953.33"/>
			<Connection Source="OR_2_BOOL.OUT" Destination="DigitalOutput_Q56.OUT" dx1="393.33"/>
			<Connection Source="E_SR_A.Q" Destination="OR_2_BOOL.IN1" dx1="373.33"/>
			<Connection Source="E_SR_B.Q" Destination="OR_2_BOOL.IN2" dx1="373.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
