<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012e" Comment="Numeric Value Input PHYS und Speichern INI mit Subapp">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I1_STORE"/>
		<Import declaration="Uebungen::const::NVS::NVS_Keys::SECTION_I1_STORE"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::InputNumber_I1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="Uebung_012c_sub" Type="Uebungen::Uebung_012e_sub" x="-3200" y="1600">
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="SECTION" Value="SECTION_I1_STORE"/>
			<Parameter Name="stObj" Value="InputNumber_I1"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
