<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_001d2" Comment="DigitalInput_I1/2 auf DigitalOutput_Q1/2, als Alternative(Verriegelt) mit Interlock, ohne ECC">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-4700" y="-600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IX" x="-4700" y="1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="ILOCK_SWITCH" Type="logiBUS::signalprocessing::interlock::ILOCK_SWITCH" x="-1900" y="-300">
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="2400" y="-600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QX" x="2500" y="1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="ILOCK_SWITCH.EI_UP" dx1="1000"/>
			<Connection Source="DigitalInput_I2.IND" Destination="ILOCK_SWITCH.EI_DOWN" dx1="1000"/>
			<Connection Source="ILOCK_SWITCH.EO_UP" Destination="DigitalOutput_Q1.REQ" dx1="1500"/>
			<Connection Source="ILOCK_SWITCH.EO_DOWN" Destination="DigitalOutput_Q2.REQ" dx1="1500"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="ILOCK_SWITCH.DI_UP" dx1="1000"/>
			<Connection Source="DigitalInput_I2.IN" Destination="ILOCK_SWITCH.DI_DOWN" dx1="1000"/>
			<Connection Source="ILOCK_SWITCH.DO_UP" Destination="DigitalOutput_Q1.OUT" dx1="1500"/>
			<Connection Source="ILOCK_SWITCH.DO_DOWN" Destination="DigitalOutput_Q2.OUT" dx1="1500"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
