<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004b3b_sub" Comment="Sub-Applikation für ein Toggle-Flip-Flop mit externen RESET-Eingang und SET-Ausgang zur Verriegelung">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-19">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="RESET" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="IND" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="EO" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="SET" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<OutputVars>
			<VarDeclaration Name="Q" Type="BOOL"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_SR_I1" Type="iec61499::events::E_SR" x="1400" y="0">
		</FB>
		<FB Name="E_SWITCH_I1" Type="iec61499::events::E_SWITCH" x="0" y="0">
		</FB>
		<EventConnections>
			<Connection Source="E_SWITCH_I1.EO0" Destination="E_SR_I1.S"/>
			<Connection Source="E_SWITCH_I1.EO1" Destination="E_SR_I1.R"/>
			<Connection Source="RESET" Destination="E_SR_I1.R" dx1="593.33"/>
			<Connection Source="E_SR_I1.EO" Destination="EO" dx1="2000"/>
			<Connection Source="IND" Destination="E_SWITCH_I1.EI" dx1="80" dx2="80" dy="-166.67"/>
			<Connection Source="E_SWITCH_I1.EO0" Destination="SET" dx1="100"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR_I1.Q" Destination="E_SWITCH_I1.G" dx1="80" dx2="80" dy="160"/>
			<Connection Source="E_SR_I1.Q" Destination="Q" dx1="2946.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
