<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_222" Comment="Standard IEC 61131-3 FB_CTUD_LINT (Vor-/Rückwärtszähler, LINT)">
	<Identification Standard="61131-3" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-20" Remarks="initial API and implementation (IEC 61131-3 version)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="FB_CTUD_LINT" Type="iec61131::counters::FB_CTUD_LINT" x="0" y="500">
			<Parameter Name="PV" Value="LINT#10"/>
		</FB>
		<FB Name="Input_CU" Type="logiBUS::io::DI::logiBUS_IX" x="-3000" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="Input_CD" Type="logiBUS::io::DI::logiBUS_IX" x="-3000" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="Input_R" Type="logiBUS::io::DI::logiBUS_IX" x="-3000" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<FB Name="Input_LD" Type="logiBUS::io::DI::logiBUS_IX" x="-3000" y="2000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
		</FB>
		<FB Name="Output_QU" Type="logiBUS::io::DQ::logiBUS_QX" x="3000" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="Output_QD" Type="logiBUS::io::DQ::logiBUS_QX" x="3000" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<EventConnections>
			<Connection Source="Input_CU.IND" Destination="FB_CTUD_LINT.REQ" dx1="600"/>
			<Connection Source="Input_CD.IND" Destination="FB_CTUD_LINT.REQ" dx1="600"/>
			<Connection Source="Input_R.IND" Destination="FB_CTUD_LINT.REQ" dx1="600"/>
			<Connection Source="Input_LD.IND" Destination="FB_CTUD_LINT.REQ" dx1="600"/>
			<Connection Source="FB_CTUD_LINT.CNF" Destination="Output_QU.REQ" dx1="500"/>
			<Connection Source="FB_CTUD_LINT.CNF" Destination="Output_QD.REQ" dx1="500"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Input_CU.IN" Destination="FB_CTUD_LINT.CU" dx1="400"/>
			<Connection Source="Input_CD.IN" Destination="FB_CTUD_LINT.CD" dx1="200"/>
			<Connection Source="Input_R.IN" Destination="FB_CTUD_LINT.R" dx1="200"/>
			<Connection Source="Input_LD.IN" Destination="FB_CTUD_LINT.LD" dx1="400"/>
			<Connection Source="FB_CTUD_LINT.QU" Destination="Output_QU.OUT" dx1="200"/>
			<Connection Source="FB_CTUD_LINT.QD" Destination="Output_QD.OUT" dx1="200"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
