<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004b5" Comment="Toggle Flip-Flop mit IX / E_SWITCH + E_T_FF">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="0" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-4300" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="E_T_FF" Type="iec61499::events::E_T_FF" x="-1700" y="-800">
		</FB>
		<FB Name="E_SWITCH" Type="iec61499::events::E_SWITCH" x="-2600" y="-800">
		</FB>
		<EventConnections>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ" dx1="613.33"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_T_FF.CLK" dx1="120"/>
			<Connection Source="DigitalInput_I1.IND" Destination="E_SWITCH.EI" dx1="406.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="626.67"/>
			<Connection Source="DigitalInput_I1.IN" Destination="E_SWITCH.G" dx1="473.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
