<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_070" Comment="WBSD auf UT ausgeben">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::TECU::DefaultPool_TECU::NumberVariable_Wheel_based_machine_speed"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="I_WBSD" Type="isobus::tecu::I_WBSD" x="-5000" y="500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="540" y="766.67">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_speed"/>
		</FB>
		<FB Name="F_UINT_TO_UDINT" Type="iec61131::conversion::F_UINT_TO_UDINT" x="-2500" y="900"/>
		<EventConnections>
			<Connection Source="F_UINT_TO_UDINT.CNF" Destination="Q_NumericValue.REQ" dx1="66.67"/>
			<Connection Source="I_WBSD.IND" Destination="F_UINT_TO_UDINT.REQ" dx1="66.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_UINT_TO_UDINT.OUT" Destination="Q_NumericValue.u32NewValue" dx1="66.67"/>
			<Connection Source="I_WBSD.WHEELBASEDMACHINESPEED" Destination="F_UINT_TO_UDINT.IN" dx1="66.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
