<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_046" Comment="Ablaufsteuerung 8-Kanal ENDLOS (Event &amp; Zeit)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10;  &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10;  &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-07-05" Remarks="generated solution">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q5"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q6"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q7"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q8"/>
		<Import declaration="logiBUS::utils::sequence::const::sequence::NO_TIME"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-6800" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QX" x="-6800" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="logiBUS::io::DQ::logiBUS_QX" x="-6800" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q3"/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QX" x="-6800" y="2000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="DigitalOutput_Q5" Type="logiBUS::io::DQ::logiBUS_QX" x="-6800" y="3000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q5"/>
		</FB>
		<FB Name="DigitalOutput_Q6" Type="logiBUS::io::DQ::logiBUS_QX" x="-6800" y="4000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q6"/>
		</FB>
		<FB Name="DigitalOutput_Q7" Type="logiBUS::io::DQ::logiBUS_QX" x="-6800" y="5000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q7"/>
		</FB>
		<FB Name="DigitalOutput_Q8" Type="logiBUS::io::DQ::logiBUS_QX" x="-6800" y="6000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q8"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-11600" y="-300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I4" Type="logiBUS::io::DI::logiBUS_IE" x="-11600" y="2700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_TimeOut" Type="iec61499::events::E_TimeOut" x="-9100" y="3500">
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="-3200" y="2400">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<FB Name="F_SINT_TO_UINT" Type="iec61131::conversion::F_SINT_TO_UINT" x="-5600" y="2600">
		</FB>
		<FB Name="sequence_block" Type="logiBUS::utils::sequence::combi::sequence_ET_08_loop" x="-9700" y="1700">
			<Parameter Name="DT_S1_S2" Value="T#1s"/>
			<Parameter Name="DT_S2_S3" Value="T#1s"/>
			<Parameter Name="DT_S3_S4" Value="T#1s"/>
			<Parameter Name="DT_S4_S5" Value="T#1s"/>
			<Parameter Name="DT_S5_S6" Value="T#1s"/>
			<Parameter Name="DT_S6_S7" Value="T#1s"/>
			<Parameter Name="DT_S7_S8" Value="T#1s"/>
			<Parameter Name="DT_S8_S1" Value="T#1s"/>
		</FB>
		<EventConnections>
			<Connection Source="F_SINT_TO_UINT.CNF" Destination="Q_NumericValue.REQ" dx1="733.33"/>
			<Connection Source="sequence_block.CNF" Destination="F_SINT_TO_UINT.REQ" dx1="2540"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="sequence_block.START_S1" dx1="406.67"/>
			<Connection Source="DigitalInput_CLK_I4.IND" Destination="sequence_block.RESET" dx1="253.33"/>
			<Connection Source="sequence_block.EO_S1" Destination="DigitalOutput_Q1.REQ" dx1="240"/>
			<Connection Source="sequence_block.EO_S2" Destination="DigitalOutput_Q2.REQ" dx1="300"/>
			<Connection Source="sequence_block.EO_S3" Destination="DigitalOutput_Q3.REQ" dx1="360"/>
			<Connection Source="sequence_block.EO_S4" Destination="DigitalOutput_Q4.REQ" dx1="420"/>
			<Connection Source="sequence_block.EO_S5" Destination="DigitalOutput_Q5.REQ" dx1="480"/>
			<Connection Source="sequence_block.EO_S6" Destination="DigitalOutput_Q6.REQ" dx1="540"/>
			<Connection Source="sequence_block.EO_S7" Destination="DigitalOutput_Q7.REQ" dx1="600"/>
			<Connection Source="sequence_block.EO_S8" Destination="DigitalOutput_Q8.REQ" dx1="660"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SINT_TO_UINT.OUT" Destination="Q_NumericValue.u32NewValue"/>
			<Connection Source="sequence_block.STATE_NR" Destination="F_SINT_TO_UINT.IN" dx1="566.67"/>
			<Connection Source="sequence_block.DO_S1" Destination="DigitalOutput_Q1.OUT" dx1="280"/>
			<Connection Source="sequence_block.DO_S2" Destination="DigitalOutput_Q2.OUT" dx1="340"/>
			<Connection Source="sequence_block.DO_S3" Destination="DigitalOutput_Q3.OUT" dx1="400"/>
			<Connection Source="sequence_block.DO_S4" Destination="DigitalOutput_Q4.OUT" dx1="460"/>
			<Connection Source="sequence_block.DO_S5" Destination="DigitalOutput_Q5.OUT" dx1="520"/>
			<Connection Source="sequence_block.DO_S6" Destination="DigitalOutput_Q6.OUT" dx1="580"/>
			<Connection Source="sequence_block.DO_S7" Destination="DigitalOutput_Q7.OUT" dx1="640"/>
			<Connection Source="sequence_block.DO_S8" Destination="DigitalOutput_Q8.OUT" dx1="700"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="sequence_block.timeOut" Destination="E_TimeOut.TimeOutSocket" dx1="80" dx2="80" dy="346.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
