<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012g" Comment="Numeric Value Input PHYS und Speichern INI">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I1_STORE"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::InputNumber_I1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="InputNumber_I1" Type="isobus::UT::io::NumericValue::NumericValue_PHYS" x="-4900" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="stObj" Value="InputNumber_I1"/>
		</FB>
		<FB Name="NVS" Type="eclipse4diac::storage::INI" x="-900" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="REAL#0.0"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue_PHYS" x="1600" y="900">
			<Parameter Name="stObj" Value="InputNumber_I1"/>
		</FB>
		<EventConnections>
			<Connection Source="NVS.GETO" Destination="Q_NumericValue.REQ" dx1="740"/>
			<Connection Source="NVS.INITO" Destination="NVS.GET" dx1="80" dx2="80" dy="-506.67"/>
			<Connection Source="InputNumber_I1.IND" Destination="NVS.SET"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="NVS.VALUEO" Destination="Q_NumericValue.rPhys" dx1="733.33"/>
			<Connection Source="InputNumber_I1.rPhys" Destination="NVS.VALUE" dx1="1660"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
