<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012e_sub" Comment="Numeric Value Input PHYS und Speichern INI mit Subapp">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-31" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="logiBUS::utils::conversion::phys::NumericObjectPool_S"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="KEY" Type="STRING" Comment="Key name."/>
			<VarDeclaration Name="SECTION" Type="STRING" Comment="Section name."/>
			<VarDeclaration Name="stObj" Type="logiBUS::utils::conversion::phys::NumericObjectPool_S" InitialValue="(u16ObjId := ID_NULL, r32Scale := 1.0, i32Offset := 0, u8Decimals := 0)"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="VALUEO" Type="REAL"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="NumericValue_PHYS" Type="isobus::UT::io::NumericValue::NumericValue_PHYS" x="-1300" y="300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="INI" Type="eclipse4diac::storage::INI" x="2100" y="100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="DEFAULT_VALUE" Value="REAL#0.0"/>
		</FB>
		<FB Name="Q_NumericValue_PHYS" Type="isobus::UT::Q::Q_NumericValue_PHYS" x="5000" y="200">
		</FB>
		<EventConnections>
			<Connection Source="NumericValue_PHYS.IND" Destination="INI.SET" dx1="380"/>
			<Connection Source="INI.SETO" Destination="IND" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INI.GETO" Destination="Q_NumericValue_PHYS.REQ" dx1="546.67"/>
			<Connection Source="INI.GETO" Destination="IND" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INI.INITO" Destination="INI.GET" dx1="80" dx2="80" dy="-580"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="NumericValue_PHYS.rPhys" Destination="INI.VALUE" dx1="186.67"/>
			<Connection Source="stObj" Destination="Q_NumericValue_PHYS.stObj" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="KEY" Destination="INI.KEY" dx1="2066.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INI.VALUEO" Destination="Q_NumericValue_PHYS.rPhys" dx1="486.67"/>
			<Connection Source="INI.VALUEO" Destination="VALUEO" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="stObj" Destination="NumericValue_PHYS.stObj" dx1="1793.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="SECTION" Destination="INI.SECTION" dx1="3493.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
