<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_016c" Comment="Background Colour umschalten -- mit SubApp für Green/White Background">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-10" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_RELEASED"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F2"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F7"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_UP_F1" Type="isobus::UT::io::Softkey::Softkey_IE" x="-4500" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="SoftKey_UP_F2" Type="isobus::UT::io::Softkey::Softkey_IE" x="-4500" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F2"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="E_SR" Type="iec61499::events::E_SR" x="-2800" y="-900">
		</FB>
		<SubApp Name="GreenWhiteBackground1" Type="MyLib::sys::GreenWhiteBackground1" x="-900" y="-1000">
			<Parameter Name="u16ObjId" Value="SoftKey_F7"/>
		</SubApp>
		<EventConnections>
			<Connection Source="SoftKey_UP_F1.IND" Destination="E_SR.S" dx1="406.67"/>
			<Connection Source="SoftKey_UP_F2.IND" Destination="E_SR.R" dx1="473.33"/>
			<Connection Source="E_SR.EO" Destination="GreenWhiteBackground1.REQ" dx1="726.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="GreenWhiteBackground1.DI1" dx1="713.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
