<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_178" Comment="Beispiel für FB_F_TRIG (Falling Edge Detection)">
	<Identification Standard="61499-2" Description="Copyright (c) 2025 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2025-02-01">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="FB_F_TRIG" Type="iec61131::edgeDetection::FB_F_TRIG" x="-1900" y="700">
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-3200" y="500">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="1000" y="553.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="Output_Q1"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_TP" Type="iec61499::events::timers::E_TP" x="-300" y="606.67">
			<Parameter Name="PT" Value="T#1s"/>
		</FB>
		<EventConnections>
			<Connection Source="E_TP.CNF" Destination="DigitalOutput_Q1.REQ" dx1="413.33"/>
			<Connection Source="FB_F_TRIG.CNF" Destination="E_TP.REQ" dx1="446.67"/>
			<Connection Source="DigitalInput_I1.IND" Destination="FB_F_TRIG.REQ" dx1="273.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_TP.Q" Destination="DigitalOutput_Q1.OUT" dx1="413.33"/>
			<Connection Source="DigitalInput_I1.IN" Destination="FB_F_TRIG.CLK" dx1="273.33"/>
			<Connection Source="FB_F_TRIG.Q" Destination="E_TP.IN" dx1="446.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
