<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_213c" Comment="Standard IEC 61131-3 FB_CTU_UDINT (Vorwärtszähler, UDINT) mit Terminal-Ausgabe (PHYS_LREAL)">
	<Identification Standard="61131-3" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-04-21" Remarks="Added terminal output for counter value (PHYS_LREAL, direct connection)">
	</VersionInfo>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-20" Remarks="initial API and implementation (IEC 61131-3 version)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::Container_Horse"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::ObjectPointer_Horse"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_00"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_01"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_02"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_03"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_04"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_05"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_06"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_07"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_08"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_09"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_10"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_11"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_12"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_13"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_14"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_15"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_16"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_17"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_18"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_19"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_20"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_21"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_22"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_23"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_24"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_25"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_26"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_27"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_28"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_29"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_30"/>
		<Import declaration="Uebungen::const::UT::Horse::DefaultPool_Horse::frame_31"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="FB_CTU_UDINT" Type="iec61131::counters::FB_CTU_UDINT" x="-100" y="1400">
			<Parameter Name="PV" Value="UDINT#31"/>
		</FB>
		<FB Name="START" Type="logiBUS::io::DI::logiBUS_IE" x="-4000" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="4700" y="2400">
			<Parameter Name="u16ObjId" Value="ObjectPointer_Horse"/>
		</FB>
		<FB Name="F_MUX_32" Type="iec61131::selection::F_MUX_32" x="2700" y="2600">
			<Parameter Name="IN1" Value="frame_00"/>
			<Parameter Name="IN2" Value="frame_01"/>
			<Parameter Name="IN3" Value="frame_02"/>
			<Parameter Name="IN4" Value="frame_03"/>
			<Parameter Name="IN5" Value="frame_04"/>
			<Parameter Name="IN6" Value="frame_05"/>
			<Parameter Name="IN7" Value="frame_06"/>
			<Parameter Name="IN8" Value="frame_07"/>
			<Parameter Name="IN9" Value="frame_08"/>
			<Parameter Name="IN10" Value="frame_09"/>
			<Parameter Name="IN11" Value="frame_10"/>
			<Parameter Name="IN12" Value="frame_11"/>
			<Parameter Name="IN13" Value="frame_12"/>
			<Parameter Name="IN14" Value="frame_13"/>
			<Parameter Name="IN15" Value="frame_14"/>
			<Parameter Name="IN16" Value="frame_15"/>
			<Parameter Name="IN17" Value="frame_16"/>
			<Parameter Name="IN18" Value="frame_17"/>
			<Parameter Name="IN19" Value="frame_18"/>
			<Parameter Name="IN20" Value="frame_19"/>
			<Parameter Name="IN21" Value="frame_20"/>
			<Parameter Name="IN22" Value="frame_21"/>
			<Parameter Name="IN23" Value="frame_22"/>
			<Parameter Name="IN24" Value="frame_23"/>
			<Parameter Name="IN25" Value="frame_24"/>
			<Parameter Name="IN26" Value="frame_25"/>
			<Parameter Name="IN27" Value="frame_26"/>
			<Parameter Name="IN28" Value="frame_27"/>
			<Parameter Name="IN29" Value="frame_28"/>
			<Parameter Name="IN30" Value="frame_29"/>
			<Parameter Name="IN31" Value="frame_30"/>
			<Parameter Name="IN32" Value="frame_31"/>
		</FB>
		<FB Name="E_PERMIT" Type="iec61499::events::E_PERMIT" x="2700" y="1200">
		</FB>
		<FB Name="E_CYCLE" Type="iec61499::events::E_CYCLE" x="-1900" y="1400">
			<Parameter Name="DT" Value="T#100ms"/>
		</FB>
		<FB Name="STOP" Type="logiBUS::io::DI::logiBUS_IE" x="-4000" y="1800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_T_FF" Type="iec61499::events::E_T_FF" x="-1200" y="1400">
		</FB>
		<FB Name="Q_ObjHideShow" Type="isobus::UT::Q::Q_ObjHideShow" x="-1600" y="200">
			<Parameter Name="u16ObjId" Value="Container_Horse"/>
			<Parameter Name="qVisible" Value="BYTE#1"/>
		</FB>
		<EventConnections>
			<Connection Source="FB_CTU_UDINT.CNF" Destination="F_MUX_32.REQ" dx1="500"/>
			<Connection Source="F_MUX_32.CNF" Destination="Q_NumericValue.REQ" dx1="420"/>
			<Connection Source="FB_CTU_UDINT.CNF" Destination="E_PERMIT.EI" dx1="493.33"/>
			<Connection Source="E_PERMIT.EO" Destination="FB_CTU_UDINT.REQ" dx1="80" dx2="80" dy="-440"/>
			<Connection Source="STOP.IND" Destination="E_CYCLE.STOP" dx1="320"/>
			<Connection Source="E_CYCLE.EO" Destination="E_T_FF.CLK"/>
			<Connection Source="E_T_FF.EO" Destination="FB_CTU_UDINT.REQ"/>
			<Connection Source="START.IND" Destination="E_CYCLE.START" dx1="600"/>
			<Connection Source="START.IND" Destination="Q_ObjHideShow.REQ" dx1="753.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="FB_CTU_UDINT.CV" Destination="F_MUX_32.K" dx1="260"/>
			<Connection Source="F_MUX_32.OUT" Destination="Q_NumericValue.u32NewValue" dx1="553.33"/>
			<Connection Source="FB_CTU_UDINT.Q" Destination="FB_CTU_UDINT.R" dx1="2900" dx2="320" dy="-1033.33"/>
			<Connection Source="FB_CTU_UDINT.Q" Destination="E_PERMIT.PERMIT" dx1="1266.67"/>
			<Connection Source="E_T_FF.Q" Destination="FB_CTU_UDINT.CU"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
