<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_175" Comment="Exercise for E_TABLE_CTRL">
	<Identification Standard="61499-2" Description="Copyright (c) 2025 Meisterschulen am Ostbahnhof     This program and the accompanying materials are made   available under the terms of the Eclipse Public License 2.0   which is available at https://www.eclipse.org/legal/epl-2.0/     SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2025-02-01">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_TABLE_CTRL_1" Type="iec61499::events::E_TABLE_CTRL" x="-3000" y="-1000">
		</FB>
		<Comment Comment="TODO&#10;" x="-3100" y="-100" width="1500" height="300"/>
	</SubAppNetwork>
</SubAppType>
