<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_006a5" Comment="SR und T-Flip-Flop als Rastend/Tastend Implementierung">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-01-15" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_LONG_PRESS_START"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_LONG_PRESS_UP"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="BUTTON_LONG_PRESS_START" Type="logiBUS::io::DI::logiBUS_IE" x="-4600" y="-900">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_LONG_PRESS_START"/>
		</FB>
		<FB Name="BUTTON_LONG_PRESS_UP" Type="logiBUS::io::DI::logiBUS_IE" x="-4540" y="113.34">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_LONG_PRESS_UP"/>
		</FB>
		<FB Name="E_T_FF_SR" Type="iec61499::events::E_T_FF_SR" x="-2600" y="100">
		</FB>
		<FB Name="BUTTON_SINGLE_CLICK" Type="logiBUS::io::DI::logiBUS_IE" x="-4533.33" y="1133.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="900" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<Comment Comment="Universal Eingang: &#10;so können wir mit einem Taster ODER  einem Schalter arbeiten. " x="-2400" y="1800" width="2500" height="700"/>
		<EventConnections>
			<Connection Source="BUTTON_LONG_PRESS_START.IND" Destination="E_T_FF_SR.S" dx1="511.76"/>
			<Connection Source="BUTTON_LONG_PRESS_UP.IND" Destination="E_T_FF_SR.R" dx1="486.67"/>
			<Connection Source="BUTTON_SINGLE_CLICK.IND" Destination="E_T_FF_SR.CLK" dx1="673.33"/>
			<Connection Source="E_T_FF_SR.EO" Destination="DigitalOutput_Q1.REQ" dx1="1120"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF_SR.Q" Destination="DigitalOutput_Q1.OUT" dx1="1120"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
