<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012k_sub" Comment="String Input und Speichern INI mit Subapp">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-31" Remarks="initial API and implementation and/or initial documentation"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event"/>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="KEY" Type="STRING"/>
			<VarDeclaration Name="SECTION" Type="STRING"/>
			<VarDeclaration Name="u16ObjId" Type="UINT" InitialValue="ID_NULL"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="VALUEO" Type="STRING"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="StringValue_IS" Type="isobus::UT::io::StringValue::StringValue_IS" x="-1100" y="200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="INI" Type="eclipse4diac::storage::INI" x="2100" y="100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="DEFAULT_VALUE" Value="STRING#''"/>
		</FB>
		<FB Name="Q_StringValue" Type="isobus::UT::Q::Q_StringValue" x="4500" y="100"/>
		<EventConnections>
			<Connection Source="StringValue_IS.IND" Destination="INI.SET" dx1="380"/>
			<Connection Source="INI.SETO" Destination="IND" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INI.GETO" Destination="Q_StringValue.REQ" dx1="546.67"/>
			<Connection Source="INI.GETO" Destination="IND" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INI.INITO" Destination="INI.GET" dx1="80" dx2="80" dy="-580"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="StringValue_IS.IN" Destination="INI.VALUE" dx1="186.67"/>
			<Connection Source="u16ObjId" Destination="Q_StringValue.u16ObjId" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="KEY" Destination="INI.KEY" dx1="2066.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INI.VALUEO" Destination="Q_StringValue.pau8String" dx1="486.67"/>
			<Connection Source="INI.VALUEO" Destination="VALUEO" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId" Destination="StringValue_IS.u16ObjId" dx1="1793.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="SECTION" Destination="INI.SECTION" dx1="3493.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
