<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_001c2" Comment="DigitalInput_I1 negiert auf DigitalOutput_Q1 --&gt; Eingang abfragen bei Boot.">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-4500" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="F_NOT_BOOL" Type="iec61131::bitwiseOperators::F_NOT_BOOL" x="-1600" y="-700"/>
		<Comment Comment="ohne die Linie INITO-&gt;REQ ist der Ausgang Q1 beim Start FALSE. mit der Linie ist er TRUE. &#10;" x="-4800" y="100" width="2200" height="500"/>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="F_NOT_BOOL.REQ" dx1="953.33"/>
			<Connection Source="DigitalInput_I1.INITO" Destination="DigitalInput_I1.REQ" dx1="80" dx2="80" dy="46.67"/>
			<Connection Source="DigitalInput_I1.CNF" Destination="F_NOT_BOOL.REQ" dx1="1166.67"/>
			<Connection Source="F_NOT_BOOL.CNF" Destination="DigitalOutput_Q1.REQ" dx1="673.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="F_NOT_BOOL.IN" dx1="953.33"/>
			<Connection Source="F_NOT_BOOL.OUT" Destination="DigitalOutput_Q1.OUT" dx1="673.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
