<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_080e3" Comment="Beispiel für E_CTU mit Eventbremse durch E_D_FF_ANY">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="200" y="300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-8900" y="-1900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_CTU" Type="iec61499::events::E_CTU" x="-6200" y="-800">
			<Parameter Name="PV" Value="UINT#5"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-8900" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_SPLIT_4" Type="iec61499::events::E_SPLIT_4" x="-4400" y="-900"/>
		<FB Name="E_MERGE_4" Type="iec61499::events::E_MERGE_4" x="-3300" y="-900"/>
		<FB Name="E_D_FF_ANY" Type="logiBUS::signalprocessing::hysteresis::E_D_FF_ANY_HYS" x="-2100" y="-500">
			<Parameter Name="HYSTERESIS" Value="UINT#25"/>
		</FB>
		<FB Name="E_D_FF" Type="iec61499::events::E_D_FF" x="-1900" y="600"/>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="-100" y="-600">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<FB Name="E_CYCLE" Type="iec61499::events::E_CYCLE" x="-6900" y="-1600">
			<Parameter Name="DT" Value="T#1ms"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_CYCLE.START" dx1="453.33"/>
			<Connection Source="E_CTU.CUO" Destination="E_SPLIT_4.EI" dx1="466.67"/>
			<Connection Source="E_CTU.RO" Destination="E_SPLIT_4.EI" dx1="786.67"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_CTU.R" dx1="273.33"/>
			<Connection Source="E_SPLIT_4.EO1" Destination="E_MERGE_4.EI1"/>
			<Connection Source="E_SPLIT_4.EO2" Destination="E_MERGE_4.EI2"/>
			<Connection Source="E_SPLIT_4.EO3" Destination="E_MERGE_4.EI3"/>
			<Connection Source="E_SPLIT_4.EO4" Destination="E_MERGE_4.EI4"/>
			<Connection Source="E_MERGE_4.EO" Destination="E_D_FF_ANY.CLK" dx1="246.67"/>
			<Connection Source="E_D_FF_ANY.EO" Destination="Q_NumericValue.REQ" dx1="366.67"/>
			<Connection Source="E_MERGE_4.EO" Destination="E_D_FF.CLK" dx1="173.33"/>
			<Connection Source="E_D_FF.EO" Destination="DigitalOutput_Q1.REQ" dx1="766.67"/>
			<Connection Source="E_CYCLE.EO" Destination="E_CTU.CU" dx1="80" dx2="80" dy="400"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_CYCLE.STOP" dx1="553.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTU.CV" Destination="E_D_FF_ANY.D" dx1="853.33"/>
			<Connection Source="E_D_FF_ANY.Q" Destination="Q_NumericValue.u32NewValue" dx1="266.67"/>
			<Connection Source="E_CTU.Q" Destination="E_D_FF.D" dx1="80"/>
			<Connection Source="E_D_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="766.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
