<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_080e" Comment="Beispiel für E_CTU mit Eventbremse durch E_D_FF_ANY">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="200" y="300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-8000" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_CTU" Type="iec61499::events::E_CTU" x="-6200" y="-800">
			<Parameter Name="PV" Value="UINT#5"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-8000" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_SPLIT_4" Type="iec61499::events::E_SPLIT_4" x="-4400" y="-900"/>
		<FB Name="E_MERGE_4" Type="iec61499::events::E_MERGE_4" x="-3300" y="-900"/>
		<FB Name="RT_E_EC_COUPLER" Type="eclipse4diac::rtevents::RT_E_REND" x="-1800" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Tmin" Value="T#500ms"/>
			<Parameter Name="Deadline" Value="T#20ms"/>
			<Parameter Name="WCET" Value="T#1ms"/>
		</FB>
		<FB Name="RT_E_EC_COUPLER_1" Type="eclipse4diac::rtevents::RT_E_REND" x="-1200" y="-2900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Tmin" Value="T#500ms"/>
			<Parameter Name="Deadline" Value="T#20ms"/>
			<Parameter Name="WCET" Value="T#1ms"/>
		</FB>
		<FB Name="RT_E_EC_COUPLER_2" Type="eclipse4diac::rtevents::RT_E_REND" x="100" y="-1800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Tmin" Value="T#500ms"/>
			<Parameter Name="Deadline" Value="T#20ms"/>
			<Parameter Name="WCET" Value="T#1ms"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_CTU.CU" dx1="453.33"/>
			<Connection Source="E_CTU.CUO" Destination="E_SPLIT_4.EI" dx1="466.67"/>
			<Connection Source="E_CTU.RO" Destination="E_SPLIT_4.EI" dx1="786.67"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_CTU.R" dx1="273.33"/>
			<Connection Source="E_SPLIT_4.EO1" Destination="E_MERGE_4.EI1"/>
			<Connection Source="E_SPLIT_4.EO2" Destination="E_MERGE_4.EI2"/>
			<Connection Source="E_SPLIT_4.EO3" Destination="E_MERGE_4.EI3"/>
			<Connection Source="E_SPLIT_4.EO4" Destination="E_MERGE_4.EI4"/>
			<Connection Source="E_MERGE_4.EO" Destination="RT_E_EC_COUPLER.EI1" dx1="713.33"/>
			<Connection Source="RT_E_EC_COUPLER.EO" Destination="DigitalOutput_Q1.REQ" dx1="706.67"/>
			<Connection Source="E_MERGE_4.EO" Destination="RT_E_EC_COUPLER.EI2" dx1="713.33"/>
			<Connection Source="E_MERGE_4.EO" Destination="RT_E_EC_COUPLER_1.EI1" dx1="660"/>
			<Connection Source="E_MERGE_4.EO" Destination="RT_E_EC_COUPLER_1.EI2" dx1="660"/>
			<Connection Source="E_MERGE_4.EO" Destination="RT_E_EC_COUPLER_2.EI1" dx1="660"/>
			<Connection Source="E_MERGE_4.EO" Destination="RT_E_EC_COUPLER_2.EI2" dx1="660"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTU.Q" Destination="DigitalOutput_Q1.OUT" dx1="240"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
