<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_170" Comment="Exercise for ARTimeOut">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2025-02-01" Remarks="initial API and implementation and/or initial documentation"/>
	<CompilerInfo packageName="Uebungen"/>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="ARTimeOut_1" Type="iec61499::events::E_RTimeOut" x="-900" y="300"/>
	</SubAppNetwork>
</SubAppType>
