<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_230" Comment="Analog-Eingang">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="DataPanel::io::MI::AI::DataPanel_MI_AI::AnalogInput_5A"/>
		<Import declaration="DataPanel::io::MI::const::MI::MI_00"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DataPanel_MI_IW_0_10V" Type="DataPanel::io::MI::AI::DataPanel_MI_IW_0_10V" x="-4800" y="1200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="MI_00"/>
			<Parameter Name="Input" Value="AnalogInput_5A"/>
			<Parameter Name="AnalogInput_hysteresis" Value="50"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT_I8" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="-2600" y="1500">
		</FB>
		<Comment Comment="ACHTUNG!!! &#10;&#10;X-Board hat u.U. nur 5A-8B, 1A-4B Fehlen ! " x="-5900" y="2400" width="1000" height="500"/>
		<EventConnections>
			<Connection Source="DataPanel_MI_IW_0_10V.CNF" Destination="F_DWORD_TO_UDINT_I8.REQ" dx1="373.33"/>
			<Connection Source="DataPanel_MI_IW_0_10V.IND" Destination="F_DWORD_TO_UDINT_I8.REQ" dx1="373.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DataPanel_MI_IW_0_10V.IN" Destination="F_DWORD_TO_UDINT_I8.IN" dx1="673.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
