<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_011b1_PHYS" Comment="Numeric Value Input ADD (PHYS)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-24" Remarks="PHYS variant of Uebung_011b1 with REAL arithmetic">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::InputNumber_I3"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::InputNumber_I4"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::OutputNumber_N3"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="InputNumber_I3" Type="isobus::UT::io::NumericValue::NumericValue_PHYS" x="-6900" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="stObj" Value="InputNumber_I3"/>
		</FB>
		<FB Name="InputNumber_I4" Type="isobus::UT::io::NumericValue::NumericValue_PHYS" x="-6900" y="1800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="stObj" Value="InputNumber_I4"/>
		</FB>
		<FB Name="ADD_2" Type="iec61131::arithmetic::ADD_2" x="-2400" y="1300">
		</FB>
		<FB Name="Q_NumericValue_PHYS" Type="isobus::UT::Q::Q_NumericValue_PHYS" x="-500" y="1100">
			<Parameter Name="stObj" Value="OutputNumber_N3"/>
		</FB>
		<EventConnections>
			<Connection Source="InputNumber_I3.IND" Destination="ADD_2.REQ" dx1="833.33"/>
			<Connection Source="InputNumber_I4.IND" Destination="ADD_2.REQ" dx1="833.33"/>
			<Connection Source="ADD_2.CNF" Destination="Q_NumericValue_PHYS.REQ" dx1="686.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="InputNumber_I3.rPhys" Destination="ADD_2.IN1" dx1="426.67"/>
			<Connection Source="InputNumber_I4.rPhys" Destination="ADD_2.IN2" dx1="1173.33"/>
			<Connection Source="ADD_2.OUT" Destination="Q_NumericValue_PHYS.rPhys" dx1="686.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
