<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_220" Comment="Standard IEC 61131-3 FB_CTUD (Vor-/Rückwärtszähler, INT) mit Terminal-Ausgabe">
	<Identification Standard="61131-3" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-04-21" Remarks="Added terminal output for counter value"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-20" Remarks="initial API and implementation (IEC 61131-3 version)"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="FB_CTUD" Type="iec61131::counters::FB_CTUD" x="0" y="500">
			<Parameter Name="PV" Value="INT#10"/>
		</FB>
		<FB Name="Input_CU" Type="logiBUS::io::DI::logiBUS_IX" x="-3000" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="Input_CD" Type="logiBUS::io::DI::logiBUS_IX" x="-3000" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="Input_R" Type="logiBUS::io::DI::logiBUS_IX" x="-3000" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<FB Name="Input_LD" Type="logiBUS::io::DI::logiBUS_IX" x="-3000" y="2000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
		</FB>
		<FB Name="Output_QU" Type="logiBUS::io::DQ::logiBUS_QX" x="3000" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="Output_QD" Type="logiBUS::io::DQ::logiBUS_QX" x="3000" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="3200" y="1300">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<FB Name="F_INT_TO_UDINT" Type="iec61131::conversion::F_INT_TO_UDINT" x="1500" y="1500"/>
		<Comment Comment="F_INT_TO_UDINT ist großer Quatsch ... keine Negativen Zahlen möglich" x="700" y="2200" width="2200" height="500"/>
		<EventConnections>
			<Connection Source="Input_CU.IND" Destination="FB_CTUD.REQ" dx1="500"/>
			<Connection Source="Input_CD.IND" Destination="FB_CTUD.REQ" dx1="500"/>
			<Connection Source="Input_R.IND" Destination="FB_CTUD.REQ" dx1="500"/>
			<Connection Source="Input_LD.IND" Destination="FB_CTUD.REQ" dx1="500"/>
			<Connection Source="FB_CTUD.CNF" Destination="Output_QU.REQ" dx1="500"/>
			<Connection Source="FB_CTUD.CNF" Destination="Output_QD.REQ" dx1="500"/>
			<Connection Source="FB_CTUD.CNF" Destination="F_INT_TO_UDINT.REQ" dx1="520"/>
			<Connection Source="F_INT_TO_UDINT.CNF" Destination="Q_NumericValue.REQ" dx1="200"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Input_CU.IN" Destination="FB_CTUD.CU" dx1="313.33"/>
			<Connection Source="Input_CD.IN" Destination="FB_CTUD.CD" dx1="200"/>
			<Connection Source="Input_R.IN" Destination="FB_CTUD.R" dx1="200"/>
			<Connection Source="Input_LD.IN" Destination="FB_CTUD.LD" dx1="313.33"/>
			<Connection Source="FB_CTUD.QU" Destination="Output_QU.OUT" dx1="1013.33"/>
			<Connection Source="FB_CTUD.QD" Destination="Output_QD.OUT" dx1="1693.33"/>
			<Connection Source="FB_CTUD.CV" Destination="F_INT_TO_UDINT.IN" dx1="200"/>
			<Connection Source="F_INT_TO_UDINT.OUT" Destination="Q_NumericValue.u32NewValue" dx1="200"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
