<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_174" Comment="Exercise for E_RESTART">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2025-02-01" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_RESTART_1" Type="iec61499::events::E_RESTART" x="-3000" y="-1000">
		</FB>
		<Comment Comment="TODO&#10;" x="-3100" y="-300" width="1500" height="300"/>
	</SubAppNetwork>
</SubAppType>
