<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_000b" Comment="AND">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-01-16" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AND_2" Type="iec61131::booleanOperators::AND_BOOL_2" x="400" y="400">
			<Parameter Name="IN1" Value="TRUE"/>
			<Parameter Name="IN2" Value="TRUE"/>
		</FB>
		<FB Name="INIT" Type="iec61131::booleanOperators::INIT" x="-900" y="300">
		</FB>
		<EventConnections>
			<Connection Source="INIT.INITO" Destination="INIT.REQ" dx1="80" dx2="80" dy="53.33"/>
			<Connection Source="INIT.CNF" Destination="AND_2.REQ" dx1="166.67"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
