<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_011e" Comment="Numeric Value Input I1 Durchschleifen auf N3 (Software Scale via NumericObjectPool_S)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-14">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="InputNumber_I1" Type="isobus::UT::io::NumericValue::NumericValue_ID" x="-6600" y="400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="DefaultPool::InputNumber_I1"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT" Type="iec61131::conversion::F_DWORD_TO_REAL" x="-4900" y="700">
		</FB>
		<FB Name="Q_NumericValue_PHYS" Type="isobus::UT::Q::Q_NumericValue_PHYS" x="0" y="500">
			<Parameter Name="stObj" Value="DefaultPool_Numeric::OutputNumber_N3"/>
		</FB>
		<Comment Comment=" Beispiel: I1-Eingabe 100000 → F_RAW_TO_PHYS(I1) → 100000.0 → Q_NumericValue_PHYS(N3) → N3 zeigt 0.00." x="-4900" y="2100" width="4500" height="500"/>
		<EventConnections>
			<Connection Source="InputNumber_I1.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="486.67"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="Q_NumericValue_PHYS.REQ" dx1="1953.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="InputNumber_I1.IN" Destination="F_DWORD_TO_UDINT.IN" dx1="486.67"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="Q_NumericValue_PHYS.rPhys" dx1="1953.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
