<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004b4c_sub" Comment="Sub-Applikation für ein verriegelbares Toggle-Flip-Flop mit AE2-Adapter (identisch zu 004b3c_sub)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-19">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="IND" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="EO" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<OutputVars>
			<VarDeclaration Name="Q" Type="BOOL"/>
		</OutputVars>
		<Plugs>
			<AdapterDeclaration Name="PLUG" Type="adapter::types::bidirectional::AE2"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="SOCKET" Type="adapter::types::bidirectional::AE2"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_SR_I1" Type="iec61499::events::E_SR" x="2100" y="-900">
		</FB>
		<FB Name="E_SWITCH_I1" Type="iec61499::events::E_SWITCH" x="-1100" y="-900">
		</FB>
		<FB Name="AE2_EVENT_TO_E" Type="adapter::conversion::bidirectional::AE2_EVENT_TO_E" x="600" y="600">
		</FB>
		<FB Name="AE2_E_TO_EVENT" Type="adapter::conversion::bidirectional::AE2_E_TO_EVENT" x="600" y="0">
		</FB>
		<EventConnections>
			<Connection Source="E_SWITCH_I1.EO0" Destination="E_SR_I1.S"/>
			<Connection Source="E_SWITCH_I1.EO1" Destination="E_SR_I1.R"/>
			<Connection Source="E_SR_I1.EO" Destination="EO" dx1="780"/>
			<Connection Source="IND" Destination="E_SWITCH_I1.EI" dx1="693.33"/>
			<Connection Source="E_SWITCH_I1.EO0" Destination="AE2_EVENT_TO_E.REQ" dx1="353.33"/>
			<Connection Source="AE2_E_TO_EVENT.CNF" Destination="E_SR_I1.R" dx1="300"/>
			<Connection Source="AE2_EVENT_TO_E.CNF" Destination="E_SR_I1.R" dx1="426.67"/>
			<Connection Source="E_SWITCH_I1.EO0" Destination="AE2_E_TO_EVENT.REQ" dx1="593.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR_I1.Q" Destination="E_SWITCH_I1.G" dx1="80" dx2="80" dy="160"/>
			<Connection Source="E_SR_I1.Q" Destination="Q" dx1="1306.67"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="SOCKET" Destination="AE2_E_TO_EVENT.AE2_IN" dx1="80"/>
			<Connection Source="AE2_EVENT_TO_E.AE2_OUT" Destination="PLUG" dx1="3313.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
