<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_011f" Comment="Numeric Value Input I3 Durchschleifen auf N3 (Input und Output PHYS via NumericObjectPool_S)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-14" Remarks="initial API and implementation and/or initial documentation"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::InputNumber_I3"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::OutputNumber_N3"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="NumericValue_PHYS" Type="isobus::UT::io::NumericValue::NumericValue_PHYS" x="-4700" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="stObj" Value="InputNumber_I3"/>
		</FB>
		<FB Name="Q_NumericValue_PHYS" Type="isobus::UT::Q::Q_NumericValue_PHYS" x="-1600" y="700">
			<Parameter Name="stObj" Value="OutputNumber_N3"/>
		</FB>
		<Comment Comment=" Beispiel: I3-Eingabe -500.00 → rPhys=-500.0 → Q_NumericValue_PHYS(N3) → N3 zeigt -500.00." x="-4700" y="1700" width="4200" height="500"/>
		<EventConnections>
			<Connection Source="NumericValue_PHYS.IND" Destination="Q_NumericValue_PHYS.REQ" dx1="1160"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="NumericValue_PHYS.rPhys" Destination="Q_NumericValue_PHYS.rPhys" dx1="486.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
