<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_219b" Comment="Standard IEC 61131-3 FB_CTD_UDINT (Rückwärtszähler, UDINT) mit Terminal-Ausgabe (PHYS_LREAL)">
	<Identification Standard="61131-3" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-04-21" Remarks="Added terminal output for counter value (PHYS_LREAL, direct connection)">
	</VersionInfo>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-20" Remarks="initial API and implementation (IEC 61131-3 version)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::OutputNumber_N3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="FB_CTD_UDINT" Type="iec61131::counters::FB_CTD_UDINT" x="0" y="500">
			<Parameter Name="PV" Value="UDINT#10"/>
		</FB>
		<FB Name="Input_CD" Type="logiBUS::io::DI::logiBUS_IX" x="-3000" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="Input_LD" Type="logiBUS::io::DI::logiBUS_IX" x="-3000" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="Output_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="3000" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="Q_NumericValue_L" Type="isobus::UT::Q::Q_NumericValue_PHYS_LREAL" x="3000" y="1000">
			<Parameter Name="stObj" Value="OutputNumber_N3"/>
		</FB>
		<EventConnections>
			<Connection Source="Input_CD.IND" Destination="FB_CTD_UDINT.REQ" dx1="500"/>
			<Connection Source="Input_LD.IND" Destination="FB_CTD_UDINT.REQ" dx1="500"/>
			<Connection Source="FB_CTD_UDINT.CNF" Destination="Output_Q1.REQ" dx1="500"/>
			<Connection Source="FB_CTD_UDINT.CNF" Destination="Q_NumericValue_L.REQ" dx1="500"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Input_CD.IN" Destination="FB_CTD_UDINT.CD" dx1="200"/>
			<Connection Source="Input_LD.IN" Destination="FB_CTD_UDINT.LD" dx1="200"/>
			<Connection Source="FB_CTD_UDINT.Q" Destination="Output_Q1.OUT" dx1="200"/>
			<Connection Source="FB_CTD_UDINT.CV" Destination="Q_NumericValue_L.lrPhys" dx1="226.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
