<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_006e2" Comment="RS-Flip-Flop mit 2x IX">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-1500" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-4500" y="-1200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IX" x="-4500" y="200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="FB_RS" Type="iec61131::bistableElements::FB_RS" x="-2800" y="-800">
		</FB>
		<EventConnections>
			<Connection Source="FB_RS.CNF" Destination="DigitalOutput_Q1.REQ" dx1="320"/>
			<Connection Source="DigitalInput_I2.IND" Destination="FB_RS.REQ" dx1="440"/>
			<Connection Source="DigitalInput_I1.IND" Destination="FB_RS.REQ" dx1="440"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="FB_RS.Q1" Destination="DigitalOutput_Q1.OUT" dx1="446.67"/>
			<Connection Source="DigitalInput_I1.IN" Destination="FB_RS.S" dx1="600"/>
			<Connection Source="DigitalInput_I2.IN" Destination="FB_RS.R1" dx1="746.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
