<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_171" Comment="Exercise for E_MOVE">
	<Identification Standard="61499-2" Description="Copyright (c) 2025 Meisterschulen am Ostbahnhof     This program and the accompanying materials are made   available under the terms of the Eclipse Public License 2.0   which is available at https://www.eclipse.org/legal/epl-2.0/     SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2025-02-01">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_MOVE" Type="iec61499::events::E_MOVE" x="-2500" y="-800">
		</FB>
		<FB Name="F_MOVE" Type="iec61131::selection::F_MOVE" x="-4100" y="-100">
			<Attribute Name="DataType" Value="INT"/>
		</FB>
		<Comment Comment="TODO&#10;" x="-2800" y="-100" width="1500" height="300"/>
		<DataConnections>
			<Connection Source="F_MOVE.OUT" Destination="E_MOVE.IN" dx1="513.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
