<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_076" Comment="MSS mit Compound Scaling auf UT ausgeben">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-06-01" Remarks="MSS Machine Selected Speed mit Compound Scaling (0.256 upper / 0.001 lower)"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::TECU::DefaultPool_TECU_Numeric::NumberVariable_Wheel_based_machine_speed"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="I_MSS" Type="isobus::tecu::I_MSS" x="-3300" y="400">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="COMPOUND_SCALE" Type="logiBUS::signalprocessing::fieldbus::FIELDBUS_UINT_TO_SIGNAL_COMPOUND_SCALE" x="-500" y="700">
			<Parameter Name="SCALE_HIGH" Value="REAL#0.256"/>
			<Parameter Name="SCALE_LOW" Value="REAL#0.001"/>
			<Parameter Name="OFFSET" Value="DINT#0"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue_PHYS" x="3900" y="600">
			<Parameter Name="stObj" Value="NumberVariable_Wheel_based_machine_speed"/>
		</FB>
		<Comment Comment="TODO: &#10;NumberVariable_Machine_selected_speed&#10;im Object Pool anlegen, und hier umändern.&#10;&#10;solange verwenden wir hier NumberVariable_Wheel_based_machine_speed ersatzweise" x="1800" y="1600" width="3100" height="700"/>
		<EventConnections>
			<Connection Source="I_MSS.IND" Destination="COMPOUND_SCALE.REQ" dx1="66.67"/>
			<Connection Source="COMPOUND_SCALE.CNF" Destination="Q_NumericValue.REQ" dx1="1120"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="I_MSS.SELECTEDMACHINESPEED" Destination="COMPOUND_SCALE.IN" dx1="66.67"/>
			<Connection Source="COMPOUND_SCALE.OUT" Destination="Q_NumericValue.rPhys" dx1="1120"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
