<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010a5" Comment="SoftKey_F1 auf DigitalOutput_Q1 (Datapanel)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="DataPanel::io::MI::DQ::DataPanel_MI_DO::Input_Power_Port_5"/>
		<Import declaration="DataPanel::io::MI::const::MI::MI_00"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Input_Power_Port_5" Type="DataPanel::io::MI::DQ::DataPanel_MI_QX" x="-1400" y="-300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="MI_00"/>
			<Parameter Name="Output" Value="Input_Power_Port_5"/>
		</FB>
		<FB Name="SoftKey_F1" Type="isobus::UT::io::Softkey::Softkey_IX" x="-4600" y="-500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_F1.IND" Destination="Input_Power_Port_5.REQ" dx1="1206.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="SoftKey_F1.IN" Destination="Input_Power_Port_5.OUT" dx1="1206.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
