<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_011d" Comment="Numeric Value Input I1 Durchschleifen auf N3 (Offset/Scale Effekt)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-14">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::InputNumber_I1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N3"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="InputNumber_I1" Type="isobus::UT::io::NumericValue::NumericValue_ID" x="-5000" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="-3200" y="1000">
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="-900" y="800">
			<Parameter Name="u16ObjId" Value="OutputNumber_N3"/>
		</FB>
		<Comment Comment=" Beispiel: I1-Eingabe 100000 → N3 zeigt 0.00, Eingabe 50000 → N3 zeigt -500.00." x="-4300" y="1700" width="4000" height="500"/>
		<EventConnections>
			<Connection Source="InputNumber_I1.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="486.67"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="Q_NumericValue.REQ" dx1="486.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="InputNumber_I1.IN" Destination="F_DWORD_TO_UDINT.IN" dx1="486.67"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="Q_NumericValue.u32NewValue" dx1="486.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
