<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_072d" Comment="WBSD auf UT ausgeben, mit QI">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::TECU::DefaultPool_TECU::NumberVariable_Ground_based_machine_speed"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="I_GBSD" Type="isobus::tecu::I_GBSD" x="-5000" y="500"/>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="540" y="766.67">
			<Parameter Name="u16ObjId" Value="NumberVariable_Ground_based_machine_speed"/>
		</FB>
		<FB Name="F_UINT_TO_UDINT" Type="iec61131::conversion::F_UINT_TO_UDINT" x="-2500" y="900"/>
		<Comment Comment="Uebung_094a nutzt dasselbe Prinzip" x="-6400" y="3200" width="1000" height="500"/>
		<FB Name="E_T_FF" Type="iec61499::events::E_T_FF" x="-6500" y="2300"/>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-8000" y="2100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QX" x="-3200" y="2400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<EventConnections>
			<Connection Source="F_UINT_TO_UDINT.CNF" Destination="Q_NumericValue.REQ" dx1="66.67"/>
			<Connection Source="I_GBSD.IND" Destination="F_UINT_TO_UDINT.REQ" dx1="66.67"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_T_FF.CLK" dx1="306.67"/>
			<Connection Source="E_T_FF.EO" Destination="I_GBSD.INIT" dx1="73.33"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q2.REQ" dx1="1086.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_UINT_TO_UDINT.OUT" Destination="Q_NumericValue.u32NewValue" dx1="66.67"/>
			<Connection Source="I_GBSD.GROUNDBASEDMACHINESPEED" Destination="F_UINT_TO_UDINT.IN" dx1="66.67"/>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q2.OUT" dx1="900"/>
			<Connection Source="E_T_FF.Q" Destination="I_GBSD.QI" dx1="466.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
