<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AUI_AX_SEL_AUI_fix" Comment="binary selection">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 HR Agrartechnik GmbH  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="HR Agrartechnik GmbH" Version="1.0" Author="Franz Höpfinger" Date="2026-04-19" Remarks="initial API and implementation">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::fix">
		<Import declaration="eclipse4diac::core::TypeHash"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="OUT" Type="adapter::types::unidirectional::AUI" Comment="Selected Output"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="IN0" Type="adapter::types::unidirectional::AUI" Comment="Selectable input variable"/>
			<AdapterDeclaration Name="IN1" Type="adapter::types::unidirectional::AUI" Comment="Selectable input variable"/>
			<AdapterDeclaration Name="G" Type="adapter::types::unidirectional::AX" Comment="Selector"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_SEL" Type="iec61131::selection::F_SEL" x="1920" y="880">
		</FB>
		<FB Name="IN_0" Type="adapter::conversion::unidirectional::AUI_UI_TO_UINT" x="666.67" y="933.33">
		</FB>
		<FB Name="OUT_0" Type="adapter::conversion::unidirectional::AUI_UINT_TO_UI" x="2753.33" y="880">
		</FB>
		<FB Name="IN_1" Type="adapter::conversion::unidirectional::AUI_UI_TO_UINT" x="666.67" y="1833.33">
		</FB>
		<FB Name="G_0" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="533.33" y="33.33">
		</FB>
		<EventConnections>
			<Connection Source="F_SEL.CNF" Destination="OUT_0.REQ"/>
			<Connection Source="IN_0.CNF" Destination="F_SEL.REQ" dx1="66.67"/>
			<Connection Source="IN_1.CNF" Destination="F_SEL.REQ" dx1="66.67"/>
			<Connection Source="G_0.CNF" Destination="F_SEL.REQ" dx1="293.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SEL.OUT" Destination="OUT_0.OUT"/>
			<Connection Source="IN_0.IN" Destination="F_SEL.IN0" dx1="133.33"/>
			<Connection Source="IN_1.IN" Destination="F_SEL.IN1" dx1="133.33"/>
			<Connection Source="G_0.IN" Destination="F_SEL.G" dx1="360"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="OUT_0.AUI_OUT" Destination="OUT" dx1="686.67"/>
			<Connection Source="G" Destination="G_0.AX_IN" dx1="2486.67"/>
			<Connection Source="IN1" Destination="IN_1.AUI_IN" dx1="133.33"/>
			<Connection Source="IN0" Destination="IN_0.AUI_IN" dx1="1546.67"/>
		</AdapterConnections>
	</SubAppNetwork>
	<Service RightInterface="RESOURCE" LeftInterface="APPLICATION">
	</Service>
	<Attribute Name="eclipse4diac::core::TypeHash" Value="''"/>
</SubAppType>
