<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AUI_AX_SEL_AUI_fix" Comment="binary selection">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 HR Agrartechnik GmbH  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="HR Agrartechnik GmbH" Version="1.0" Author="Franz Höpfinger" Date="2026-04-19" Remarks="initial API and implementation">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::fix">
		<Import declaration="eclipse4diac::core::TypeHash"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="OUT" Type="adapter::types::unidirectional::AUI" Comment="Selected Output"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="IN0" Type="adapter::types::unidirectional::AUI" Comment="Selectable input variable"/>
			<AdapterDeclaration Name="IN1" Type="adapter::types::unidirectional::AUI" Comment="Selectable input variable"/>
			<AdapterDeclaration Name="G" Type="adapter::types::unidirectional::AX" Comment="Selector"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="IN_0" Type="adapter::conversion::unidirectional::AUI_UI_TO_UINT" x="-1900" y="600">
		</FB>
		<FB Name="OUT_0" Type="adapter::conversion::unidirectional::AUI_UINT_TO_UI" x="4600" y="100">
		</FB>
		<FB Name="IN_1" Type="adapter::conversion::unidirectional::AUI_UI_TO_UINT" x="-2900" y="1100">
		</FB>
		<FB Name="G_0" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-2900" y="100">
		</FB>
		<FB Name="E_D_FF_ANY_IN0" Type="iec61499::events::E_D_FF_ANY" x="-600" y="600">
		</FB>
		<FB Name="F_MOVE_IN1" Type="iec61131::selection::F_MOVE" x="400" y="1100">
			<Attribute Name="DataType" Value="UINT"/>
		</FB>
		<FB Name="E_D_FF_G" Type="iec61499::events::E_D_FF" x="-600" y="100">
		</FB>
		<FB Name="F_MOVE_IN0" Type="iec61131::selection::F_MOVE" x="400" y="600">
			<Attribute Name="DataType" Value="UINT"/>
		</FB>
		<FB Name="F_SEL" Type="iec61131::selection::F_SEL" x="1700" y="100">
		</FB>
		<FB Name="F_MOVE_OUT" Type="iec61131::selection::F_MOVE" x="2600" y="100">
			<Attribute Name="DataType" Value="UINT"/>
		</FB>
		<FB Name="E_D_FF_ANY_OUT" Type="iec61499::events::E_D_FF_ANY" x="3600" y="100">
		</FB>
		<FB Name="E_D_FF_ANY_IN1" Type="iec61499::events::E_D_FF_ANY" x="-600" y="1100">
		</FB>
		<EventConnections>
			<Connection Source="F_MOVE_IN1.CNF" Destination="F_SEL.REQ" dx1="413.33"/>
			<Connection Source="F_MOVE_OUT.CNF" Destination="E_D_FF_ANY_OUT.CLK"/>
			<Connection Source="E_D_FF_ANY_IN0.EO" Destination="F_MOVE_IN0.REQ"/>
			<Connection Source="F_SEL.CNF" Destination="F_MOVE_OUT.REQ"/>
			<Connection Source="E_D_FF_ANY_IN1.EO" Destination="F_MOVE_IN1.REQ"/>
			<Connection Source="E_D_FF_G.EO" Destination="F_SEL.REQ"/>
			<Connection Source="F_MOVE_IN0.CNF" Destination="F_SEL.REQ" dx1="413.33"/>
			<Connection Source="E_D_FF_ANY_OUT.EO" Destination="OUT_0.REQ"/>
			<Connection Source="G_0.CNF" Destination="E_D_FF_G.CLK"/>
			<Connection Source="IN_0.CNF" Destination="E_D_FF_ANY_IN0.CLK"/>
			<Connection Source="IN_1.CNF" Destination="E_D_FF_ANY_IN1.CLK"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_D_FF_ANY_IN1.Q" Destination="F_MOVE_IN1.IN"/>
			<Connection Source="F_MOVE_IN1.OUT" Destination="F_SEL.IN1" dx1="653.33"/>
			<Connection Source="E_D_FF_G.Q" Destination="F_SEL.G"/>
			<Connection Source="F_SEL.OUT" Destination="F_MOVE_OUT.IN"/>
			<Connection Source="F_MOVE_OUT.OUT" Destination="E_D_FF_ANY_OUT.D"/>
			<Connection Source="E_D_FF_ANY_IN0.Q" Destination="F_MOVE_IN0.IN"/>
			<Connection Source="F_MOVE_IN0.OUT" Destination="F_SEL.IN0" dx1="613.33"/>
			<Connection Source="E_D_FF_ANY_OUT.Q" Destination="OUT_0.OUT"/>
			<Connection Source="G_0.IN" Destination="E_D_FF_G.D"/>
			<Connection Source="IN_0.IN" Destination="E_D_FF_ANY_IN0.D"/>
			<Connection Source="IN_1.IN" Destination="E_D_FF_ANY_IN1.D"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="OUT_0.AUI_OUT" Destination="OUT" dx1="686.67"/>
			<Connection Source="G" Destination="G_0.AX_IN" dx1="1573.33"/>
			<Connection Source="IN1" Destination="IN_1.AUI_IN" dx1="393.33"/>
			<Connection Source="IN0" Destination="IN_0.AUI_IN" dx1="646.67"/>
		</AdapterConnections>
	</SubAppNetwork>
	<Service RightInterface="RESOURCE" LeftInterface="APPLICATION">
	</Service>
	<Attribute Name="eclipse4diac::core::TypeHash" Value="''"/>
</SubAppType>
