<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004a8" Comment="mit E_SPLIT_2">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-4300" y="-100">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="IE" x="-8533.33" y="-6.66">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_T_FF_Q1" Type="E_T_FF" x="-5466.67" y="0">
		</FB>
		<FB Name="E_T_FF_Q2" Type="E_T_FF" x="-5500" y="900">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" x="-4300" y="800">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_SPLIT_2" Type="E_SPLIT_2" x="-7100" y="200">
		</FB>
		<EventConnections>
			<Connection Source="E_T_FF_Q1.EO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_T_FF_Q2.EO" Destination="DigitalOutput_Q2.REQ"/>
			<Connection Source="E_SPLIT_2.EO1" Destination="E_T_FF_Q1.CLK" dx1="493.33"/>
			<Connection Source="E_SPLIT_2.EO2" Destination="E_T_FF_Q2.CLK" dx1="493.33"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_SPLIT_2.EI"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF_Q1.Q" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="E_T_FF_Q2.Q" Destination="DigitalOutput_Q2.OUT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
