<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_019" Comment="Umschalten einer Maske">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_UP_F1" Type="IE" x="-4500" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DataMask_M1" Type="Q_ActiveMask" x="-2300" y="-800">
			<Parameter Name="u16WorkSetId" Value="DefaultPool::WorkingSet_0"/>
			<Parameter Name="u16NewMaskId" Value="DefaultPool::DataMask_M1"/>
		</FB>
		<FB Name="SoftKey_UP_F2" Type="IE" x="-4600" y="200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DataMask_M2" Type="Q_ActiveMask" x="-2400" y="300">
			<Parameter Name="u16WorkSetId" Value="DefaultPool::WorkingSet_0"/>
			<Parameter Name="u16NewMaskId" Value="DefaultPool::DataMask_M2"/>
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_UP_F1.IND" Destination="DataMask_M1.REQ"/>
			<Connection Source="SoftKey_UP_F2.IND" Destination="DataMask_M2.REQ"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
