<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010b3" Comment="Toggle Flip-Flop mit IE AuxFunction2_X1" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-3900" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AuxFunction2_X1_UP" Type="IE" x="-7300" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" x="-5560" y="0">
		</FB>
		<EventConnections>
			<Connection Source="AuxFunction2_X1_UP.IND" Destination="E_T_FF.CLK"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="580"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
