<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_009" Comment="Ticker" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="566.67" y="-906.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_CYCLE" Type="E_CYCLE" x="-2493.33" y="-680">
			<Parameter Name="DT" Value="T#1s"/>
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" x="-1586.67" y="-680">
		</FB>
		<FB Name="E_SR" Type="E_SR" x="-680" y="-680">
		</FB>
		<FB Name="E_PERMIT" Type="E_PERMIT" x="573.33" y="226.67">
		</FB>
		<FB Name="E_CTUD_UDINT" Type="E_CTUD_UDINT" x="1706.66" y="226.67">
			<Parameter Name="PV" Value="0"/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" x="3513.33" y="226.67">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<EventConnections>
			<Connection Source="E_CYCLE.EO" Destination="E_SWITCH.EI"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_SR.S"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_SR.R"/>
			<Connection Source="E_SR.EO" Destination="DigitalOutput_Q1.REQ" dx1="380"/>
			<Connection Source="E_SR.EO" Destination="E_PERMIT.EI" dx1="480"/>
			<Connection Source="E_PERMIT.EO" Destination="E_CTUD_UDINT.CU"/>
			<Connection Source="E_CTUD_UDINT.CO" Destination="Q_NumericValue.REQ" dx1="333.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="E_SWITCH.G" dx1="80" dx2="80" dy="160"/>
			<Connection Source="E_SR.Q" Destination="DigitalOutput_Q1.OUT" dx1="400"/>
			<Connection Source="E_SR.Q" Destination="E_PERMIT.PERMIT" dx1="366.67"/>
			<Connection Source="E_CTUD_UDINT.CV" Destination="Q_NumericValue.u32NewValue" dx1="333.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
