<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020h" Comment="DigitalInput_I1 auf DigitalOutput_Q1; E_PULSE; Impulsformend">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-5860" y="460">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_PULSE" Type="E_PULSE" Comment="" x="-7193.33" y="573.33">
			<Parameter Name="PT" Value="T#5S" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" Comment="" x="-8953.33" y="340">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="3880">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_PULSE.CNF" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="373.33" dx2="373.33" dy="0"/>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_PULSE.REQ" Comment=""/>
			<Connection Source="INIT" Destination="DigitalInput_I1_CLK.INIT" Comment="" dx1="2640">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_PULSE.Q" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="73.33" dx2="73.33" dy="0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
