<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020h" Comment="DigitalInput_I1 auf DigitalOutput_Q1; E_PULSE; Impulsformend" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-5860" y="460">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_PULSE" Type="E_PULSE" x="-7193.33" y="573.33">
			<Parameter Name="PT" Value="T#5S"/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" x="-8953.33" y="340">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="E_PULSE.CNF" Destination="DigitalOutput_Q1.REQ" dx1="373.33"/>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_PULSE.REQ" dx1="520"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_PULSE.Q" Destination="DigitalOutput_Q1.OUT" dx1="73.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
