<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_003c" Comment="DigitalInput_I1-2-3-4 auf AUX">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="logiBUS_8_DO" Type="UT_AuxiliaryOutputMapping_Type_02_Bool_NonLatched" x="-3400" y="100">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_1" Value="'App.Control.functions.F1.QX'"/>
			<Parameter Name="DigitalOutput_2" Value="'App.Control.functions.F2.QX'"/>
			<Parameter Name="DigitalOutput_3" Value="'App.Control.functions.F3.QX'"/>
			<Parameter Name="DigitalOutput_4" Value="'App.Control.functions.F4.QX'"/>
		</FB>
		<FB Name="logiBUS_8_DI" Type="logiBUS_8_DI" x="-3400" y="-900">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I1" Value="'App.Control.functions.F1.IX'"/>
			<Parameter Name="DigitalInput_I2" Value="'App.Control.functions.F2.IX'"/>
			<Parameter Name="DigitalInput_I3" Value="'App.Control.functions.F3.IX'"/>
			<Parameter Name="DigitalInput_I4" Value="'App.Control.functions.F4.IX'"/>
			<Parameter Name="DigitalInput_I5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
	</SubAppNetwork>
</SubAppType>
