<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_012b" Comment="Numeric Value Input und Speichern">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_NumericValueInputMapping" Type="UT_NumericValueInputMapping" Comment="" x="-3966.67" y="566.67">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_1" Value="InputNumber_I1" Comment=""/>
			<Parameter Name="NumericValueInput_1" Value="'Ventilsteuerung.functions.InputNumber_I1'" Comment=""/>
			<Parameter Name="u16ObjId_2" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="NumericValueInput_2" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_3" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="NumericValueInput_3" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_4" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="NumericValueInput_4" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_5" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="NumericValueInput_5" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_6" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="NumericValueInput_6" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_7" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="NumericValueInput_7" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId_8" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="NumericValueInput_8" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="UT_NumericValueInputMapping.INIT" Comment="" dx1="2006.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
