<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012b" Comment="Numeric Value Input und Speichern" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_DWORD_TO_UDINT" Type="F_DWORD_TO_UDINT" x="-3060" y="1253.33">
		</FB>
		<FB Name="InputNumber_I1" Type="ID" x="-4126.66" y="680">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="INI" Type="INI" x="-913.33" y="680">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="SECTION" Value="SECTION_I1_STORE"/>
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#55"/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" x="1020" y="906.67">
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="CbVtStatus" Type="CbVtStatus" x="-4133.33" y="-6.67">
			<Parameter Name="STATUS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8Instance" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="qWsActive" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="wPage" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="InputNumber_I1.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="300"/>
			<Connection Source="CbVtStatus.IND" Destination="Q_NumericValue.REQ" dx1="4206.67"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="INI.SET" dx1="253.33" dx2="253.33" dy="0"/>
			<Connection Source="INI.INITO" Destination="INI.GET" dx1="80" dx2="80" dy="-253.33"/>
			<Connection Source="INI.INITO" Destination="Q_NumericValue.INIT" dx1="693.33" dx2="693.33" dy="0"/>
			<Connection Source="INI.GETO" Destination="Q_NumericValue.REQ" dx1="486.67" dx2="486.67" dy="0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="InputNumber_I1.IN" Destination="F_DWORD_TO_UDINT.IN" dx1="226.67"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="INI.VALUE" dx1="560"/>
			<Connection Source="INI.VALUEO" Destination="Q_NumericValue.u32NewValue" dx1="453.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
