<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012b" Comment="Numeric Value Input und Speichern" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_DWORD_TO_UDINT" Type="F_DWORD_TO_UDINT" x="-3100" y="1200">
		</FB>
		<FB Name="InputNumber_I1" Type="ID" x="-4200" y="800">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="INI" Type="INI" x="-900" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="SECTION" Value="SECTION_I1_STORE"/>
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#55"/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" x="1000" y="900">
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="CbVtStatus" Type="CbVtStatus" x="-4300" y="0">
			<Parameter Name="STATUS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8Instance" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="qWsActive" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="wPage" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="InputNumber_I1.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="300"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="INI.SET" dx1="253.33"/>
			<Connection Source="INI.GETO" Destination="Q_NumericValue.REQ" dx1="440"/>
			<Connection Source="CbVtStatus.IND" Destination="INI.GET" dx1="2073.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="InputNumber_I1.IN" Destination="F_DWORD_TO_UDINT.IN"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="INI.VALUE"/>
			<Connection Source="INI.VALUEO" Destination="Q_NumericValue.u32NewValue"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
