<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012b" Comment="Numeric Value Input und Speichern">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_DWORD_TO_UDINT" Type="F_DWORD_TO_UDINT" Comment="" x="-3060" y="1253.33">
		</FB>
		<FB Name="InputNumber_I1" Type="ID" Comment="" x="-4126.66" y="680">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="NVS_UDINT" Type="INI_UDINT" Comment="" x="-913.33" y="680">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="SECTION" Value="SECTION_I1_STORE" Comment=""/>
			<Parameter Name="KEY" Value="KEY_I1_STORE" Comment=""/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" Comment="" x="1020" y="906.67">
			<Parameter Name="u16ObjId" Value="InputNumber_I1" Comment=""/>
		</FB>
		<FB Name="CbVtStatus" Type="CbVtStatus" Comment="" x="-4133.33" y="-6.67">
			<Parameter Name="STATUS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8Instance" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="qWsActive" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="wPage" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="InputNumber_I1.IND" Destination="F_DWORD_TO_UDINT.REQ" Comment="" dx1="300"/>
			<Connection Source="INIT" Destination="InputNumber_I1.INIT" Comment="" dx1="833.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="CbVtStatus.INIT" Comment="" dx1="1466.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CbVtStatus.IND" Destination="Q_NumericValue.REQ" Comment="" dx1="4206.67"/>
			<Connection Source="INIT" Destination="NVS_UDINT.INIT" Comment="" dx1="3913.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="NVS_UDINT.SET" Comment="" dx1="253.33"/>
			<Connection Source="NVS_UDINT.INITO" Destination="NVS_UDINT.GET" Comment="" dx1="80" dx2="393.33" dy="-253.33"/>
			<Connection Source="NVS_UDINT.INITO" Destination="Q_NumericValue.INIT" Comment="" dx1="693.33"/>
			<Connection Source="NVS_UDINT.GETO" Destination="Q_NumericValue.REQ" Comment="" dx1="486.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="InputNumber_I1.IN" Destination="F_DWORD_TO_UDINT.IN" Comment="" dx1="226.67"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="NVS_UDINT.VALUE" Comment=""/>
			<Connection Source="NVS_UDINT.VALUEO" Destination="Q_NumericValue.u32NewValue" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
