<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="tastend" Comment="Subapplication Type">
	<Identification Standard="61499-2" Description="Copyright (c) 2024 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2024-10-23">
	</VersionInfo>
	<CompilerInfo packageName="FBs::Uebungen::Uebung_103::subapp">
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="OUT" Type="AX"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="IN" Type="AX"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<AdapterConnections>
			<Connection Source="IN" Destination="OUT" dx1="3386.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
