<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_008" Comment="Blinker mit E_CYCLE, E_SWITCH und E_SR" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="566.67" y="-906.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_CYCLE" Type="E_CYCLE" x="-3740" y="-680">
			<Parameter Name="DT" Value="T#1s"/>
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" x="-2266.67" y="-680">
		</FB>
		<FB Name="E_SR" Type="E_SR" x="-680" y="-680">
		</FB>
		<EventConnections>
			<Connection Source="E_CYCLE.EO" Destination="E_SWITCH.EI"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_SR.S"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_SR.R"/>
			<Connection Source="E_SR.EO" Destination="DigitalOutput_Q1.REQ" dx1="380"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="E_SWITCH.G" dx1="80" dx2="80" dy="160"/>
			<Connection Source="E_SR.Q" Destination="DigitalOutput_Q1.OUT" dx1="400"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
