<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_DI" Type="Hutschienenmoped_XL_8_DI" Comment="" x="-3733.3333333333335" y="-666.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="255" Comment=""/>
			<Parameter Name="u16ObjId" Value="65535" Comment=""/>
			<Parameter Name="DigitalInput_I1" Value="'Ventilsteuerung.functions.DigitalInput_I1'" Comment=""/>
			<Parameter Name="DigitalInput_I2" Value="'Ventilsteuerung.functions.DigitalInput_I2'" Comment=""/>
			<Parameter Name="DigitalInput_I3" Value="'Ventilsteuerung.functions.DigitalInput_I3'" Comment=""/>
			<Parameter Name="DigitalInput_I4" Value="'Ventilsteuerung.functions.DigitalInput_I4'" Comment=""/>
		</FB>
		<Comment Comment="BUTTON_PRESS_NORMAL" x="-5333.333333333334" y="-666.6666666666667" width="1300.0" height="226.66666666666669"/>
		<FB Name="Hutschienenmoped_XL_1_LED" Type="Hutschienenmoped_XL_1_LED" Comment="" x="-153.33333333333334" y="-666.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="Output_Q1" Comment=""/>
			<Parameter Name="u16ObjId" Value="65535" Comment=""/>
			<Parameter Name="LED_5HZ" Value="'Ventilsteuerung.functions.LED_Q1_5HZ'" Comment=""/>
			<Parameter Name="LED_1HZ" Value="'Ventilsteuerung.functions.LED_Q1_1HZ'" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="Hutschienenmoped_XL_8_DI.INIT" Comment="" dx1="80.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="Hutschienenmoped_XL_1_LED.INIT" Comment="" dx1="3260.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
