<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_028" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_DO" Type="Hutschienenmoped_XL_8_DO" Comment="" x="-3333.3333333333335" y="800.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment=""/>
			<Parameter Name="u16ObjId" Value="ID_NULL" Comment=""/>
			<Parameter Name="DigitalOutput_Q1" Value="'Ventilsteuerung.functions.DigitalOutput_Q1'" Comment=""/>
			<Parameter Name="DigitalOutput_Q2" Value="'Ventilsteuerung.functions.DigitalOutput_Q2'" Comment=""/>
			<Parameter Name="DigitalOutput_Q3" Value="'Ventilsteuerung.functions.DigitalOutput_Q3'" Comment=""/>
			<Parameter Name="DigitalOutput_Q4" Value="'Ventilsteuerung.functions.DigitalOutput_Q4'" Comment=""/>
		</FB>
		<FB Name="Hutschienenmoped_XL_8_DI" Type="Hutschienenmoped_XL_8_DI" Comment="" x="-3333.3333333333335" y="-1066.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment=""/>
			<Parameter Name="u16ObjId" Value="ID_NULL" Comment=""/>
			<Parameter Name="DigitalInput_I1" Value="'Ventilsteuerung.functions.DigitalInput_I1'" Comment=""/>
			<Parameter Name="DigitalInput_I2" Value="'Ventilsteuerung.functions.DigitalInput_I2'" Comment=""/>
			<Parameter Name="DigitalInput_I3" Value="'Ventilsteuerung.functions.DigitalInput_I3'" Comment=""/>
			<Parameter Name="DigitalInput_I4" Value="'Ventilsteuerung.functions.DigitalInput_I4'" Comment=""/>
		</FB>
		<FB Name="Hutschienenmoped_XL_8_AI" Type="Hutschienenmoped_XL_8_AI" Comment="" x="-3466.666666666667" y="2666.666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment=""/>
			<Parameter Name="u16ObjId" Value="ID_NULL" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="Hutschienenmoped_XL_8_DI.INIT" Comment="" dx1="73.33333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="Hutschienenmoped_XL_8_DO.INIT" Comment="" dx1="73.33333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
