<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_TC_SC" Comment="für TC-SC also Task Controller Section Control">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="TC_InputMapping" Type="TC_InputMapping" Comment="" x="1006.6666666666667" y="153.33333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment=""/>
			<Parameter Name="u16ObjId" Value="ID_NULL" Comment=""/>
			<Parameter Name="wDevElementNumb_1" Value="DE_NUM_DEVICE" Comment=""/>
			<Parameter Name="wDDI_1" Value="DDI_SETPOINT_CONDENSED_WORK_STATE_1_16" Comment=""/>
			<Parameter Name="Input_1" Value="'SETPOINT_CONDENSED_WORK_STATE_1_16'" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="TC_InputMapping.INIT" Comment="" dx1="1173.3333333333335" dx2="1173.3333333333335" dy="0.0"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
