<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_003a" Comment="DigitalInput_I1/_I2 auf DigitalOutput_Q1/_I2">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_DO" Type="Hutschienenmoped_XL_8_DO" Comment="" x="-3333.3333333333335" y="-133.33333333333334">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="ID_NULL" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q1" Value="'Ventilsteuerung.functions.F1.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_Q2" Value="'Ventilsteuerung.functions.F2.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_Q3" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q4" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q5" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q6" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q7" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalOutput_Q8" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_8_DI" Type="Hutschienenmoped_XL_8_DI" Comment="" x="-3333.3333333333335" y="-1066.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="GLOBAL" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="ID_NULL" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I1" Value="'Ventilsteuerung.functions.F1.IX'" Comment=""/>
			<Parameter Name="DigitalInput_I2" Value="'Ventilsteuerung.functions.F2.IX'" Comment=""/>
			<Parameter Name="DigitalInput_I3" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I4" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I5" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I6" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I7" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I8" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="Hutschienenmoped_XL_8_DI.INIT" Comment="" dx1="73.33333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="Hutschienenmoped_XL_8_DO.INIT" Comment="" dx1="73.33333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
