<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Ventilsteuerung" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="mapping" Type="mapping" Comment="" x="133.33333333333334" y="-1066.6666666666667">
		</SubApp>
		<SubApp Name="Schieber" Type="TimedFunc" Comment="" x="133.33333333333334" y="-533.3333333333334">
			<Parameter Name="u16ObjId" Value="SoftKey_F1" Comment=""/>
			<Parameter Name="u16ObjIdA" Value="AuxFunction2_X1" Comment=""/>
		</SubApp>
		<FB Name="QX" Type="QX" Comment="" x="2133.3333333333335" y="-533.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="mapping.COLD" Comment="" dx1="733.3333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="Schieber.INIT" Comment="" dx1="800.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="QX.INIT" Comment="" dx1="1733.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Schieber.CNF" Destination="QX.REQ" Comment="" dx1="646.6666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Schieber.OUT" Destination="QX.OUT" Comment="" dx1="646.6666666666667"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
