<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Ventilsteuerung" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="mapping" Type="mapping_Uebung_034" Comment="" x="-266.6666666666667" y="-266.6666666666667">
		</SubApp>
		<SubApp Name="functions" Type="Uebung_034" Comment="" x="-266.6666666666667" y="273.33333333333337">
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="mapping.INIT" Comment="" dx1="533.3333333333334" dx2="533.3333333333334" dy="0.0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="functions.INIT" Comment="" dx1="800.0" dx2="800.0" dy="0.0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
