<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_018" Comment="Control Audio Signal und Delay" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_F1_UP" Type="IE" x="-4500" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_CtrlAudioSignal_0" Type="Q_CtrlAudioSignal" x="-2700" y="-800">
			<Parameter Name="u8NumOfRepit" Value="1"/>
			<Parameter Name="u16Frequency" Value="440"/>
			<Parameter Name="u16OnTimeMs" Value="150"/>
			<Parameter Name="u16OffTimeMs" Value="0"/>
		</FB>
		<FB Name="Q_CtrlAudioSignal_1" Type="Q_CtrlAudioSignal" x="1200" y="-800">
			<Parameter Name="u8NumOfRepit" Value="1"/>
			<Parameter Name="u16Frequency" Value="880"/>
			<Parameter Name="u16OnTimeMs" Value="150"/>
			<Parameter Name="u16OffTimeMs" Value="0"/>
		</FB>
		<FB Name="E_DELAY" Type="E_DELAY" x="-400" y="-700">
			<Parameter Name="DT" Value="T#250ms"/>
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_F1_UP.IND" Destination="Q_CtrlAudioSignal_0.REQ"/>
			<Connection Source="E_DELAY.EO" Destination="Q_CtrlAudioSignal_1.REQ"/>
			<Connection Source="Q_CtrlAudioSignal_0.CNF" Destination="E_DELAY.START"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
