<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_102" Comment="DigitalInput_I1 auf DigitalOutput_Q1, mit Plug and Socket" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IXA" x="400" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QXA" x="3000" y="-300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_OR_2" Type="io::adp::boolean::AX_OR_2" x="1700" y="100">
		</FB>
		<FB Name="DigitalInput_I2" Type="IXA" x="400" y="700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<AdapterConnections>
			<Connection Source="AX_OR_2.OUT" Destination="DigitalOutput_Q1.OUT" dx1="346.67"/>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_OR_2.IN1" dx1="266.67"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AX_OR_2.IN2" dx1="186.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
