<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_102" Comment="DigitalInput_I1 auf DigitalOutput_Q1, mit Plug and Socket" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IXA" x="400" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QXA" x="3000" y="-300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_OR_2" Type="AX_OR_2" x="1700" y="100">
		</FB>
		<FB Name="DigitalInput_I2" Type="IXA" x="400" y="700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<AdapterConnections>
			<Connection Source="AX_OR_2.OUT" Destination="DigitalOutput_Q1.OUT" dx1="346.67"/>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_OR_2.IN1" dx1="266.67"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AX_OR_2.IN2" dx1="186.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
