<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012" Comment="Numeric Value Input und Speichern" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_DWORD_TO_UDINT" Type="F_DWORD_TO_UDINT" x="-2700" y="1100">
		</FB>
		<FB Name="InputNumber_I1" Type="ID" x="-3800" y="700">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="NVS" Type="NVS" x="-900" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#0"/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" x="800" y="800">
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="CbVtStatus" Type="CbVtStatus" x="-3740" y="0">
			<Parameter Name="STATUS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8Instance" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="qWsActive" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="wPage" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="InputNumber_I1.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="300"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="NVS.SET" dx1="380"/>
			<Connection Source="NVS.GETO" Destination="Q_NumericValue.REQ"/>
			<Connection Source="CbVtStatus.IND" Destination="NVS.GET" dx1="1033.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="InputNumber_I1.IN" Destination="F_DWORD_TO_UDINT.IN"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="NVS.VALUE"/>
			<Connection Source="NVS.VALUEO" Destination="Q_NumericValue.u32NewValue" dx1="313.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
