<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_050" Comment="DigitalInput_I1 auf DigitalOutput_Q1">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="ID" Type="ID" Comment="" x="-460.0" y="-393.33333333333337">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="QD" Type="QD" Comment="" x="-420.0" y="933.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="STRUCT_DEMUX" Type="STRUCT_DEMUX" Comment="" x="2533.3333333333335" y="-1066.6666666666667">
			<Attribute Name="StructuredType" Type="STRING" Value="ANY_STRUCT"/>
		</FB>
	</SubAppNetwork>
</SubAppType>
