<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_003a_sub" Comment="IX auf QX (generisch)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="QX" Type="QX" Comment="" x="-2533.3333333333335" y="-800.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="IX" Type="IX" Comment="" x="-4533.333333333334" y="-1026.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="IX.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="IX.INITO" Destination="QX.INIT" Comment="" dx1="1373.3333333333335"/>
			<Connection Source="IX.IND" Destination="QX.REQ" Comment="" dx1="993.3333333333334"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="IX.IN" Destination="QX.OUT" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
