<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_028" Comment="Analog-Eingang">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-1253.3333333333335" y="13.333333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-4320.0" y="-100.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="AnalogInput_I4" Type="ID" Comment="" x="-1193.3333333333335" y="1066.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="AnalogInput_I7" Type="ID" Comment="" x="-1193.3333333333335" y="2400.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_DWORD_TO_UDINT_I7" Type="F_DWORD_TO_UDINT" Comment="" x="533.3333333333334" y="2853.3333333333335">
		</FB>
		<FB Name="F_DWORD_TO_UDINT_I4" Type="F_DWORD_TO_UDINT" Comment="" x="533.3333333333334" y="1520.0">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="DigitalOutput_Q1.REQ" Comment=""/>
			<Connection Source="DigitalInput_I1.INITO" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="1200.0"/>
			<Connection Source="COLD" Destination="DigitalInput_I1.INIT" Comment="" dx1="1180.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="AnalogInput_I4.INIT" Comment="" dx1="2740.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="AnalogInput_I7.INIT" Comment="" dx1="2733.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="AnalogInput_I7.IND" Destination="F_DWORD_TO_UDINT_I7.REQ" Comment="" dx1="960.0"/>
			<Connection Source="AnalogInput_I4.IND" Destination="F_DWORD_TO_UDINT_I4.REQ" Comment="" dx1="960.0"/>
			<Connection Source="DigitalInput_I1.IND" Destination="AnalogInput_I4.REQ" Comment="" dx1="1213.3333333333335"/>
			<Connection Source="DigitalInput_I1.IND" Destination="AnalogInput_I7.REQ" Comment="" dx1="1213.3333333333335"/>
			<Connection Source="AnalogInput_I7.CNF" Destination="F_DWORD_TO_UDINT_I7.REQ" Comment="" dx1="960.0"/>
			<Connection Source="AnalogInput_I4.CNF" Destination="F_DWORD_TO_UDINT_I4.REQ" Comment="" dx1="960.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="1273.3333333333335"/>
			<Connection Source="AnalogInput_I7.IN" Destination="F_DWORD_TO_UDINT_I7.IN" Comment=""/>
			<Connection Source="AnalogInput_I4.IN" Destination="F_DWORD_TO_UDINT_I4.IN" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
