<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_025" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-2833.3333333333335" y="-500.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="SoftKey_F1_UP" Type="IE" Comment="" x="-6833.333333333334" y="-500.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_SR_Ausfahren_Cyl_1" Type="E_SR" Comment="" x="-5000.0" y="-300.0">
		</FB>
		<FB Name="SoftKey_F2_DOWN" Type="IE" Comment="" x="-6833.333333333334" y="1000.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<Comment Comment="START-Knopf Ausfahren" x="-8500.0" y="-333.33333333333337" width="1375.0" height="366.6666666666667"/>
		<Comment Comment="Endlage Ausfahren_Cyl_1 &amp;#10;" x="-8500.0" y="1166.6666666666667" width="1375.0" height="366.6666666666667"/>
		<FB Name="DigitalOutput_Q2" Type="QX" Comment="" x="-2833.3333333333335" y="1166.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_SR_Ausfahren_Cyl_2" Type="E_SR" Comment="" x="-4833.333333333334" y="1366.6666666666667">
		</FB>
		<Comment Comment="Endlage Ausfahren_Cyl_2 &amp;#10;" x="-8500.0" y="2500.0" width="1375.0" height="366.6666666666667"/>
		<FB Name="SoftKey_F3_DOWN" Type="IE" Comment="" x="-6833.333333333334" y="2333.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<Comment Comment="Ausfahren_Cyl_1" x="-3500.0" y="333.33333333333337" width="1375.0" height="366.6666666666667"/>
		<Comment Comment="Ausfahren_Cyl_2" x="-3500.0" y="2000.0" width="1375.0" height="366.6666666666667"/>
		<FB Name="SoftKey_F9_DOWN" Type="IE" Comment="" x="-6608.333333333334" y="6591.666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_SR_Einfahren_Cyl_2" Type="E_SR" Comment="" x="-4500.0" y="3833.3333333333335">
		</FB>
		<FB Name="DigitalOutput_Q3" Type="QX" Comment="" x="-2608.3333333333335" y="3758.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<Comment Comment="Einfahren Zeit gesteuert" x="-8275.0" y="3925.0" width="1375.0" height="366.6666666666667"/>
		<FB Name="DigitalOutput_Q4" Type="QX" Comment="" x="-2608.3333333333335" y="5425.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_SR_Einfahren_Cyl_1" Type="E_SR" Comment="" x="-4608.333333333334" y="5625.0">
		</FB>
		<Comment Comment="Endlage Einfahren_Cyl_1  &amp;#10;" x="-8275.0" y="6758.333333333334" width="1375.0" height="366.6666666666667"/>
		<FB Name="SoftKey_F8_DOWN" Type="IE" Comment="" x="-6608.333333333334" y="5258.333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<Comment Comment="Einfahren_Cyl_2" x="-3275.0" y="4591.666666666667" width="1375.0" height="366.6666666666667"/>
		<Comment Comment="Endlage Einfahren_Cyl_2  &amp;#10;" x="-8275.0" y="5425.0" width="1375.0" height="366.6666666666667"/>
		<Comment Comment="Einfahren_Cyl_1 &amp;#10;" x="-3275.0" y="6258.333333333334" width="1375.0" height="366.6666666666667"/>
		<FB Name="E_DELAY" Type="E_DELAY" Comment="" x="-6500.0" y="3666.666666666667">
			<Parameter Name="DT" Value="T#2s" Comment=""/>
		</FB>
		<FB Name="E_REND_Ausfahren_Cyl_1" Type="E_REND" Comment="" x="-6000.0" y="666.6666666666667">
		</FB>
		<FB Name="E_REND_Ausfahren_Cyl_2" Type="E_REND" Comment="" x="-5833.333333333334" y="2000.0">
		</FB>
		<FB Name="E_REND_Einfahren_Cyl_2" Type="E_REND" Comment="" x="-5666.666666666667" y="4333.333333333334">
		</FB>
		<FB Name="E_REND_Einfahren_Cyl_1" Type="E_REND" Comment="" x="-5666.666666666667" y="5833.333333333334">
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="SoftKey_F1_UP.INIT" Comment="" dx1="750.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="2758.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_F1_UP.IND" Destination="E_SR_Ausfahren_Cyl_1.S" Comment=""/>
			<Connection Source="COLD" Destination="SoftKey_F2_DOWN.INIT" Comment="" dx1="750.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="E_SR_Ausfahren_Cyl_1.EO" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="816.6666666666667"/>
			<Connection Source="COLD" Destination="DigitalOutput_Q2.INIT" Comment="" dx1="4341.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="E_SR_Ausfahren_Cyl_2.EO" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="641.6666666666667"/>
			<Connection Source="COLD" Destination="SoftKey_F3_DOWN.INIT" Comment="" dx1="2350.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="SoftKey_F9_DOWN.INIT" Comment="" dx1="2350.0" dx2="2350.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="DigitalOutput_Q3.INIT" Comment="" dx1="2758.3333333333335" dx2="2758.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="DigitalOutput_Q4.INIT" Comment="" dx1="4341.666666666667" dx2="4341.666666666667" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="E_SR_Einfahren_Cyl_2.EO" Destination="DigitalOutput_Q3.REQ" Comment="" dx1="583.3333333333334"/>
			<Connection Source="COLD" Destination="SoftKey_F8_DOWN.INIT" Comment="" dx1="750.0" dx2="750.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="E_SR_Einfahren_Cyl_1.EO" Destination="DigitalOutput_Q4.REQ" Comment="" dx1="641.6666666666667" dx2="641.6666666666667" dy="0.0"/>
			<Connection Source="E_DELAY.EO" Destination="E_SR_Einfahren_Cyl_2.S" Comment="" dx1="616.6666666666667"/>
			<Connection Source="E_REND_Ausfahren_Cyl_1.EO" Destination="E_SR_Ausfahren_Cyl_1.R" Comment="" dx1="183.33333333333334"/>
			<Connection Source="E_REND_Ausfahren_Cyl_1.EO" Destination="E_SR_Ausfahren_Cyl_2.S" Comment="" dx1="266.6666666666667"/>
			<Connection Source="SoftKey_F1_UP.IND" Destination="E_REND_Ausfahren_Cyl_1.EI1" Comment="" dx1="158.33333333333334"/>
			<Connection Source="SoftKey_F2_DOWN.IND" Destination="E_REND_Ausfahren_Cyl_1.EI2" Comment="" dx1="158.33333333333334"/>
			<Connection Source="SoftKey_F2_DOWN.IND" Destination="E_REND_Ausfahren_Cyl_2.EI1" Comment="" dx1="241.66666666666669"/>
			<Connection Source="SoftKey_F3_DOWN.IND" Destination="E_REND_Ausfahren_Cyl_2.EI2" Comment="" dx1="241.66666666666669"/>
			<Connection Source="E_REND_Ausfahren_Cyl_2.EO" Destination="E_SR_Ausfahren_Cyl_2.R" Comment="" dx1="183.33333333333334"/>
			<Connection Source="E_REND_Einfahren_Cyl_1.EO" Destination="E_SR_Einfahren_Cyl_1.R" Comment="" dx1="216.66666666666669"/>
			<Connection Source="SoftKey_F8_DOWN.IND" Destination="E_REND_Einfahren_Cyl_1.EI1" Comment="" dx1="208.33333333333334"/>
			<Connection Source="SoftKey_F9_DOWN.IND" Destination="E_REND_Einfahren_Cyl_1.EI2" Comment="" dx1="208.33333333333334"/>
			<Connection Source="E_REND_Einfahren_Cyl_2.EO" Destination="E_SR_Einfahren_Cyl_1.S" Comment="" dx1="216.66666666666669"/>
			<Connection Source="E_REND_Einfahren_Cyl_2.EO" Destination="E_SR_Einfahren_Cyl_2.R" Comment="" dx1="441.6666666666667"/>
			<Connection Source="E_DELAY.EO" Destination="E_REND_Einfahren_Cyl_2.EI1" Comment="" dx1="175.0"/>
			<Connection Source="SoftKey_F8_DOWN.IND" Destination="E_REND_Einfahren_Cyl_2.EI2" Comment="" dx1="208.33333333333334"/>
			<Connection Source="E_REND_Ausfahren_Cyl_2.EO" Destination="E_DELAY.START" Comment="" dx1="100.0" dx2="100.0" dy="1233.3333333333335"/>
			<Connection Source="SoftKey_F1_UP.IND" Destination="E_REND_Ausfahren_Cyl_1.R" Comment="" dx1="100.0"/>
			<Connection Source="SoftKey_F2_DOWN.IND" Destination="E_REND_Ausfahren_Cyl_2.R" Comment="" dx1="125.0"/>
			<Connection Source="E_DELAY.EO" Destination="E_REND_Einfahren_Cyl_2.R" Comment="" dx1="100.0"/>
			<Connection Source="SoftKey_F8_DOWN.IND" Destination="E_REND_Einfahren_Cyl_1.R" Comment="" dx1="141.66666666666669"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR_Ausfahren_Cyl_1.Q" Destination="DigitalOutput_Q1.OUT" Comment=""/>
			<Connection Source="E_SR_Ausfahren_Cyl_2.Q" Destination="DigitalOutput_Q2.OUT" Comment=""/>
			<Connection Source="E_SR_Einfahren_Cyl_1.Q" Destination="DigitalOutput_Q4.OUT" Comment=""/>
			<Connection Source="E_SR_Einfahren_Cyl_2.Q" Destination="DigitalOutput_Q3.OUT" Comment="" dx1="583.3333333333334"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
