<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_052" Comment="DigitalInput_I1-_I4 auf DigitalOutput_Q1-_Q4">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-6040.0" y="-1086.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" Comment="" x="-6040.0" y="26.666666666666668">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I3" Type="IX" Comment="" x="-6040.0" y="1140.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="QX" Comment="" x="-1386.6666666666667" y="140.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I4" Type="IX" Comment="" x="-6040.0" y="2253.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="GET_STRUCT_VALUE" Type="GET_STRUCT_VALUE" Comment="" x="-3233.3333333333335" y="253.33333333333334">
			<Parameter Name="member" Value="'b00'" Comment=""/>
		</FB>
		<FB Name="STRUCT_MUX" Type="STRUCT_MUX" Comment="" x="-4800.0" y="253.33333333333334">
			<Attribute Name="StructuredType" Type="STRING" Value="st04b"/>
			<Parameter Name="b00" Value="" Comment="BIT 00"/>
			<Parameter Name="b01" Value="" Comment="BIT 01"/>
			<Parameter Name="b02" Value="" Comment="BIT 02"/>
			<Parameter Name="b03" Value="" Comment="BIT 03"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I2.INIT" Comment="" dx1="1146.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I3.INIT" Comment="" dx1="1073.3333333333335" dx2="1073.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I4.INIT" Comment="" dx1="1140.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q4.INIT" Comment="" dx1="3946.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="GET_STRUCT_VALUE.CNF" Destination="DigitalOutput_Q4.REQ" Comment=""/>
			<Connection Source="DigitalInput_I1.IND" Destination="STRUCT_MUX.REQ" Comment="" dx1="80.0"/>
			<Connection Source="DigitalInput_I2.IND" Destination="STRUCT_MUX.REQ" Comment=""/>
			<Connection Source="DigitalInput_I3.IND" Destination="STRUCT_MUX.REQ" Comment="" dx1="80.0"/>
			<Connection Source="DigitalInput_I4.IND" Destination="STRUCT_MUX.REQ" Comment="" dx1="80.0"/>
			<Connection Source="STRUCT_MUX.CNF" Destination="GET_STRUCT_VALUE.REQ" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="GET_STRUCT_VALUE.output" Destination="DigitalOutput_Q4.OUT" Comment="" dx1="73.33333333333334"/>
			<Connection Source="STRUCT_MUX.OUT" Destination="GET_STRUCT_VALUE.in_struct" Comment="" dx1="73.33333333333334"/>
			<Connection Source="DigitalInput_I1.IN" Destination="STRUCT_MUX.b00" Comment="" dx1="146.66666666666669"/>
			<Connection Source="DigitalInput_I2.IN" Destination="STRUCT_MUX.b01" Comment="" dx1="146.66666666666669"/>
			<Connection Source="DigitalInput_I3.IN" Destination="STRUCT_MUX.b02" Comment="" dx1="146.66666666666669"/>
			<Connection Source="DigitalInput_I4.IN" Destination="STRUCT_MUX.b03" Comment="" dx1="213.33333333333334"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
