<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004a4" Comment="mit E_SPLIT">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS_QX" x="-3700" y="-100">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS_IE" x="-8533.33" y="-6.66">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I1"/>
			<Parameter Name="InputEvent" Value="logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_T_FF_Q1" Type="E_T_FF" x="-5466.67" y="0">
		</FB>
		<FB Name="E_T_FF_Q2" Type="E_T_FF" x="-5500" y="900">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS_QX" x="-3700" y="800">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q2"/>
		</FB>
		<FB Name="E_SPLIT" Type="E_SPLIT" x="-7100" y="200">
		</FB>
		<EventConnections>
			<Connection Source="E_T_FF_Q1.EO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_T_FF_Q2.EO" Destination="DigitalOutput_Q2.REQ"/>
			<Connection Source="E_SPLIT.EO1" Destination="E_T_FF_Q1.CLK" dx1="493.33"/>
			<Connection Source="E_SPLIT.EO2" Destination="E_T_FF_Q2.CLK" dx1="493.33"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_SPLIT.EI"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF_Q1.Q" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="E_T_FF_Q2.Q" Destination="DigitalOutput_Q2.OUT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
