<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_122" Comment="Übung zu ISOBUS Name">
	<Identification Standard="61499-2" Description="Copyright (c) 2025 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
		<Import declaration="isobus::pgn::ISOUSERHOME_e"/>
		<Import declaration="isobus::pgn::ISO_CAN_NODE"/>
		<Import declaration="isobus::pgn::NAMEFIELD_T"/>
		<Import declaration="isobus::pgn::ISONETEVENT_T"/>
		<Import declaration="isobus::pgn::CF_INFO_T"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="NmGetCfInfo" Type="isobus::pgn::NmGetCfInfo" x="-1300" y="6400">
			<Parameter Name="u8CanIdx" Value="ISO_CAN_NODE::NODE1"/>
			<Parameter Name="member" Value="ISOUSERHOME_e::intern"/>
		</FB>
		<FB Name="LOG_16" Type="eclipse4diac::utils::logging::LOG_16" x="2700" y="4900">
		</FB>
		<FB Name="LOG_16B" Type="eclipse4diac::utils::logging::LOG_16" x="2700" y="6900">
		</FB>
		<FB Name="STRUCT_DEMUX" Type="eclipse4diac::convert::STRUCT_DEMUX" x="7200" y="3700">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_1" Type="eclipse4diac::convert::STRUCT_DEMUX" x="7200" y="7200">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_2" Type="eclipse4diac::convert::STRUCT_DEMUX" x="7200" y="4900">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_3" Type="eclipse4diac::convert::STRUCT_DEMUX" x="7200" y="6100">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_4" Type="eclipse4diac::convert::STRUCT_DEMUX" x="7200" y="8500">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_5" Type="eclipse4diac::convert::STRUCT_DEMUX" x="7200" y="9800">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<EventConnections>
			<Connection Source="NmGetCfInfo.IND" Destination="LOG_16.REQ" dx1="980"/>
			<Connection Source="NmGetCfInfo.IND" Destination="LOG_16B.REQ" dx1="1826.67"/>
			<Connection Source="LOG_16.CNF" Destination="STRUCT_DEMUX.REQ" dx1="1966.67"/>
			<Connection Source="LOG_16B.CNF" Destination="STRUCT_DEMUX_1.REQ" dx1="2513.33"/>
			<Connection Source="LOG_16.CNF" Destination="STRUCT_DEMUX_2.REQ"/>
			<Connection Source="LOG_16.CNF" Destination="STRUCT_DEMUX_3.REQ" dx1="2166.67"/>
			<Connection Source="LOG_16B.CNF" Destination="STRUCT_DEMUX_4.REQ" dx1="2513.33"/>
			<Connection Source="LOG_16B.CNF" Destination="STRUCT_DEMUX_5.REQ" dx1="2513.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="NmGetCfInfo.sNetEv" Destination="LOG_16.IN" dx1="1280"/>
			<Connection Source="NmGetCfInfo.sCfInfo" Destination="LOG_16B.IN" dx1="1580"/>
			<Connection Source="LOG_16.OUT1" Destination="STRUCT_DEMUX.IN" dx1="1166.67"/>
			<Connection Source="LOG_16B.OUT1" Destination="STRUCT_DEMUX_1.IN" dx1="1113.33"/>
			<Connection Source="LOG_16.OUT2" Destination="STRUCT_DEMUX_2.IN" dx1="1966.67"/>
			<Connection Source="LOG_16.OUT3" Destination="STRUCT_DEMUX_3.IN" dx1="1966.67"/>
			<Connection Source="LOG_16B.OUT3" Destination="STRUCT_DEMUX_5.IN" dx1="640"/>
			<Connection Source="LOG_16B.OUT2" Destination="STRUCT_DEMUX_4.IN" dx1="966.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
