<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-533.3333333333334" y="-800.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-4533.333333333334" y="-933.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="comp" Type="comp" Comment="" x="-2400.0" y="-800.0">
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="DigitalInput_I1.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1.INITO" Destination="comp.INIT" Comment="" dx1="720.0"/>
			<Connection Source="comp.INITO" Destination="DigitalOutput_Q1.INIT" Comment=""/>
			<Connection Source="DigitalInput_I1.IND" Destination="comp.REQ" Comment="" dx1="720.0"/>
			<Connection Source="comp.CNF" Destination="DigitalOutput_Q1.REQ" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="comp.QO" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="673.3333333333334"/>
			<Connection Source="DigitalInput_I1.IN" Destination="comp.QI" Comment="" dx1="720.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
