<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039" Comment="Spiegelabfolge V2 mit Schrittkette">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_TimeOut" Type="E_TimeOut" Comment="" x="-6053.333333333334" y="3553.3333333333335">
		</FB>
		<FB Name="DigitalInput_UP_I1" Type="IE" Comment="" x="-9866.666666666668" y="166.66666666666669">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_UP_I2" Type="IE" Comment="" x="-9866.666666666668" y="1146.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_UP_I3" Type="IE" Comment="" x="-9866.666666666668" y="2126.666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_UP_I4" Type="IE" Comment="" x="-9866.666666666668" y="3106.666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="sequence_04" Type="sequence_ET_05" Comment="" x="-8153.333333333334" y="-120.0">
			<Parameter Name="DT_S1_S2" Value="NO_TIME" Comment=""/>
			<Parameter Name="DT_S2_S3" Value="NO_TIME" Comment=""/>
			<Parameter Name="DT_S3_S4" Value="T#5s" Comment=""/>
			<Parameter Name="DT_S4_S5" Value="NO_TIME" Comment=""/>
			<Parameter Name="DT_S5_START" Value="NO_TIME" Comment=""/>
		</FB>
		<SubApp Name="NumbAnzeig" Type="Uebung_039_sub_NumbAnzeig" Comment="" x="-6526.666666666667" y="-986.6666666666667">
		</SubApp>
		<FB Name="SoftKey_F1_UP" Type="IE" Comment="" x="-11373.333333333334" y="-346.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<SubApp Name="Q1" Type="Uebung_039_sub_Outputs" Comment="" x="-6053.333333333334" y="-233.33333333333334">
			<Parameter Name="u16ObjId" Value="SoftKey_F8" Comment=""/>
		</SubApp>
		<SubApp Name="Q4" Type="Uebung_039_sub_Outputs" Comment="" x="-6053.333333333334" y="2606.666666666667">
			<Parameter Name="u16ObjId" Value="SoftKey_F3" Comment=""/>
		</SubApp>
		<SubApp Name="Q2" Type="Uebung_039_sub_Outputs" Comment="" x="-6053.333333333334" y="713.3333333333334">
			<Parameter Name="u16ObjId" Value="SoftKey_F2" Comment=""/>
		</SubApp>
		<SubApp Name="Q3" Type="Uebung_039_sub_Outputs" Comment="" x="-6053.333333333334" y="1660.0">
			<Parameter Name="u16ObjId" Value="SoftKey_F9" Comment=""/>
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_UP_I1.INIT" Comment="" dx1="453.33333333333337">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_UP_I2.INIT" Comment="" dx1="273.33333333333337">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_UP_I3.INIT" Comment="" dx1="453.33333333333337" dx2="453.33333333333337" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_UP_I4.INIT" Comment="" dx1="1453.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_UP_I1.IND" Destination="sequence_04.S1_S2" Comment="" dx1="220.0"/>
			<Connection Source="DigitalInput_UP_I2.IND" Destination="sequence_04.S2_S3" Comment="" dx1="286.6666666666667"/>
			<Connection Source="DigitalInput_UP_I3.IND" Destination="sequence_04.S4_S5" Comment="" dx1="353.33333333333337"/>
			<Connection Source="DigitalInput_UP_I4.IND" Destination="sequence_04.S5_START" Comment="" dx1="420.0"/>
			<Connection Source="sequence_04.CNF" Destination="NumbAnzeig.CNF" Comment="" dx1="73.33333333333334"/>
			<Connection Source="INIT" Destination="NumbAnzeig.INIT" Comment="" dx1="2933.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="SoftKey_F1_UP.INIT" Comment="" dx1="173.33333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_F1_UP.IND" Destination="sequence_04.START_S1" Comment=""/>
			<Connection Source="INIT" Destination="Q1.INIT" Comment="" dx1="3066.666666666667" dx2="3066.666666666667" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="sequence_04.EO_S1" Destination="Q1.REQ" Comment="" dx1="406.6666666666667" dx2="406.6666666666667" dy="0.0"/>
			<Connection Source="INIT" Destination="Q4.INIT" Comment="" dx1="2613.3333333333335" dx2="2613.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="sequence_04.EO_S5" Destination="Q4.REQ" Comment="" dx1="273.33333333333337" dx2="273.33333333333337" dy="0.0"/>
			<Connection Source="INIT" Destination="Q2.INIT" Comment="" dx1="2613.3333333333335" dx2="2613.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="sequence_04.EO_S2" Destination="Q2.REQ" Comment="" dx1="540.0" dx2="540.0" dy="0.0"/>
			<Connection Source="INIT" Destination="Q3.INIT" Comment="" dx1="2613.3333333333335" dx2="2613.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="sequence_04.EO_S4" Destination="Q3.REQ" Comment="" dx1="406.6666666666667" dx2="406.6666666666667" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="sequence_04.STATE_NR" Destination="NumbAnzeig.STATE_NR" Comment="" dx1="340.0"/>
			<Connection Source="sequence_04.DO_S1" Destination="Q1.OUT" Comment="" dx1="473.33333333333337" dx2="473.33333333333337" dy="0.0"/>
			<Connection Source="sequence_04.DO_S5" Destination="Q4.OUT" Comment="" dx1="140.0" dx2="140.0" dy="0.0"/>
			<Connection Source="sequence_04.DO_S2" Destination="Q2.OUT" Comment="" dx1="540.0" dx2="540.0" dy="0.0"/>
			<Connection Source="sequence_04.DO_S4" Destination="Q3.OUT" Comment="" dx1="206.66666666666669" dx2="206.66666666666669" dy="0.0"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="sequence_04.timeOut" Destination="E_TimeOut.TimeOutSocket" Comment="" dx1="73.33333333333334"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
