<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012a" Comment="Numeric Value Input und Speichern">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="CbVtStatus" Type="CbVtStatus" Comment="" x="-5600.0" y="1333.3333333333335">
		</FB>
		<SubApp Name="Uebung_012a_sub" Type="Uebung_012a_sub" Comment="" x="-3066.666666666667" y="1560.0">
			<Parameter Name="KEY" Value="KEY_I1_STORE" Comment=""/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1" Comment=""/>
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="CbVtStatus.INIT" Comment="" dx1="326.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Uebung_012a_sub.INIT" Comment="" dx1="1466.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="CbVtStatus.IND" Destination="Uebung_012a_sub.IND" Comment="" dx1="893.3333333333334"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
