<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_122" Comment="Übung zu ISOBUS Name">
	<Identification Standard="61499-2" Description="Copyright (c) 2025 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
		<Import declaration="isobus::pgn::ISOUSERHOME_e"/>
		<Import declaration="isobus::pgn::ISO_CAN_NODE"/>
		<Import declaration="isobus::pgn::NAMEFIELD_T"/>
		<Import declaration="isobus::pgn::ISONETEVENT_T"/>
		<Import declaration="isobus::pgn::CF_INFO_T"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="NmGetCfInfo" Type="isobus::pgn::NmGetCfInfo" x="-5400" y="9600">
			<Parameter Name="u8CanIdx" Value="ISO_CAN_NODE::NODE1"/>
			<Parameter Name="member" Value="ISOUSERHOME_e::intern"/>
		</FB>
		<FB Name="LOG_16" Type="eclipse4diac::utils::logging::LOG_16" x="-1700" y="-2120">
		</FB>
		<FB Name="LOG_16B" Type="eclipse4diac::utils::logging::LOG_16" x="-1800" y="21320">
		</FB>
		<FB Name="SD_A_1" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-12273.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_2" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-10886.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_3" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-9500">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_4" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-8113.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_5" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-6726.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_6" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-5340">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_7" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-3953.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_8" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6373.33" y="-2566.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_9" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6373.33" y="-1180">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_10" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="206.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_11" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="1593.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_12" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="2980">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_13" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="4366.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_14" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="5753.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_15" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="7140">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_16" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="8526.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_B_1" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="9966.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_2" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="11553.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_3" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="13140">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_4" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="14726.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_5" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="16313.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_6" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="17900">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_7" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="19486.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_8" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="21073.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_9" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="22660">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_10" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="24246.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_11" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="25833.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_12" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="27420">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_13" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="29006.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_14" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="30593.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_15" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="32180">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="SD_B_16" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6273.33" y="33766.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<EventConnections>
			<Connection Source="NmGetCfInfo.IND" Destination="LOG_16.REQ" dx1="1520"/>
			<Connection Source="NmGetCfInfo.IND" Destination="LOG_16B.REQ" dx1="1493.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_1.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_2.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_3.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_4.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_5.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_6.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_7.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_8.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_9.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_10.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_11.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_12.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_13.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_14.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_15.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_16.REQ" dx1="533.33"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_1.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_2.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_3.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_4.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_5.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_6.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_7.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_8.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_9.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_10.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_11.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_12.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_13.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_14.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_15.REQ" dx1="600"/>
			<Connection Source="LOG_16B.CNF" Destination="SD_B_16.REQ" dx1="600"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="NmGetCfInfo.sNetEv" Destination="LOG_16.IN" dx1="1786.67"/>
			<Connection Source="NmGetCfInfo.sCfInfo" Destination="LOG_16B.IN" dx1="1813.33"/>
			<Connection Source="LOG_16.OUT1" Destination="SD_A_1.IN" dx1="66.67"/>
			<Connection Source="LOG_16.OUT2" Destination="SD_A_2.IN" dx1="133.33"/>
			<Connection Source="LOG_16.OUT3" Destination="SD_A_3.IN" dx1="200"/>
			<Connection Source="LOG_16.OUT4" Destination="SD_A_4.IN" dx1="266.67"/>
			<Connection Source="LOG_16.OUT5" Destination="SD_A_5.IN" dx1="333.33"/>
			<Connection Source="LOG_16.OUT6" Destination="SD_A_6.IN" dx1="400"/>
			<Connection Source="LOG_16.OUT7" Destination="SD_A_7.IN" dx1="466.67"/>
			<Connection Source="LOG_16.OUT8" Destination="SD_A_8.IN" dx1="600"/>
			<Connection Source="LOG_16.OUT9" Destination="SD_A_9.IN" dx1="600"/>
			<Connection Source="LOG_16.OUT10" Destination="SD_A_10.IN" dx1="466.67"/>
			<Connection Source="LOG_16.OUT11" Destination="SD_A_11.IN" dx1="400"/>
			<Connection Source="LOG_16.OUT12" Destination="SD_A_12.IN" dx1="333.33"/>
			<Connection Source="LOG_16.OUT13" Destination="SD_A_13.IN" dx1="266.67"/>
			<Connection Source="LOG_16.OUT14" Destination="SD_A_14.IN" dx1="200"/>
			<Connection Source="LOG_16.OUT15" Destination="SD_A_15.IN" dx1="133.33"/>
			<Connection Source="LOG_16.OUT16" Destination="SD_A_16.IN" dx1="66.67"/>
			<Connection Source="LOG_16B.OUT1" Destination="SD_B_1.IN" dx1="66.67"/>
			<Connection Source="LOG_16B.OUT2" Destination="SD_B_2.IN" dx1="133.33"/>
			<Connection Source="LOG_16B.OUT3" Destination="SD_B_3.IN" dx1="200"/>
			<Connection Source="LOG_16B.OUT4" Destination="SD_B_4.IN" dx1="266.67"/>
			<Connection Source="LOG_16B.OUT5" Destination="SD_B_5.IN" dx1="333.33"/>
			<Connection Source="LOG_16B.OUT6" Destination="SD_B_6.IN" dx1="400"/>
			<Connection Source="LOG_16B.OUT7" Destination="SD_B_7.IN" dx1="466.67"/>
			<Connection Source="LOG_16B.OUT8" Destination="SD_B_8.IN" dx1="533.33"/>
			<Connection Source="LOG_16B.OUT9" Destination="SD_B_9.IN" dx1="533.33"/>
			<Connection Source="LOG_16B.OUT10" Destination="SD_B_10.IN" dx1="466.67"/>
			<Connection Source="LOG_16B.OUT11" Destination="SD_B_11.IN" dx1="400"/>
			<Connection Source="LOG_16B.OUT12" Destination="SD_B_12.IN" dx1="333.33"/>
			<Connection Source="LOG_16B.OUT13" Destination="SD_B_13.IN" dx1="266.67"/>
			<Connection Source="LOG_16B.OUT14" Destination="SD_B_14.IN" dx1="200"/>
			<Connection Source="LOG_16B.OUT15" Destination="SD_B_15.IN" dx1="133.33"/>
			<Connection Source="LOG_16B.OUT16" Destination="SD_B_16.IN" dx1="66.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
