<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_102b" Comment="DigitalInput_I1 auf DigitalOutput_Q1/_Q2, mit Plug and Socket" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0" >
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IXA" x="400" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QXA" x="3000" y="-300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QXA" x="3000" y="500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_SPLIT" Type="AX_SPLIT" x="1800" y="100">
		</FB>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_SPLIT.IN"/>
			<Connection Source="AX_SPLIT.OUT0" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="AX_SPLIT.OUT1" Destination="DigitalOutput_Q2.OUT" dx1="233.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
