<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_056" Comment="DigitalInput_I1-_I4 auf DigitalOutput_Q1-_Q4">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-11066.666666666668" y="0.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="BOOL_TO_Q_I1" Type="BOOL_TO_Q" Comment="" x="-8633.333333333334" y="173.33333333333334">
		</FB>
		<FB Name="QUARTERS_TO_BYTE" Type="QUARTERS_TO_BYTE" Comment="" x="-6000.0" y="1333.3333333333335">
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" Comment="" x="-11066.666666666668" y="1073.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="BOOL_TO_Q_I2" Type="BOOL_TO_Q" Comment="" x="-8633.333333333334" y="1253.3333333333335">
		</FB>
		<FB Name="DigitalInput_I3" Type="IX" Comment="" x="-11066.666666666668" y="2153.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="BOOL_TO_Q_I3" Type="BOOL_TO_Q" Comment="" x="-8633.333333333334" y="2333.3333333333335">
		</FB>
		<FB Name="DigitalInput_I4" Type="IX" Comment="" x="-11066.666666666668" y="3333.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="BOOL_TO_Q_I4" Type="BOOL_TO_Q" Comment="" x="-8633.333333333334" y="3513.3333333333335">
		</FB>
		<FB Name="Q_TO_STR_STATUS_I1" Type="Q_TO_STR_STATUS" Comment="" x="-7386.666666666667" y="173.33333333333334">
		</FB>
		<FB Name="Q_TO_STR_STATUS_I2" Type="Q_TO_STR_STATUS" Comment="" x="-7466.666666666667" y="800.0">
		</FB>
		<FB Name="Q_TO_STR_STATUS_I3" Type="Q_TO_STR_STATUS" Comment="" x="-7466.666666666667" y="2400.0">
		</FB>
		<FB Name="Q_TO_STR_STATUS_I4" Type="Q_TO_STR_STATUS" Comment="" x="-7386.666666666667" y="3513.3333333333335">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" Comment="" x="2266.666666666667" y="240.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="Q_TO_BOOL_Q1" Type="Q_TO_BOOL" Comment="" x="-906.6666666666667" y="-553.3333333333334">
		</FB>
		<FB Name="Q_TO_BOOL_Q2" Type="Q_TO_BOOL" Comment="" x="-906.6666666666667" y="386.6666666666667">
		</FB>
		<FB Name="DigitalOutput_Q3" Type="QX" Comment="" x="2266.666666666667" y="1186.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="BYTE_TO_QUARTERS" Type="BYTE_TO_QUARTERS" Comment="" x="-3866.666666666667" y="1333.3333333333335">
		</FB>
		<FB Name="Q_TO_BOOL_Q3" Type="Q_TO_BOOL" Comment="" x="-906.6666666666667" y="1333.3333333333335">
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="2266.666666666667" y="-706.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="Q_TO_BOOL_Q4" Type="Q_TO_BOOL" Comment="" x="-886.6666666666667" y="2146.666666666667">
		</FB>
		<FB Name="DigitalOutput_Q4" Type="QX" Comment="" x="2286.666666666667" y="1993.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="Q_TO_STR_STATUS_Q4" Type="Q_TO_STR_STATUS" Comment="" x="493.33333333333337" y="2193.3333333333335">
		</FB>
		<FB Name="Q_TO_STR_STATUS_Q3" Type="Q_TO_STR_STATUS" Comment="" x="473.33333333333337" y="1380.0">
		</FB>
		<FB Name="Q_TO_STR_STATUS_Q1" Type="Q_TO_STR_STATUS" Comment="" x="473.33333333333337" y="-506.6666666666667">
		</FB>
		<FB Name="Q_TO_STR_STATUS_Q2" Type="Q_TO_STR_STATUS" Comment="" x="473.33333333333337" y="433.33333333333337">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="593.3333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1.IND" Destination="BOOL_TO_Q_I1.REQ" Comment="" dx1="853.3333333333334"/>
			<Connection Source="BOOL_TO_Q_I1.CNF" Destination="QUARTERS_TO_BYTE.REQ" Comment="" dx1="273.33333333333337" dx2="346.6666666666667" dy="380.0"/>
			<Connection Source="INIT" Destination="DigitalInput_I2.INIT" Comment="" dx1="860.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="BOOL_TO_Q_I2.CNF" Destination="QUARTERS_TO_BYTE.REQ" Comment="" dx1="1546.6666666666667"/>
			<Connection Source="DigitalInput_I2.IND" Destination="BOOL_TO_Q_I2.REQ" Comment="" dx1="840.0"/>
			<Connection Source="INIT" Destination="DigitalInput_I3.INIT" Comment="" dx1="860.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="BOOL_TO_Q_I3.CNF" Destination="QUARTERS_TO_BYTE.REQ" Comment="" dx1="186.66666666666669"/>
			<Connection Source="DigitalInput_I3.IND" Destination="BOOL_TO_Q_I3.REQ" Comment="" dx1="853.3333333333334"/>
			<Connection Source="INIT" Destination="DigitalInput_I4.INIT" Comment="" dx1="860.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="BOOL_TO_Q_I4.CNF" Destination="QUARTERS_TO_BYTE.REQ" Comment="" dx1="186.66666666666669"/>
			<Connection Source="DigitalInput_I4.IND" Destination="BOOL_TO_Q_I4.REQ" Comment="" dx1="853.3333333333334"/>
			<Connection Source="BOOL_TO_Q_I1.CNF" Destination="Q_TO_STR_STATUS_I1.REQ" Comment=""/>
			<Connection Source="DigitalInput_I2.IND" Destination="Q_TO_STR_STATUS_I2.REQ" Comment="" dx1="840.0"/>
			<Connection Source="DigitalInput_I3.IND" Destination="Q_TO_STR_STATUS_I3.REQ" Comment="" dx1="853.3333333333334" dx2="273.33333333333337" dy="-266.6666666666667"/>
			<Connection Source="BOOL_TO_Q_I4.CNF" Destination="Q_TO_STR_STATUS_I4.REQ" Comment=""/>
			<Connection Source="BYTE_TO_QUARTERS.CNF" Destination="Q_TO_BOOL_Q2.REQ" Comment="" dx1="966.6666666666667"/>
			<Connection Source="Q_TO_BOOL_Q1.CNF" Destination="Q_TO_STR_STATUS_Q1.REQ" Comment="" dx1="320.0"/>
			<Connection Source="BYTE_TO_QUARTERS.CNF" Destination="Q_TO_BOOL_Q4.REQ" Comment="" dx1="900.0"/>
			<Connection Source="BYTE_TO_QUARTERS.CNF" Destination="Q_TO_BOOL_Q3.REQ" Comment=""/>
			<Connection Source="Q_TO_BOOL_Q4.CNF" Destination="Q_TO_STR_STATUS_Q4.REQ" Comment="" dx1="320.0"/>
			<Connection Source="Q_TO_BOOL_Q4.CNF" Destination="DigitalOutput_Q4.REQ" Comment="" dx1="320.0" dx2="393.33333333333337" dy="-173.33333333333334"/>
			<Connection Source="Q_TO_BOOL_Q2.CNF" Destination="Q_TO_STR_STATUS_Q2.REQ" Comment="" dx1="320.0"/>
			<Connection Source="BYTE_TO_QUARTERS.CNF" Destination="Q_TO_BOOL_Q1.REQ" Comment="" dx1="966.6666666666667"/>
			<Connection Source="Q_TO_BOOL_Q3.CNF" Destination="Q_TO_STR_STATUS_Q3.REQ" Comment="" dx1="320.0"/>
			<Connection Source="Q_TO_BOOL_Q3.CNF" Destination="DigitalOutput_Q3.REQ" Comment="" dx1="320.0" dx2="393.33333333333337" dy="-173.33333333333334"/>
			<Connection Source="Q_TO_BOOL_Q1.CNF" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="320.0" dx2="393.33333333333337" dy="-173.33333333333334"/>
			<Connection Source="Q_TO_BOOL_Q2.CNF" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="320.0" dx2="393.33333333333337" dy="-173.33333333333334"/>
			<Connection Source="QUARTERS_TO_BYTE.CNF" Destination="BYTE_TO_QUARTERS.REQ" Comment=""/>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="7133.333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q4.INIT" Comment="" dx1="7140.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q3.INIT" Comment="" dx1="7133.333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q2.INIT" Comment="" dx1="7133.333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="BOOL_TO_Q_I1.I" Comment="" dx1="853.3333333333334"/>
			<Connection Source="BOOL_TO_Q_I1.QB" Destination="QUARTERS_TO_BYTE.IN_00" Comment="" dx1="240.0" dx2="380.0" dy="186.66666666666669"/>
			<Connection Source="DigitalInput_I2.IN" Destination="BOOL_TO_Q_I2.I" Comment="" dx1="873.3333333333334"/>
			<Connection Source="DigitalInput_I3.IN" Destination="BOOL_TO_Q_I3.I" Comment="" dx1="853.3333333333334"/>
			<Connection Source="DigitalInput_I4.IN" Destination="BOOL_TO_Q_I4.I" Comment="" dx1="853.3333333333334"/>
			<Connection Source="BOOL_TO_Q_I2.QB" Destination="QUARTERS_TO_BYTE.IN_01" Comment="" dx1="946.6666666666667"/>
			<Connection Source="BOOL_TO_Q_I3.QB" Destination="QUARTERS_TO_BYTE.IN_02" Comment="" dx1="220.0"/>
			<Connection Source="BOOL_TO_Q_I4.QB" Destination="QUARTERS_TO_BYTE.IN_03" Comment="" dx1="253.33333333333334"/>
			<Connection Source="BOOL_TO_Q_I1.QB" Destination="Q_TO_STR_STATUS_I1.IB" Comment=""/>
			<Connection Source="DigitalInput_I2.IN" Destination="Q_TO_STR_STATUS_I2.IB" Comment="" dx1="873.3333333333334"/>
			<Connection Source="DigitalInput_I3.IN" Destination="Q_TO_STR_STATUS_I3.IB" Comment="" dx1="2733.3333333333335"/>
			<Connection Source="BOOL_TO_Q_I4.QB" Destination="Q_TO_STR_STATUS_I4.IB" Comment=""/>
			<Connection Source="Q_TO_BOOL_Q3.Q" Destination="Q_TO_STR_STATUS_Q3.IB" Comment="" dx1="320.0"/>
			<Connection Source="BYTE_TO_QUARTERS.OUT_01" Destination="Q_TO_BOOL_Q2.IB" Comment="" dx1="1000.0"/>
			<Connection Source="BYTE_TO_QUARTERS.OUT_00" Destination="Q_TO_BOOL_Q1.IB" Comment="" dx1="933.3333333333334"/>
			<Connection Source="BYTE_TO_QUARTERS.OUT_02" Destination="Q_TO_BOOL_Q3.IB" Comment="" dx1="1033.3333333333335"/>
			<Connection Source="BYTE_TO_QUARTERS.OUT_03" Destination="Q_TO_BOOL_Q4.IB" Comment="" dx1="866.6666666666667"/>
			<Connection Source="Q_TO_BOOL_Q3.Q" Destination="DigitalOutput_Q3.OUT" Comment="" dx1="320.0" dx2="526.6666666666667" dy="206.66666666666669"/>
			<Connection Source="Q_TO_BOOL_Q1.Q" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="320.0" dx2="526.6666666666667" dy="206.66666666666669"/>
			<Connection Source="Q_TO_BOOL_Q2.Q" Destination="Q_TO_STR_STATUS_Q2.IB" Comment="" dx1="320.0"/>
			<Connection Source="Q_TO_BOOL_Q4.Q" Destination="DigitalOutput_Q4.OUT" Comment="" dx1="320.0" dx2="526.6666666666667" dy="206.66666666666669"/>
			<Connection Source="Q_TO_BOOL_Q2.Q" Destination="DigitalOutput_Q2.OUT" Comment="" dx1="320.0" dx2="526.6666666666667" dy="206.66666666666669"/>
			<Connection Source="Q_TO_BOOL_Q4.Q" Destination="Q_TO_STR_STATUS_Q4.IB" Comment="" dx1="320.0"/>
			<Connection Source="Q_TO_BOOL_Q1.Q" Destination="Q_TO_STR_STATUS_Q1.IB" Comment="" dx1="320.0"/>
			<Connection Source="QUARTERS_TO_BYTE.OUT" Destination="BYTE_TO_QUARTERS.IN" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
