<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_041" Comment="Lauflicht 8 mit einer Taste">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-6666.666666666667" y="-2400.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" Comment="" x="-6666.666666666667" y="-1333.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="QX" Comment="" x="-6666.666666666667" y="-266.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="QX" Comment="" x="-6666.666666666667" y="800.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" Comment="" x="-11466.666666666668" y="-2133.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I4_CLK" Type="IE" Comment="" x="-16533.333333333336" y="1333.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q5" Type="QX" Comment="" x="-6666.666666666667" y="1866.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q6" Type="QX" Comment="" x="-6666.666666666667" y="2933.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q7" Type="QX" Comment="" x="-6666.666666666667" y="4000.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q8" Type="QX" Comment="" x="-6666.666666666667" y="5066.666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" Comment="" x="-2666.666666666667" y="-2000.0">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1" Comment=""/>
		</FB>
		<FB Name="F_SINT_TO_UINT" Type="F_SINT_TO_UINT" Comment="" x="-4906.666666666667" y="-1820.0">
		</FB>
		<FB Name="loop" Type="sequence_E_08_loop" Comment="" x="-9613.333333333334" y="-600.0">
		</FB>
		<FB Name="E_CTU_0" Type="E_CTU" Comment="" x="-14933.333333333334" y="-533.3333333333334">
			<Parameter Name="PV" Value="0" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" Comment="" x="-16533.333333333336" y="-800.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="F_SUB_0" Type="F_SUB" Comment="" x="-13600.0" y="-533.3333333333334">
			<Parameter Name="IN2" Value="UINT#1" Comment=""/>
		</FB>
		<FB Name="E_DEMUX_0" Type="E_DEMUX8" Comment="" x="-12000.0" y="-533.3333333333334">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalOutput_Q4.INIT" Comment="" dx1="2613.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q3.INIT" Comment="" dx1="2613.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q2.INIT" Comment="" dx1="2613.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="2613.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I1_CLK.INIT" Comment="" dx1="453.33333333333337">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I4_CLK.INIT" Comment="" dx1="826.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q5.INIT" Comment="" dx1="2346.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q6.INIT" Comment="" dx1="3346.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q7.INIT" Comment="" dx1="2680.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q8.INIT" Comment="" dx1="3346.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="F_SINT_TO_UINT.CNF" Destination="Q_NumericValue.REQ" Comment="" dx1="633.3333333333334"/>
			<Connection Source="INIT" Destination="Q_NumericValue.INIT" Comment="" dx1="4666.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I4_CLK.IND" Destination="loop.RESET" Comment="" dx1="5146.666666666667"/>
			<Connection Source="loop.CNF" Destination="F_SINT_TO_UINT.REQ" Comment="" dx1="3060.0"/>
			<Connection Source="loop.EO_S1" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="600.0"/>
			<Connection Source="loop.EO_S2" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="760.0"/>
			<Connection Source="loop.EO_S3" Destination="DigitalOutput_Q3.REQ" Comment="" dx1="660.0"/>
			<Connection Source="loop.EO_S4" Destination="DigitalOutput_Q4.REQ" Comment="" dx1="660.0"/>
			<Connection Source="loop.EO_S5" Destination="DigitalOutput_Q5.REQ" Comment="" dx1="626.6666666666667"/>
			<Connection Source="loop.EO_S6" Destination="DigitalOutput_Q6.REQ" Comment="" dx1="560.0"/>
			<Connection Source="loop.EO_S7" Destination="DigitalOutput_Q7.REQ" Comment="" dx1="493.33333333333337"/>
			<Connection Source="loop.EO_S8" Destination="DigitalOutput_Q8.REQ" Comment="" dx1="426.6666666666667"/>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="loop.START_S1" Comment="" dx1="466.6666666666667"/>
			<Connection Source="INIT" Destination="DigitalInput_I2_CLK.INIT" Comment="" dx1="826.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_CTU_0.CU" Comment="" dx1="340.0"/>
			<Connection Source="E_CTU_0.CUO" Destination="F_SUB_0.REQ" Comment=""/>
			<Connection Source="DigitalInput_I4_CLK.IND" Destination="E_CTU_0.R" Comment="" dx1="206.66666666666669"/>
			<Connection Source="F_SUB_0.CNF" Destination="E_DEMUX_0.EI" Comment=""/>
			<Connection Source="E_DEMUX_0.EO0" Destination="loop.S1_S2" Comment="" dx1="846.6666666666667"/>
			<Connection Source="E_DEMUX_0.EO1" Destination="loop.S2_S3" Comment="" dx1="846.6666666666667"/>
			<Connection Source="E_DEMUX_0.EO2" Destination="loop.S3_S4" Comment="" dx1="846.6666666666667"/>
			<Connection Source="E_DEMUX_0.EO3" Destination="loop.S4_S5" Comment="" dx1="846.6666666666667"/>
			<Connection Source="E_DEMUX_0.EO4" Destination="loop.S5_S6" Comment="" dx1="846.6666666666667"/>
			<Connection Source="E_DEMUX_0.EO5" Destination="loop.S6_S7" Comment="" dx1="846.6666666666667"/>
			<Connection Source="E_DEMUX_0.EO6" Destination="loop.S7_S8" Comment="" dx1="846.6666666666667"/>
			<Connection Source="E_DEMUX_0.EO7" Destination="loop.S8_S1" Comment="" dx1="846.6666666666667"/>
			<Connection Source="E_DEMUX_0.EO7" Destination="E_CTU_0.R" Comment="" dx1="353.33333333333337" dx2="66.66666666666667" dy="460.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SINT_TO_UINT.OUT" Destination="Q_NumericValue.u32NewValue" Comment="" dx1="286.6666666666667"/>
			<Connection Source="loop.STATE_NR" Destination="F_SINT_TO_UINT.IN" Comment="" dx1="726.6666666666667"/>
			<Connection Source="loop.DO_S1" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="693.3333333333334"/>
			<Connection Source="loop.DO_S2" Destination="DigitalOutput_Q2.OUT" Comment="" dx1="793.3333333333334"/>
			<Connection Source="loop.DO_S3" Destination="DigitalOutput_Q3.OUT" Comment="" dx1="826.6666666666667"/>
			<Connection Source="loop.DO_S4" Destination="DigitalOutput_Q4.OUT" Comment="" dx1="660.0"/>
			<Connection Source="loop.DO_S5" Destination="DigitalOutput_Q5.OUT" Comment="" dx1="593.3333333333334"/>
			<Connection Source="loop.DO_S6" Destination="DigitalOutput_Q6.OUT" Comment="" dx1="526.6666666666667"/>
			<Connection Source="loop.DO_S7" Destination="DigitalOutput_Q7.OUT" Comment="" dx1="460.0"/>
			<Connection Source="loop.DO_S8" Destination="DigitalOutput_Q8.OUT" Comment="" dx1="393.33333333333337"/>
			<Connection Source="E_CTU_0.CV" Destination="F_SUB_0.IN1" Comment="" dx1="253.33333333333334"/>
			<Connection Source="F_SUB_0.OUT" Destination="E_DEMUX_0.K" Comment="" dx1="526.6666666666667"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
