<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_006a4" Comment="SR und T-Flip-Flop mit 3x IE">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_CLK_I1" Type="IE" x="-4600" y="-900">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="IE" x="-4540" y="113.34">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_T_FF_SR" Type="E_T_FF_SR" x="-2800" y="-700">
		</FB>
		<FB Name="DigitalInput_CLK_I3" Type="IE" x="-4533.33" y="1133.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Rechtslauf" Type="QX" x="3200" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Linkslauf" Type="QX" x="3200" y="300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="LinksRechts" Type="LinksRechts" x="-1200" y="-1800">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_T_FF_SR.S"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_T_FF_SR.R" dx1="486.67"/>
			<Connection Source="DigitalInput_CLK_I3.IND" Destination="E_T_FF_SR.CLK" dx1="673.33"/>
			<Connection Source="E_T_FF_SR.EO" Destination="LinksRechts.EI_ON" dx1="246.67"/>
			<Connection Source="LinksRechts.EO" Destination="Linkslauf.REQ" dx1="946.67"/>
			<Connection Source="LinksRechts.EO" Destination="Rechtslauf.REQ" dx1="1360"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="LinksRechts.Rechts" Destination="Rechtslauf.OUT" dx1="1253.33"/>
			<Connection Source="E_T_FF_SR.Q" Destination="LinksRechts.EIN" dx1="346.67"/>
			<Connection Source="LinksRechts.Links" Destination="Linkslauf.OUT" dx1="886.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
