<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_123" Comment="Übung zu ISOBUS Name">
	<Identification Standard="61499-2" Description="Copyright (c) 2025 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
		<Import declaration="isobus::pgn::ISOUSERHOME_e"/>
		<Import declaration="isobus::pgn::ISO_CAN_NODE"/>
		<Import declaration="isobus::pgn::NAMEFIELD_T"/>
		<Import declaration="isobus::pgn::ISONETEVENT_T"/>
		<Import declaration="isobus::pgn::CF_INFO_T"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="NmGetCfInfo" Type="isobus::pgn::NmGetCfInfo" x="-10100" y="-1200">
			<Parameter Name="u8CanIdx" Value="ISO_CAN_NODE::NODE1"/>
			<Parameter Name="member" Value="ISOUSERHOME_e::thisMember"/>
		</FB>
		<FB Name="STRUCT_DEMUX" Type="eclipse4diac::convert::STRUCT_DEMUX" x="-7900" y="-200">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_1" Type="eclipse4diac::convert::STRUCT_DEMUX" x="-7900" y="1000">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_2" Type="eclipse4diac::convert::STRUCT_DEMUX" x="-7800" y="2300">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_3" Type="eclipse4diac::convert::STRUCT_DEMUX" x="-7800" y="7400">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="NmGetCfInfo_1" Type="isobus::pgn::NmGetCfInfo" x="-10100" y="3900">
			<Parameter Name="u8CanIdx" Value="ISO_CAN_NODE::NODE1"/>
			<Parameter Name="member" Value="ISOUSERHOME_e::network"/>
			<Parameter Name="address" Value="Filter::VT_ADD"/>
			<Parameter Name="mask" Value="Filter::VT_FLT"/>
		</FB>
		<FB Name="STRUCT_DEMUX_4" Type="eclipse4diac::convert::STRUCT_DEMUX" x="-7900" y="6100">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_5" Type="eclipse4diac::convert::STRUCT_DEMUX" x="-7900" y="4900">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<EventConnections>
			<Connection Source="NmGetCfInfo.IND" Destination="STRUCT_DEMUX.REQ" dx1="593.33"/>
			<Connection Source="NmGetCfInfo.IND" Destination="STRUCT_DEMUX_1.REQ" dx1="593.33"/>
			<Connection Source="NmGetCfInfo.IND" Destination="STRUCT_DEMUX_2.REQ" dx1="593.33"/>
			<Connection Source="NmGetCfInfo_1.IND" Destination="STRUCT_DEMUX_3.REQ" dx1="593.33"/>
			<Connection Source="NmGetCfInfo_1.IND" Destination="STRUCT_DEMUX_4.REQ" dx1="593.33"/>
			<Connection Source="NmGetCfInfo_1.IND" Destination="STRUCT_DEMUX_5.REQ" dx1="593.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="NmGetCfInfo.sNetEv" Destination="STRUCT_DEMUX.IN" dx1="660"/>
			<Connection Source="NmGetCfInfo.sCfInfo" Destination="STRUCT_DEMUX_1.IN" dx1="626.67"/>
			<Connection Source="NmGetCfInfo.sNameField" Destination="STRUCT_DEMUX_2.IN" dx1="560"/>
			<Connection Source="NmGetCfInfo_1.sNameField" Destination="STRUCT_DEMUX_3.IN" dx1="560"/>
			<Connection Source="NmGetCfInfo_1.sNetEv" Destination="STRUCT_DEMUX_5.IN" dx1="660"/>
			<Connection Source="NmGetCfInfo_1.sCfInfo" Destination="STRUCT_DEMUX_4.IN" dx1="626.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
