<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_120" Comment="Übung zu ISOBUS Name">
	<Identification Standard="61499-2" Description="Copyright (c) 2025 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="STRUCT_DEMUX" Type="eclipse4diac::convert::STRUCT_DEMUX" x="2400" y="1400">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::NAMEFIELD_T"/>
		</FB>
		<FB Name="STRUCT_MUX" Type="eclipse4diac::convert::STRUCT_MUX" x="300" y="1400">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::NAMEFIELD_T"/>
		</FB>
		<FB Name="NmSetName" Type="isobus::NmSetName" x="500" y="4500">
		</FB>
		<FB Name="NmSetNameField" Type="isobus::NmSetNameField" x="1700" y="4500">
		</FB>
		<FB Name="STRUCT_MUX_1" Type="eclipse4diac::convert::STRUCT_MUX" x="-1000" y="4500">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::NAMEFIELD_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_1" Type="eclipse4diac::convert::STRUCT_DEMUX" x="3100" y="4500">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::NAMEFIELD_T"/>
		</FB>
		<FB Name="NmGetCfInfo" Type="isobus::NmGetCfInfo" x="100" y="6300">
		</FB>
		<EventConnections>
			<Connection Source="STRUCT_MUX.CNF" Destination="STRUCT_DEMUX.REQ" dx1="673.33"/>
			<Connection Source="NmSetName.CNF" Destination="NmSetNameField.REQ"/>
			<Connection Source="STRUCT_MUX_1.CNF" Destination="NmSetName.REQ" dx1="200"/>
			<Connection Source="NmSetNameField.CNF" Destination="STRUCT_DEMUX_1.REQ" dx1="233.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="STRUCT_MUX.OUT" Destination="STRUCT_DEMUX.IN" dx1="673.33"/>
			<Connection Source="NmSetName." Destination="NmSetNameField.au8IsoName"/>
			<Connection Source="NmSetNameField." Destination="STRUCT_DEMUX_1.IN" dx1="80"/>
			<Connection Source="STRUCT_MUX_1.OUT" Destination="NmSetName.psNameField" dx1="180"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
