<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_003a" Comment="DigitalInput_I1/_I2 auf DigitalOutput_Q1/_I2">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="F1" Type="Uebung_003a_sub" Comment="" x="140.0" y="606.6666666666667">
		</SubApp>
		<SubApp Name="F2" Type="Uebung_003a_sub" Comment="" x="133.33333333333334" y="1066.6666666666667">
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="F1.INIT" Comment="" dx1="740.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="F2.INIT" Comment="" dx1="733.3333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
