<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_002b3" Comment="DigitalInput_I1/_I2/_I3 auf DigitalOutput_Q1">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS_QX" x="1900" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="DataPanel_MI_DO::Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS_IX" x="-4500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I1"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS_IX" x="-4500" y="300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I2"/>
		</FB>
		<FB Name="AND_2_BOOL" Type="AND_2_BOOL" x="-2100" y="500">
		</FB>
		<FB Name="DigitalInput_I3" Type="logiBUS_IX" x="-4500" y="1300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I3"/>
		</FB>
		<FB Name="OR_2_BOOL" Type="OR_2_BOOL" x="100" y="1500">
		</FB>
		<Comment Comment="kein F_MOVE mehr nötig. " x="-300" y="800" width="1300" height="200"/>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="AND_2_BOOL.REQ" dx1="1626.67"/>
			<Connection Source="DigitalInput_I2.IND" Destination="AND_2_BOOL.REQ"/>
			<Connection Source="OR_2_BOOL.CNF" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="DigitalInput_I3.IND" Destination="OR_2_BOOL.REQ"/>
			<Connection Source="AND_2_BOOL.CNF" Destination="OR_2_BOOL.REQ" dx1="926.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AND_2_BOOL.IN1" dx1="900"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AND_2_BOOL.IN2" dx1="853.33"/>
			<Connection Source="DigitalInput_I3.IN" Destination="OR_2_BOOL.IN2" dx1="1973.33"/>
			<Connection Source="OR_2_BOOL.OUT" Destination="DigitalOutput_Q1.OUT" dx1="373.33"/>
			<Connection Source="AND_2_BOOL.OUT" Destination="OR_2_BOOL.IN1" dx1="680"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
