<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020d" Comment="DigitalInput_I1 auf DigitalOutput_Q1; TOF Ausschaltverzögert; aufgelöst" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-3553.33" y="460">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" x="-8706.67" y="346.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" x="-7466.67" y="573.33">
		</FB>
		<FB Name="E_RS" Type="E_RS" x="-4840" y="573.33">
		</FB>
		<FB Name="E_DELAY" Type="E_DELAY" x="-5993.33" y="573.33">
			<Parameter Name="DT" Value="T#2S"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="E_SWITCH.EI" dx1="273.33"/>
			<Connection Source="E_RS.EO" Destination="DigitalOutput_Q1.REQ" dx1="426.67"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_RS.S" dx1="73.33" dx2="466.67" dy="446.67"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_DELAY.START"/>
			<Connection Source="E_DELAY.EO" Destination="E_RS.R"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_DELAY.STOP"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="E_SWITCH.G" dx1="80"/>
			<Connection Source="E_RS.Q" Destination="DigitalOutput_Q1.OUT" dx1="73.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
