<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_056" Comment="DigitalInput_I1-_I4 auf DigitalOutput_Q1-_Q4">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-11066.67" y="0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="ASSEMBLE_BYTE_FROM_QUARTERS" Type="ASSEMBLE_BYTE_FROM_QUARTERS" Comment="" x="-6000" y="1333.33">
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" Comment="" x="-11066.67" y="1073.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I3" Type="IX" Comment="" x="-11066.67" y="2153.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I4" Type="IX" Comment="" x="-11066.67" y="3333.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" Comment="" x="2266.67" y="240">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="QX" Comment="" x="2266.67" y="1186.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="SPLIT_BYTE_INTO_QUARTERS" Type="SPLIT_BYTE_INTO_QUARTERS" Comment="" x="-3866.67" y="1333.33">
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="2266.67" y="-706.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="QX" Comment="" x="2286.67" y="1993.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="Q_TO_BOOL_Q1" Type="QUARTER_TO_BOOL" Comment="" x="-906.67" y="-553.33">
		</FB>
		<FB Name="Q_TO_BOOL_Q4" Type="QUARTER_TO_BOOL" Comment="" x="-886.67" y="2146.67">
		</FB>
		<FB Name="Q_TO_BOOL_Q2" Type="QUARTER_TO_BOOL" Comment="" x="-906.67" y="386.67">
		</FB>
		<FB Name="Q_TO_BOOL_Q3" Type="QUARTER_TO_BOOL" Comment="" x="-906.67" y="1333.33">
		</FB>
		<FB Name="Q_TO_STR_STATUS_Q3" Type="QUARTER_TO_STR_STATUS" Comment="" x="473.33" y="1380">
		</FB>
		<FB Name="Q_TO_STR_STATUS_Q1" Type="QUARTER_TO_STR_STATUS" Comment="" x="473.33" y="-506.67">
		</FB>
		<FB Name="Q_TO_STR_STATUS_I3" Type="QUARTER_TO_STR_STATUS" Comment="" x="-7466.67" y="2400">
		</FB>
		<FB Name="Q_TO_STR_STATUS_I1" Type="QUARTER_TO_STR_STATUS" Comment="" x="-7386.67" y="173.33">
		</FB>
		<FB Name="Q_TO_STR_STATUS_I4" Type="QUARTER_TO_STR_STATUS" Comment="" x="-7386.67" y="3513.33">
		</FB>
		<FB Name="Q_TO_STR_STATUS_Q4" Type="QUARTER_TO_STR_STATUS" Comment="" x="493.33" y="2193.33">
		</FB>
		<FB Name="Q_TO_STR_STATUS_Q2" Type="QUARTER_TO_STR_STATUS" Comment="" x="473.33" y="433.33">
		</FB>
		<FB Name="Q_TO_STR_STATUS_I2" Type="QUARTER_TO_STR_STATUS" Comment="" x="-7466.67" y="800">
		</FB>
		<FB Name="BOOL_TO_Q_I1" Type="BOOL_TO_QUARTER" Comment="" x="-8633.33" y="173.33">
		</FB>
		<FB Name="BOOL_TO_Q_I2" Type="BOOL_TO_QUARTER" Comment="" x="-8633.33" y="1253.33">
		</FB>
		<FB Name="BOOL_TO_Q_I4" Type="BOOL_TO_QUARTER" Comment="" x="-8633.33" y="3513.33">
		</FB>
		<FB Name="BOOL_TO_Q_I3" Type="BOOL_TO_QUARTER" Comment="" x="-8633.33" y="2333.33">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="593.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I2.INIT" Comment="" dx1="860">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I3.INIT" Comment="" dx1="860">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I4.INIT" Comment="" dx1="860">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="ASSEMBLE_BYTE_FROM_QUARTERS.CNF" Destination="SPLIT_BYTE_INTO_QUARTERS.REQ" Comment=""/>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="7133.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q4.INIT" Comment="" dx1="7140">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q3.INIT" Comment="" dx1="7133.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q2.INIT" Comment="" dx1="7133.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="SPLIT_BYTE_INTO_QUARTERS.CNF" Destination="Q_TO_BOOL_Q1.REQ" Comment="" dx1="966.67" dx2="966.67" dy="0"/>
			<Connection Source="Q_TO_BOOL_Q1.CNF" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="320" dx2="320" dy="-173.33"/>
			<Connection Source="SPLIT_BYTE_INTO_QUARTERS.CNF" Destination="Q_TO_BOOL_Q4.REQ" Comment="" dx1="900" dx2="900" dy="0"/>
			<Connection Source="Q_TO_BOOL_Q4.CNF" Destination="DigitalOutput_Q4.REQ" Comment="" dx1="320" dx2="320" dy="-173.33"/>
			<Connection Source="SPLIT_BYTE_INTO_QUARTERS.CNF" Destination="Q_TO_BOOL_Q2.REQ" Comment="" dx1="966.67" dx2="966.67" dy="0"/>
			<Connection Source="Q_TO_BOOL_Q2.CNF" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="320" dx2="320" dy="-173.33"/>
			<Connection Source="SPLIT_BYTE_INTO_QUARTERS.CNF" Destination="Q_TO_BOOL_Q3.REQ" Comment=""/>
			<Connection Source="Q_TO_BOOL_Q3.CNF" Destination="DigitalOutput_Q3.REQ" Comment="" dx1="320" dx2="320" dy="-173.33"/>
			<Connection Source="Q_TO_BOOL_Q3.CNF" Destination="Q_TO_STR_STATUS_Q3.REQ" Comment="" dx1="320" dx2="320" dy="0"/>
			<Connection Source="Q_TO_BOOL_Q1.CNF" Destination="Q_TO_STR_STATUS_Q1.REQ" Comment="" dx1="320" dx2="320" dy="0"/>
			<Connection Source="DigitalInput_I3.IND" Destination="Q_TO_STR_STATUS_I3.REQ" Comment="" dx1="853.33" dx2="853.33" dy="-266.67"/>
			<Connection Source="Q_TO_BOOL_Q4.CNF" Destination="Q_TO_STR_STATUS_Q4.REQ" Comment="" dx1="320" dx2="320" dy="0"/>
			<Connection Source="Q_TO_BOOL_Q2.CNF" Destination="Q_TO_STR_STATUS_Q2.REQ" Comment="" dx1="320" dx2="320" dy="0"/>
			<Connection Source="DigitalInput_I2.IND" Destination="Q_TO_STR_STATUS_I2.REQ" Comment="" dx1="840" dx2="840" dy="0"/>
			<Connection Source="DigitalInput_I1.IND" Destination="BOOL_TO_Q_I1.REQ" Comment="" dx1="853.33" dx2="853.33" dy="0"/>
			<Connection Source="BOOL_TO_Q_I1.CNF" Destination="ASSEMBLE_BYTE_FROM_QUARTERS.REQ" Comment="" dx1="273.33" dx2="273.33" dy="380"/>
			<Connection Source="BOOL_TO_Q_I1.CNF" Destination="Q_TO_STR_STATUS_I1.REQ" Comment=""/>
			<Connection Source="DigitalInput_I2.IND" Destination="BOOL_TO_Q_I2.REQ" Comment="" dx1="840" dx2="840" dy="0"/>
			<Connection Source="BOOL_TO_Q_I2.CNF" Destination="ASSEMBLE_BYTE_FROM_QUARTERS.REQ" Comment="" dx1="1546.67" dx2="1546.67" dy="0"/>
			<Connection Source="DigitalInput_I4.IND" Destination="BOOL_TO_Q_I4.REQ" Comment="" dx1="853.33" dx2="853.33" dy="0"/>
			<Connection Source="BOOL_TO_Q_I4.CNF" Destination="ASSEMBLE_BYTE_FROM_QUARTERS.REQ" Comment="" dx1="186.67" dx2="186.67" dy="0"/>
			<Connection Source="BOOL_TO_Q_I4.CNF" Destination="Q_TO_STR_STATUS_I4.REQ" Comment=""/>
			<Connection Source="DigitalInput_I3.IND" Destination="BOOL_TO_Q_I3.REQ" Comment="" dx1="853.33" dx2="853.33" dy="0"/>
			<Connection Source="BOOL_TO_Q_I3.CNF" Destination="ASSEMBLE_BYTE_FROM_QUARTERS.REQ" Comment="" dx1="186.67" dx2="186.67" dy="0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="SPLIT_BYTE_INTO_QUARTERS.OUT_00" Destination="Q_TO_BOOL_Q1.IB" Comment="" dx1="933.33" dx2="933.33" dy="0"/>
			<Connection Source="Q_TO_BOOL_Q1.Q" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="320" dx2="320" dy="206.67"/>
			<Connection Source="SPLIT_BYTE_INTO_QUARTERS.OUT_03" Destination="Q_TO_BOOL_Q4.IB" Comment="" dx1="866.67" dx2="866.67" dy="0"/>
			<Connection Source="Q_TO_BOOL_Q4.Q" Destination="DigitalOutput_Q4.OUT" Comment="" dx1="320" dx2="320" dy="206.67"/>
			<Connection Source="SPLIT_BYTE_INTO_QUARTERS.OUT_01" Destination="Q_TO_BOOL_Q2.IB" Comment="" dx1="1000" dx2="1000" dy="0"/>
			<Connection Source="Q_TO_BOOL_Q2.Q" Destination="DigitalOutput_Q2.OUT" Comment="" dx1="320" dx2="320" dy="206.67"/>
			<Connection Source="SPLIT_BYTE_INTO_QUARTERS.OUT_02" Destination="Q_TO_BOOL_Q3.IB" Comment="" dx1="1033.33" dx2="1033.33" dy="0"/>
			<Connection Source="Q_TO_BOOL_Q3.Q" Destination="DigitalOutput_Q3.OUT" Comment="" dx1="320" dx2="320" dy="206.67"/>
			<Connection Source="Q_TO_BOOL_Q3.Q" Destination="Q_TO_STR_STATUS_Q3.IB" Comment="" dx1="320" dx2="320" dy="0"/>
			<Connection Source="Q_TO_BOOL_Q1.Q" Destination="Q_TO_STR_STATUS_Q1.IB" Comment="" dx1="320" dx2="320" dy="0"/>
			<Connection Source="DigitalInput_I3.IN" Destination="Q_TO_STR_STATUS_I3.IB" Comment="" dx1="2733.33" dx2="2733.33" dy="0"/>
			<Connection Source="Q_TO_BOOL_Q4.Q" Destination="Q_TO_STR_STATUS_Q4.IB" Comment="" dx1="320" dx2="320" dy="0"/>
			<Connection Source="Q_TO_BOOL_Q2.Q" Destination="Q_TO_STR_STATUS_Q2.IB" Comment="" dx1="320" dx2="320" dy="0"/>
			<Connection Source="DigitalInput_I2.IN" Destination="Q_TO_STR_STATUS_I2.IB" Comment="" dx1="873.33" dx2="873.33" dy="0"/>
			<Connection Source="DigitalInput_I1.IN" Destination="BOOL_TO_Q_I1.I" Comment="" dx1="853.33" dx2="853.33" dy="0"/>
			<Connection Source="BOOL_TO_Q_I1.QB" Destination="ASSEMBLE_BYTE_FROM_QUARTERS.IN_00" Comment="" dx1="240" dx2="240" dy="186.67"/>
			<Connection Source="BOOL_TO_Q_I1.QB" Destination="Q_TO_STR_STATUS_I1.IB" Comment=""/>
			<Connection Source="DigitalInput_I2.IN" Destination="BOOL_TO_Q_I2.I" Comment="" dx1="873.33" dx2="873.33" dy="0"/>
			<Connection Source="BOOL_TO_Q_I2.QB" Destination="ASSEMBLE_BYTE_FROM_QUARTERS.IN_01" Comment="" dx1="946.67" dx2="946.67" dy="0"/>
			<Connection Source="DigitalInput_I4.IN" Destination="BOOL_TO_Q_I4.I" Comment="" dx1="853.33" dx2="853.33" dy="0"/>
			<Connection Source="BOOL_TO_Q_I4.QB" Destination="ASSEMBLE_BYTE_FROM_QUARTERS.IN_03" Comment="" dx1="253.33" dx2="253.33" dy="0"/>
			<Connection Source="BOOL_TO_Q_I4.QB" Destination="Q_TO_STR_STATUS_I4.IB" Comment=""/>
			<Connection Source="DigitalInput_I3.IN" Destination="BOOL_TO_Q_I3.I" Comment="" dx1="853.33" dx2="853.33" dy="0"/>
			<Connection Source="BOOL_TO_Q_I3.QB" Destination="ASSEMBLE_BYTE_FROM_QUARTERS.IN_02" Comment="" dx1="220" dx2="220" dy="0"/>
			<Connection Source="ASSEMBLE_BYTE_FROM_QUARTERS." Destination="SPLIT_BYTE_INTO_QUARTERS.IN" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
