<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_035" Comment="Spiegelabfolge V2 mit Schrittkette">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-7840.0" y="-986.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="sequence_04" Type="sequence_04" Comment="" x="-9673.333333333334" y="1713.3333333333335">
			<Parameter Name="DT_S1_S2" Value="T#2s" Comment=""/>
			<Parameter Name="DT_S2_S3" Value="T#2s" Comment=""/>
			<Parameter Name="DT_S3_S4" Value="T#2s" Comment=""/>
			<Parameter Name="DT_S4_START" Value="T#2s" Comment=""/>
		</FB>
		<FB Name="E_TimeOut" Type="E_TimeOut" Comment="" x="-7840.0" y="2933.3333333333335">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" Comment="" x="-7840.0" y="-6.666666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="QX" Comment="" x="-7840.0" y="973.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="QX" Comment="" x="-7840.0" y="1953.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" Comment="" x="-11373.333333333334" y="-20.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" Comment="" x="-11373.333333333334" y="960.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I3_CLK" Type="IE" Comment="" x="-11373.333333333334" y="1940.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I4_CLK" Type="IE" Comment="" x="-11373.333333333334" y="2920.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="sequence_04.EO_S1" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="73.33333333333334"/>
			<Connection Source="sequence_04.EO_S2" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="206.66666666666669"/>
			<Connection Source="sequence_04.EO_S3" Destination="DigitalOutput_Q3.REQ" Comment="" dx1="340.0"/>
			<Connection Source="sequence_04.EO_S4" Destination="DigitalOutput_Q4.REQ" Comment="" dx1="473.33333333333337"/>
			<Connection Source="INIT" Destination="DigitalOutput_Q4.INIT" Comment="" dx1="2613.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q3.INIT" Comment="" dx1="2613.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q2.INIT" Comment="" dx1="2613.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="2613.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I1_CLK.INIT" Comment="" dx1="453.33333333333337">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="sequence_04.START_S1" Comment="" dx1="333.33333333333337"/>
			<Connection Source="INIT" Destination="DigitalInput_I2_CLK.INIT" Comment="" dx1="273.33333333333337">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I3_CLK.INIT" Comment="" dx1="453.33333333333337" dx2="453.33333333333337" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I4_CLK.INIT" Comment="" dx1="1453.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I4_CLK.IND" Destination="sequence_04.RESET" Comment="" dx1="266.6666666666667"/>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="sequence_04.S2_S3" Comment="" dx1="266.6666666666667"/>
			<Connection Source="DigitalInput_I3_CLK.IND" Destination="sequence_04.S4_START" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="sequence_04.DO_S4" Destination="DigitalOutput_Q4.OUT" Comment="" dx1="473.33333333333337"/>
			<Connection Source="sequence_04.DO_S3" Destination="DigitalOutput_Q3.OUT" Comment="" dx1="406.6666666666667"/>
			<Connection Source="sequence_04.DO_S2" Destination="DigitalOutput_Q2.OUT" Comment="" dx1="273.33333333333337"/>
			<Connection Source="sequence_04.DO_S1" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="140.0"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="sequence_04.timeOut" Destination="E_TimeOut.TimeOutSocket" Comment=""/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
