<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_060" Comment="DigitalInput_I1 auf DigitalOutput_Q1">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SETPOINT_CONDENSED_WORK_STATE_1_16" Type="ID" Comment="" x="-240.0" y="-986.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DWORD_TO_QUARTERS" Type="DWORD_TO_QUARTERS" Comment="" x="2160.0" y="-760.0">
		</FB>
		<FB Name="QUARTERS_TO_DWORD" Type="QUARTERS_TO_DWORD" Comment="" x="-213.33333333333334" y="1693.3333333333335">
		</FB>
		<FB Name="ACTUAL_CONDENSED_WORK_STATE_1_16" Type="QD" Comment="" x="2160.0" y="1580.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-3373.3333333333335" y="-760.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" Comment="" x="-3373.3333333333335" y="353.33333333333337">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I3" Type="IX" Comment="" x="-3373.3333333333335" y="1466.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I4" Type="IX" Comment="" x="-3373.3333333333335" y="2580.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="BOOLS_TO_QUARTERS" Type="BOOLS_TO_QUARTERS" Comment="" x="-2133.3333333333335" y="1693.3333333333335">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="SETPOINT_CONDENSED_WORK_STATE_1_16.INIT" Comment="" dx1="393.33333333333337">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="SETPOINT_CONDENSED_WORK_STATE_1_16.IND" Destination="DWORD_TO_QUARTERS.REQ" Comment=""/>
			<Connection Source="QUARTERS_TO_DWORD.CNF" Destination="ACTUAL_CONDENSED_WORK_STATE_1_16.REQ" Comment=""/>
			<Connection Source="INIT" Destination="ACTUAL_CONDENSED_WORK_STATE_1_16.INIT" Comment="" dx1="3586.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="320.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I2.INIT" Comment="" dx1="320.0" dx2="320.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I3.INIT" Comment="" dx1="273.33333333333337">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I4.INIT" Comment="" dx1="340.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="BOOLS_TO_QUARTERS.CNF" Destination="QUARTERS_TO_DWORD.REQ" Comment=""/>
			<Connection Source="DigitalInput_I1.IND" Destination="BOOLS_TO_QUARTERS.REQ" Comment="" dx1="80.0"/>
			<Connection Source="DigitalInput_I2.IND" Destination="BOOLS_TO_QUARTERS.REQ" Comment="" dx1="80.0"/>
			<Connection Source="DigitalInput_I3.IND" Destination="BOOLS_TO_QUARTERS.REQ" Comment=""/>
			<Connection Source="DigitalInput_I4.IND" Destination="BOOLS_TO_QUARTERS.REQ" Comment="" dx1="80.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="SETPOINT_CONDENSED_WORK_STATE_1_16.IN" Destination="DWORD_TO_QUARTERS.IN" Comment="" dx1="966.6666666666667"/>
			<Connection Source="QUARTERS_TO_DWORD.OUT" Destination="ACTUAL_CONDENSED_WORK_STATE_1_16.OUT" Comment="" dx1="560.0"/>
			<Connection Source="DigitalInput_I1.IN" Destination="BOOLS_TO_QUARTERS.I_00" Comment="" dx1="213.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_00" Destination="QUARTERS_TO_DWORD.IN_00" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_01" Destination="QUARTERS_TO_DWORD.IN_01" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_02" Destination="QUARTERS_TO_DWORD.IN_02" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_03" Destination="QUARTERS_TO_DWORD.IN_03" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_04" Destination="QUARTERS_TO_DWORD.IN_04" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_05" Destination="QUARTERS_TO_DWORD.IN_05" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_06" Destination="QUARTERS_TO_DWORD.IN_06" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_07" Destination="QUARTERS_TO_DWORD.IN_07" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_08" Destination="QUARTERS_TO_DWORD.IN_08" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_09" Destination="QUARTERS_TO_DWORD.IN_09" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_10" Destination="QUARTERS_TO_DWORD.IN_10" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_11" Destination="QUARTERS_TO_DWORD.IN_11" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_12" Destination="QUARTERS_TO_DWORD.IN_12" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_13" Destination="QUARTERS_TO_DWORD.IN_13" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_14" Destination="QUARTERS_TO_DWORD.IN_14" Comment="" dx1="73.33333333333334"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_15" Destination="QUARTERS_TO_DWORD.IN_15" Comment="" dx1="73.33333333333334"/>
			<Connection Source="DigitalInput_I2.IN" Destination="BOOLS_TO_QUARTERS.I_01" Comment="" dx1="146.66666666666669"/>
			<Connection Source="DigitalInput_I3.IN" Destination="BOOLS_TO_QUARTERS.I_02" Comment="" dx1="146.66666666666669"/>
			<Connection Source="DigitalInput_I4.IN" Destination="BOOLS_TO_QUARTERS.I_03" Comment="" dx1="146.66666666666669"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
