<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_034b" Comment="LONG_PRESS_HOLD-Eingang auf PWM Ausgang">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="PWMOutput_Q1" Type="logiBUS_QD_PWM" x="6100" y="1600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="DataPanel_MI_DO::Output_Q1"/>
		</FB>
		<FB Name="IE_SPEED_UP" Type="logiBUS_IE" x="413.33" y="33.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I1"/>
			<Parameter Name="InputEvent" Value="logiBUS_DI_Events::BUTTON_LONG_PRESS_HOLD"/>
		</FB>
		<FB Name="IE_SPEED_DOWN" Type="logiBUS_IE" x="413.33" y="1113.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I2"/>
			<Parameter Name="InputEvent" Value="logiBUS_DI_Events::BUTTON_LONG_PRESS_HOLD"/>
		</FB>
		<FB Name="E_CTUD" Type="E_CTUD_UDINT" x="1686.67" y="1700">
			<Parameter Name="PV" Value="1023"/>
		</FB>
		<FB Name="F_UDINT_TO_DWORD" Type="F_UDINT_TO_DWORD" x="4000" y="1700">
		</FB>
		<FB Name="IE_STOP" Type="logiBUS_IE" x="413.33" y="2193.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I3"/>
			<Parameter Name="InputEvent" Value="logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="IE_FULL" Type="logiBUS_IE" x="413.33" y="3273.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I4"/>
			<Parameter Name="InputEvent" Value="logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="F_MUL" Type="F_MUL" x="3173.33" y="1700">
			<Parameter Name="IN2" Value="UDINT#8"/>
		</FB>
		<EventConnections>
			<Connection Source="E_CTUD.CO" Destination="F_MUL.REQ"/>
			<Connection Source="E_CTUD.RO" Destination="F_MUL.REQ" dx1="73.33"/>
			<Connection Source="IE_SPEED_UP.IND" Destination="E_CTUD.CU" dx1="140"/>
			<Connection Source="IE_SPEED_DOWN.IND" Destination="E_CTUD.CD" dx1="73.33"/>
			<Connection Source="IE_STOP.IND" Destination="E_CTUD.R" dx1="73.33"/>
			<Connection Source="IE_FULL.IND" Destination="E_CTUD.LD" dx1="140"/>
			<Connection Source="E_CTUD.LDO" Destination="F_MUL.REQ" dx1="73.33"/>
			<Connection Source="F_UDINT_TO_DWORD.CNF" Destination="PWMOutput_Q1.REQ"/>
			<Connection Source="F_MUL.CNF" Destination="F_UDINT_TO_DWORD.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTUD.CV" Destination="F_MUL.IN1" dx1="140"/>
			<Connection Source="F_UDINT_TO_DWORD.OUT" Destination="PWMOutput_Q1.OUT"/>
			<Connection Source="F_MUL.OUT" Destination="F_UDINT_TO_DWORD.IN"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
