<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_053" Comment="DigitalInput_I1-_I4 auf DigitalOutput_Q1-_Q4">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-1753.33" y="-1086.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-6040" y="-486.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" Comment="" x="-1753.33" y="-106.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" Comment="" x="-6040" y="626.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="QX" Comment="" x="-1753.33" y="873.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I3" Type="IX" Comment="" x="-6040" y="1740">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="QX" Comment="" x="-1753.33" y="1853.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I4" Type="IX" Comment="" x="-6040" y="2853.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="BOOLS_TO_BYTE" Type="BOOLS_TO_BYTE" Comment="" x="-4800" y="1966.67">
		</FB>
		<FB Name="BYTE_TO_BOOLS" Type="BYTE_TO_BOOLS" Comment="" x="-3413.33" y="1966.67">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="1073.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I2.INIT" Comment="" dx1="1146.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I3.INIT" Comment="" dx1="1073.33" dx2="1073.33" dy="0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I4.INIT" Comment="" dx1="1140">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="3946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q2.INIT" Comment="" dx1="3946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q3.INIT" Comment="" dx1="3946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q4.INIT" Comment="" dx1="3946.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="BOOLS_TO_BYTE.CNF" Destination="BYTE_TO_BOOLS.REQ" Comment=""/>
			<Connection Source="DigitalInput_I1.IND" Destination="BOOLS_TO_BYTE.REQ" Comment="" dx1="80"/>
			<Connection Source="DigitalInput_I2.IND" Destination="BOOLS_TO_BYTE.REQ" Comment="" dx1="80"/>
			<Connection Source="DigitalInput_I3.IND" Destination="BOOLS_TO_BYTE.REQ" Comment=""/>
			<Connection Source="DigitalInput_I4.IND" Destination="BOOLS_TO_BYTE.REQ" Comment="" dx1="80"/>
			<Connection Source="BYTE_TO_BOOLS.CNF" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="206.67"/>
			<Connection Source="BYTE_TO_BOOLS.CNF" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="206.67"/>
			<Connection Source="BYTE_TO_BOOLS.CNF" Destination="DigitalOutput_Q3.REQ" Comment="" dx1="206.67"/>
			<Connection Source="BYTE_TO_BOOLS.CNF" Destination="DigitalOutput_Q4.REQ" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="BYTE_TO_BOOLS.OUT_00" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="73.33"/>
			<Connection Source="BYTE_TO_BOOLS.OUT_01" Destination="DigitalOutput_Q2.OUT" Comment="" dx1="140"/>
			<Connection Source="BYTE_TO_BOOLS.OUT_02" Destination="DigitalOutput_Q3.OUT" Comment="" dx1="273.33"/>
			<Connection Source="BYTE_TO_BOOLS.OUT_03" Destination="DigitalOutput_Q4.OUT" Comment="" dx1="340"/>
			<Connection Source="DigitalInput_I4.IN" Destination="BOOLS_TO_BYTE.IN_03" Comment="" dx1="146.67"/>
			<Connection Source="DigitalInput_I3.IN" Destination="BOOLS_TO_BYTE.IN_02" Comment="" dx1="146.67"/>
			<Connection Source="DigitalInput_I2.IN" Destination="BOOLS_TO_BYTE.IN_01" Comment="" dx1="146.67"/>
			<Connection Source="DigitalInput_I1.IN" Destination="BOOLS_TO_BYTE.IN_00" Comment="" dx1="213.33"/>
			<Connection Source="BOOLS_TO_BYTE." Destination="BYTE_TO_BOOLS.IN" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
