<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_034" Comment="Analog-Eingang auf PWM Ausgang">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AnalogInput_I7" Type="ID" Comment="" x="-2533.3333333333335" y="533.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_DWORD_TO_UDINT_I7" Type="F_DWORD_TO_UDINT" Comment="" x="-806.6666666666667" y="986.6666666666667">
		</FB>
		<FB Name="PWMOutput_Q4" Type="QD" Comment="" x="1733.3333333333335" y="1066.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="AnalogInput_I7.INIT" Comment="" dx1="1446.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="AnalogInput_I7.IND" Destination="F_DWORD_TO_UDINT_I7.REQ" Comment="" dx1="960.0"/>
			<Connection Source="AnalogInput_I7.CNF" Destination="F_DWORD_TO_UDINT_I7.REQ" Comment="" dx1="960.0"/>
			<Connection Source="AnalogInput_I7.INITO" Destination="PWMOutput_Q4.INIT" Comment="" dx1="3433.3333333333335"/>
			<Connection Source="AnalogInput_I7.IND" Destination="PWMOutput_Q4.REQ" Comment="" dx1="3246.666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AnalogInput_I7.IN" Destination="F_DWORD_TO_UDINT_I7.IN" Comment=""/>
			<Connection Source="AnalogInput_I7.IN" Destination="PWMOutput_Q4.OUT" Comment="" dx1="553.3333333333334"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
