<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_125_sub" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2025-10-22">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="PLUG1" Type="isobus::pgn::tx::Callback"/>
		</Plugs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="CallbackFB" Type="isobus::pgn::tx::CallbackFB" x="0" y="0">
			<Parameter Name="DI1" Value="(data := [16#FF, 16#FF, 16#FF, 16#FF, 16#FF, 16#FF, 16#FF, 16#FF])"/>
		</FB>
		<FB Name="E_CTU" Type="iec61499::events::E_CTU" x="1900" y="-600">
			<Parameter Name="PV" Value="USINT#0"/>
		</FB>
		<FB Name="STRUCT_MUX" Type="eclipse4diac::convert::STRUCT_MUX" x="-2400" y="100">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CAN_MSG"/>
		</FB>
		<FB Name="SET_AT_INDEX" Type="eclipse4diac::utils::SET_AT_INDEX" x="-3800" y="900">
			<Parameter Name="INDEX" Value="0"/>
		</FB>
		<FB Name="STRUCT_DEMUX" Type="eclipse4diac::convert::STRUCT_DEMUX" x="-6900" y="0">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CAN_MSG"/>
		</FB>
		<EventConnections>
			<Connection Source="CallbackFB.REQ" Destination="E_CTU.CU" dx1="573.33"/>
			<Connection Source="E_CTU.CUO" Destination="SET_AT_INDEX.REQ" dx1="80" dx2="80" dy="-446.67"/>
			<Connection Source="SET_AT_INDEX.CNF" Destination="STRUCT_MUX.REQ" dx1="240"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="STRUCT_MUX.OUT" Destination="CallbackFB.DI1" dx1="1226.67"/>
			<Connection Source="STRUCT_DEMUX.data" Destination="SET_AT_INDEX.IN_ARRAY" dx1="473.33"/>
			<Connection Source="E_CTU.CV" Destination="SET_AT_INDEX.VALUE" dx1="833.33" dx2="720" dy="-1026.67"/>
			<Connection Source="SET_AT_INDEX.OUT_ARRAY" Destination="STRUCT_MUX.data" dx1="340"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="CallbackFB.PLUG1" Destination="PLUG1" dx1="4780"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
