<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039_sub_NumbAnzeig" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2024-03-03">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="CNF" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="20"/>
			</SubAppEvent>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="29"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="STATE_NR" Type="SINT" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="75"/>
			</VarDeclaration>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_SINT_TO_UINT" Type="F_SINT_TO_UINT" Comment="" x="-800.0" y="0.0">
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" Comment="" x="1340.0" y="-873.3333333333334">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="F_SINT_TO_UINT.CNF" Destination="Q_NumericValue.REQ" Comment="" dx1="213.33333333333334"/>
			<Connection Source="CNF" Destination="F_SINT_TO_UINT.REQ" Comment="" dx1="273.33333333333337"/>
			<Connection Source="INIT" Destination="Q_NumericValue.INIT" Comment="" dx1="1326.6666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SINT_TO_UINT.OUT" Destination="Q_NumericValue.u32NewValue" Comment="" dx1="246.66666666666669"/>
			<Connection Source="STATE_NR" Destination="F_SINT_TO_UINT.IN" Comment="" dx1="240.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
