<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039a" Comment="Spiegelabfolge V2 mit Schrittkette">
	<Identification Standard="61499-2" Description="Spiegelabfolge V2 mit Schrittkette &#10;geeignet für hydraulisches Ringsystem 3/2 Wege Ventile  (z.B. Claas)&#10;oder pneumatische 5/2 Wege Ventile &#10;" >
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_TimeOut" Type="E_TimeOut" Comment="" x="-8626.666666666668" y="3553.3333333333335">
		</FB>
		<FB Name="DigitalInput_DOWN_I1" Type="IE" Comment="" x="-12533.333333333334" y="166.66666666666669">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_DOWN_I2" Type="IE" Comment="" x="-12533.333333333334" y="1146.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_DOWN_I3" Type="IE" Comment="" x="-12533.333333333334" y="2126.666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_DOWN_I4" Type="IE" Comment="" x="-12533.333333333334" y="3106.666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="sequence_05" Type="sequence_ET_05" Comment="" x="-10726.666666666668" y="-126.66666666666667">
			<Parameter Name="DT_S1_S2" Value="NO_TIME" Comment=""/>
			<Parameter Name="DT_S2_S3" Value="NO_TIME" Comment=""/>
			<Parameter Name="DT_S3_S4" Value="T#5s" Comment=""/>
			<Parameter Name="DT_S4_S5" Value="NO_TIME" Comment=""/>
			<Parameter Name="DT_S5_START" Value="NO_TIME" Comment=""/>
		</FB>
		<SubApp Name="NumbAnzeig" Type="Uebung_039_sub_NumbAnzeig" Comment="" x="-8766.666666666668" y="-986.6666666666667">
		</SubApp>
		<FB Name="SoftKey_F1_UP" Type="IE" Comment="" x="-14040.0" y="-353.33333333333337">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<SubApp Name="Q1" Type="Uebung_039_sub_Outputs" Comment="" x="-8626.666666666668" y="-233.33333333333334">
			<Parameter Name="u16ObjId" Value="SoftKey_F8" Comment=""/>
		</SubApp>
		<SubApp Name="Q4" Type="Uebung_039_sub_Outputs" Comment="" x="-8626.666666666668" y="2606.666666666667">
			<Parameter Name="u16ObjId" Value="SoftKey_F3" Comment=""/>
		</SubApp>
		<SubApp Name="Q2" Type="Uebung_039_sub_Outputs" Comment="" x="-8626.666666666668" y="713.3333333333334">
			<Parameter Name="u16ObjId" Value="SoftKey_F2" Comment=""/>
		</SubApp>
		<SubApp Name="Q3" Type="Uebung_039_sub_Outputs" Comment="" x="-8626.666666666668" y="1660.0">
			<Parameter Name="u16ObjId" Value="SoftKey_F9" Comment=""/>
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_DOWN_I1.INIT" Comment="" dx1="453.33333333333337">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_DOWN_I2.INIT" Comment="" dx1="273.33333333333337">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_DOWN_I3.INIT" Comment="" dx1="453.33333333333337" dx2="453.33333333333337" dy="0.0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_DOWN_I4.INIT" Comment="" dx1="1453.3333333333335">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_DOWN_I1.IND" Destination="sequence_05.S1_S2" Comment="" dx1="313.33333333333337"/>
			<Connection Source="DigitalInput_DOWN_I2.IND" Destination="sequence_05.S2_S3" Comment="" dx1="380.0"/>
			<Connection Source="DigitalInput_DOWN_I3.IND" Destination="sequence_05.S4_S5" Comment="" dx1="446.6666666666667"/>
			<Connection Source="DigitalInput_DOWN_I4.IND" Destination="sequence_05.S5_START" Comment="" dx1="513.3333333333334"/>
			<Connection Source="sequence_05.CNF" Destination="NumbAnzeig.CNF" Comment="" dx1="73.33333333333334"/>
			<Connection Source="INIT" Destination="NumbAnzeig.INIT" Comment="" dx1="2933.3333333333335">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="SoftKey_F1_UP.INIT" Comment="" dx1="173.33333333333334">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_F1_UP.IND" Destination="sequence_05.START_S1" Comment=""/>
			<Connection Source="INIT" Destination="Q1.INIT" Comment="" dx1="3066.666666666667" dx2="3066.666666666667" dy="0.0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="sequence_05.EO_S1" Destination="Q1.REQ" Comment="" dx1="406.6666666666667"/>
			<Connection Source="INIT" Destination="Q4.INIT" Comment="" dx1="2613.3333333333335" dx2="2613.3333333333335" dy="0.0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="sequence_05.EO_S5" Destination="Q4.REQ" Comment="" dx1="273.33333333333337"/>
			<Connection Source="INIT" Destination="Q2.INIT" Comment="" dx1="2613.3333333333335" dx2="2613.3333333333335" dy="0.0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="sequence_05.EO_S2" Destination="Q2.REQ" Comment="" dx1="540.0"/>
			<Connection Source="INIT" Destination="Q3.INIT" Comment="" dx1="2613.3333333333335" dx2="2613.3333333333335" dy="0.0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="sequence_05.EO_S4" Destination="Q3.REQ" Comment="" dx1="406.6666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="sequence_05.STATE_NR" Destination="NumbAnzeig.STATE_NR" Comment="" dx1="340.0"/>
			<Connection Source="sequence_05.DO_S1" Destination="Q1.OUT" Comment="" dx1="473.33333333333337"/>
			<Connection Source="sequence_05.DO_S5" Destination="Q4.OUT" Comment="" dx1="140.0"/>
			<Connection Source="sequence_05.DO_S2" Destination="Q2.OUT" Comment="" dx1="540.0"/>
			<Connection Source="sequence_05.DO_S4" Destination="Q3.OUT" Comment="" dx1="206.66666666666669"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="sequence_05.timeOut" Destination="E_TimeOut.TimeOutSocket" Comment="" dx1="73.33333333333334"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
