<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_120" Comment="Übung zu ISOBUS Name">
	<Identification Standard="61499-2" Description="Copyright (c) 2025 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="STRUCT_DEMUX" Type="STRUCT_DEMUX" x="2400" y="1400">
			<Attribute Name="StructuredType" Type="STRING" Value="ISONAMEFIELD_T"/>
		</FB>
		<FB Name="STRUCT_MUX" Type="STRUCT_MUX" x="300" y="1400">
			<Attribute Name="StructuredType" Type="STRING" Value="ISONAMEFIELD_T"/>
		</FB>
		<EventConnections>
			<Connection Source="STRUCT_MUX.CNF" Destination="STRUCT_DEMUX.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="STRUCT_MUX.OUT" Destination="STRUCT_DEMUX.IN"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
