<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_049" Comment="DigitalInput_I1 auf DigitalOutput_Q1">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-1320.0" y="-820.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-4386.666666666667" y="-933.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" Comment="" x="-1320.0" y="673.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" Comment="" x="-4386.666666666667" y="560.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="QX" Comment="" x="-1320.0" y="2060.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I3" Type="IX" Comment="" x="-4386.666666666667" y="1946.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="QX" Comment="" x="-1320.0" y="3340.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I4" Type="IX" Comment="" x="-4386.666666666667" y="3226.666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1.IND" Destination="DigitalOutput_Q1.REQ" Comment=""/>
			<Connection Source="INIT" Destination="DigitalInput_I2.INIT" Comment="" dx1="1146.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I2.IND" Destination="DigitalOutput_Q2.REQ" Comment=""/>
			<Connection Source="INIT" Destination="DigitalInput_I3.INIT" Comment="" dx1="1073.3333333333335" dx2="1073.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I3.IND" Destination="DigitalOutput_Q3.REQ" Comment=""/>
			<Connection Source="INIT" Destination="DigitalInput_I4.INIT" Comment="" dx1="1073.3333333333335" dx2="1073.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I4.IND" Destination="DigitalOutput_Q4.REQ" Comment=""/>
			<Connection Source="DigitalInput_I3.INITO" Destination="DigitalOutput_Q3.INIT" Comment="" dx1="1200.0"/>
			<Connection Source="DigitalInput_I4.INITO" Destination="DigitalOutput_Q4.INIT" Comment="" dx1="1200.0"/>
			<Connection Source="DigitalInput_I2.INITO" Destination="DigitalOutput_Q2.INIT" Comment="" dx1="1200.0"/>
			<Connection Source="DigitalInput_I1.INITO" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="1200.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT" Comment=""/>
			<Connection Source="DigitalInput_I2.IN" Destination="DigitalOutput_Q2.OUT" Comment=""/>
			<Connection Source="DigitalInput_I3.IN" Destination="DigitalOutput_Q3.OUT" Comment=""/>
			<Connection Source="DigitalInput_I4.IN" Destination="DigitalOutput_Q4.OUT" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
