<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_055" Comment="DigitalInput_I1-_I4 auf DigitalOutput_Q1-_Q4">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-4706.666666666667" y="-873.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-8706.666666666668" y="-986.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="Q_TO_STR_STATUS" Type="QUARTER_TO_STR_STATUS" Comment="" x="-4933.333333333334" y="400.0">
		</FB>
		<FB Name="Q_TO_BOOL" Type="QUARTER_TO_BOOL" Comment="" x="-6226.666666666667" y="-760.0">
		</FB>
		<FB Name="BOOL_TO_Q" Type="BOOL_TO_QUARTER" Comment="" x="-7473.333333333334" y="-760.0">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="3946.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Q_TO_BOOL.CNF" Destination="DigitalOutput_Q1.REQ" Comment=""/>
			<Connection Source="DigitalInput_I1.IND" Destination="BOOL_TO_Q.REQ" Comment=""/>
			<Connection Source="BOOL_TO_Q.CNF" Destination="Q_TO_STR_STATUS.REQ" Comment="" dx1="286.6666666666667" dx2="286.6666666666667" dy="0.0"/>
			<Connection Source="BOOL_TO_Q.CNF" Destination="Q_TO_BOOL.REQ" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Q_TO_BOOL.Q" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="73.33333333333334" dx2="73.33333333333334" dy="0.0"/>
			<Connection Source="DigitalInput_I1.IN" Destination="BOOL_TO_Q.I" Comment="" dx1="73.33333333333334" dx2="73.33333333333334" dy="0.0"/>
			<Connection Source="BOOL_TO_Q.QB" Destination="Q_TO_STR_STATUS.IB" Comment="" dx1="100.0" dx2="100.0" dy="0.0"/>
			<Connection Source="BOOL_TO_Q.QB" Destination="Q_TO_BOOL.IB" Comment="" dx1="73.33333333333334" dx2="73.33333333333334" dy="0.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
