<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_029" Comment="LED_DO Blinkende LED">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="LED_Q1_5HZ" Type="QX" Comment="" x="-1466.6666666666667" y="-833.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-4533.333333333334" y="-946.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="LED_Q1_1HZ" Type="QX" Comment="" x="-1466.6666666666667" y="400.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" Comment="" x="-4533.333333333334" y="286.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="LED_Q1_ON" Type="QX" Comment="" x="-1466.6666666666667" y="1566.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I3" Type="IX" Comment="" x="-4533.333333333334" y="1453.3333333333335">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="COLD" Destination="DigitalInput_I1.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1.INITO" Destination="LED_Q1_5HZ.INIT" Comment="" dx1="1200.0"/>
			<Connection Source="DigitalInput_I1.IND" Destination="LED_Q1_5HZ.REQ" Comment=""/>
			<Connection Source="DigitalInput_I2.IND" Destination="LED_Q1_1HZ.REQ" Comment=""/>
			<Connection Source="COLD" Destination="DigitalInput_I2.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I2.INITO" Destination="LED_Q1_1HZ.INIT" Comment="" dx1="1186.6666666666667"/>
			<Connection Source="COLD" Destination="DigitalInput_I3.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I3.IND" Destination="LED_Q1_ON.REQ" Comment=""/>
			<Connection Source="DigitalInput_I3.INITO" Destination="LED_Q1_ON.INIT" Comment="" dx1="1186.6666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="LED_Q1_5HZ.OUT" Comment=""/>
			<Connection Source="DigitalInput_I2.IN" Destination="LED_Q1_1HZ.OUT" Comment=""/>
			<Connection Source="DigitalInput_I3.IN" Destination="LED_Q1_ON.OUT" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
