<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010bA2" Comment="Toggle Flip-Flop mit IE AuxFunction2_X1 AuxEnabled">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS_QX" x="-3900" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q1"/>
		</FB>
		<FB Name="Button_A1" Type="Aux_IE" x="-7200" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="DefaultPool::AuxFunction2_X1"/>
			<Parameter Name="InputEvent" Value="AuxiliaryState::AuxEnabled"/>
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" x="-5560" y="0">
		</FB>
		<Comment Comment="AuxEnabled wird nicht wiederholt bei einem AUX Type 2&#10;bei Aux Type 0 schon.&#10;Lange drücken ergibt 1 Event bei Type 2" x="-9000" y="800" width="1500" height="700"/>
		<EventConnections>
			<Connection Source="Button_A1.IND" Destination="E_T_FF.CLK"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="580"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
