<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039" Comment="Spiegelabfolge V2 mit Schrittkette" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0&#10;   &#10;Spiegelabfolge V2 mit Schrittkette &#10;geeignet für hydraulische 4/3 Wege Ventile  &#10;oder pneumatische 5/3 Wege Ventile &#10;jeweils Mittelstellung gesperrt. " >
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_TimeOut" Type="E_TimeOut" x="-8626.67" y="3553.33">
		</FB>
		<FB Name="DigitalInput_DOWN_I1" Type="IE" x="-13000" y="100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_DOWN_I2" Type="IE" x="-13000" y="1080">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_DOWN_I3" Type="IE" x="-13000" y="2060">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_DOWN_I4" Type="IE" x="-13000" y="3040">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="sequence_05" Type="sequence_ET_05" x="-10726.67" y="-126.67">
			<Parameter Name="DT_S1_S2" Value="sequence::NO_TIME"/>
			<Parameter Name="DT_S2_S3" Value="sequence::NO_TIME"/>
			<Parameter Name="DT_S3_S4" Value="T#5s"/>
			<Parameter Name="DT_S4_S5" Value="sequence::NO_TIME"/>
			<Parameter Name="DT_S5_START" Value="sequence::NO_TIME"/>
		</FB>
		<SubApp Name="NumbAnzeig" Type="Uebung_039_sub_NumbAnzeig" x="-8766.67" y="-986.67">
		</SubApp>
		<FB Name="SoftKey_UP_F1" Type="IE" x="-14133.33" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<SubApp Name="Q1" Type="Uebung_039_sub_Outputs" x="-8626.67" y="-233.33">
			<Parameter Name="u16ObjId" Value="DefaultPool::SoftKey_F8"/>
		</SubApp>
		<SubApp Name="Q4" Type="Uebung_039_sub_Outputs" x="-8626.67" y="2606.67">
			<Parameter Name="u16ObjId" Value="DefaultPool::SoftKey_F3"/>
		</SubApp>
		<SubApp Name="Q2" Type="Uebung_039_sub_Outputs" x="-8626.67" y="713.33">
			<Parameter Name="u16ObjId" Value="DefaultPool::SoftKey_F2"/>
		</SubApp>
		<SubApp Name="Q3" Type="Uebung_039_sub_Outputs" x="-8626.67" y="1660">
			<Parameter Name="u16ObjId" Value="DefaultPool::SoftKey_F9"/>
		</SubApp>
		<EventConnections>
			<Connection Source="DigitalInput_DOWN_I1.IND" Destination="sequence_05.S1_S2" dx1="313.33"/>
			<Connection Source="DigitalInput_DOWN_I2.IND" Destination="sequence_05.S2_S3" dx1="380"/>
			<Connection Source="DigitalInput_DOWN_I3.IND" Destination="sequence_05.S4_S5" dx1="446.67"/>
			<Connection Source="DigitalInput_DOWN_I4.IND" Destination="sequence_05.S5_START" dx1="513.33"/>
			<Connection Source="sequence_05.CNF" Destination="NumbAnzeig.CNF" dx1="73.33"/>
			<Connection Source="SoftKey_UP_F1.IND" Destination="sequence_05.START_S1" dx1="1360"/>
			<Connection Source="sequence_05.EO_S1" Destination="Q1.REQ" dx1="406.67"/>
			<Connection Source="sequence_05.EO_S5" Destination="Q4.REQ" dx1="273.33"/>
			<Connection Source="sequence_05.EO_S2" Destination="Q2.REQ" dx1="540"/>
			<Connection Source="sequence_05.EO_S4" Destination="Q3.REQ" dx1="406.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="sequence_05.STATE_NR" Destination="NumbAnzeig.STATE_NR" dx1="340"/>
			<Connection Source="sequence_05.DO_S1" Destination="Q1.OUT" dx1="473.33"/>
			<Connection Source="sequence_05.DO_S5" Destination="Q4.OUT" dx1="140"/>
			<Connection Source="sequence_05.DO_S2" Destination="Q2.OUT" dx1="540"/>
			<Connection Source="sequence_05.DO_S4" Destination="Q3.OUT" dx1="206.67"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="sequence_05.timeOut" Destination="E_TimeOut.TimeOutSocket" dx1="73.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
