<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_080" Comment="Beispiel für E_CTU">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0&#10;   &#10;Beispiel für E_CTU&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 92">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-4886.67" y="-886.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="IE" x="-8006.67" y="-986.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_CTU" Type="E_CTU" x="-6253.33" y="-786.67">
			<Parameter Name="PV" Value="UINT#5"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="IE" x="-8006.67" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_CTU.CU"/>
			<Connection Source="E_CTU.CUO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_CTU.RO" Destination="DigitalOutput_Q1.REQ" dx1="286.67"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_CTU.R" dx1="273.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTU.Q" Destination="DigitalOutput_Q1.OUT" dx1="286.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
