<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012a" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="COLD" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="CbVtStatus" Type="CbVtStatus" Comment="" x="-6266.666666666667" y="933.3333333333334">
		</FB>
		<SubApp Name="Uebung_012a_sub" Type="Uebung_012a_sub" Comment="" x="-3733.3333333333335" y="666.6666666666667">
			<Parameter Name="KEY" Value="KEY_I1_STORE" Comment=""/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1" Comment=""/>
		</SubApp>
		<EventConnections>
			<Connection Source="COLD" Destination="CbVtStatus.INIT" Comment="" dx1="326.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="COLD" Destination="Uebung_012a_sub.COLD" Comment="" dx1="1466.6666666666667" dx2="1466.6666666666667" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="CbVtStatus.IND" Destination="Uebung_012a_sub.IND" Comment="" dx1="893.3333333333334"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
