<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_087a1" Comment="Beispiel für E_DEMUX_4">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0&#10;   &#10;Beispiel für E_CTD&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 93">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_DEMUX_4" Type="E_DEMUX_4" x="3900" y="2900">
		</FB>
		<FB Name="ADD_3" Type="ADD_3" x="2700" y="3200">
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" x="400" y="2300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I3" Type="IX" x="400" y="3500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I4" Type="IX" x="400" y="4700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="F_BOOL_TO_UINT_I2" Type="F_BOOL_TO_UINT" x="1400" y="2700">
		</FB>
		<FB Name="F_BOOL_TO_UINT_I3" Type="F_BOOL_TO_UINT" x="1400" y="3900">
		</FB>
		<FB Name="F_BOOL_TO_UINT_I4" Type="F_BOOL_TO_UINT" x="1400" y="5100">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" x="6900" y="2700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QX" x="6900" y="1900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="QX" x="6900" y="4300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="QX" x="6900" y="3500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_T_FF_Q1" Type="E_T_FF" x="5600" y="2200">
		</FB>
		<FB Name="E_T_FF_Q2" Type="E_T_FF" x="5800" y="3000">
		</FB>
		<FB Name="E_T_FF_Q3" Type="E_T_FF" x="5800" y="3800">
		</FB>
		<FB Name="E_T_FF_Q4" Type="E_T_FF" x="5700" y="4600">
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="IE" x="400" y="1200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<Comment Comment="Diese Taste schaltet ein oder aus&#10;" x="1400" y="1000" width="900" height="500"/>
		<Comment Comment="Die Anzahl der restlichen Tasten bestimmt den Ausgang: &#10;Keine --&gt; Q1&#10;Eine --&gt; Q2&#10;Zwei --&gt; Q3&#10;Drei --&gt; Q4" x="1400" y="1900" width="2000" height="700"/>
		<EventConnections>
			<Connection Source="DigitalInput_I2.IND" Destination="F_BOOL_TO_UINT_I2.REQ" dx1="73.33"/>
			<Connection Source="DigitalInput_I3.IND" Destination="F_BOOL_TO_UINT_I3.REQ" dx1="73.33"/>
			<Connection Source="DigitalInput_I4.IND" Destination="F_BOOL_TO_UINT_I4.REQ" dx1="73.33"/>
			<Connection Source="F_BOOL_TO_UINT_I4.CNF" Destination="ADD_3.REQ" dx1="140"/>
			<Connection Source="F_BOOL_TO_UINT_I3.CNF" Destination="ADD_3.REQ" dx1="140"/>
			<Connection Source="F_BOOL_TO_UINT_I2.CNF" Destination="ADD_3.REQ" dx1="140"/>
			<Connection Source="E_T_FF_Q4.EO" Destination="DigitalOutput_Q4.REQ" dx1="333.33"/>
			<Connection Source="E_T_FF_Q3.EO" Destination="DigitalOutput_Q3.REQ" dx1="280"/>
			<Connection Source="E_T_FF_Q2.EO" Destination="DigitalOutput_Q2.REQ" dx1="280"/>
			<Connection Source="E_T_FF_Q1.EO" Destination="DigitalOutput_Q1.REQ" dx1="380"/>
			<Connection Source="E_DEMUX_4.EO1" Destination="E_T_FF_Q1.CLK" dx1="693.33"/>
			<Connection Source="E_DEMUX_4.EO2" Destination="E_T_FF_Q2.CLK"/>
			<Connection Source="E_DEMUX_4.EO3" Destination="E_T_FF_Q3.CLK" dx1="793.33"/>
			<Connection Source="E_DEMUX_4.EO4" Destination="E_T_FF_Q4.CLK" dx1="566.67"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_DEMUX_4.EI" dx1="2500"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I2.IN" Destination="F_BOOL_TO_UINT_I2.IN"/>
			<Connection Source="DigitalInput_I3.IN" Destination="F_BOOL_TO_UINT_I3.IN"/>
			<Connection Source="DigitalInput_I4.IN" Destination="F_BOOL_TO_UINT_I4.IN"/>
			<Connection Source="F_BOOL_TO_UINT_I2.OUT" Destination="ADD_3.IN1" dx1="73.33"/>
			<Connection Source="F_BOOL_TO_UINT_I3.OUT" Destination="ADD_3.IN2" dx1="180"/>
			<Connection Source="F_BOOL_TO_UINT_I4.OUT" Destination="ADD_3.IN3" dx1="260"/>
			<Connection Source="ADD_3.OUT" Destination="E_DEMUX_4.K"/>
			<Connection Source="E_T_FF_Q4.Q" Destination="DigitalOutput_Q4.OUT"/>
			<Connection Source="E_T_FF_Q3.Q" Destination="DigitalOutput_Q3.OUT"/>
			<Connection Source="E_T_FF_Q2.Q" Destination="DigitalOutput_Q2.OUT"/>
			<Connection Source="E_T_FF_Q1.Q" Destination="DigitalOutput_Q1.OUT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
