<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_007a2" Comment="Blinker mit E_CYCLE und E_T_FF">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-400" y="-600">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_CYCLE" Type="E_CYCLE" x="-2800" y="-500">
			<Parameter Name="DT" Value="T#1s"/>
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" x="-1600" y="-500">
		</FB>
		<FB Name="START" Type="IE" x="-4700" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="STOP" Type="IE" x="-4700" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="E_CYCLE.EO" Destination="E_T_FF.CLK"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="START.IND" Destination="E_CYCLE.START" dx1="526.67"/>
			<Connection Source="STOP.IND" Destination="E_CYCLE.STOP" dx1="526.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="333.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
