<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020b" Comment="DigitalInput_I1 auf DigitalOutput_Q1; TON Einschaltverzögert">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="INT" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-3553.3333333333335" y="346.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-8706.666666666668" y="366.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" Comment="" x="-7466.666666666667" y="753.3333333333334">
		</FB>
		<FB Name="E_RS" Type="E_RS" Comment="" x="-4840.0" y="526.6666666666667">
		</FB>
		<FB Name="E_DELAY" Type="E_DELAY" Comment="" x="-5993.333333333334" y="640.0">
			<Parameter Name="DT" Value="T#2S" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="200.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="3880.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1.IND" Destination="E_SWITCH.EI" Comment="" dx1="80.0"/>
			<Connection Source="E_RS.EO" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="73.33333333333334"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_DELAY.START" Comment="" dx1="433.33333333333337"/>
			<Connection Source="E_DELAY.EO" Destination="E_RS.S" Comment=""/>
			<Connection Source="E_SWITCH.EO0" Destination="E_RS.R" Comment="" dx1="73.33333333333334" dx2="286.6666666666667" dy="-360.0"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_DELAY.STOP" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="E_SWITCH.G" Comment="" dx1="273.33333333333337"/>
			<Connection Source="E_RS.Q" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="420.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
