<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_002c" Comment="DigitalInput_I1/_I2 auf DigitalOutput_Q1">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
		<Import declaration="logiBUS::io::DI::logiBUS_DI"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="2800" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-4600" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I1"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IX" x="-4600" y="200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I2"/>
		</FB>
		<FB Name="AND_2" Type="AND_2" x="-2000" y="400">
		</FB>
		<FB Name="DigitalInput_I3" Type="logiBUS::io::DI::logiBUS_IX" x="-4500" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I3"/>
		</FB>
		<FB Name="OR_2" Type="OR_2" x="200" y="1600">
		</FB>
		<FB Name="BOOL2BOOL" Type="BOOL2BOOL" x="-1200" y="400">
		</FB>
		<FB Name="E_D_FF" Type="E_D_FF" x="1200" y="1600">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="AND_2.REQ" dx1="1720"/>
			<Connection Source="DigitalInput_I2.IND" Destination="AND_2.REQ"/>
			<Connection Source="E_D_FF.EO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="AND_2.CNF" Destination="BOOL2BOOL.REQ"/>
			<Connection Source="BOOL2BOOL.CNF" Destination="OR_2.REQ" dx1="326.67"/>
			<Connection Source="DigitalInput_I3.IND" Destination="OR_2.REQ"/>
			<Connection Source="OR_2.CNF" Destination="E_D_FF.CLK"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AND_2.IN1" dx1="900"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AND_2.IN2" dx1="953.33"/>
			<Connection Source="DigitalInput_I3.IN" Destination="OR_2.IN2" dx1="2000"/>
			<Connection Source="E_D_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="473.33"/>
			<Connection Source="AND_2.OUT" Destination="BOOL2BOOL.IN"/>
			<Connection Source="BOOL2BOOL.OUT" Destination="OR_2.IN1" dx1="80"/>
			<Connection Source="OR_2.OUT" Destination="E_D_FF.D"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
