<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_029" Comment="LED_DO Blinkende LED" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="LED_Q1_5HZ" Type="QX" x="-1500" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" x="-4500" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="LED_Q1_1HZ" Type="QX" x="-1500" y="300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" x="-4500" y="200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="LED_Q1_ON" Type="QX" x="-1500" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I3" Type="IX" x="-4500" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="LED_Q1_5HZ.REQ"/>
			<Connection Source="DigitalInput_I2.IND" Destination="LED_Q1_1HZ.REQ"/>
			<Connection Source="DigitalInput_I3.IND" Destination="LED_Q1_ON.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="LED_Q1_5HZ.OUT"/>
			<Connection Source="DigitalInput_I2.IN" Destination="LED_Q1_1HZ.OUT"/>
			<Connection Source="DigitalInput_I3.IN" Destination="LED_Q1_ON.OUT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
