<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_035" Comment="Spiegelabfolge V2 mit Schrittkette">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-2353.3333333333335" y="-266.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-3866.666666666667" y="-266.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="sequence_04" Type="sequence_04" Comment="" x="-3973.3333333333335" y="846.6666666666667">
		</FB>
		<FB Name="E_TimeOut" Type="E_TimeOut" Comment="" x="-2353.3333333333335" y="1160.0">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="1073.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1.INITO" Destination="DigitalOutput_Q1.INIT" Comment=""/>
			<Connection Source="DigitalInput_I1.IND" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="80.0"/>
			<Connection Source="INIT" Destination="sequence_04.INIT" Comment="" dx1="1346.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="80.0"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="sequence_04.timeOut" Destination="E_TimeOut.TimeOutSocket" Comment=""/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
