<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012" Comment="Numeric Value Input und Speichern">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_DWORD_TO_UDINT" Type="F_DWORD_TO_UDINT" x="-3400" y="800">
		</FB>
		<FB Name="InputNumber_I1" Type="ID" x="-4500" y="400">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="NVS" Type="NVS" x="-900" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="KEY" Value="NVS_Keys::KEY_I1_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#0"/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" x="800" y="800">
			<Parameter Name="u16ObjId" Value="DefaultPool::InputNumber_I1"/>
		</FB>
		<FB Name="CbVtStatus" Type="CbVtStatus" x="-3740" y="0">
			<Parameter Name="STATUS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8Instance" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="qWsActive" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="wPage" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="InputNumber_I1.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="300"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="NVS.SET"/>
			<Connection Source="NVS.GETO" Destination="Q_NumericValue.REQ"/>
			<Connection Source="CbVtStatus.IND" Destination="Q_NumericValue.REQ" dx1="3713.33"/>
			<Connection Source="NVS.INITO" Destination="NVS.GET" dx1="80" dx2="440" dy="-506.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="InputNumber_I1.IN" Destination="F_DWORD_TO_UDINT.IN"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="NVS.VALUE" dx1="133.33"/>
			<Connection Source="NVS.VALUEO" Destination="Q_NumericValue.u32NewValue" dx1="313.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
