<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_110" Comment="Übung zum Integer Überlauf">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-500" y="300">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="ADD_2" Type="ADD_2" x="-3600" y="400">
			<Parameter Name="IN1" Value="USINT#200"/>
			<Parameter Name="IN2" Value="USINT#200"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="IE" x="-5600" y="200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="F_GT" Type="F_GT" x="-1700" y="400">
			<Parameter Name="IN2" Value="USINT#200"/>
		</FB>
		<FB Name="F_MOVE" Type="F_MOVE" x="-2900" y="400">
			<Attribute Name="DataType" Value="USINT"/>
		</FB>
		<Comment Comment="Arithmetischer Überlauf&#10;&#10;https://de.wikipedia.org/wiki/Arithmetischer_%C3%9Cberlauf&#10;&#10;https://www.youtube.com/watch?v=TLanGc-c9Ww&#10;" x="-5400" y="1500" width="3700" height="800"/>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="ADD_2.REQ"/>
			<Connection Source="ADD_2.CNF" Destination="F_MOVE.REQ"/>
			<Connection Source="F_MOVE.CNF" Destination="F_GT.REQ"/>
			<Connection Source="F_GT.CNF" Destination="DigitalOutput_Q1.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="ADD_2.OUT" Destination="F_MOVE.IN"/>
			<Connection Source="F_MOVE.OUT" Destination="F_GT.IN1"/>
			<Connection Source="F_GT.OUT" Destination="DigitalOutput_Q1.OUT" dx1="380"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
