<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004c6" Comment="Toggle Flip-Flop mit IE mit BUTTON_MULTIPLE_CLICK (3-fach Klick)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
		<Import declaration="logiBUS::io::DI::logiBUS_DI"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-4000" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="logiBUS_DO::Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS_IE2" x="-7300" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_DI::Input_I1"/>
			<Parameter Name="InputEvent" Value="logiBUS_DI_Events::BUTTON_MULTIPLE_CLICK"/>
			<Parameter Name="arg" Value="3"/>
		</FB>
		<FB Name="E_T_FF" Type="iec61499::events::E_T_FF" x="-5600" y="0">
		</FB>
		<Comment Comment="Auswertung: 3-fach Klick" x="-7900" y="900" width="1300" height="400"/>
		<FB Name="E_SR" Type="iec61499::events::E_SR" x="-6300" y="1200">
		</FB>
		<FB Name="E_SWITCH" Type="iec61499::events::E_SWITCH" x="-7900" y="1200">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_T_FF.CLK"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_SR.S"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_SR.R"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="386.67"/>
			<Connection Source="E_SR.Q" Destination="E_SWITCH.G" dx1="80" dx2="80" dy="160"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
