<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_006" Comment="SR-Flip-Flop mit 2x IE" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-1500" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" x="-4500" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" x="-4500" y="200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SR" Type="E_SR" x="-2800" y="-800">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_SR.S"/>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_SR.R" dx1="473.33"/>
			<Connection Source="E_SR.EO" Destination="DigitalOutput_Q1.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="DigitalOutput_Q1.OUT" dx1="446.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
