<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_006a" Comment="SR&amp;amp;T-Flip-Flop mit 3x IE">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-1473.34" y="-800">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" Comment="" x="-4540" y="-913.33">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" Comment="" x="-4540" y="113.34">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_T_FF_SR" Type="E_T_FF_SR" Comment="" x="-2833.33" y="-686.66">
		</FB>
		<FB Name="DigitalInput_I3_CLK" Type="IE" Comment="" x="-4533.33" y="1133.33">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1_CLK.INIT" Comment="" dx1="1113.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I2_CLK.INIT" Comment="" dx1="1206.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_T_FF_SR.S" Comment=""/>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_T_FF_SR.R" Comment="" dx1="486.67"/>
			<Connection Source="E_T_FF_SR.EO" Destination="DigitalOutput_Q1.REQ" Comment=""/>
			<Connection Source="INIT" Destination="DigitalInput_I3_CLK.INIT" Comment="" dx1="2226.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I3_CLK.IND" Destination="E_T_FF_SR.CLK" Comment="" dx1="673.33"/>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="3646.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF_SR.Q" Destination="DigitalOutput_Q1.OUT" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
