<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_006a" Comment="SR&amp;T-Flip-Flop mit 3x IE" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-1473.34" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" x="-4540" y="-913.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" x="-4540" y="113.34">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_T_FF_SR" Type="E_T_FF_SR" x="-2833.33" y="-686.66">
		</FB>
		<FB Name="DigitalInput_I3_CLK" Type="IE" x="-4533.33" y="1133.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_T_FF_SR.S" dx1="500"/>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_T_FF_SR.R" dx1="486.67"/>
			<Connection Source="E_T_FF_SR.EO" Destination="DigitalOutput_Q1.REQ" dx1="340"/>
			<Connection Source="DigitalInput_I3_CLK.IND" Destination="E_T_FF_SR.CLK" dx1="673.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF_SR.Q" Destination="DigitalOutput_Q1.OUT" dx1="340"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
