<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_003a" Comment="DigitalInput_I1/_I2 auf DigitalOutput_Q1/_I2" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="F1" Type="Uebung_003a_sub" x="140" y="606.67">
		</SubApp>
		<SubApp Name="F2" Type="Uebung_003a_sub" x="133.33" y="1066.67">
		</SubApp>
	</SubAppNetwork>
</SubAppType>
