<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_003a_sub" Comment="IX auf QX (generisch)" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="QX" Type="QX" x="-2533.33" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="IX" Type="IX" x="-4533.33" y="-1026.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="IX.INITO" Destination="QX.INIT" dx1="1373.33"/>
			<Connection Source="IX.IND" Destination="QX.REQ" dx1="993.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="IX.IN" Destination="QX.OUT" dx1="726.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
