<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_013" Comment="SR-Flip-Flop (Softkey)" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-1400" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey_UP_F1" Type="IE" x="-4500" y="-1000">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="SoftKey_F2_UP" Type="IE" x="-4500" y="0">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_SR" Type="E_SR" x="-2800" y="-800">
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_UP_F1.IND" Destination="E_SR.S"/>
			<Connection Source="SoftKey_F2_UP.IND" Destination="E_SR.R" dx1="473.33"/>
			<Connection Source="E_SR.EO" Destination="DigitalOutput_Q1.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="DigitalOutput_Q1.OUT" dx1="460"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
