<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_013" Comment="SR-Flip-Flop (Softkey)" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-1400" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey_F1_UP" Type="IE" x="-4500" y="-1000">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="SoftKey_F2_UP" Type="IE" x="-4500" y="0">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_SR" Type="E_SR" x="-2800" y="-800">
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_F1_UP.IND" Destination="E_SR.S"/>
			<Connection Source="SoftKey_F2_UP.IND" Destination="E_SR.R" dx1="473.33"/>
			<Connection Source="E_SR.EO" Destination="DigitalOutput_Q1.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="DigitalOutput_Q1.OUT" dx1="460"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
