<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_015" Comment="Object Pointer umschalten" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_F1_UP" Type="IE" x="-4533.33" y="-1133.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="SoftKey_F2_UP" Type="IE" x="-4533.33" y="226.67">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="E_SR" Type="E_SR" x="-2833.33" y="-906.67">
		</FB>
		<FB Name="F_UINT_TO_UDINT" Type="F_UINT_TO_UDINT" x="-2800" y="0">
			<Parameter Name="IN" Value="Button_A1"/>
		</FB>
		<FB Name="F_SEL" Type="F_SEL" x="-1133.33" y="-906.67">
			<Parameter Name="IN0" Value="ID_NULL"/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" x="793.33" y="-1026.67">
			<Parameter Name="u16ObjId" Value="ObjectPointer_P1"/>
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_F1_UP.IND" Destination="E_SR.S" dx1="560"/>
			<Connection Source="SoftKey_F2_UP.IND" Destination="E_SR.R" dx1="473.33"/>
			<Connection Source="F_SEL.CNF" Destination="Q_NumericValue.REQ" dx1="700"/>
			<Connection Source="E_SR.EO" Destination="F_SEL.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SEL.OUT" Destination="Q_NumericValue.u32NewValue" dx1="313.33"/>
			<Connection Source="F_UINT_TO_UDINT.OUT" Destination="F_SEL.IN1" dx1="373.33"/>
			<Connection Source="E_SR.Q" Destination="F_SEL.G" dx1="633.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
