<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Ventilsteuerung_Uebung_015" Comment="Object Pointer umschalten" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="mapping" Type="mapping_Uebung_015" x="-266.67" y="-266.67">
		</SubApp>
		<SubApp Name="functions" Type="Uebung_015" x="-266.67" y="273.33">
		</SubApp>
	</SubAppNetwork>
</SubAppType>
