<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground2C" Comment="Hintergrundfarbe (TRUE -> Grün, FALSE -> Weiß) für 2 Objekte (Kompakt)">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-06">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EO" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="272"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="Q" Type="BOOL">
				<Attribute Name="YPOSITION" Type="INT" Value="139"/>
			</VarDeclaration>
			<VarDeclaration Name="u16ObjIdA" Type="UINT"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenWhiteBackground" Type="GreenWhiteBackground2" x="-2400" y="-2100">
		</SubApp>
		<EventConnections>
			<Connection Source="EO" Destination="GreenWhiteBackground.REQ" dx1="573.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Q" Destination="GreenWhiteBackground.DI1" dx1="680"/>
			<Connection Source="u16ObjIdA" Destination="GreenWhiteBackground.u16ObjIdA" dx1="833.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
