<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenRedBackground2" Comment="Hintergrundfarbe (TRUE -&gt; Grün, FALSE -&gt; Rot) für 2 Objekte">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="franz" Date="2026-07-21">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="isobus::UT::Q::const::colours"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_1" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="CNF_2" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="DI1" Type="BOOL" Comment="Selector"/>
			<VarDeclaration Name="u16ObjIdA" Type="UINT" Comment="Object ID AUX" InitialValue="ID_NULL"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="STATUS_1" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_1" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_1" Type="INT" Comment="retval see description"/>
			<VarDeclaration Name="STATUS_2" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_2" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_2" Type="INT" Comment="retval see description"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_BackgroundColour_1" Type="isobus::UT::Q::Q_BackgroundColour" x="1000" y="500">
		</FB>
		<FB Name="Q_BackgroundColour_2" Type="isobus::UT::Q::Q_BackgroundColourAux" x="1000" y="1300">
		</FB>
		<FB Name="F_SEL_I" Type="iec61131::selection::F_SEL" x="-1000" y="1000">
			<Parameter Name="IN0" Value="colours::COLOR_RED"/>
			<Parameter Name="IN1" Value="colours::COLOR_GREEN"/>
		</FB>
		<EventConnections>
			<Connection Source="REQ" Destination="F_SEL_I.REQ" dx1="473.33"/>
			<Connection Source="Q_BackgroundColour_1.CNF" Destination="CNF_1" dx1="1160"/>
			<Connection Source="Q_BackgroundColour_2.CNF" Destination="CNF_2" dx1="1053.33"/>
			<Connection Source="F_SEL_I.CNF" Destination="Q_BackgroundColour_1.REQ" dx1="660"/>
			<Connection Source="F_SEL_I.CNF" Destination="Q_BackgroundColour_2.REQ" dx1="726.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DI1" Destination="F_SEL_I.G" dx1="1920"/>
			<Connection Source="u16ObjIdA" Destination="Q_BackgroundColour_1.u16ObjId" dx1="5126.67"/>
			<Connection Source="Q_BackgroundColour_1.s16result" Destination="result_1" dx1="1293.33"/>
			<Connection Source="Q_BackgroundColour_1.u8OldColour" Destination="u8OldColour_1" dx1="1260"/>
			<Connection Source="Q_BackgroundColour_1.STATUS" Destination="STATUS_1" dx1="1226.67"/>
			<Connection Source="F_SEL_I.OUT" Destination="Q_BackgroundColour_1.u8Colour" dx1="760"/>
			<Connection Source="u16ObjIdA" Destination="Q_BackgroundColour_2.u16ObjId" dx1="5126.67"/>
			<Connection Source="Q_BackgroundColour_2.s16result" Destination="result_2" dx1="1253.33"/>
			<Connection Source="Q_BackgroundColour_2.u8OldColour" Destination="u8OldColour_2" dx1="1220"/>
			<Connection Source="Q_BackgroundColour_2.STATUS" Destination="STATUS_2" dx1="1186.67"/>
			<Connection Source="F_SEL_I.OUT" Destination="Q_BackgroundColour_2.u8Colour" dx1="660"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
