<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012a_sub" Comment="Numeric Value Input und Speichern" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-31">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="REQ" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="KEY" Type="STRING"/>
			<VarDeclaration Name="u16ObjId" Type="UINT"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="VALUEO" Type="UDINT"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="ID" Type="ID" x="-666.67" y="20">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT" Type="F_DWORD_TO_UDINT" x="400" y="473.33">
		</FB>
		<FB Name="NVS" Type="NVS" x="2133.33" y="20">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#0"/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" x="3866.67" y="133.33">
		</FB>
		<EventConnections>
			<Connection Source="ID.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="300"/>
			<Connection Source="REQ" Destination="Q_NumericValue.REQ" dx1="1600">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="NVS.SET" dx1="380"/>
			<Connection Source="NVS.SETO" Destination="IND" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="NVS.GETO" Destination="Q_NumericValue.REQ" dx1="546.67"/>
			<Connection Source="NVS.GETO" Destination="IND" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="ID.IN" Destination="F_DWORD_TO_UDINT.IN" dx1="186.67"/>
			<Connection Source="u16ObjId" Destination="Q_NumericValue.u16ObjId" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="KEY" Destination="NVS.KEY" dx1="2066.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="NVS.VALUE" dx1="346.67"/>
			<Connection Source="NVS.VALUEO" Destination="Q_NumericValue.u32NewValue" dx1="313.33"/>
			<Connection Source="NVS.VALUEO" Destination="VALUEO" dx1="2933.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
