<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012a" Comment="Numeric Value Input und Speichern">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="CbVtStatus" Type="CbVtStatus" Comment="" x="-5553.33" y="1593.33">
		</FB>
		<SubApp Name="Uebung_012a_sub" Type="Uebung_012a_sub" Comment="" x="-3173.34" y="1586.67">
			<Parameter Name="KEY" Value="KEY_I1_STORE" Comment=""/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1" Comment=""/>
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="CbVtStatus.INIT" Comment="" dx1="326.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Uebung_012a_sub.INIT" Comment="" dx1="1466.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CbVtStatus.IND" Destination="Uebung_012a_sub.REQ" Comment=""/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
