<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012a" Comment="Numeric Value Input und Speichern" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="CbVtStatus" Type="CbVtStatus" x="-5553.33" y="1593.33">
		</FB>
		<SubApp Name="Uebung_012a_sub" Type="Uebung_012a_sub" x="-3173.34" y="1586.67">
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</SubApp>
		<EventConnections>
			<Connection Source="CbVtStatus.IND" Destination="Uebung_012a_sub.REQ"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
