<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_083" Comment="Beispiel für E_CTUD_UDINT">
	<Identification Standard="61499-2" Description="Beispiel für E_CTD&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 94" >
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-7400" y="-100">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" Comment="" x="-10800" y="-900">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_CTUD_UDINT" Type="E_CTUD_UDINT" Comment="" x="-9000" y="0">
			<Parameter Name="PV" Value="UINT#5" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" Comment="" x="-10800" y="-100">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I3_CLK" Type="IE" Comment="" x="-10800" y="700">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalInput_I4_CLK" Type="IE" Comment="" x="-10800" y="1500">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" Comment="" x="-7400" y="800">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" Comment="" x="-7400" y="2100">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1_CLK.INIT" Comment="" dx1="2166.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" Comment="" dx1="3626.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_CTUD_UDINT.CU" Comment="" dx1="413.33" dx2="413.33" dy="0"/>
			<Connection Source="E_CTUD_UDINT.CO" Destination="DigitalOutput_Q1.REQ" Comment=""/>
			<Connection Source="E_CTUD_UDINT.LDO" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="393.33" dx2="393.33" dy="0"/>
			<Connection Source="INIT" Destination="DigitalInput_I2_CLK.INIT" Comment="" dx1="2086.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_CTUD_UDINT.CD" Comment=""/>
			<Connection Source="E_CTUD_UDINT.RO" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="393.33" dx2="393.33" dy="0"/>
			<Connection Source="INIT" Destination="DigitalInput_I3_CLK.INIT" Comment="" dx1="3013.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I3_CLK.IND" Destination="E_CTUD_UDINT.R" Comment="" dx1="260" dx2="260" dy="0"/>
			<Connection Source="INIT" Destination="DigitalInput_I4_CLK.INIT" Comment="" dx1="3013.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I4_CLK.IND" Destination="E_CTUD_UDINT.LD" Comment="" dx1="400" dx2="400" dy="0"/>
			<Connection Source="E_CTUD_UDINT.LDO" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="393.33" dx2="393.33" dy="0"/>
			<Connection Source="INIT" Destination="DigitalOutput_Q2.INIT" Comment="" dx1="3313.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_CTUD_UDINT.CO" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="393.33" dx2="393.33" dy="0"/>
			<Connection Source="E_CTUD_UDINT.RO" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="393.33" dx2="393.33" dy="0"/>
			<Connection Source="INIT" Destination="Q_NumericValue.INIT" Comment="" dx1="4666.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_CTUD_UDINT.CO" Destination="Q_NumericValue.REQ" Comment="" dx1="380"/>
			<Connection Source="E_CTUD_UDINT.RO" Destination="Q_NumericValue.REQ" Comment="" dx1="380"/>
			<Connection Source="E_CTUD_UDINT.LDO" Destination="Q_NumericValue.REQ" Comment="" dx1="380"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTUD_UDINT.QU" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="280" dx2="280" dy="0"/>
			<Connection Source="E_CTUD_UDINT.QD" Destination="DigitalOutput_Q2.OUT" Comment="" dx1="313.33" dx2="313.33" dy="0"/>
			<Connection Source="E_CTUD_UDINT.CV" Destination="Q_NumericValue.u32NewValue" Comment="" dx1="126.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
