<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_085" Comment="Beispiel für E_D_FF" >
	<Identification Standard="61499-2" Description="Beispiel für E_CTD&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 93" >
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-4900" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" x="-8000" y="100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" x="-8100" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_D_FF" Type="E_D_FF" x="-6400" y="-600">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" dx1="1746.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalOutput_Q1.INIT" dx1="3626.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="DigitalInput_I2_CLK.INIT" dx1="2086.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_D_FF.CLK"/>
			<Connection Source="E_D_FF.EO" Destination="DigitalOutput_Q1.REQ" dx1="486.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="E_D_FF.D" dx1="406.67"/>
			<Connection Source="E_D_FF.Q" Destination="DigitalOutput_Q1.OUT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
