<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_034" Comment="Analog-Eingang auf PWM Ausgang" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0" >
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_AI" Type="logiBUS_8_AI" x="-3600" y="533.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>

			<Parameter Name="AnalogInput_I1" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I1_hysteresis" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I2" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I2_hysteresis" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I3" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I3_hysteresis" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I4" Value="'App.Control.functions.AnalogInput_I4'"/>
			<Parameter Name="AnalogInput_I4_hysteresis" Value="50"/>
			<Parameter Name="AnalogInput_I5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I5_hysteresis" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I6_hysteresis" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I7" Value="'App.Control.functions.AnalogInput_I7'"/>
			<Parameter Name="AnalogInput_I7_hysteresis" Value="50"/>
			<Parameter Name="AnalogInput_I8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I8_hysteresis" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_8_PWM" Type="logiBUS_8_PWM" x="-3466.67" y="-666.67">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>

			<Parameter Name="PWMOutput_Q1" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PWMOutput_Q2" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PWMOutput_Q3" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PWMOutput_Q4" Value="'App.Control.functions.PWMOutput_Q4'"/>
			<Parameter Name="PWMOutput_Q5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PWMOutput_Q6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PWMOutput_Q7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PWMOutput_Q8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
	</SubAppNetwork>
</SubAppType>
