<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_034" Comment="Analog-Eingang auf PWM Ausgang" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_AI" Type="Hutschienenmoped_XL_8_AI" x="-3600" y="533.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="GLOBAL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="ID_NULL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I1" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I1_hysteresis" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I2" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I2_hysteresis" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I3" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I3_hysteresis" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I4" Value="'Ventilsteuerung.functions.AnalogInput_I4'"/>
			<Parameter Name="AnalogInput_I4_hysteresis" Value="50"/>
			<Parameter Name="AnalogInput_I5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I5_hysteresis" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I6_hysteresis" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I7" Value="'Ventilsteuerung.functions.AnalogInput_I7'"/>
			<Parameter Name="AnalogInput_I7_hysteresis" Value="50"/>
			<Parameter Name="AnalogInput_I8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="AnalogInput_I8_hysteresis" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_8_PWM" Type="Hutschienenmoped_XL_8_PWM" x="-3466.67" y="-666.67">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="GLOBAL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="ID_NULL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PWMOutput_Q1" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PWMOutput_Q2" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PWMOutput_Q3" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PWMOutput_Q4" Value="'Ventilsteuerung.functions.PWMOutput_Q4'"/>
			<Parameter Name="PWMOutput_Q5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PWMOutput_Q6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PWMOutput_Q7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PWMOutput_Q8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
	</SubAppNetwork>
</SubAppType>
