<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_034" Comment="Analog-Eingang auf PWM Ausgang" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AnalogInput_I7" Type="ID" x="-2533.33" y="1066.67">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_DWORD_TO_UDINT_I7" Type="F_DWORD_TO_UDINT" x="1360" y="2386.66">
		</FB>
		<FB Name="PWMOutput_Q4" Type="QD" x="1733.33" y="1066.67">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_SHL" Type="F_SHL" x="-1246.67" y="1700">
			<Parameter Name="N" Value="UINT#1"/>
		</FB>
		<EventConnections>
			<Connection Source="AnalogInput_I7.INITO" Destination="PWMOutput_Q4.INIT"/>
			<Connection Source="AnalogInput_I7.IND" Destination="F_SHL.REQ" dx1="166.67"/>
			<Connection Source="F_SHL.CNF" Destination="F_DWORD_TO_UDINT_I7.REQ" dx1="1040"/>
			<Connection Source="F_SHL.CNF" Destination="PWMOutput_Q4.REQ" dx1="1233.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AnalogInput_I7.IN" Destination="F_SHL.IN" dx1="80"/>
			<Connection Source="F_SHL.OUT" Destination="PWMOutput_Q4.OUT" dx1="1400"/>
			<Connection Source="F_SHL.OUT" Destination="F_DWORD_TO_UDINT_I7.IN" dx1="1213.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
