<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_034" Comment="Analog-Eingang auf PWM Ausgang">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AnalogInput_I7" Type="ID" Comment="" x="-2533.33" y="1066.67">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_DWORD_TO_UDINT_I7" Type="F_DWORD_TO_UDINT" Comment="" x="1360" y="2386.66">
		</FB>
		<FB Name="PWMOutput_Q4" Type="QD" Comment="" x="1733.33" y="1066.67">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_SHL" Type="F_SHL" Comment="" x="-1246.67" y="1700">
			<Parameter Name="N" Value="UINT#1" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="AnalogInput_I7.INIT" Comment="" dx1="1446.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="AnalogInput_I7.INITO" Destination="PWMOutput_Q4.INIT" Comment=""/>
			<Connection Source="AnalogInput_I7.IND" Destination="F_SHL.REQ" Comment="" dx1="166.67" dx2="166.67" dy="0"/>
			<Connection Source="F_SHL.CNF" Destination="F_DWORD_TO_UDINT_I7.REQ" Comment="" dx1="1040" dx2="1040" dy="0"/>
			<Connection Source="F_SHL.CNF" Destination="PWMOutput_Q4.REQ" Comment="" dx1="1233.33" dx2="1233.33" dy="0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AnalogInput_I7.IN" Destination="F_SHL.IN" Comment="" dx1="80" dx2="80" dy="0"/>
			<Connection Source="F_SHL.OUT" Destination="PWMOutput_Q4.OUT" Comment="" dx1="1400" dx2="1400" dy="0"/>
			<Connection Source="F_SHL.OUT" Destination="F_DWORD_TO_UDINT_I7.IN" Comment="" dx1="1213.33" dx2="1213.33" dy="0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
