<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_003" Comment="DigitalInput_I1/_I2 auf DigitalOutput_Q1/_I2" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-1473.33" y="-793.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" x="-4533.33" y="-906.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" x="-1473.33" y="226.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="IX" x="-4533.33" y="113.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.INITO" Destination="DigitalOutput_Q1.INIT" dx1="1200"/>
			<Connection Source="DigitalInput_I1.IND" Destination="DigitalOutput_Q1.REQ" dx1="1193.33"/>
			<Connection Source="DigitalInput_I2.IND" Destination="DigitalOutput_Q2.REQ" dx1="1193.33"/>
			<Connection Source="DigitalInput_I2.INITO" Destination="DigitalOutput_Q2.INIT" dx1="1200"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT" dx1="1193.33"/>
			<Connection Source="DigitalInput_I2.IN" Destination="DigitalOutput_Q2.OUT" dx1="1193.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
