<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_101" Comment="DigitalInput_I1 auf DigitalOutput_Q1, mit Plug and Socket" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="IXA" x="-4533.33" y="-933.33">
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QXA" x="-1466.67" y="-933.33">
		</FB>
		<FB Name="AX_X_TO_BOOL" Type="AX_X_TO_BOOL" x="-4000" y="0">
		</FB>
		<FB Name="AX_BOOL_TO_X" Type="AX_BOOL_TO_X" x="-2133.33" y="0">
		</FB>
		<EventConnections>
			<Connection Source="AX_X_TO_BOOL.IND" Destination="AX_BOOL_TO_X.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AX_X_TO_BOOL.IN" Destination="AX_BOOL_TO_X.OUT"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_X_TO_BOOL.AX_IN" dx1="80" dx2="80" dy="513.33"/>
			<Connection Source="AX_BOOL_TO_X.AX_OUT" Destination="DigitalOutput_Q1.OUT" dx1="80" dx2="80" dy="-513.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
