<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_033_VV_FORTE_PC_B" Comment="LED Strip Blinkende LED" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_1_LED_YELLOW" Type="Hutschienenmoped_XL_1_LED_strip" x="-3866.67" y="0">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_YELLOW"/>
			<Parameter Name="LED_5HZ" Value="'App_functions.LED_YELLOW_5HZ'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_GREEN" Type="Hutschienenmoped_XL_1_LED_strip" x="-3866.67" y="-800">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_GREEN"/>
			<Parameter Name="LED_5HZ" Value="'App_functions.LED_GREEN_5HZ'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_RED" Type="Hutschienenmoped_XL_1_LED_strip" x="-3866.67" y="800">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_RED"/>
			<Parameter Name="LED_5HZ" Value="'App_functions.LED_RED_5HZ'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_BLUE" Type="Hutschienenmoped_XL_1_LED_strip" x="-3866.67" y="1600">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_BLUE"/>
			<Parameter Name="LED_5HZ" Value="'App_functions.LED_BLUE_5HZ'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
	</SubAppNetwork>
</SubAppType>
