<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_033_VV_FORTE_PC_B" Comment="LED Strip Blinkende LED" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 HR Agrartechnik GmbH  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0" >
	</Identification>
	<VersionInfo Organization="HR Agrartechnik GmbH" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_1_LED_YELLOW" Type="logiBUS_1_LED_strip" x="-3866.67" y="0">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="LED_strip::Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_COLOURS::LED_YELLOW"/>
			<Parameter Name="LED_5HZ" Value="'App_functions.LED_YELLOW_5HZ'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_GREEN" Type="logiBUS_1_LED_strip" x="-3866.67" y="-800">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="LED_strip::Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_COLOURS::LED_GREEN"/>
			<Parameter Name="LED_5HZ" Value="'App_functions.LED_GREEN_5HZ'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_RED" Type="logiBUS_1_LED_strip" x="-3866.67" y="800">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="LED_strip::Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_COLOURS::LED_RED"/>
			<Parameter Name="LED_5HZ" Value="'App_functions.LED_RED_5HZ'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_BLUE" Type="logiBUS_1_LED_strip" x="-3866.67" y="1600">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="LED_strip::Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_COLOURS::LED_BLUE"/>
			<Parameter Name="LED_5HZ" Value="'App_functions.LED_BLUE_5HZ'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
	</SubAppNetwork>
</SubAppType>
