<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_028" Comment="Analog-Eingang" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-1246.67" y="-113.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" x="-4193.33" y="-113.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="AnalogInput_I4" Type="ID" x="-1193.33" y="1066.67">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="AnalogInput_I7" Type="ID" x="-1193.33" y="2400">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_DWORD_TO_UDINT_I7" Type="F_DWORD_TO_UDINT" x="533.33" y="2853.33">
		</FB>
		<FB Name="F_DWORD_TO_UDINT_I4" Type="F_DWORD_TO_UDINT" x="533.33" y="1520">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="DigitalOutput_Q1.REQ" dx1="1273.33"/>
			<Connection Source="DigitalInput_I1.INITO" Destination="DigitalOutput_Q1.INIT"/>
			<Connection Source="AnalogInput_I7.IND" Destination="F_DWORD_TO_UDINT_I7.REQ" dx1="960"/>
			<Connection Source="AnalogInput_I4.IND" Destination="F_DWORD_TO_UDINT_I4.REQ" dx1="960"/>
			<Connection Source="DigitalInput_I1.IND" Destination="AnalogInput_I4.REQ" dx1="1213.33"/>
			<Connection Source="DigitalInput_I1.IND" Destination="AnalogInput_I7.REQ" dx1="1213.33"/>
			<Connection Source="AnalogInput_I7.CNF" Destination="F_DWORD_TO_UDINT_I7.REQ" dx1="960"/>
			<Connection Source="AnalogInput_I4.CNF" Destination="F_DWORD_TO_UDINT_I4.REQ" dx1="960"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT" dx1="1273.33"/>
			<Connection Source="AnalogInput_I7.IN" Destination="F_DWORD_TO_UDINT_I7.IN" dx1="553.33"/>
			<Connection Source="AnalogInput_I4.IN" Destination="F_DWORD_TO_UDINT_I4.IN" dx1="553.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
