<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_028" Comment="Analog-Eingang">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="-1246.67" y="-113.33">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" Comment="" x="-4193.33" y="-113.33">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="AnalogInput_I4" Type="ID" Comment="" x="-1193.33" y="1066.67">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="AnalogInput_I7" Type="ID" Comment="" x="-1193.33" y="2400">
			<Parameter Name="QI" Value="TRUE" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="" Comment="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="F_DWORD_TO_UDINT_I7" Type="F_DWORD_TO_UDINT" Comment="" x="533.33" y="2853.33">
		</FB>
		<FB Name="F_DWORD_TO_UDINT_I4" Type="F_DWORD_TO_UDINT" Comment="" x="533.33" y="1520">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="1273.33"/>
			<Connection Source="DigitalInput_I1.INITO" Destination="DigitalOutput_Q1.INIT" Comment=""/>
			<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="1180">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="AnalogInput_I4.INIT" Comment="" dx1="2740">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="AnalogInput_I7.INIT" Comment="" dx1="2733.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="AnalogInput_I7.IND" Destination="F_DWORD_TO_UDINT_I7.REQ" Comment="" dx1="960"/>
			<Connection Source="AnalogInput_I4.IND" Destination="F_DWORD_TO_UDINT_I4.REQ" Comment="" dx1="960"/>
			<Connection Source="DigitalInput_I1.IND" Destination="AnalogInput_I4.REQ" Comment="" dx1="1213.33"/>
			<Connection Source="DigitalInput_I1.IND" Destination="AnalogInput_I7.REQ" Comment="" dx1="1213.33"/>
			<Connection Source="AnalogInput_I7.CNF" Destination="F_DWORD_TO_UDINT_I7.REQ" Comment="" dx1="960"/>
			<Connection Source="AnalogInput_I4.CNF" Destination="F_DWORD_TO_UDINT_I4.REQ" Comment="" dx1="960"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="1273.33"/>
			<Connection Source="AnalogInput_I7.IN" Destination="F_DWORD_TO_UDINT_I7.IN" Comment=""/>
			<Connection Source="AnalogInput_I4.IN" Destination="F_DWORD_TO_UDINT_I4.IN" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
