<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020g" Comment="DigitalInput_I1 auf DigitalOutput_Q1; E_TONOF; Ein-/Ausschaltverzögert" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-5860" y="460">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="IX" x="-8706.67" y="346.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_TONOF" Type="E_TONOF" x="-7193.33" y="573.33">
			<Parameter Name="PT_ON" Value="T#5S"/>
			<Parameter Name="PT_OFF" Value="T#5S"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="E_TONOF.REQ" dx1="413.33"/>
			<Connection Source="E_TONOF.CNF" Destination="DigitalOutput_Q1.REQ" dx1="373.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="E_TONOF.IN" dx1="80"/>
			<Connection Source="E_TONOF.Q" Destination="DigitalOutput_Q1.OUT" dx1="73.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
