<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_052_AX" Comment="DigitalInput_I1-_I4 auf DigitalOutput_Q1-_Q4, mit Plug and Socket">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-09" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-8600" y="-1300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-8600" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="DigitalInput_I3" Type="logiBUS::io::DI::logiBUS_IXA" x="-8600" y="900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QXA" x="4000" y="2300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I4" Type="logiBUS::io::DI::logiBUS_IXA" x="-8600" y="2300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
		</FB>
		<FB Name="GET_STRUCT_VALUE" Type="eclipse4diac::convert::GET_STRUCT_VALUE" x="1500" y="2400">
			<Parameter Name="member" Value="'X_00'"/>
		</FB>
		<FB Name="STRUCT_MUX" Type="eclipse4diac::convert::STRUCT_MUX" x="-1000" y="2300">
			<Attribute Name="StructuredType" Type="STRING" Value="logiBUS::utils::conversion::types::ST04X"/>
		</FB>
		<FB Name="AX_X_TO_BOOL_1" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-6800" y="-1300">
		</FB>
		<FB Name="AX_X_TO_BOOL_2" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-6800" y="-200">
		</FB>
		<FB Name="AX_X_TO_BOOL_3" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-6800" y="900">
		</FB>
		<FB Name="AX_X_TO_BOOL_4" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-6800" y="2300">
		</FB>
		<FB Name="AX_BOOL_TO_X" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="2900" y="2400">
		</FB>
		<EventConnections>
			<Connection Source="GET_STRUCT_VALUE.CNF" Destination="AX_BOOL_TO_X.REQ"/>
			<Connection Source="AX_X_TO_BOOL_1.CNF" Destination="STRUCT_MUX.REQ" dx1="1073.33"/>
			<Connection Source="AX_X_TO_BOOL_2.CNF" Destination="STRUCT_MUX.REQ" dx1="1073.33"/>
			<Connection Source="AX_X_TO_BOOL_3.CNF" Destination="STRUCT_MUX.REQ" dx1="1073.33"/>
			<Connection Source="AX_X_TO_BOOL_4.CNF" Destination="STRUCT_MUX.REQ" dx1="1073.33"/>
			<Connection Source="STRUCT_MUX.CNF" Destination="GET_STRUCT_VALUE.REQ" dx1="426.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="GET_STRUCT_VALUE.output" Destination="AX_BOOL_TO_X.OUT" dx1="433.33"/>
			<Connection Source="AX_X_TO_BOOL_1.IN" Destination="STRUCT_MUX.X_00" dx1="713.33"/>
			<Connection Source="AX_X_TO_BOOL_2.IN" Destination="STRUCT_MUX.X_01" dx1="520"/>
			<Connection Source="AX_X_TO_BOOL_3.IN" Destination="STRUCT_MUX.X_02" dx1="286.67"/>
			<Connection Source="AX_X_TO_BOOL_4.IN" Destination="STRUCT_MUX.X_03" dx1="573.33"/>
			<Connection Source="STRUCT_MUX.OUT" Destination="GET_STRUCT_VALUE.in_struct" dx1="73.33"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_X_TO_BOOL_1.AX_IN"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AX_X_TO_BOOL_2.AX_IN"/>
			<Connection Source="DigitalInput_I3.IN" Destination="AX_X_TO_BOOL_3.AX_IN"/>
			<Connection Source="DigitalInput_I4.IN" Destination="AX_X_TO_BOOL_4.AX_IN"/>
			<Connection Source="AX_BOOL_TO_X.AX_OUT" Destination="DigitalOutput_Q4.OUT" dx1="700"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
