<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_249b_AX" Comment="Asynchrone Objektattribut-Abfrage mittels gebündelter SubApp I_GetAttribute_IDA (Kommando + asynchroner Empfang in einem Baustein) bei Tasterdruck (Input_I1) und Anzeige auf OutputNumber_N1">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-15" Remarks="Initial implementation of Uebung_249b_AX using I_GetAttribute_IDA SubApp">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::InputNumber_I1"/>
		<Import declaration="isobus::UT::Q::const::AID::AID_IN::VALUE"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::OutputNumber_N1_N"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-5700" y="1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<SubApp Name="I_GetAttribute_IDA_I1" Type="MyLib::sys::I_GetAttribute_IDA" x="-3700" y="1200">
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
			<Parameter Name="u8AID" Value="VALUE"/>
		</SubApp>
		<FB Name="AD_TO_AR_NUM" Type="adapter::conversion::unidirectional::AD_TO_AR_NUM" x="-1900" y="1400">
		</FB>
		<FB Name="OutputNumber_N1" Type="isobus::UT::Q::Q_NumericValue_PHYSA" x="-200" y="800">
			<Parameter Name="stObj" Value="OutputNumber_N1_N"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="I_GetAttribute_IDA_I1.REQ" dx1="600"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="I_GetAttribute_IDA_I1.IN" Destination="AD_TO_AR_NUM.AD_IN" dx1="593.33"/>
			<Connection Source="AD_TO_AR_NUM.AR_OUT" Destination="OutputNumber_N1.rPhys" dx1="600"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
