<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_170_AX" Comment="Exercise for AX_D_FF">
	<Identification Standard="61499-2" Description="Copyright (c) 2025 Meisterschulen am Ostbahnhof     This program and the accompanying materials are made   available under the terms of the Eclipse Public License 2.0   which is available at https://www.eclipse.org/legal/epl-2.0/     SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2025-02-01">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AX_D_FF_1" Type="adapter::events::unidirectional::AX_D_FF" x="-1700" y="0">
		</FB>
	</SubAppNetwork>
</SubAppType>
