<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_076c_AUI" Comment="MSS mit Compound Scaling + AR_Timeout_Zero auf UT ausgeben (Adapter Version)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-17" Remarks="MSS mit Compound Scaling und AR_Timeout_Zero SubApp (Adapter Version, analog Krauternter TECU_MSS.SUB)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::TECU::DefaultPool_TECU_Numeric::NumberVariable_Wheel_based_machine_speed_N"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="IA_MSS" Type="isobus::tecu::IA_MSS" x="-2100" y="900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="COMPOUND_SCALE" Type="logiBUS::signalprocessing::fieldbus::AUI_FIELDBUS_UINT_TO_SIGNAL_COMPOUND_SCALE" x="100" y="800">
			<Parameter Name="SCALE_HIGH" Value="REAL#0.256"/>
			<Parameter Name="SCALE_LOW" Value="REAL#0.001"/>
			<Parameter Name="OFFSET" Value="DINT#0"/>
		</FB>
		<SubApp Name="TZ_MSS" Type="MyLib::sys::AR_Timeout_Zero" x="2700" y="800">
		</SubApp>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue_PHYSA" x="5500" y="800">
			<Parameter Name="stObj" Value="NumberVariable_Wheel_based_machine_speed_N"/>
		</FB>
		<AdapterConnections>
			<Connection Source="IA_MSS.SPEED" Destination="COMPOUND_SCALE.IN" dx1="600"/>
			<Connection Source="COMPOUND_SCALE.OUT" Destination="TZ_MSS.IN0" dx1="173.33"/>
			<Connection Source="IA_MSS.TIMEOUT" Destination="TZ_MSS.G" dx1="286.67"/>
			<Connection Source="TZ_MSS.OUT" Destination="Q_NumericValue.rPhys" dx1="600"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
