<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_046_AX" Comment="Ablaufsteuerung 8-Kanal ENDLOS (Event &amp; Zeit) (Adapter Version)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10;  &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10;  &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-07-05" Remarks="generated solution">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q5"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q6"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q7"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q8"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="-2400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="-1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q3"/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="DigitalOutput_Q5" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="1600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q5"/>
		</FB>
		<FB Name="DigitalOutput_Q6" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="2600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q6"/>
		</FB>
		<FB Name="DigitalOutput_Q7" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="3600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q7"/>
		</FB>
		<FB Name="DigitalOutput_Q8" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="4600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q8"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-12000" y="-2400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I4" Type="logiBUS::io::DI::logiBUS_IE" x="-12000" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_TimeOut" Type="iec61499::events::E_TimeOut" x="-9200" y="2400">
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="-2666.67" y="-2000">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<FB Name="AS_TO_AUDI" Type="adapter::conversion::unidirectional::AS_TO_AUDI" x="-4906.67" y="-1820">
		</FB>
		<FB Name="sequence_block" Type="logiBUS::utils::sequence::combi::sequence_ET_08_loop_AX" x="-9700" y="-1100">
			<Parameter Name="DT_S1_S2" Value="T#1s"/>
			<Parameter Name="DT_S2_S3" Value="T#1s"/>
			<Parameter Name="DT_S3_S4" Value="T#1s"/>
			<Parameter Name="DT_S4_S5" Value="T#1s"/>
			<Parameter Name="DT_S5_S6" Value="T#1s"/>
			<Parameter Name="DT_S6_S7" Value="T#1s"/>
			<Parameter Name="DT_S7_S8" Value="T#1s"/>
			<Parameter Name="DT_S8_S1" Value="T#1s"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="sequence_block.START_S1" dx1="686.67"/>
			<Connection Source="DigitalInput_CLK_I4.IND" Destination="sequence_block.RESET" dx1="686.67"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="sequence_block.STATE_NR" Destination="AS_TO_AUDI.AS_IN" dx1="780" dx2="460" dy="-3553.33"/>
			<Connection Source="AS_TO_AUDI.AUDI_OUT" Destination="Q_NumericValue.u32NewValue" dx1="700"/>
			<Connection Source="sequence_block.DO_S1" Destination="DigitalOutput_Q1.OUT" dx1="813.33"/>
			<Connection Source="sequence_block.DO_S2" Destination="DigitalOutput_Q2.OUT" dx1="846.67"/>
			<Connection Source="sequence_block.DO_S3" Destination="DigitalOutput_Q3.OUT" dx1="880"/>
			<Connection Source="sequence_block.DO_S4" Destination="DigitalOutput_Q4.OUT" dx1="913.33"/>
			<Connection Source="sequence_block.DO_S5" Destination="DigitalOutput_Q5.OUT" dx1="893.33"/>
			<Connection Source="sequence_block.DO_S6" Destination="DigitalOutput_Q6.OUT" dx1="860"/>
			<Connection Source="sequence_block.DO_S7" Destination="DigitalOutput_Q7.OUT" dx1="826.67"/>
			<Connection Source="sequence_block.DO_S8" Destination="DigitalOutput_Q8.OUT" dx1="793.33"/>
			<Connection Source="sequence_block.timeOut" Destination="E_TimeOut.TimeOutSocket" dx1="66.67" dx2="66.67" dy="220"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
