<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_153_AX" Comment="Impulszähler &amp; PID Regler, mit Plug and Socket">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-10" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::PI::logiBUS_PI::PulseInput_I8"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="logiBUS_PI_IDA" Type="logiBUS::io::PI::logiBUS_PI_IDA" x="-5200" y="400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="PulseInput_I8"/>
			<Parameter Name="ImpulseDelta" Value="100"/>
			<Parameter Name="TimeDelta" Value="50000"/>
			<Parameter Name="TimeRateLimit" Value="10000"/>
		</FB>
		<FB Name="AD_D_TO_DWORD" Type="adapter::conversion::unidirectional::AD_D_TO_DWORD" x="-3800" y="600">
		</FB>
		<FB Name="FT_DERIV" Type="OSCAT::Basic::POUs::Engineering::Control::FT_DERIV_10" x="500" y="-1600">
			<Parameter Name="K" Value="9"/>
			<Parameter Name="Faktor" Value="1.0"/>
			<Parameter Name="run" Value="TRUE"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="-2600" y="700">
		</FB>
		<FB Name="F_UDINT_TO_REAL" Type="iec61131::conversion::F_UDINT_TO_REAL" x="-1300" y="700">
		</FB>
		<FB Name="PWMOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QDA_PWM" x="7300" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="CTRL_PID" Type="OSCAT::Basic::POUs::Engineering::Control::CTRL_PID" x="2600" y="1300">
			<Parameter Name="SET" Value="16.0"/>
			<Parameter Name="SUP" Value="0.0"/>
			<Parameter Name="OFS" Value="0.0"/>
			<Parameter Name="M_I" Value="8184.0"/>
			<Parameter Name="KP" Value="10.0"/>
			<Parameter Name="TN" Value="1.0"/>
			<Parameter Name="TV" Value="1.0"/>
			<Parameter Name="LL" Value="0.0"/>
			<Parameter Name="LH" Value="8184.0"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-4800" y="1800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="AX_T_FF" Type="adapter::events::unidirectional::AX_T_FF" x="-2300" y="1900">
		</FB>
		<FB Name="AX_X_TO_BOOL" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-1000" y="1900">
		</FB>
		<FB Name="F_LREAL_TO_UDINT" Type="iec61131::conversion::F_LREAL_TO_UDINT" x="3900" y="1300">
		</FB>
		<FB Name="AUDI_UDINT_TO_UDI" Type="adapter::conversion::unidirectional::AUDI_UDINT_TO_UDI" x="5100" y="1300">
		</FB>
		<FB Name="AUDI_TO_AD" Type="adapter::conversion::unidirectional::AUDI_TO_AD" x="6200" y="1300">
		</FB>
		<FB Name="E_CYCLE" Type="iec61499::events::E_CYCLE" x="-6500" y="500">
			<Parameter Name="DT" Value="T#200ms"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-8400" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_I3" Type="logiBUS::io::DI::logiBUS_IE" x="-8400" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<EventConnections>
			<Connection Source="AD_D_TO_DWORD.CNF" Destination="F_DWORD_TO_UDINT.REQ" dx1="100"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="F_UDINT_TO_REAL.REQ"/>
			<Connection Source="F_UDINT_TO_REAL.CNF" Destination="FT_DERIV.REQ" dx1="160"/>
			<Connection Source="FT_DERIV.CNF" Destination="CTRL_PID.REQ" dx1="1220"/>
			<Connection Source="DigitalInput_I1.IND" Destination="AX_T_FF.CLK" dx1="806.67"/>
			<Connection Source="AX_X_TO_BOOL.CNF" Destination="CTRL_PID.REQ" dx1="280"/>
			<Connection Source="CTRL_PID.CNF" Destination="F_LREAL_TO_UDINT.REQ"/>
			<Connection Source="F_LREAL_TO_UDINT.CNF" Destination="AUDI_UDINT_TO_UDI.REQ"/>
			<Connection Source="DigitalInput_I2.IND" Destination="E_CYCLE.START" dx1="533.33"/>
			<Connection Source="DigitalInput_I3.IND" Destination="E_CYCLE.STOP" dx1="360"/>
			<Connection Source="E_CYCLE.EO" Destination="logiBUS_PI_IDA.REQ" dx1="593.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AD_D_TO_DWORD.IN" Destination="F_DWORD_TO_UDINT.IN" dx1="100"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="F_UDINT_TO_REAL.IN"/>
			<Connection Source="F_UDINT_TO_REAL.OUT" Destination="FT_DERIV.in" dx1="353.33"/>
			<Connection Source="FT_DERIV.out" Destination="CTRL_PID.ACT" dx1="766.67"/>
			<Connection Source="AX_X_TO_BOOL.IN" Destination="CTRL_PID.MAN" dx1="2673.33"/>
			<Connection Source="CTRL_PID.Y" Destination="F_LREAL_TO_UDINT.IN" dx1="340"/>
			<Connection Source="F_LREAL_TO_UDINT.OUT" Destination="AUDI_UDINT_TO_UDI.OUT"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="logiBUS_PI_IDA.IN" Destination="AD_D_TO_DWORD.AD_IN" dx1="293.33"/>
			<Connection Source="AX_T_FF.Q" Destination="AX_X_TO_BOOL.AX_IN" dx1="393.33"/>
			<Connection Source="AUDI_UDINT_TO_UDI.AUDI_OUT" Destination="AUDI_TO_AD.AUDI_IN"/>
			<Connection Source="AUDI_TO_AD.AD_OUT" Destination="PWMOutput_Q1.OUT"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
