<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_019_AX" Comment="Umschalten einer Maske">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-09" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::DataMask_M1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::DataMask_M2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-8100" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-8100" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<SubApp Name="Select_2_AUI" Type="MyLib::sys::AUI_AUI_MUX_2_VAL" x="-4800" y="-200">
			<Parameter Name="val1" Value="DataMask_M1"/>
			<Parameter Name="val2" Value="DataMask_M2"/>
		</SubApp>
		<FB Name="Q_ActiveMask" Type="isobus::UT::Q::Q_ActiveMask_AUI" x="-2100" y="-300">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="Select_2_AUI.EI1" dx1="1206.67"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="Select_2_AUI.EI2" dx1="1253.33"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="Select_2_AUI.OUT" Destination="Q_ActiveMask.u16NewMaskId" dx1="600"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
