<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_034_AX" Comment="Analog-Eingang auf PWM Ausgang (Adapter Version)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-20" Remarks="initial API and implementation (Adapter Version of Uebung_034)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::AI::logiBUS_AI"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AnalogInput_I7" Type="logiBUS::io::AI::logiBUS_AI_IDA" x="-4000" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_AI::AnalogInput_I7"/>
			<Parameter Name="AnalogInput_hysteresis" Value="50"/>
		</FB>
		<FB Name="PWMOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QDA_PWM" x="4000" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="AD_SHL" Type="adapter::iec61131::bitwise::AD_SHL" x="300" y="1800">
			<Parameter Name="N" Value="UINT#1"/>
		</FB>
		<EventConnections>
			<Connection Source="AnalogInput_I7.INITO" Destination="PWMOutput_Q4.INIT" dx1="5000"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="AnalogInput_I7.IN" Destination="AD_SHL.IN" dx1="200"/>
			<Connection Source="AD_SHL.OUT" Destination="PWMOutput_Q4.OUT" dx1="1013.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
