<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_210b_AR" Comment="Standard IEC 61131-3 AI_FB_CTU (Adapter Version, Vorwärtszähler, INT) mit Terminal-Ausgabe (PHYS)">
	<Identification Standard="61131-3" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.2" Author="Franz Höpfinger" Date="2026-05-13" Remarks="Added AI_INT_TO_I init block connected to PV">
	</VersionInfo>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-04-21" Remarks="Added terminal output for counter value (PHYS)">
	</VersionInfo>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-21" Remarks="initial API and implementation (Adapter version)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::OutputNumber_N3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AI_FB_CTU" Type="adapter::iec61131::counters::AI_FB_CTU" x="0" y="0">
		</FB>
		<FB Name="AI_INT_TO_I" Type="adapter::conversion::unidirectional::AI_INT_TO_I" x="-1600" y="700">
			<Parameter Name="OUT" Value="INT#5"/>
		</FB>
		<FB Name="Input_CU" Type="logiBUS::io::DI::logiBUS_IXA" x="-2500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="Input_R" Type="logiBUS::io::DI::logiBUS_IXA" x="-3000" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="Output_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="2500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="AI_TO_AR" Type="adapter::conversion::unidirectional::AI_TO_AR" x="1100" y="1400">
		</FB>
		<FB Name="Q_NumericValue_1" Type="isobus::UT::Q::Q_NumericValue_PHYSA" x="2400" y="700">
			<Parameter Name="stObj" Value="OutputNumber_N3"/>
		</FB>
		<Comment Comment="hier sind negative Werte möglich ! " x="800" y="1800" width="1200" height="300"/>
		<Comment Comment="hier gegebenenfalls einen AX_D_FF einbauen, damit die Events reduziert werden. " x="1000" y="-700" width="1000" height="500"/>
		<EventConnections>
			<Connection Source="Input_R.INITO" Destination="AI_INT_TO_I.REQ"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="Input_CU.IN" Destination="AI_FB_CTU.CU" dx1="400"/>
			<Connection Source="Input_R.IN" Destination="AI_FB_CTU.R" dx1="200"/>
			<Connection Source="AI_FB_CTU.Q" Destination="Output_Q1.OUT" dx1="200"/>
			<Connection Source="AI_FB_CTU.CV" Destination="AI_TO_AR.AI_IN" dx1="173.33"/>
			<Connection Source="AI_TO_AR.AR_OUT" Destination="Q_NumericValue_1.rPhys" dx1="293.33"/>
			<Connection Source="AI_INT_TO_I.AI_OUT" Destination="AI_FB_CTU.PV" dx1="346.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
