<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_075a_AUI" Comment="FPTO Speed + SpeedSet auf UT ausgeben mit AR_Timeout_Zero (Adapter Version)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-17" Remarks="FPTO (Front PTO) Speed + SpeedSet mit PHYS Skalierung (0.125) und 2x AR_Timeout_Zero Fendt-Schaltung (Adapter Version, analog Krauternter TECU_FPTO.SUB)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::TECU::DefaultPool_TECU_Numeric::NumberVariable_Rear_PTO_output_shaft_speed_N"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="IA_FPTO" Type="isobus::tecu::IA_FPTO" x="-3400" y="100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Conv_Speed" Type="logiBUS::signalprocessing::fieldbus::AUI_FIELDBUS_UINT_TO_SIGNAL_SCALED" x="-1700" y="-300">
			<Parameter Name="SCALE" Value="0.125"/>
			<Parameter Name="OFFSET" Value="0"/>
		</FB>
		<SubApp Name="TZ_Speed" Type="MyLib::sys::AR_Timeout_Zero" x="900" y="300">
		</SubApp>
		<FB Name="Q_NumericValue_FPTO_Speed" Type="isobus::UT::Q::Q_NumericValue_PHYSA" x="4100" y="-600">
			<Parameter Name="stObj" Value="NumberVariable_Rear_PTO_output_shaft_speed_N"/>
		</FB>
		<FB Name="Conv_SpeedSet" Type="logiBUS::signalprocessing::fieldbus::AUI_FIELDBUS_UINT_TO_SIGNAL_SCALED" x="-1700" y="500">
			<Parameter Name="SCALE" Value="0.125"/>
			<Parameter Name="OFFSET" Value="0"/>
		</FB>
		<SubApp Name="TZ_SpeedSet" Type="MyLib::sys::AR_Timeout_Zero" x="900" y="800">
		</SubApp>
		<FB Name="Q_NumericValue_FPTO_SpeedSet" Type="isobus::UT::Q::Q_NumericValue_PHYSA" x="4100" y="400">
			<Parameter Name="stObj" Value="NumberVariable_Rear_PTO_output_shaft_speed_N"/>
		</FB>
		<FB Name="AX_SPLIT_2_Timeout" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-800" y="1500">
		</FB>
		<AdapterConnections>
			<Connection Source="IA_FPTO.TIMEOUT" Destination="AX_SPLIT_2_Timeout.IN" dx1="80"/>
			<Connection Source="IA_FPTO.SPEED" Destination="Conv_Speed.IN" dx1="600"/>
			<Connection Source="Conv_Speed.OUT" Destination="TZ_Speed.IN0" dx1="360"/>
			<Connection Source="AX_SPLIT_2_Timeout.OUT1" Destination="TZ_Speed.G" dx1="520"/>
			<Connection Source="TZ_Speed.OUT" Destination="Q_NumericValue_FPTO_Speed.rPhys" dx1="600"/>
			<Connection Source="IA_FPTO.SPEED_SET" Destination="Conv_SpeedSet.IN" dx1="600"/>
			<Connection Source="Conv_SpeedSet.OUT" Destination="TZ_SpeedSet.IN0" dx1="600"/>
			<Connection Source="AX_SPLIT_2_Timeout.OUT2" Destination="TZ_SpeedSet.G" dx1="660"/>
			<Connection Source="TZ_SpeedSet.OUT" Destination="Q_NumericValue_FPTO_SpeedSet.rPhys" dx1="600"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
