<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_014_AXb" Comment="Container (visible/invisible)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::Container_B"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F2"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="SoftKey_UP_F1" Type="isobus::UT::io::Softkey::Softkey_IXA" x="-4400" y="-1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
		</FB>
		<FB Name="SoftKey_UP_F2" Type="isobus::UT::io::Softkey::Softkey_IXA" x="-4400" y="-300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F2"/>
		</FB>
		<FB Name="AX_FB_SR" Type="adapter::iec61131::bistableElements::AX_FB_SR" x="-2800" y="-700"/>
		<FB Name="Q_ObjHideShow" Type="isobus::UT::Q::Q_ObjHideShow_AX" x="-1000" y="-900">
			<Parameter Name="u16ObjId" Value="Container_B"/>
		</FB>
		<AdapterConnections>
			<Connection Source="AX_FB_SR.Q1" Destination="Q_ObjHideShow.qVisible" dx1="660"/>
			<Connection Source="SoftKey_UP_F1.IN" Destination="AX_FB_SR.SET1" dx1="446.67"/>
			<Connection Source="SoftKey_UP_F2.IN" Destination="AX_FB_SR.RESET" dx1="446.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
