<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_215_AI" Comment="Standard IEC 61131-3 AI_FB_CTD (Adapter Version, Rückwärtszähler, INT) mit Terminal-Ausgabe">
	<Identification Standard="61131-3" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.2" Author="Franz Höpfinger" Date="2026-05-13" Remarks="Added AI_INT_TO_I init block connected to PV"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-04-21" Remarks="Added terminal output for counter value"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-21" Remarks="initial API and implementation (Adapter version)"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="AI_FB_CTD" Type="adapter::iec61131::counters::AI_FB_CTD" x="0" y="0"/>
		<FB Name="AI_INT_TO_I" Type="adapter::conversion::unidirectional::AI_INT_TO_I" x="-1400" y="800">
			<Parameter Name="OUT" Value="INT#10"/>
		</FB>
		<FB Name="Input_CD" Type="logiBUS::io::DI::logiBUS_IXA" x="-2500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="Input_LD" Type="logiBUS::io::DI::logiBUS_IXA" x="-2900" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="Output_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="2500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="AI_TO_AUDI" Type="adapter::conversion::unidirectional::AI_TO_AUDI" x="1000" y="800"/>
		<FB Name="Q_NumericValue_AUDI" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="3000" y="400">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<Comment Comment="AI_TO_AUDI ist großer Quatsch ... keine Negativen Zahlen möglich" x="400" y="1500" width="2200" height="500"/>
		<Comment Comment="hier gegebenenfalls einen AX_D_FF einbauen, damit die Events reduziert werden. " x="1000" y="-700" width="1000" height="500"/>
		<EventConnections>
			<Connection Source="Input_LD.INITO" Destination="AI_INT_TO_I.REQ"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="Input_CD.IN" Destination="AI_FB_CTD.CD" dx1="400"/>
			<Connection Source="Input_LD.IN" Destination="AI_FB_CTD.LD" dx1="200"/>
			<Connection Source="AI_FB_CTD.Q" Destination="Output_Q1.OUT" dx1="200"/>
			<Connection Source="AI_FB_CTD.CV" Destination="AI_TO_AUDI.AI_IN" dx1="200"/>
			<Connection Source="AI_TO_AUDI.AUDI_OUT" Destination="Q_NumericValue_AUDI.u32NewValue" dx1="200"/>
			<Connection Source="AI_INT_TO_I.AI_OUT" Destination="AI_FB_CTD.PV" dx1="146.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
