<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_054_AX" Comment="DigitalInput_I1-_I4 auf DigitalOutput_Q1-_Q4, mit Plug and Socket">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-09" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="8500" y="-1300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-9700" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="8500" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-9700" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="logiBUS::io::DQ::logiBUS_QXA" x="8500" y="900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q3"/>
		</FB>
		<FB Name="DigitalInput_I3" Type="logiBUS::io::DI::logiBUS_IXA" x="-9700" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QXA" x="8500" y="1900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="DigitalInput_I4" Type="logiBUS::io::DI::logiBUS_IXA" x="-9700" y="2400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
		</FB>
		<FB Name="ARR08B_TO_BOOLS" Type="logiBUS::utils::conversion::arr::forwarding::ARR08X_TO_BOOLS" x="4200" y="900">
		</FB>
		<FB Name="BOOLS_TO_ARR08B" Type="logiBUS::utils::conversion::arr::reversing::BOOLS_TO_ARR08X" x="1300" y="900">
		</FB>
		<FB Name="AX_X_TO_BOOL_1" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-7500" y="-900">
		</FB>
		<FB Name="AX_X_TO_BOOL_2" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-7500" y="0">
		</FB>
		<FB Name="AX_X_TO_BOOL_3" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-7500" y="1400">
		</FB>
		<FB Name="AX_X_TO_BOOL_4" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-7500" y="2400">
		</FB>
		<FB Name="AX_BOOL_TO_X_1" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="6300" y="-1300">
		</FB>
		<FB Name="AX_BOOL_TO_X_2" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="6300" y="-200">
		</FB>
		<FB Name="AX_BOOL_TO_X_3" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="6300" y="900">
		</FB>
		<FB Name="AX_BOOL_TO_X_4" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="6300" y="1900">
		</FB>
		<EventConnections>
			<Connection Source="BOOLS_TO_ARR08B.CNF" Destination="ARR08B_TO_BOOLS.REQ" dx1="260"/>
			<Connection Source="AX_X_TO_BOOL_1.CNF" Destination="BOOLS_TO_ARR08B.REQ" dx1="73.33"/>
			<Connection Source="AX_X_TO_BOOL_2.CNF" Destination="BOOLS_TO_ARR08B.REQ" dx1="73.33"/>
			<Connection Source="AX_X_TO_BOOL_3.CNF" Destination="BOOLS_TO_ARR08B.REQ" dx1="373.33"/>
			<Connection Source="AX_X_TO_BOOL_4.CNF" Destination="BOOLS_TO_ARR08B.REQ" dx1="73.33"/>
			<Connection Source="ARR08B_TO_BOOLS.CNF" Destination="AX_BOOL_TO_X_1.REQ" dx1="206.67"/>
			<Connection Source="ARR08B_TO_BOOLS.CNF" Destination="AX_BOOL_TO_X_2.REQ" dx1="206.67"/>
			<Connection Source="ARR08B_TO_BOOLS.CNF" Destination="AX_BOOL_TO_X_3.REQ" dx1="206.67"/>
			<Connection Source="ARR08B_TO_BOOLS.CNF" Destination="AX_BOOL_TO_X_4.REQ" dx1="660"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="BOOLS_TO_ARR08B.OUT" Destination="ARR08B_TO_BOOLS.IN" dx1="260"/>
			<Connection Source="AX_X_TO_BOOL_1.IN" Destination="BOOLS_TO_ARR08B.IN_00" dx1="206.67"/>
			<Connection Source="AX_X_TO_BOOL_2.IN" Destination="BOOLS_TO_ARR08B.IN_01" dx1="140"/>
			<Connection Source="AX_X_TO_BOOL_3.IN" Destination="BOOLS_TO_ARR08B.IN_02" dx1="373.33"/>
			<Connection Source="AX_X_TO_BOOL_4.IN" Destination="BOOLS_TO_ARR08B.IN_03" dx1="140"/>
			<Connection Source="ARR08B_TO_BOOLS.OUT_00" Destination="AX_BOOL_TO_X_1.OUT" dx1="73.33"/>
			<Connection Source="ARR08B_TO_BOOLS.OUT_01" Destination="AX_BOOL_TO_X_2.OUT" dx1="140"/>
			<Connection Source="ARR08B_TO_BOOLS.OUT_02" Destination="AX_BOOL_TO_X_3.OUT" dx1="273.33"/>
			<Connection Source="ARR08B_TO_BOOLS.OUT_03" Destination="AX_BOOL_TO_X_4.OUT" dx1="486.67"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_X_TO_BOOL_1.AX_IN"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AX_X_TO_BOOL_2.AX_IN"/>
			<Connection Source="DigitalInput_I3.IN" Destination="AX_X_TO_BOOL_3.AX_IN"/>
			<Connection Source="DigitalInput_I4.IN" Destination="AX_X_TO_BOOL_4.AX_IN"/>
			<Connection Source="AX_BOOL_TO_X_1.AX_OUT" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="AX_BOOL_TO_X_2.AX_OUT" Destination="DigitalOutput_Q2.OUT"/>
			<Connection Source="AX_BOOL_TO_X_3.AX_OUT" Destination="DigitalOutput_Q3.OUT"/>
			<Connection Source="AX_BOOL_TO_X_4.AX_OUT" Destination="DigitalOutput_Q4.OUT"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
