<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_011e_MIX_AX" Comment="Numeric Value Input I1 Durchschleifen auf N3 (Software Scale via NumericObjectPool_S) falsch gemischt!">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-14" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::InputNumber_I1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::OutputNumber_N3_N"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="InputNumber_I1" Type="isobus::UT::io::NumericValue::NumericValue_IDA" x="-6600" y="400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="AD_TO_AR_NUM" Type="adapter::conversion::unidirectional::AD_TO_AR_NUM" x="-4900" y="400">
		</FB>
		<FB Name="Q_NumericValue_PHYS" Type="isobus::UT::Q::Q_NumericValue_PHYSA" x="-1600" y="400">
			<Parameter Name="stObj" Value="OutputNumber_N3_N"/>
		</FB>
		<Comment Comment=" Beispiel: I1-Eingabe 10 → F_RAW_TO_PHYS(I1) → 10.0 → Q_NumericValue_PHYS(N3) → N3 zeigt 10.00.&#10;&#10;die beiden Namespaces sind INKOMPATIBEL !!!&#10;" x="-6300" y="1800" width="5300" height="500"/>
		<Comment Comment="Uebungen::const::UT::DefaultPool::InputNumber_I1" x="-7400" y="1500" width="2400" height="200"/>
		<Comment Comment="Uebungen::const::UT::DefaultPool_Numeric::OutputNumber_N3_N" x="-2600" y="1500" width="3200" height="200"/>
		<AdapterConnections>
			<Connection Source="InputNumber_I1.IN" Destination="AD_TO_AR_NUM.AD_IN" dx1="400"/>
			<Connection Source="AD_TO_AR_NUM.AR_OUT" Destination="Q_NumericValue_PHYS.rPhys" dx1="600"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
