<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020c4_AX" Comment="DigitalInput_I1 auf DigitalOutput_Q1; E_TON Einschaltverzögert; Zeit eingeben und speichern, INI">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I1_STORE"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::InputNumber_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="Uebungen::const::NVS::NVS_Keys::SECTION_I1_STORE"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-5300" y="100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-9800" y="200">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="E_TON" Type="adapter::events::unidirectional::timers::ATM_AX_TON" x="-7100" y="500">
		</FB>
		<SubApp Name="INI_IN_AND_STORE_AR" Type="MyLib::sys::INI_IN_AND_STORE_AR" x="-11200" y="1700">
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="SECTION" Value="SECTION_I1_STORE"/>
			<Parameter Name="stObj" Value="InputNumber_I1"/>
		</SubApp>
		<FB Name="AR_MULTIME" Type="adapter::iec61131::arithmetic::AR_MULTIME" x="-9400" y="1800">
			<Parameter Name="IN1" Value="T#1s"/>
		</FB>
		<AdapterConnections>
			<Connection Source="AR_MULTIME.OUT" Destination="E_TON.PT" dx1="253.33"/>
			<Connection Source="DigitalInput_I1.IN" Destination="E_TON.IN" dx1="386.67"/>
			<Connection Source="E_TON.Q" Destination="DigitalOutput_Q1.OUT" dx1="460"/>
			<Connection Source="INI_IN_AND_STORE_AR.VALUEO" Destination="AR_MULTIME.IN2" dx1="313.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
