<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_003f_AX" Comment="DigitalInput_I1-8 auf DigitalOutput_Q1-8">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-10-05" Remarks="initial API and implementation and/or initial documentation - wie Uebung_003b_AX, aber alle 8 Kanaele statt nur 4">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I5"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I6"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I7"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I8"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q5"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q6"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q7"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q8"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="F1" Type="MyLib::sys::logiBUS_IX_TO_logiBUS_QX" x="100" y="700">
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</SubApp>
		<SubApp Name="F2" Type="MyLib::sys::logiBUS_IX_TO_logiBUS_QX" x="100" y="1200">
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</SubApp>
		<SubApp Name="F3" Type="MyLib::sys::logiBUS_IX_TO_logiBUS_QX" x="100" y="1700">
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="Output" Value="Output_Q3"/>
		</SubApp>
		<SubApp Name="F4" Type="MyLib::sys::logiBUS_IX_TO_logiBUS_QX" x="100" y="2200">
			<Parameter Name="Input" Value="Input_I4"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</SubApp>
		<SubApp Name="F5" Type="MyLib::sys::logiBUS_IX_TO_logiBUS_QX" x="100" y="2700">
			<Parameter Name="Input" Value="Input_I5"/>
			<Parameter Name="Output" Value="Output_Q5"/>
		</SubApp>
		<SubApp Name="F6" Type="MyLib::sys::logiBUS_IX_TO_logiBUS_QX" x="100" y="3200">
			<Parameter Name="Input" Value="Input_I6"/>
			<Parameter Name="Output" Value="Output_Q6"/>
		</SubApp>
		<SubApp Name="F7" Type="MyLib::sys::logiBUS_IX_TO_logiBUS_QX" x="100" y="3700">
			<Parameter Name="Input" Value="Input_I7"/>
			<Parameter Name="Output" Value="Output_Q7"/>
		</SubApp>
		<SubApp Name="F8" Type="MyLib::sys::logiBUS_IX_TO_logiBUS_QX" x="100" y="4200">
			<Parameter Name="Input" Value="Input_I8"/>
			<Parameter Name="Output" Value="Output_Q8"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
