<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_034a1_Q1_AX" Comment="Numeric Value Input auf PWM Ausgang (Adapter Version)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-20" Remarks="initial API and implementation (Adapter Version)"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::PWM::DefaultPool_PWM::InputNumber_PWM_Value"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="PWMOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QDA_PWM" x="2000" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="PWM_Value" Type="isobus::UT::io::NumericValue::NumericValue_IDA" x="-2000" y="900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_PWM_Value"/>
		</FB>
		<Comment Comment="ACHTUNG !! &#10;Ereignis erscheint erst im Adapter, &#10;wenn man die Numeric Value mit OK Bestätigt. &#10;nicht bei Button Druck. &#10;" x="-2000" y="1800" width="1480" height="800"/>
		<AdapterConnections>
			<Connection Source="PWM_Value.IN" Destination="PWMOutput_Q1.OUT" dx1="1000"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
