<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_033_AX" Comment="LED Strip Blinkende LED, mit Plug and Socket">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-09" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DO_LED::LED_COLOURS"/>
		<Import declaration="logiBUS::io::DO_LED::LED_strip"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GREEN" Type="MyLib::sys::IXA_TO_logiBUS_LED_strip_QXA" x="-4000" y="-400">
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="Colour" Value="LED_COLOURS::LED_GREEN"/>
			<Parameter Name="Output" Value="LED_strip::Output_strip"/>
		</SubApp>
		<SubApp Name="YELLOW" Type="MyLib::sys::IXA_TO_logiBUS_LED_strip_QXA" x="-4000" y="200">
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="Colour" Value="LED_COLOURS::LED_YELLOW"/>
			<Parameter Name="Output" Value="LED_strip::Output_strip"/>
		</SubApp>
		<SubApp Name="RED" Type="MyLib::sys::IXA_TO_logiBUS_LED_strip_QXA" x="-4000" y="800">
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="Colour" Value="LED_COLOURS::LED_RED"/>
			<Parameter Name="Output" Value="LED_strip::Output_strip"/>
		</SubApp>
		<SubApp Name="BLUE" Type="MyLib::sys::IXA_TO_logiBUS_LED_strip_QXA" x="-4000" y="1400">
			<Parameter Name="Input" Value="Input_I4"/>
			<Parameter Name="Colour" Value="LED_COLOURS::LED_BLUE"/>
			<Parameter Name="Output" Value="LED_strip::Output_strip"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
