<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_080c_AX" Comment="Beispiel für E_CTU mit AX_T_FF und AX_PERMIT (Event-Halbierung)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023-2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-19" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-2800" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IEA" x="-10500" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_CTU" Type="iec61499::events::E_CTU" x="-5600" y="-800">
			<Parameter Name="PV" Value="UINT#5"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IEA" x="-8000" y="200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="AX_T_FF" Type="adapter::events::unidirectional::AX_T_FF" x="-9000" y="-1000">
		</FB>
		<FB Name="AX_PERMIT" Type="adapter::events::unidirectional::AX_PERMIT" x="-7600" y="-1000">
		</FB>
		<FB Name="AE_E_TO_EVENT_1" Type="adapter::conversion::unidirectional::AE_E_TO_EVENT" x="-10500" y="0">
		</FB>
		<FB Name="AE_E_TO_EVENT_2" Type="adapter::conversion::unidirectional::AE_E_TO_EVENT" x="-6800" y="-1000">
		</FB>
		<FB Name="AE_E_TO_EVENT_3" Type="adapter::conversion::unidirectional::AE_E_TO_EVENT" x="-6800" y="200">
		</FB>
		<FB Name="AX_BOOL_TO_X" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="-4200" y="-800">
		</FB>
		<EventConnections>
			<Connection Source="E_CTU.CUO" Destination="AX_BOOL_TO_X.REQ" dx1="466.67"/>
			<Connection Source="E_CTU.RO" Destination="AX_BOOL_TO_X.REQ"/>
			<Connection Source="AE_E_TO_EVENT_2.CNF" Destination="E_CTU.CU"/>
			<Connection Source="AE_E_TO_EVENT_3.CNF" Destination="E_CTU.R" dx1="273.33"/>
			<Connection Source="AE_E_TO_EVENT_1.CNF" Destination="AX_T_FF.CLK" dx1="100"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTU.Q" Destination="AX_BOOL_TO_X.OUT" dx1="286.67"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="DigitalInput_CLK_I1.IN" Destination="AE_E_TO_EVENT_1.AE_IN" dx1="200"/>
			<Connection Source="DigitalInput_CLK_I2.IN" Destination="AE_E_TO_EVENT_3.AE_IN" dx1="200"/>
			<Connection Source="AX_BOOL_TO_X.AX_OUT" Destination="DigitalOutput_Q1.OUT" dx1="200"/>
			<Connection Source="AX_T_FF.Q" Destination="AX_PERMIT.IN" dx1="200"/>
			<Connection Source="AX_PERMIT.OUT" Destination="AE_E_TO_EVENT_2.AE_IN" dx1="200"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
