<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012_AX" Comment="Numeric Value Input und Speichern NVS">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I1_STORE"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::InputNumber_I1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="InputNumber_I1" Type="isobus::UT::io::NumericValue::NumericValue_IDA" x="-5300" y="900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="AD_TO_AUDI" Type="adapter::conversion::unidirectional::AD_TO_AUDI" x="-3300" y="1300">
		</FB>
		<FB Name="NVS" Type="logiBUS::storage::esp32_nvs::NVS_AUDI" x="-900" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#0"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="1600" y="800">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<AdapterConnections>
			<Connection Source="InputNumber_I1.IN" Destination="AD_TO_AUDI.AD_IN" dx1="400"/>
			<Connection Source="AD_TO_AUDI.AUDI_OUT" Destination="NVS.AUDI_IN" dx1="600"/>
			<Connection Source="NVS.AUDI_OUT" Destination="Q_NumericValue.u32NewValue" dx1="600"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
