<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_089_AX" Comment="Beispiel für E_R_TRIG, mit Plug and Socket">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-10" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="4300" y="-300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-4500" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="OR_2" Type="iec61131::bitwiseOperators::OR_2" x="-2400" y="-200">
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-4500" y="300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="E_R_TRIG" Type="iec61499::events::E_R_TRIG" x="-1200" y="-200">
		</FB>
		<FB Name="E_T_FF_Q1" Type="iec61499::events::E_T_FF" x="0" y="-200">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="4300" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="E_T_FF_1_Q2" Type="iec61499::events::E_T_FF" x="0" y="900">
		</FB>
		<FB Name="E_SWITCH" Type="iec61499::events::E_SWITCH" x="-1200" y="800">
		</FB>
		<FB Name="AX_X_TO_BOOL_1" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-3200" y="-900">
		</FB>
		<FB Name="AX_X_TO_BOOL_2" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-3200" y="300">
		</FB>
		<FB Name="AX_BOOL_TO_X_1" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="2100" y="-300">
		</FB>
		<FB Name="AX_BOOL_TO_X_2" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="2100" y="800">
		</FB>
		<Comment Comment="R_TRIG schaltet nur wenn wirklich steigende Flanke" x="-1300" y="-700" width="1200" height="400"/>
		<Comment Comment="E_SWITCH schaltet auch, wenn anderweitig ein Event kommt. " x="-1300" y="1600" width="1200" height="400"/>
		<EventConnections>
			<Connection Source="AX_X_TO_BOOL_2.CNF" Destination="OR_2.REQ" dx1="886.67"/>
			<Connection Source="AX_X_TO_BOOL_1.CNF" Destination="OR_2.REQ" dx1="893.33"/>
			<Connection Source="OR_2.CNF" Destination="E_R_TRIG.EI"/>
			<Connection Source="E_R_TRIG.EO" Destination="E_T_FF_Q1.CLK"/>
			<Connection Source="E_T_FF_Q1.EO" Destination="AX_BOOL_TO_X_1.REQ"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_T_FF_1_Q2.CLK"/>
			<Connection Source="OR_2.CNF" Destination="E_SWITCH.EI" dx1="513.33"/>
			<Connection Source="E_T_FF_1_Q2.EO" Destination="AX_BOOL_TO_X_2.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AX_X_TO_BOOL_1.IN" Destination="OR_2.IN1" dx1="700"/>
			<Connection Source="AX_X_TO_BOOL_2.IN" Destination="OR_2.IN2" dx1="700"/>
			<Connection Source="OR_2.OUT" Destination="E_R_TRIG.QI"/>
			<Connection Source="E_T_FF_Q1.Q" Destination="AX_BOOL_TO_X_1.OUT" dx1="620"/>
			<Connection Source="OR_2.OUT" Destination="E_SWITCH.G" dx1="366.67"/>
			<Connection Source="E_T_FF_1_Q2.Q" Destination="AX_BOOL_TO_X_2.OUT" dx1="666.67"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_X_TO_BOOL_1.AX_IN"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AX_X_TO_BOOL_2.AX_IN"/>
			<Connection Source="AX_BOOL_TO_X_1.AX_OUT" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="AX_BOOL_TO_X_2.AX_OUT" Destination="DigitalOutput_Q2.OUT"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
