<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_015_AX" Comment="Object Pointer umschalten">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-10" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_RELEASED"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::Button_A1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::ObjectPointer_P1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F2"/>
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_UP_F1" Type="isobus::UT::io::Softkey::Softkey_IE" x="-4500" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="SoftKey_UP_F2" Type="isobus::UT::io::Softkey::Softkey_IE" x="-4500" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F2"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="AX_SR" Type="adapter::events::unidirectional::AX_SR" x="-2800" y="-900">
		</FB>
		<FB Name="F_UINT_TO_UDINT" Type="adapter::types::unidirectional::AUDI::initval::initval_AUDI" x="-3100" y="-1500">
			<Parameter Name="INIT_VAL" Value="Button_A1"/>
		</FB>
		<FB Name="F_SEL" Type="adapter::iec61131::selection::AUDI_AX_SEL_AUDI" x="-1100" y="-900">
		</FB>
		<FB Name="Q_NumericValue_AUDI" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="1100" y="-1300">
			<Parameter Name="u16ObjId" Value="ObjectPointer_P1"/>
		</FB>
		<FB Name="initval_AUDI" Type="adapter::types::unidirectional::AUDI::initval::initval_AUDI" x="-3100" y="-2100">
			<Parameter Name="INIT_VAL" Value="ID_NULL"/>
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_UP_F1.IND" Destination="AX_SR.S" dx1="406.67"/>
			<Connection Source="SoftKey_UP_F2.IND" Destination="AX_SR.R" dx1="473.33"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="F_UINT_TO_UDINT.OUT" Destination="F_SEL.IN1" dx1="406.67"/>
			<Connection Source="AX_SR.Q" Destination="F_SEL.G" dx1="220"/>
			<Connection Source="initval_AUDI.OUT" Destination="F_SEL.IN0" dx1="673.33"/>
			<Connection Source="F_SEL.OUT" Destination="Q_NumericValue_AUDI.u32NewValue" dx1="980"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
