<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012e_AR" Comment="Numeric Value Input PHYS und Speichern INI mit Subapp (AR Adapter)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-24" Remarks="AR adapter variant of Uebung_012e">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I1_STORE"/>
		<Import declaration="Uebungen::const::NVS::NVS_Keys::SECTION_I1_STORE"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::InputNumber_I3"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::OutputNumber_N3"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="Uebung_012e_sub_AR" Type="Uebungen::Uebung_012e_sub_AR" x="-3200" y="1600">
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="SECTION" Value="SECTION_I1_STORE"/>
			<Parameter Name="stObj_Input" Value="InputNumber_I3"/>
			<Parameter Name="stObj_Output" Value="OutputNumber_N3"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
