<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_055_AX" Comment="DigitalInput_I1 auf DigitalOutput_Q1, mit Plug and Socket">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-09" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="6500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-9700" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="Q_TO_STR_STATUS" Type="logiBUS::utils::quarter::QUARTER_TO_STR_STATUS" x="-5100" y="300">
		</FB>
		<FB Name="Q_TO_BOOL" Type="logiBUS::utils::quarter::QUARTER_TO_BOOL" x="4300" y="-700">
		</FB>
		<FB Name="BOOL_TO_Q" Type="logiBUS::utils::quarter::BOOL_TO_QUARTER" x="-7600" y="-700">
		</FB>
		<FB Name="AX_X_TO_BOOL" Type="adapter::conversion::unidirectional::AX_X_TO_BOOL" x="-8600" y="-700">
		</FB>
		<FB Name="AX_BOOL_TO_X" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="5400" y="-700">
		</FB>
		<EventConnections>
			<Connection Source="Q_TO_BOOL.CNF" Destination="AX_BOOL_TO_X.REQ" dx1="286.67"/>
			<Connection Source="AX_X_TO_BOOL.CNF" Destination="BOOL_TO_Q.REQ" dx1="273.33"/>
			<Connection Source="BOOL_TO_Q.CNF" Destination="Q_TO_STR_STATUS.REQ" dx1="186.67"/>
			<Connection Source="BOOL_TO_Q.CNF" Destination="Q_TO_BOOL.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Q_TO_BOOL.Q" Destination="AX_BOOL_TO_X.OUT" dx1="73.33"/>
			<Connection Source="AX_X_TO_BOOL.IN" Destination="BOOL_TO_Q.I" dx1="73.33"/>
			<Connection Source="BOOL_TO_Q." Destination="Q_TO_STR_STATUS.IB" dx1="100"/>
			<Connection Source="BOOL_TO_Q." Destination="Q_TO_BOOL.IB" dx1="206.67"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_X_TO_BOOL.AX_IN"/>
			<Connection Source="AX_BOOL_TO_X.AX_OUT" Destination="DigitalOutput_Q1.OUT"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
