<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004b_AX_ASR_X" Comment="Toggle Flip-Flop mit IE / E_SWITCH + E_SR">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="500" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IEA" x="-7700" y="-1200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="ASR_AX_SR" Type="adapter::events::unidirectional::ASR_AX_SR" x="-2500" y="-600">
		</FB>
		<FB Name="AX_ASR_SWITCH" Type="adapter::events::unidirectional::AX_ASR_SWITCH" x="-4000" y="-600">
		</FB>
		<FB Name="AX_SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-1500" y="-600">
		</FB>
		<Comment Comment="Kommentar FH: &#10;nicht empfohlen !!!&#10;viel zu viel Bausteine" x="-7600" y="0" width="1300" height="600"/>
		<FB Name="AX_AE_MERGE" Type="adapter::events::unidirectional::AX_AE_MERGE" x="-5300" y="-600">
		</FB>
		<AdapterConnections>
			<Connection Source="ASR_AX_SR.Q" Destination="AX_SPLIT_2.IN"/>
			<Connection Source="AX_SPLIT_2.OUT2" Destination="AX_AE_MERGE.IN_AX" dx1="246.67" dx2="246.67" dy="800"/>
			<Connection Source="AX_ASR_SWITCH.Q" Destination="ASR_AX_SR.S_R"/>
			<Connection Source="DigitalInput_CLK_I1.IN" Destination="AX_AE_MERGE.IN_AE" dx1="553.33"/>
			<Connection Source="AX_AE_MERGE.OUT" Destination="AX_ASR_SWITCH.G"/>
			<Connection Source="AX_SPLIT_2.OUT1" Destination="DigitalOutput_Q1.OUT" dx1="473.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
