<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_006a3_sub_AX" Comment="Subapplication Type">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Moritz Ortmeier" Date="2026-01-13">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="EI" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="EO" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="DI" Type="BOOL"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="Rechts" Type="BOOL"/>
			<VarDeclaration Name="Links" Type="BOOL"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AXT_FF" Type="adapter::events::unidirectional::AX_T_FF" x="1100" y="-200">
		</FB>
		<FB Name="AX_SWITCH" Type="adapter::events::unidirectional::AX_SWITCH" x="0" y="-200">
		</FB>
		<FB Name="F_NOT" Type="adapter::booleanOperators::AX_NOT" x="2100" y="-100">
		</FB>
		<EventConnections>
			<Connection Source="AXT_FF.EO" Destination="F_NOT.REQ" dx1="235.29"/>
			<Connection Source="EI" Destination="AX_SWITCH.EI" dx1="1700"/>
			<Connection Source="F_NOT.CNF" Destination="EO" dx1="973.33"/>
			<Connection Source="AX_SWITCH.EO1" Destination="AXT_FF.CLK" dx1="211.76"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DI" Destination="AX_SWITCH.G" dx1="980"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
