<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_070_AX" Comment="WBSD auf UT ausgeben">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::TECU::DefaultPool_TECU::NumberVariable_Wheel_based_machine_speed"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="I_WBSD" Type="isobus::tecu::IA_WBSD" x="-4300" y="800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="-900" y="500">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_speed"/>
		</FB>
		<FB Name="F_UINT_TO_UDINT" Type="adapter::conversion::unidirectional::AUI_TO_AUDI" x="-2600" y="1100">
		</FB>
		<AdapterConnections>
			<Connection Source="I_WBSD.SPEED" Destination="F_UINT_TO_UDINT.AUI_IN" dx1="980"/>
			<Connection Source="F_UINT_TO_UDINT.AUDI_OUT" Destination="Q_NumericValue.u32NewValue" dx1="760"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
