<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_077_AUI" Comment="RHS Position/Force/Draft auf UT ausgeben mit AR_Timeout_Zero (Adapter Version)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-17" Remarks="ISOBUS TECU Rear Hitch Status (RHS): Position/Force/Draft mit AR_Timeout_Zero Fendt-Schaltung auf UT ausgeben (Adapter Version, analog Krauternter TECU_RHS.SUB)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::TECU::DefaultPool_TECU_Numeric::NumberVariable_Wheel_based_machine_speed_N"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="RHS_Inst" Type="isobus::tecu::IA_RHS" x="0" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<SubApp Name="Conv_Position" Type="MyLib::sys::AUS_FIELDBUS_USINT_TO_AR" x="1600" y="0">
		</SubApp>
		<SubApp Name="TZ_Position" Type="MyLib::sys::AR_Timeout_Zero" x="2900" y="0">
		</SubApp>
		<FB Name="Q_NumericValue_RHS_Position" Type="isobus::UT::Q::Q_NumericValue_PHYSA" x="4700" y="-900">
			<Parameter Name="stObj" Value="NumberVariable_Wheel_based_machine_speed_N"/>
		</FB>
		<SubApp Name="Conv_Force" Type="MyLib::sys::AUS_FIELDBUS_USINT_TO_AR" x="1500" y="400">
		</SubApp>
		<SubApp Name="TZ_Force" Type="MyLib::sys::AR_Timeout_Zero" x="2900" y="450">
		</SubApp>
		<FB Name="Q_NumericValue_RHS_Force" Type="isobus::UT::Q::Q_NumericValue_PHYSA" x="4700" y="0">
			<Parameter Name="stObj" Value="NumberVariable_Wheel_based_machine_speed_N"/>
		</FB>
		<SubApp Name="Conv_Draft" Type="MyLib::sys::AUI_FIELDBUS_UINT_TO_AR" x="1600" y="900">
		</SubApp>
		<SubApp Name="TZ_Draft" Type="MyLib::sys::AR_Timeout_Zero" x="2900" y="900">
		</SubApp>
		<FB Name="Q_NumericValue_RHS_Draft" Type="isobus::UT::Q::Q_NumericValue_PHYSA" x="4700" y="900">
			<Parameter Name="stObj" Value="NumberVariable_Wheel_based_machine_speed_N"/>
		</FB>
		<FB Name="AX_SPLIT_3_Timeout" Type="adapter::events::unidirectional::AX_SPLIT_3" x="-700" y="1600">
		</FB>
		<AdapterConnections>
			<Connection Source="RHS_Inst.TIMEOUT" Destination="AX_SPLIT_3_Timeout.IN" dx1="600"/>
			<Connection Source="RHS_Inst.POSITION" Destination="Conv_Position.IN" dx1="600"/>
			<Connection Source="Conv_Position.OUT" Destination="TZ_Position.IN0" dx1="600"/>
			<Connection Source="AX_SPLIT_3_Timeout.OUT1" Destination="TZ_Position.G" dx1="600"/>
			<Connection Source="TZ_Position.OUT" Destination="Q_NumericValue_RHS_Position.rPhys" dx1="600"/>
			<Connection Source="RHS_Inst.FORCE" Destination="Conv_Force.IN" dx1="600"/>
			<Connection Source="Conv_Force.OUT" Destination="TZ_Force.IN0" dx1="600"/>
			<Connection Source="AX_SPLIT_3_Timeout.OUT2" Destination="TZ_Force.G" dx1="600"/>
			<Connection Source="TZ_Force.OUT" Destination="Q_NumericValue_RHS_Force.rPhys" dx1="600"/>
			<Connection Source="RHS_Inst.DRAFT" Destination="Conv_Draft.IN" dx1="600"/>
			<Connection Source="Conv_Draft.OUT" Destination="TZ_Draft.IN0" dx1="600"/>
			<Connection Source="AX_SPLIT_3_Timeout.OUT3" Destination="TZ_Draft.G" dx1="600"/>
			<Connection Source="TZ_Draft.OUT" Destination="Q_NumericValue_RHS_Draft.rPhys" dx1="600"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
