<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_003a2b_AX" Comment="2x R_IO mit IXA">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-01-13" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-700" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-4600" y="-800">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-4600" y="200">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="AX_FB_R_IO_Q1" Type="adapter::monostableElements::AX_FB_R_IO" x="-2800" y="-500">
		</FB>
		<FB Name="DigitalInput_CLK_I3" Type="logiBUS::io::DI::logiBUS_IXA" x="-5500" y="-2000">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<FB Name="AX_FB_R_IO_Q2" Type="adapter::monostableElements::AX_FB_R_IO" x="-2900" y="500">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="-700" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<Comment Comment="Hausmeister-Aus (alles Aus mit einem Schalter)&#10;Schalter müsste RASTEND sein. Ansonsten ist nur solange aus wie der Taster gehalten wird." x="-4500" y="-2100" width="2200" height="400"/>
		<FB Name="AX_SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-4100" y="-1600">
		</FB>
		<Comment Comment="AND wäre auch möglich, &#10;dann HAusmeiser ein Zustimmschalter !" x="-2100" y="0" width="1000" height="500"/>
		<Comment Comment="Vorteil dieser Lösung: wird an RESET1 nichts angeschlossen: ist der Baustein Funktionsfähig.&#10;Prinzip wie FB_RS&#10;" x="-2700" y="-1400" width="1400" height="600"/>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I3.INITO" Destination="DigitalInput_CLK_I3.REQ" dx1="80" dx2="80" dy="53.33"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="AX_FB_R_IO_Q1.OUT" Destination="DigitalOutput_Q1.OUT" dx1="673.33"/>
			<Connection Source="AX_FB_R_IO_Q2.OUT" Destination="DigitalOutput_Q2.OUT" dx1="720"/>
			<Connection Source="DigitalInput_CLK_I1.IN" Destination="AX_FB_R_IO_Q1.IN" dx1="473.33"/>
			<Connection Source="DigitalInput_CLK_I2.IN" Destination="AX_FB_R_IO_Q2.IN" dx1="426.67"/>
			<Connection Source="DigitalInput_CLK_I3.IN" Destination="AX_SPLIT_2.IN" dx1="173.33"/>
			<Connection Source="AX_SPLIT_2.OUT2" Destination="AX_FB_R_IO_Q2.RESET1" dx1="220"/>
			<Connection Source="AX_SPLIT_2.OUT1" Destination="AX_FB_R_IO_Q1.RESET1" dx1="273.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
