<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012f_AR2" Comment="Numeric Value Input PHYS und Speichern NVS mit Subapp (AR2 Adapter, echter in sich geschlossener Baustein)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-08-31" Remarks="AR2 variant of Uebung_012f_AR - NVS_IN_AND_STORE_AR2 (NumericValue_TO_AR2 + NVS_AR2, echt selbstspeichernd) statt NVS_IN_AND_STORE_AR (NumericValue_PHYSA + NVS_AR)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I1_STORE"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::InputNumber_I3_N"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="Uebung_012f_sub_AR2" Type="MyLib::sys::NVS_IN_AND_STORE_AR2" x="-3200" y="1600">
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="stObj" Value="InputNumber_I3_N"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
