<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_001f_AX" Comment="DigitalInput_I1 negiert mit INIT auf DigitalOutput_Q1">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-1300" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-4500" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="AX_NOT_INIT" Type="adapter::booleanOperators::AX_NOT_INIT" x="-2900" y="-500"/>
		<Comment Comment="obwohl I1 nicht abgefragt wird beim BOOT, wird AX_NOT hier TRUE ausgeben." x="-4600" y="200" width="2000" height="500"/>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_NOT_INIT.IN" dx1="420"/>
			<Connection Source="AX_NOT_INIT.OUT" Destination="DigitalOutput_Q1.OUT" dx1="466.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
