<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_074b_AUI" Comment="RPTO auf UT ausgeben (Adapter Version) ohne Fendt-Schaltung">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-19" Remarks="initial API and implementation (Adapter Version of Uebung_074)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::TECU::DefaultPool_TECU::NumberVariable_Rear_PTO_output_shaft_speed"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="IA_RPTO" Type="isobus::tecu::IA_RPTO" x="-5200" y="500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_PTO" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="-700" y="500">
			<Parameter Name="u16ObjId" Value="NumberVariable_Rear_PTO_output_shaft_speed"/>
		</FB>
		<FB Name="CONV_AUI_AUDI" Type="adapter::conversion::unidirectional::AUI_TO_AUDI" x="-2300" y="1200">
		</FB>
		<EventConnections>
			<Connection Source="IA_RPTO.INITO" Destination="Q_NumericValue_PTO.INIT"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="CONV_AUI_AUDI.AUDI_OUT" Destination="Q_NumericValue_PTO.u32NewValue" dx1="500"/>
			<Connection Source="IA_RPTO.SPEED" Destination="CONV_AUI_AUDI.AUI_IN" dx1="2133.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
