<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_071_AX" Comment="WBSD auf UT ausgeben, Q1 Schalten wenn Speed &gt; 0 (Adapter Version)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023-2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-19" Remarks="initial API and implementation (Adapter Version of Uebung_071)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::TECU::DefaultPool_TECU::NumberVariable_Wheel_based_machine_speed"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="IA_WBSD" Type="isobus::tecu::IA_WBSD" x="-5200" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_WBSD" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="1400" y="500">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_speed"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="1400" y="1900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="CONV_AUI_AUDI" Type="adapter::conversion::unidirectional::AUI_TO_AUDI" x="-800" y="1000">
		</FB>
		<FB Name="AUI_SPLIT_2" Type="adapter::events::unidirectional::AUI_SPLIT_2" x="-3500" y="1200">
		</FB>
		<SubApp Name="AX_GT_0_UINT" Type="MyLib::sys::AX_GT_0_UINT" x="-1300" y="2500">
		</SubApp>
		<AdapterConnections>
			<Connection Source="AUI_SPLIT_2.OUT1" Destination="CONV_AUI_AUDI.AUI_IN" dx1="200"/>
			<Connection Source="CONV_AUI_AUDI.AUDI_OUT" Destination="Q_NumericValue_WBSD.u32NewValue" dx1="200"/>
			<Connection Source="IA_WBSD.SPEED" Destination="AUI_SPLIT_2.IN" dx1="526.67"/>
			<Connection Source="AUI_SPLIT_2.OUT2" Destination="AX_GT_0_UINT.OUT2" dx1="700"/>
			<Connection Source="AX_GT_0_UINT.AX_OUT" Destination="DigitalOutput_Q1.OUT" dx1="1760"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
