<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_001d2_AX" Comment="DigitalInput_I1/2 auf DigitalOutput_Q1/2, als Alternative(Verriegelt) mit Plug and Socket, ohne ECC">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-4700" y="-600">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="2400" y="-600">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="Output_Q1"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="AX_AND_2_Q1" Type="adapter::booleanOperators::AX_AND_2" x="-1900" y="-300">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="2500" y="1100">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="Output_Q2"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="AX_AND_2_Q2" Type="adapter::booleanOperators::AX_AND_2" x="-1900" y="1300">
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-4800" y="1100">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="AX_SPLIT_2_Q1" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-900" y="-300">
		</FB>
		<FB Name="AX_SPLIT_2_Q2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-900" y="1300">
		</FB>
		<FB Name="AX_NOT_INIT_Q1" Type="adapter::booleanOperators::AX_NOT_INIT" x="200" y="100">
		</FB>
		<FB Name="AX_NOT_INIT_Q2" Type="adapter::booleanOperators::AX_NOT_INIT" x="200" y="900">
		</FB>
		<FB Name="AX_D_FF_Q1" Type="adapter::events::unidirectional::AX_D_FF" x="1200" y="200">
		</FB>
		<FB Name="AX_D_FF_Q2" Type="adapter::events::unidirectional::AX_D_FF" x="1200" y="1000">
		</FB>
		<Comment Comment="Kompliziert. &#10;&#10;BESSER: ILOCK-Baustein" x="-1900" y="2000" width="1000" height="500"/>
		<AdapterConnections>
			<Connection Source="AX_AND_2_Q1.OUT" Destination="AX_SPLIT_2_Q1.IN"/>
			<Connection Source="AX_AND_2_Q2.OUT" Destination="AX_SPLIT_2_Q2.IN"/>
			<Connection Source="AX_SPLIT_2_Q1.OUT2" Destination="AX_NOT_INIT_Q1.IN" dx1="173.33"/>
			<Connection Source="AX_SPLIT_2_Q2.OUT1" Destination="AX_NOT_INIT_Q2.IN" dx1="173.33"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AX_AND_2_Q2.IN2" dx1="1046.67"/>
			<Connection Source="AX_SPLIT_2_Q2.OUT2" Destination="DigitalOutput_Q2.OUT" dx1="1320"/>
			<Connection Source="AX_SPLIT_2_Q1.OUT1" Destination="DigitalOutput_Q1.OUT" dx1="1273.33"/>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_AND_2_Q1.IN1" dx1="1000"/>
			<Connection Source="AX_NOT_INIT_Q2.OUT" Destination="AX_D_FF_Q2.I" dx1="100"/>
			<Connection Source="AX_NOT_INIT_Q1.OUT" Destination="AX_D_FF_Q1.I" dx1="100"/>
			<Connection Source="AX_D_FF_Q1.Q" Destination="AX_AND_2_Q2.IN1" dx1="433.33" dx2="80" dy="340"/>
			<Connection Source="AX_D_FF_Q2.Q" Destination="AX_AND_2_Q1.IN2" dx1="80" dx2="80" dy="-593.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
