<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_034_AX" Comment="Analog-Eingang auf PWM Ausgang (Adapter Version)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023-2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-20" Remarks="initial API and implementation (Adapter Version of Uebung_034)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::AI::logiBUS_AI"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AnalogInput_I7" Type="logiBUS::io::AI::logiBUS_AI_IDA" x="-4000" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_AI::AnalogInput_I7"/>
			<Parameter Name="AnalogInput_hysteresis" Value="50"/>
		</FB>
		<FB Name="PWMOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QDA_PWM" x="4000" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="AD_D_TO_DWORD" Type="adapter::conversion::unidirectional::AD_D_TO_DWORD" x="-1500" y="1700">
		</FB>
		<FB Name="F_SHL" Type="iec61131::bitwiseOperators::F_SHL" x="500" y="1700">
			<Parameter Name="N" Value="UINT#1"/>
		</FB>
		<FB Name="AD_DWORD_TO_D" Type="adapter::conversion::unidirectional::AD_DWORD_TO_D" x="2500" y="1700">
		</FB>
		<EventConnections>
			<Connection Source="AnalogInput_I7.INITO" Destination="PWMOutput_Q4.INIT" dx1="5000"/>
			<Connection Source="AD_D_TO_DWORD.CNF" Destination="F_SHL.REQ" dx1="100"/>
			<Connection Source="F_SHL.CNF" Destination="AD_DWORD_TO_D.REQ" dx1="100"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AD_D_TO_DWORD.IN" Destination="F_SHL.IN" dx1="100"/>
			<Connection Source="F_SHL.OUT" Destination="AD_DWORD_TO_D.OUT" dx1="100"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="AnalogInput_I7.IN" Destination="AD_D_TO_DWORD.AD_IN" dx1="200"/>
			<Connection Source="AD_DWORD_TO_D.AD_OUT" Destination="PWMOutput_Q4.OUT" dx1="200"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
