<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_011b1_AUDI" Comment="Numeric Value Input ADD">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-14">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::InputNumber_I1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::InputNumber_I2"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="InputNumber_I1" Type="isobus::UT::io::NumericValue::NumericValue_IDA" x="-6900" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="InputNumber_I2" Type="isobus::UT::io::NumericValue::NumericValue_IDA" x="-6900" y="1800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_I2"/>
		</FB>
		<FB Name="AD_TO_AUDI_1" Type="adapter::conversion::unidirectional::AD_TO_AUDI" x="-5100" y="1300">
		</FB>
		<FB Name="AD_TO_AUDI_2" Type="adapter::conversion::unidirectional::AD_TO_AUDI" x="-5100" y="2200">
		</FB>
		<FB Name="AX_ADD_2" Type="adapter::booleanOperators::AUDI_ADD_2" x="-3100" y="1600">
		</FB>
		<FB Name="Q_NumericValue_AUDI" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="-500" y="1200">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<AdapterConnections>
			<Connection Source="InputNumber_I1.IN" Destination="AD_TO_AUDI_1.AD_IN" dx1="380"/>
			<Connection Source="InputNumber_I2.IN" Destination="AD_TO_AUDI_2.AD_IN" dx1="380"/>
			<Connection Source="AD_TO_AUDI_1.AUDI_OUT" Destination="AX_ADD_2.IN1" dx1="593.33"/>
			<Connection Source="AD_TO_AUDI_2.AUDI_OUT" Destination="AX_ADD_2.IN2" dx1="593.33"/>
			<Connection Source="AX_ADD_2.OUT" Destination="Q_NumericValue_AUDI.u32NewValue" dx1="920"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
