<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_028c2_AR" Comment="Analog-Eingang Kalibrierung mit Adaptern NVS und Hysterese-Regler am Ausgang und Display Anzeige">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-05-07" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::PWM::DefaultPool_PWM_Numeric::InputNumber_HYSTERESIS"/>
		<Import declaration="Uebungen::const::UT::PWM::DefaultPool_PWM_Numeric::InputNumber_PWM_DUTY_OUT"/>
		<Import declaration="Uebungen::const::UT::PWM::DefaultPool_PWM_Numeric::InputNumber_THRESHOLD"/>
		<Import declaration="logiBUS::io::AI::logiBUS_AI::AnalogInput_I7"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-7300" y="400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-4500" y="400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="AnalogInput_I4" Type="logiBUS::io::AI::logiBUS_AI_IDA" x="-4300" y="1900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="AnalogInput_I7"/>
			<Parameter Name="AnalogInput_hysteresis" Value="50"/>
			<Parameter Name="TimeDelta" Value="250"/>
			<Parameter Name="TimeRateLimit" Value="100"/>
		</FB>
		<FB Name="CALIBRATE" Type="adapter::Engineering::measurements::AR_CALIBRATE" x="1000" y="1500">
			<Parameter Name="Y_Offset" Value="0.0"/>
			<Parameter Name="Y_Scale" Value="100.0"/>
		</FB>
		<FB Name="NVS_OFFSET" Type="logiBUS::storage::esp32_nvs::NVS_AR2" x="3100" y="2600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="KEY" Value="'OFFSET'"/>
			<Parameter Name="DEFAULT_VALUE" Value="0.0"/>
		</FB>
		<FB Name="NVS_SCALE" Type="logiBUS::storage::esp32_nvs::NVS_AR2" x="3100" y="3600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="KEY" Value="'SCALE'"/>
			<Parameter Name="DEFAULT_VALUE" Value="1.0"/>
		</FB>
		<FB Name="DigitalInput_I2_CO" Type="logiBUS::io::DI::logiBUS_IXA" x="-2000" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="DigitalInput_I3_CS" Type="logiBUS::io::DI::logiBUS_IXA" x="-2000" y="2500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<FB Name="AX_SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-6100" y="1000">
		</FB>
		<SubApp Name="THRESHOLD" Type="MyLib::sys::NVS_IN_AND_STORE_AR" x="4300" y="800">
			<Parameter Name="KEY" Value="'THRESHOLD'"/>
			<Parameter Name="stObj" Value="InputNumber_THRESHOLD"/>
		</SubApp>
		<SubApp Name="HYSTERESIS" Type="MyLib::sys::NVS_IN_AND_STORE_AR" x="4300" y="1500">
			<Parameter Name="KEY" Value="'HYSTERESIS'"/>
			<Parameter Name="stObj" Value="InputNumber_HYSTERESIS"/>
		</SubApp>
		<FB Name="Hysteresis_AR_AX" Type="logiBUS::signalprocessing::hysteresis::Hysteresis_AR_AX" x="6100" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AR_SPLIT_2" Type="adapter::events::unidirectional::AR_SPLIT_2" x="4000" y="-500">
		</FB>
		<FB Name="Q_NumericValue_PHYSA" Type="isobus::UT::Q::Q_NumericValue_PHYSA" x="6400" y="-1500">
			<Parameter Name="stObj" Value="InputNumber_PWM_DUTY_OUT"/>
		</FB>
		<FB Name="AD_TO_AUDI" Type="adapter::conversion::unidirectional::AD_TO_AUDI" x="-2300" y="900">
		</FB>
		<FB Name="AUDI_TO_AR" Type="adapter::conversion::unidirectional::AUDI_TO_AR" x="-1100" y="900">
		</FB>
		<Comment Comment="WICHTIG ! Doppelte Konvertierung. ein AD_TO_AR wäre wie ein &quot;reinterpret_cast&quot; " x="-2100" y="200" width="1700" height="400"/>
		<Comment Comment="Beispiel: &#10;0.0 =&gt; 0,5V&#10;100.0 =&gt; 4,5V&#10;(Typ. Sensor Automotive)" x="1000" y="900" width="1400" height="500"/>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="8300" y="-300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_SPLIT_2.IN" dx1="306.67"/>
			<Connection Source="AnalogInput_I4.IN" Destination="AD_TO_AUDI.AD_IN" dx1="173.33"/>
			<Connection Source="AUDI_TO_AR.AR_OUT" Destination="CALIBRATE.X" dx1="800"/>
			<Connection Source="DigitalInput_I2_CO.IN" Destination="CALIBRATE.CO" dx1="1086.67"/>
			<Connection Source="DigitalInput_I3_CS.IN" Destination="CALIBRATE.CS" dx1="800"/>
			<Connection Source="AX_SPLIT_2.OUT1" Destination="DigitalOutput_Q1.OUT" dx1="220"/>
			<Connection Source="CALIBRATE.OFFSET" Destination="NVS_OFFSET.VAL" dx1="320"/>
			<Connection Source="CALIBRATE.SCALE" Destination="NVS_SCALE.VAL" dx1="206.67"/>
			<Connection Source="CALIBRATE.Y" Destination="AR_SPLIT_2.IN" dx1="926.67"/>
			<Connection Source="THRESHOLD.VALUEO" Destination="Hysteresis_AR_AX.THRESHOLD" dx1="333.33"/>
			<Connection Source="HYSTERESIS.VALUEO" Destination="Hysteresis_AR_AX.HYSTERESIS" dx1="540"/>
			<Connection Source="AR_SPLIT_2.OUT2" Destination="Hysteresis_AR_AX.INPUT" dx1="673.33"/>
			<Connection Source="AR_SPLIT_2.OUT1" Destination="Q_NumericValue_PHYSA.rPhys" dx1="873.33"/>
			<Connection Source="AD_TO_AUDI.AUDI_OUT" Destination="AUDI_TO_AR.AUDI_IN"/>
			<Connection Source="AX_SPLIT_2.OUT2" Destination="AnalogInput_I4.SREQ" dx1="164.71"/>
			<Connection Source="Hysteresis_AR_AX.OUTPUT" Destination="DigitalOutput_Q2.OUT" dx1="580"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
