<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010e2_AX" Comment="SR und T-Flip-Flop mit 3x SoftKey (Softkey_IE, SK_RELEASED) mit GreenWhiteBackground am Toggle-SoftKey mit Subapp">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-02" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F2"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="Uebung_010e2_sub_AX" Type="Uebungen::Uebung_010e2_sub_AX" x="-4600" y="-500">
			<Parameter Name="u16ObjId_SET" Value="SoftKey_F1" Comment="Object ID SET SoftKey"/>
			<Parameter Name="u16ObjId_RESET" Value="SoftKey_F2" Comment="Object ID RESET SoftKey"/>
			<Parameter Name="u16ObjId_TOGGLE" Value="SoftKey_F3" Comment="Object ID TOGGLE SoftKey (auch fuer GreenWhiteBackground)"/>
			<Parameter Name="Output" Value="Output_Q1" Comment="Identify the Output Output_Q1..Q8"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
