<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_230_AX" Comment="Wie Uebung_229_AX, aber mit ASR-Adapter-Umbau: 2x AX_ASR_RF_TRIG + ASR_MERGE_2 + ASR_AX_SR statt loser Event-Verkabelung">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-06" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-6000" y="-600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-6000" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="AX_ASR_RF_TRIG_1" Type="adapter::events::unidirectional::AX_ASR_RF_TRIG" x="-4600" y="-100">
		</FB>
		<FB Name="AX_ASR_RF_TRIG_2" Type="adapter::events::unidirectional::AX_ASR_RF_TRIG" x="-4500" y="1100">
		</FB>
		<FB Name="ASR_MERGE_2" Type="adapter::events::unidirectional::ASR_MERGE_2" x="-3200" y="400">
		</FB>
		<FB Name="ASR_AX_SR" Type="adapter::events::unidirectional::ASR_AX_SR" x="-1800" y="400">
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="0" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_ASR_RF_TRIG_1.QI" dx1="300"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AX_ASR_RF_TRIG_2.QI" dx1="300"/>
			<Connection Source="AX_ASR_RF_TRIG_1.Q" Destination="ASR_MERGE_2.IN1" dx1="200"/>
			<Connection Source="AX_ASR_RF_TRIG_2.Q" Destination="ASR_MERGE_2.IN2" dx1="200"/>
			<Connection Source="ASR_MERGE_2.OUT" Destination="ASR_AX_SR.S_R"/>
			<Connection Source="ASR_AX_SR.Q" Destination="DigitalOutput_Q1.OUT" dx1="400"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
