<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_073_AUI" Comment="VDS auf UT ausgeben (Adapter Version)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-19" Remarks="initial API and implementation (Adapter Version of Uebung_073)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::TECU::DefaultPool_TECU::NumberVariable_Wheel_based_machine_speed"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="IA_VDS" Type="isobus::tecu::IA_VDS" x="-5200" y="500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_VDS" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="1400" y="500">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_speed"/>
		</FB>
		<FB Name="CONV_VDS" Type="adapter::conversion::unidirectional::AUI_TO_AUDI" x="-1600" y="900">
		</FB>
		<AdapterConnections>
			<Connection Source="IA_VDS.NAV_SPEED" Destination="CONV_VDS.AUI_IN" dx1="200"/>
			<Connection Source="CONV_VDS.AUDI_OUT" Destination="Q_NumericValue_VDS.u32NewValue" dx1="200"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
