<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_225b_AXA" Comment="Dreieck-Sollwertmarker (wie 225b, aber mit AR-Adapter-Bausteinen: NumericValue_PHYSA, PositionMarkerFSA, Q_NumericValue_PHYSA)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-05" Remarks="adapter variant of Uebung_225b_AX using NumericValue_PHYSA/PositionMarkerFSA/Q_NumericValue_PHYSA">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::Dreieck::DefaultPool_Dreieck_PositionMarker::Container_PositionMarker"/>
		<Import declaration="Uebungen::const::UT::Dreieck::DefaultPool_Dreieck_Numeric::InputNumber_Sollwert_N"/>
		<Import declaration="Uebungen::const::UT::Dreieck::DefaultPool_Dreieck_Numeric::NumberVariable_Istwert_N"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Sollwert_N" Type="isobus::UT::io::NumericValue::NumericValue_PHYSA" x="-7300" y="900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="stObj" Value="InputNumber_Sollwert_N"/>
		</FB>
		<FB Name="Split" Type="adapter::events::unidirectional::AR_SPLIT_2" x="-4700" y="1200">
		</FB>
		<FB Name="Marker_Dreieck" Type="isobus::UT::Q::PositionMarkerFSA" x="-2600" y="200">
			<Parameter Name="stObj" Value="Container_PositionMarker"/>
		</FB>
		<FB Name="Istwert_N" Type="isobus::UT::Q::Q_NumericValue_PHYSA" x="-2600" y="1400">
			<Parameter Name="stObj" Value="NumberVariable_Istwert_N"/>
		</FB>
		<AdapterConnections>
			<Connection Source="Sollwert_N.rPhys" Destination="Split.IN" dx1="900"/>
			<Connection Source="Split.OUT2" Destination="Istwert_N.rPhys" dx1="80"/>
			<Connection Source="Split.OUT1" Destination="Marker_Dreieck.rPhys" dx1="80"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
