<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_019c_AX" Comment="Umschalten einer Maske, mit Plug and Socket">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-09" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::AlarmMask_A2_medium"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::DataMask_M1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::DataMask_M2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q8"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-8600" y="-500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-8600" y="500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<SubApp Name="Select_4_AUI" Type="MyLib::sys::AUI_AUI_MUX_4_VAL" x="-2800" y="-200">
			<Parameter Name="val1" Value="DataMask_M1"/>
			<Parameter Name="val2" Value="DataMask_M2"/>
			<Parameter Name="val3" Value="DataMask_M1"/>
			<Parameter Name="val4" Value="AlarmMask_A2_medium"/>
		</SubApp>
		<FB Name="Q_ActiveMask" Type="isobus::UT::Q::Q_ActiveMask_AUI" x="-900" y="200">
		</FB>
		<FB Name="ACK" Type="logiBUS::io::DI::logiBUS_IE" x="-8600" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="AX_SR" Type="adapter::events::unidirectional::AX_SR" x="-4100" y="3100">
		</FB>
		<FB Name="Alarmausgang" Type="logiBUS::io::DQ::logiBUS_QXA" x="-900" y="2800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q8"/>
		</FB>
		<FB Name="Alarmeingang" Type="logiBUS::io::DI::logiBUS_IXA" x="-8500" y="2600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<FB Name="AX_R_TRIG_Alarm" Type="adapter::events::unidirectional::AX_R_TRIG" x="-5700" y="3100">
		</FB>
		<SubApp Name="AX_E_PERMIT_INVERT_1" Type="MyLib::sys::AX_E_PERMIT_INVERT_3" x="-6000" y="-200">
		</SubApp>
		<FB Name="AX_SPLIT_4" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-7200" y="3100">
		</FB>
		<EventConnections>
			<Connection Source="AX_R_TRIG_Alarm.EO" Destination="AX_SR.S"/>
			<Connection Source="ACK.IND" Destination="AX_E_PERMIT_INVERT_1.EI3" dx1="413.33"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="AX_E_PERMIT_INVERT_1.EI1" dx1="440"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="AX_E_PERMIT_INVERT_1.EI2" dx1="233.33"/>
			<Connection Source="AX_E_PERMIT_INVERT_1.EO3" Destination="AX_SR.R" dx1="286.67"/>
			<Connection Source="AX_E_PERMIT_INVERT_1.EO3" Destination="Select_4_AUI.EI3"/>
			<Connection Source="AX_E_PERMIT_INVERT_1.EO2" Destination="Select_4_AUI.EI2"/>
			<Connection Source="AX_E_PERMIT_INVERT_1.EO1" Destination="Select_4_AUI.EI1"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="Select_4_AUI.OUT" Destination="Q_ActiveMask.u16NewMaskId" dx1="600"/>
			<Connection Source="AX_SR.Q" Destination="Alarmausgang.OUT" dx1="700"/>
			<Connection Source="Alarmeingang.IN" Destination="AX_SPLIT_4.IN" dx1="246.67"/>
			<Connection Source="AX_SPLIT_4.OUT1" Destination="AX_E_PERMIT_INVERT_1.PERMIT" dx1="273.33"/>
			<Connection Source="AX_SPLIT_4.OUT2" Destination="AX_R_TRIG_Alarm.QI"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
