<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_011g1_AX" Comment="Numeric Value Input -- multiple IOObservers">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-05-05" Remarks="multiple IOObservers">
	</VersionInfo>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::InputNumber_I1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="InputNumber_I1_1" Type="isobus::UT::io::NumericValue::NumericValue_IDA" x="-5000" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="InputNumber_I1_2" Type="isobus::UT::io::NumericValue::NumericValue_IDA" x="-5000" y="1600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="InputNumber_I1_3" Type="isobus::UT::io::NumericValue::NumericValue_IDA" x="-5000" y="2600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="AD_TO_AUDI_1" Type="adapter::conversion::unidirectional::AD_TO_AUDI" x="-3200" y="600">
		</FB>
		<FB Name="AD_TO_AUDI_2" Type="adapter::conversion::unidirectional::AD_TO_AUDI" x="-3200" y="1600">
		</FB>
		<FB Name="AD_TO_AUDI_3" Type="adapter::conversion::unidirectional::AD_TO_AUDI" x="-3200" y="2600">
		</FB>
		<AdapterConnections>
			<Connection Source="InputNumber_I1_1.IN" Destination="AD_TO_AUDI_1.AD_IN" dx1="400"/>
			<Connection Source="InputNumber_I1_2.IN" Destination="AD_TO_AUDI_2.AD_IN" dx1="400"/>
			<Connection Source="InputNumber_I1_3.IN" Destination="AD_TO_AUDI_3.AD_IN" dx1="400"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
