<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012c_AIS" Comment="String Input und Speichern">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-13" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_S1_STORE"/>
		<Import declaration="Uebungen::const::NVS::NVS_Keys::SECTION_S1_STORE"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::InputNumber_I1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="InputString_I1" Type="isobus::UT::io::StringValue::StringValue_AIS" x="-5000" y="493.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="INI_AIS" Type="eclipse4diac::storage::INI_AIS" x="-2000" y="493.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="SECTION" Value="SECTION_S1_STORE"/>
			<Parameter Name="KEY" Value="KEY_S1_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="STRING#'Test'"/>
		</FB>
		<FB Name="Q_StringValue_AIS" Type="isobus::UT::Q::Q_StringValue_AIS" x="600" y="493.33">
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<AdapterConnections>
			<Connection Source="InputString_I1.IN" Destination="INI_AIS.AIS_IN"/>
			<Connection Source="INI_AIS.AIS_OUT" Destination="Q_StringValue_AIS.pau8String"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
