<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020f4_AX" Comment="DigitalInput_I1 auf DataPanel_1A; BLINKER">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="DataPanel::io::MI::DQ::DataPanel_MI_DO::DigitalOutput_1A"/>
		<Import declaration="DataPanel::io::MI::const::MI::MI_00"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AX_BLINK" Type="adapter::events::unidirectional::signals::AX_BLINK" x="-7000" y="600">
			<Parameter Name="TIMELOW" Value="T#1s"/>
			<Parameter Name="TIMEHIGH" Value="T#1s200ms"/>
		</FB>
		<FB Name="DigitalOutput_1A" Type="DataPanel::io::MI::DQ::DataPanel_MI_QXA" x="-5100" y="400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="MI_00"/>
			<Parameter Name="Output" Value="DigitalOutput_1A"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalOutput_1A.INITO" Destination="AX_BLINK.START" dx1="633.33" dx2="393.33" dy="-406.67"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="AX_BLINK.OUT" Destination="DigitalOutput_1A.OUT" dx1="520"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
