<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_016b_AX" Comment="Background Colour umschalten -- 3-fach mit SubApp">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-10" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_RELEASED"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F2"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F3"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F7"/>
		<Import declaration="isobus::UT::Q::const::colours::COLOR_GREEN"/>
		<Import declaration="isobus::UT::Q::const::colours::COLOR_RED"/>
		<Import declaration="isobus::UT::Q::const::colours::COLOR_WHITE"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_UP_F1" Type="isobus::UT::io::Softkey::Softkey_IE" x="-4600" y="-2100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="SoftKey_UP_F2" Type="isobus::UT::io::Softkey::Softkey_IE" x="-4600" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F2"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="SoftKey_UP_F3" Type="isobus::UT::io::Softkey::Softkey_IE" x="-4600" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F3"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<SubApp Name="Select_3_AUS" Type="MyLib::sys::AUS_AUI_MUX_3_VAL" x="-1500" y="-1000">
			<Parameter Name="val1" Value="COLOR_WHITE"/>
			<Parameter Name="val2" Value="COLOR_GREEN"/>
			<Parameter Name="val3" Value="COLOR_RED"/>
		</SubApp>
		<FB Name="Q_BackgroundColour" Type="isobus::UT::Q::Q_BackgroundColour_AUS" x="2000" y="-1300">
			<Parameter Name="u16ObjId" Value="SoftKey_F7"/>
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_UP_F1.IND" Destination="Select_3_AUS.EI1" dx1="1253.33"/>
			<Connection Source="SoftKey_UP_F2.IND" Destination="Select_3_AUS.EI2" dx1="1040"/>
			<Connection Source="SoftKey_UP_F3.IND" Destination="Select_3_AUS.EI3" dx1="1353.33"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="Select_3_AUS.OUT" Destination="Q_BackgroundColour.u8Colour" dx1="926.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
