<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012e2_AR" Comment="Numeric Value Input PHYS und Speichern INI mit Subapp (AR Adapter)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-24" Remarks="AR adapter variant of Uebung_012e">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I1_STORE"/>
		<Import declaration="Uebungen::const::NVS::NVS_Keys::SECTION_I1_STORE"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::InputNumber_I3"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="Uebung_012e_sub_AR" Type="MyLib::sys::INI_IN_AND_STORE_AR" x="-3100" y="3700">
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="SECTION" Value="SECTION_I1_STORE"/>
			<Parameter Name="stObj" Value="InputNumber_I3"/>
		</SubApp>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="1300" y="2700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="AX_TON" Type="adapter::events::unidirectional::timers::ATM_AX_TON" x="-300" y="3100">
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-2000" y="2700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="AR_MULTIME" Type="adapter::iec61131::arithmetic::AR_MULTIME" x="-1600" y="3800">
			<Parameter Name="IN1" Value="T#100ms"/>
		</FB>
		<Comment Comment="Einstellbarer Timer " x="-400" y="3800" width="1200" height="200"/>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_TON.IN" dx1="246.67"/>
			<Connection Source="AX_TON.Q" Destination="DigitalOutput_Q1.OUT" dx1="320"/>
			<Connection Source="Uebung_012e_sub_AR.VALUEO" Destination="AR_MULTIME.IN2" dx1="246.67"/>
			<Connection Source="AR_MULTIME.OUT" Destination="AX_TON.PT" dx1="273.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
