<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_213b_AX" Comment="Standard IEC 61131-3 AUDI_FB_CTU (Adapter Version, UDINT) mit Terminal-Ausgabe">
	<Identification Standard="61131-3" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-04-21" Remarks="Added terminal output for counter value">
	</VersionInfo>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-21" Remarks="initial API and implementation (Adapter version)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AUDI_FB_CTU" Type="adapter::iec61131_3::counters::AUDI_FB_CTU" x="0" y="0">
		</FB>
		<FB Name="Input_CU" Type="logiBUS::io::DI::logiBUS_IXA" x="-2500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="Input_R" Type="logiBUS::io::DI::logiBUS_IXA" x="-2500" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="Output_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="2500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="Q_NumericValue_AUDI" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="2500" y="800">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<AdapterConnections>
			<Connection Source="Input_CU.IN" Destination="AUDI_FB_CTU.CU" dx1="400"/>
			<Connection Source="Input_R.IN" Destination="AUDI_FB_CTU.R" dx1="200"/>
			<Connection Source="AUDI_FB_CTU.Q" Destination="Output_Q1.OUT" dx1="200"/>
			<Connection Source="AUDI_FB_CTU.CV" Destination="Q_NumericValue_AUDI.u32NewValue" dx1="500"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
