<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004b2_AX" Comment="Toggle Flip-Flop mit IE / Split / doppelt (aus AX_E_SWITCH und AX_SR aufgebaut)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="900" y="-1200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-4500" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_SWITCH_I1" Type="adapter::events::unidirectional::AX_E_SWITCH" x="-2900" y="-900">
		</FB>
		<FB Name="AX_SR_I1" Type="adapter::events::unidirectional::AX_SR" x="-1800" y="-900">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="900" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-4500" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_SWITCH_I2" Type="adapter::events::unidirectional::AX_E_SWITCH" x="-2900" y="200">
		</FB>
		<FB Name="AX_SR_I2" Type="adapter::events::unidirectional::AX_SR" x="-1800" y="200">
		</FB>
		<FB Name="SPLIT_1" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-900" y="-700">
		</FB>
		<FB Name="SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-800" y="400">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_SWITCH_I1.EI" dx1="353.33"/>
			<Connection Source="E_SWITCH_I1.EO0" Destination="AX_SR_I1.S"/>
			<Connection Source="E_SWITCH_I1.EO1" Destination="AX_SR_I1.R"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_SWITCH_I2.EI" dx1="353.33"/>
			<Connection Source="E_SWITCH_I2.EO0" Destination="AX_SR_I2.S"/>
			<Connection Source="E_SWITCH_I2.EO1" Destination="AX_SR_I2.R"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="AX_SR_I1.Q" Destination="SPLIT_1.IN" dx1="240"/>
			<Connection Source="SPLIT_1.OUT2" Destination="E_SWITCH_I1.G" dx1="80" dx2="80" dy="200"/>
			<Connection Source="SPLIT_2.OUT2" Destination="E_SWITCH_I2.G" dx1="80" dx2="80" dy="106.67"/>
			<Connection Source="AX_SR_I2.Q" Destination="SPLIT_2.IN" dx1="240"/>
			<Connection Source="SPLIT_2.OUT1" Destination="DigitalOutput_Q2.OUT" dx1="473.33"/>
			<Connection Source="SPLIT_1.OUT1" Destination="DigitalOutput_Q1.OUT" dx1="520"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
