<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_223b_ALR" Comment="Standard IEC 61131-3 AUDI_FB_CTUD (Adapter Version, Vorwärts-/Rückwärtszähler, UDINT) mit Terminal-Ausgabe (PHYSA_LREAL)">
	<Identification Standard="61131-3" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.2" Author="Franz Höpfinger" Date="2026-05-13" Remarks="Added AUDI_UDINT_TO_UDI init block connected to PV">
	</VersionInfo>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-04-21" Remarks="Added terminal output for counter value">
	</VersionInfo>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-21" Remarks="initial API and implementation (Adapter version)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::OutputNumber_N3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AUDI_FB_CTUD" Type="adapter::iec61131::counters::AUDI_FB_CTUD" x="0" y="0">
		</FB>
		<FB Name="AUDI_UDINT_TO_UDI" Type="adapter::conversion::unidirectional::AUDI_UDINT_TO_UDI" x="-1300" y="1500">
			<Parameter Name="OUT" Value="UDINT#5"/>
		</FB>
		<FB Name="Input_CU" Type="logiBUS::io::DI::logiBUS_IXA" x="-3000" y="-1300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="Input_CD" Type="logiBUS::io::DI::logiBUS_IXA" x="-3000" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="Input_R" Type="logiBUS::io::DI::logiBUS_IXA" x="-3000" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<FB Name="Input_LD" Type="logiBUS::io::DI::logiBUS_IXA" x="-3100" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
		</FB>
		<FB Name="Output_QU" Type="logiBUS::io::DQ::logiBUS_QXA" x="2500" y="-1300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="Output_QD" Type="logiBUS::io::DQ::logiBUS_QXA" x="2500" y="-300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="AUDI_TO_ALR" Type="adapter::conversion::unidirectional::AUDI_TO_ALR" x="1100" y="1400">
		</FB>
		<FB Name="Q_NumericValue_PHYSA_LREAL" Type="isobus::UT::Q::Q_NumericValue_PHYSA_LREAL" x="2800" y="900">
			<Parameter Name="stObj" Value="OutputNumber_N3"/>
		</FB>
		<Comment Comment="hier sind negative Werte möglich ! " x="800" y="1800" width="1500" height="300"/>
		<Comment Comment="hier gegebenenfalls je einen AX_D_FF einbauen, damit die Events reduziert werden. " x="1300" y="-100" width="1000" height="500"/>
		<EventConnections>
			<Connection Source="Input_LD.INITO" Destination="AUDI_UDINT_TO_UDI.REQ"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="Input_CU.IN" Destination="AUDI_FB_CTUD.CU" dx1="500"/>
			<Connection Source="Input_CD.IN" Destination="AUDI_FB_CTUD.CD" dx1="400"/>
			<Connection Source="Input_R.IN" Destination="AUDI_FB_CTUD.R" dx1="300"/>
			<Connection Source="Input_LD.IN" Destination="AUDI_FB_CTUD.LD" dx1="493.33"/>
			<Connection Source="AUDI_FB_CTUD.QU" Destination="Output_QU.OUT" dx1="200"/>
			<Connection Source="AUDI_FB_CTUD.QD" Destination="Output_QD.OUT" dx1="746.67"/>
			<Connection Source="AUDI_FB_CTUD.CV" Destination="AUDI_TO_ALR.AUDI_IN" dx1="173.33"/>
			<Connection Source="AUDI_TO_ALR.ALR_OUT" Destination="Q_NumericValue_PHYSA_LREAL.lrPhys" dx1="293.33"/>
			<Connection Source="AUDI_UDINT_TO_UDI.AUDI_OUT" Destination="AUDI_FB_CTUD.PV" dx1="140"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
