<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_019b_AX" Comment="Umschalten einer Maske, mit Plug and Socket">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-09" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::AlarmMask_A2_medium"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::DataMask_M1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::DataMask_M2"/>
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_PRESSED"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-8100" y="-700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-8100" y="400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I3" Type="logiBUS::io::DI::logiBUS_IE" x="-8100" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="ACK" Type="isobus::UT::io::Softkey::Softkey_IE" x="-8000" y="2600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="ID_NULL"/>
			<Parameter Name="InputEvent" Value="SK_PRESSED"/>
		</FB>
		<SubApp Name="Select_4_AUI" Type="MyLib::sys::AUI_AUI_MUX_4_VAL" x="-3800" y="-300">
			<Parameter Name="val1" Value="DataMask_M1"/>
			<Parameter Name="val2" Value="DataMask_M2"/>
			<Parameter Name="val3" Value="AlarmMask_A2_medium"/>
			<Parameter Name="val4" Value="DataMask_M1"/>
		</SubApp>
		<FB Name="Q_ActiveMask" Type="isobus::UT::Q::Q_ActiveMask_AUI" x="-1100" y="-400">
		</FB>
		<FB Name="AX_SR" Type="adapter::events::unidirectional::AX_SR" x="-5000" y="1800">
		</FB>
		<FB Name="Alarmausgang" Type="logiBUS::io::DQ::logiBUS_QXA" x="600" y="1700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="Select_4_AUI.EI1" dx1="1706.67"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="Select_4_AUI.EI2" dx1="313.33"/>
			<Connection Source="DigitalInput_CLK_I3.IND" Destination="Select_4_AUI.EI3" dx1="1560"/>
			<Connection Source="ACK.IND" Destination="Select_4_AUI.EI4" dx1="840"/>
			<Connection Source="DigitalInput_CLK_I3.IND" Destination="AX_SR.S" dx1="1560"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="AX_SR.R" dx1="1153.33"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="AX_SR.R" dx1="1153.33"/>
			<Connection Source="ACK.IND" Destination="AX_SR.R" dx1="1153.33"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="Select_4_AUI.OUT" Destination="Q_ActiveMask.u16NewMaskId" dx1="600"/>
			<Connection Source="AX_SR.Q" Destination="Alarmausgang.OUT" dx1="700"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
