<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_022b_AX2" Comment="Spiegelabfolge (2) - AX Variante">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-20" Remarks="AX Variante">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_PRESSED"/>
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_RELEASED"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F2"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-2833.33" y="-500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="SoftKey_UP_F1" Type="isobus::UT::io::Softkey::Softkey_IE" x="-7600" y="-500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="AX_SR_Ausfahren_Cyl_1" Type="adapter::events::unidirectional::AX_SR" x="-4700" y="-300">
		</FB>
		<FB Name="SoftKey_F2_DOWN" Type="isobus::UT::io::Softkey::Softkey_IE" x="-7600" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F2"/>
			<Parameter Name="InputEvent" Value="SK_PRESSED"/>
		</FB>
		<Comment Comment="START-Knopf" x="-9066.67" y="-333.33" width="1373.33" height="366.67"/>
		<Comment Comment="Endlage Ausfahren_Cyl_1 &#10;" x="-9066.67" y="1166.67" width="1373.33" height="366.67"/>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="-2833.33" y="1166.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="AX_SR_Ausfahren_Cyl_2" Type="adapter::events::unidirectional::AX_SR" x="-4700" y="1300">
		</FB>
		<Comment Comment="Endlage Ausfahren_Cyl_2 &#10;" x="-9066.67" y="2500" width="1373.33" height="366.67"/>
		<FB Name="SoftKey_F3_DOWN" Type="isobus::UT::io::Softkey::Softkey_IE" x="-7600" y="2333.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F3"/>
			<Parameter Name="InputEvent" Value="SK_PRESSED"/>
		</FB>
		<Comment Comment="Ausfahren_Cyl_1" x="-3400" y="400" width="1373.33" height="366.67"/>
		<Comment Comment="Ausfahren_Cyl_2" x="-3400" y="2100" width="1373.33" height="366.67"/>
		<EventConnections>
			<Connection Source="SoftKey_UP_F1.IND" Destination="AX_SR_Ausfahren_Cyl_1.S" dx1="1206.67"/>
			<Connection Source="SoftKey_F2_DOWN.IND" Destination="AX_SR_Ausfahren_Cyl_1.R" dx1="1206.67"/>
			<Connection Source="SoftKey_F2_DOWN.IND" Destination="AX_SR_Ausfahren_Cyl_2.S" dx1="1206.67"/>
			<Connection Source="SoftKey_F3_DOWN.IND" Destination="AX_SR_Ausfahren_Cyl_2.R" dx1="1206.67"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="AX_SR_Ausfahren_Cyl_1.Q" Destination="DigitalOutput_Q1.OUT" dx1="760"/>
			<Connection Source="AX_SR_Ausfahren_Cyl_2.Q" Destination="DigitalOutput_Q2.OUT" dx1="660"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
