<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_075_AX" Comment="LD auf Q">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-19" Remarks="initial API and implementation (Adapter Version of Uebung_074)"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q3"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="4900" y="2000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="logiBUS::io::DQ::logiBUS_QXA" x="4900" y="4133.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q3"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="4900" y="3066.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="IA_Lighting" Type="isobus::tecu::IA_Lighting" x="800" y="2100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<AdapterConnections>
			<Connection Source="IA_Lighting.RIGHT_TURN_SIGNAL_LIGHTS" Destination="DigitalOutput_Q1.OUT" dx1="1026.67"/>
			<Connection Source="IA_Lighting.LEFT_TURN_SIGNAL_LIGHTS" Destination="DigitalOutput_Q2.OUT" dx1="1026.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
