<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_201b_AX" Comment="Interlock: ILOCK_BLOCK_AX (Motor Rechts/Linkslauf via Adapter)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023-2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-19" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q5"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q56"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q6"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-4000" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-4000" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="ILOCK_AX" Type="logiBUS::signalprocessing::interlock::ILOCK_BLOCK_AX" x="-1700" y="200">
		</FB>
		<FB Name="Rechtslauf" Type="logiBUS::io::DQ::logiBUS_QXA" x="3000" y="-600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q5"/>
		</FB>
		<FB Name="LowSide_Treiber" Type="logiBUS::io::DQ::logiBUS_QXA" x="3000" y="300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q56"/>
		</FB>
		<SubApp Name="AX_2_TO_3" Type="MyLib::sys::AX_2_TO_3" x="500" y="200">
		</SubApp>
		<FB Name="Linkslauf" Type="logiBUS::io::DQ::logiBUS_QXA" x="3000" y="1200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q6"/>
		</FB>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="ILOCK_AX.UP_IN" dx1="200"/>
			<Connection Source="DigitalInput_I2.IN" Destination="ILOCK_AX.DOWN_IN" dx1="200"/>
			<Connection Source="AX_2_TO_3.DOWN_OUT" Destination="Linkslauf.OUT" dx1="146.67"/>
			<Connection Source="AX_2_TO_3.OR_OUT" Destination="LowSide_Treiber.OUT" dx1="846.67"/>
			<Connection Source="AX_2_TO_3.UP_OUT" Destination="Rechtslauf.OUT" dx1="846.67"/>
			<Connection Source="ILOCK_AX.UP_OUT" Destination="AX_2_TO_3.UP_IN"/>
			<Connection Source="ILOCK_AX.DOWN_OUT" Destination="AX_2_TO_3.DOWN_IN"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
