<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_072_AX" Comment="GBSD und WBSD auf UT ausgeben (Adapter Version)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023-2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-19" Remarks="initial API and implementation (Adapter Version of Uebung_072)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::TECU::DefaultPool_TECU::NumberVariable_Ground_based_machine_speed"/>
		<Import declaration="Uebungen::const::UT::TECU::DefaultPool_TECU::NumberVariable_Wheel_based_machine_speed"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="IA_GBSD" Type="isobus::tecu::IA_GBSD" x="-5213.33" y="453.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_GBSD" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="1400" y="453.33">
			<Parameter Name="u16ObjId" Value="NumberVariable_Ground_based_machine_speed"/>
		</FB>
		<FB Name="IA_WBSD" Type="isobus::tecu::IA_WBSD" x="-5200" y="1900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_WBSD" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="1400" y="1900">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_speed"/>
		</FB>
		<FB Name="CONV_GBSD" Type="adapter::conversion::unidirectional::AUI_TO_AUDI" x="-500" y="453.33">
		</FB>
		<FB Name="CONV_WBSD" Type="adapter::conversion::unidirectional::AUI_TO_AUDI" x="-500" y="1900">
		</FB>
		<EventConnections>
			<Connection Source="IA_GBSD.INITO" Destination="Q_NumericValue_GBSD.INIT" dx1="500"/>
			<Connection Source="IA_WBSD.INITO" Destination="Q_NumericValue_WBSD.INIT" dx1="500"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="IA_GBSD.SPEED" Destination="CONV_GBSD.AUI_IN" dx1="200"/>
			<Connection Source="CONV_GBSD.AUDI_OUT" Destination="Q_NumericValue_GBSD.u32NewValue" dx1="200"/>
			<Connection Source="IA_WBSD.SPEED" Destination="CONV_WBSD.AUI_IN" dx1="200"/>
			<Connection Source="CONV_WBSD.AUDI_OUT" Destination="Q_NumericValue_WBSD.u32NewValue" dx1="200"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
