<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012d_AR" Comment="Numeric Value Input PHYS und Speichern NVS (AR Adapter, plain)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-24" Remarks="AR adapter variant of Uebung_012d, plain without subapp">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I1_STORE"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::InputNumber_I3"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::OutputNumber_N3"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="InputNumber_I3" Type="isobus::UT::io::NumericValue::NumericValue_PHYSA" x="-4800" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="stObj" Value="InputNumber_I3"/>
		</FB>
		<FB Name="NVS_AR" Type="logiBUS::storage::esp32_nvs::NVS_AR" x="-1000" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="REAL#0.0"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue_PHYSA" x="1700" y="800">
			<Parameter Name="stObj" Value="OutputNumber_N3"/>
		</FB>
		<AdapterConnections>
			<Connection Source="InputNumber_I3.rPhys" Destination="NVS_AR.AR_IN" dx1="1660"/>
			<Connection Source="NVS_AR.AR_OUT" Destination="Q_NumericValue.rPhys"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
