<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_082_AX" Comment="Beispiel für E_CTUD, mit Plug and Socket">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-09" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="6700" y="-1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-4000" y="-1600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_CTUD" Type="iec61499::events::E_CTUD" x="-2000" y="-500">
			<Parameter Name="PV" Value="UINT#5"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-4000" y="-500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I3" Type="logiBUS::io::DI::logiBUS_IE" x="-4000" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I4" Type="logiBUS::io::DI::logiBUS_IE" x="-4000" y="1700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="6700" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="AX_BOOL_TO_X_1" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="4700" y="-1500">
		</FB>
		<FB Name="AX_BOOL_TO_X_2" Type="adapter::conversion::unidirectional::AX_BOOL_TO_X" x="4700" y="600">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_CTUD.CU" dx1="413.33"/>
			<Connection Source="E_CTUD.CO" Destination="AX_BOOL_TO_X_1.REQ"/>
			<Connection Source="E_CTUD.LDO" Destination="AX_BOOL_TO_X_1.REQ" dx1="453.33"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_CTUD.CD"/>
			<Connection Source="E_CTUD.RO" Destination="AX_BOOL_TO_X_1.REQ" dx1="453.33"/>
			<Connection Source="DigitalInput_CLK_I3.IND" Destination="E_CTUD.R" dx1="260"/>
			<Connection Source="DigitalInput_CLK_I4.IND" Destination="E_CTUD.LD" dx1="400"/>
			<Connection Source="E_CTUD.LDO" Destination="AX_BOOL_TO_X_2.REQ" dx1="453.33"/>
			<Connection Source="E_CTUD.CO" Destination="AX_BOOL_TO_X_2.REQ" dx1="453.33"/>
			<Connection Source="E_CTUD.RO" Destination="AX_BOOL_TO_X_2.REQ" dx1="453.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTUD.QU" Destination="AX_BOOL_TO_X_1.OUT" dx1="246.67"/>
			<Connection Source="E_CTUD.QD" Destination="AX_BOOL_TO_X_2.OUT" dx1="260"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="AX_BOOL_TO_X_1.AX_OUT" Destination="DigitalOutput_Q1.OUT" dx1="900"/>
			<Connection Source="AX_BOOL_TO_X_2.AX_OUT" Destination="DigitalOutput_Q2.OUT" dx1="900"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
