<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_001c3_AX" Comment="DigitalInput_I1 auf DigitalOutput_Q1 --&gt; Eingang abfragen bei Boot.">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-09" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-4500" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="AX_NOOP" Type="adapter::booleanOperators::AX_NOOP" x="-1600" y="-700">
		</FB>
		<Comment Comment="ohne die Linie INITO-&gt;REQ ist der Ausgang Q1 beim Start FALSE. mit der Linie ist er TRUE. &#10;" x="-4800" y="100" width="2200" height="500"/>
		<Comment Comment="In Adapter-Architektur entspricht der doppelten Negierung (NOT an NOT) der Baustein AX_NOOP." x="-2000" y="0" width="1500" height="500"/>
		<EventConnections>
			<Connection Source="DigitalInput_I1.INITO" Destination="DigitalInput_I1.REQ" dx1="80" dx2="80" dy="46.67"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_NOOP.IN" dx1="953.33"/>
			<Connection Source="AX_NOOP.OUT" Destination="DigitalOutput_Q1.OUT" dx1="673.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
