<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012l_AIS" Comment="String Input und Speichern NVS (AIS Adapter, plain)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-24" Remarks="AIS adapter variant of Uebung_012l, plain without subapp">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_S1_STORE"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::InputString_S1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="StringValue_AIS" Type="isobus::UT::io::StringValue::StringValue_AIS" x="-4800" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputString_S1"/>
		</FB>
		<FB Name="NVS_AIS" Type="logiBUS::storage::esp32_nvs::NVS_AIS" x="-1200" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="KEY" Value="KEY_S1_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="STRING#'Test'"/>
		</FB>
		<FB Name="Q_StringValue_AIS" Type="isobus::UT::Q::Q_StringValue_AIS" x="1700" y="900">
			<Parameter Name="u16ObjId" Value="InputString_S1"/>
		</FB>
		<AdapterConnections>
			<Connection Source="StringValue_AIS.IN" Destination="NVS_AIS.AIS_IN" dx1="1480"/>
			<Connection Source="NVS_AIS.AIS_OUT" Destination="Q_StringValue_AIS.pau8String" dx1="793.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>