<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_011a_AUDI" Comment="Numeric Value Output und BUTTON_PRESS_REPEAT_DONE">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-14">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_PRESS_REPEAT_DONE"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="logiBUS_IBA" Type="logiBUS::io::DI::logiBUS_IBA" x="-3700" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_PRESS_REPEAT_DONE"/>
		</FB>
		<FB Name="AB_TO_AUDI" Type="adapter::conversion::unidirectional::AB_TO_AUDI" x="-1600" y="1300">
		</FB>
		<FB Name="Q_NumericValue_AUDI" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="600" y="900">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<AdapterConnections>
			<Connection Source="logiBUS_IBA.IN" Destination="AB_TO_AUDI.AB_IN" dx1="453.33"/>
			<Connection Source="AB_TO_AUDI.AUDI_OUT" Destination="Q_NumericValue_AUDI.u32NewValue" dx1="840"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
