<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_009_AX" Comment="Ticker">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="2100" y="-1600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="E_CYCLE" Type="iec61499::events::E_CYCLE" x="-2500" y="-700">
			<Parameter Name="DT" Value="T#1s"/>
		</FB>
		<FB Name="E_SWITCH" Type="adapter::events::unidirectional::AX_E_SWITCH" x="-1600" y="-700">
		</FB>
		<FB Name="E_SR" Type="adapter::events::unidirectional::AX_SR" x="-700" y="-700">
		</FB>
		<FB Name="E_PERMIT" Type="adapter::events::unidirectional::AX_PERMIT" x="2000" y="-200">
		</FB>
		<FB Name="E_CTUD_UDINT" Type="adapter::events::unidirectional::AUDI_CTUD_UDINT" x="3500" y="200">
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="6100" y="400">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<FB Name="INIT" Type="iec61131::booleanOperators::INIT" x="-3600" y="-1400">
		</FB>
		<FB Name="SPLIT_1" Type="adapter::events::unidirectional::AX_SPLIT_3" x="400" y="-500">
		</FB>
		<EventConnections>
			<Connection Source="E_CYCLE.EO" Destination="E_SWITCH.EI"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_SR.S"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_SR.R"/>
			<Connection Source="E_PERMIT.EO" Destination="E_CTUD_UDINT.CU" dx1="246.67"/>
			<Connection Source="INIT.INITO" Destination="INIT.REQ" dx1="80" dx2="80" dy="53.33"/>
			<Connection Source="INIT.CNF" Destination="E_CYCLE.START" dx1="266.67"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="SPLIT_1.OUT1" Destination="DigitalOutput_Q1.OUT" dx1="426.67"/>
			<Connection Source="E_SR.Q" Destination="SPLIT_1.IN" dx1="440"/>
			<Connection Source="SPLIT_1.OUT3" Destination="E_SWITCH.G" dx1="80" dx2="80" dy="160"/>
			<Connection Source="SPLIT_1.OUT2" Destination="E_PERMIT.PERMIT" dx1="573.33"/>
			<Connection Source="E_CTUD_UDINT.CV" Destination="Q_NumericValue.u32NewValue" dx1="806.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
