<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_040_AX" Comment="Lauflicht 8 Event gesteuert">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q5"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q6"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q7"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q8"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="-2400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="-1333.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="-266.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q3"/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-16600" y="-4500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I4" Type="logiBUS::io::DI::logiBUS_IE" x="-17126.67" y="826.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalOutput_Q5" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="1866.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q5"/>
		</FB>
		<FB Name="DigitalOutput_Q6" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="2933.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q6"/>
		</FB>
		<FB Name="DigitalOutput_Q7" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="4000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q7"/>
		</FB>
		<FB Name="DigitalOutput_Q8" Type="logiBUS::io::DQ::logiBUS_QXA" x="-6666.67" y="5066.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q8"/>
		</FB>
		<FB Name="Q_NumericValue_AUDI" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="-2666.67" y="-2000">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<FB Name="AS_TO_AUDI" Type="adapter::conversion::unidirectional::AS_TO_AUDI" x="-4906.67" y="-1820">
		</FB>
		<FB Name="loop" Type="logiBUS::utils::sequence::event::sequence_E_08_loop_AX" x="-9613.33" y="-600">
		</FB>
		<FB Name="E_CTU_0" Type="adapter::events::unidirectional::AUI_CTU" x="-15000" y="-3466.67">
		</FB>
		<FB Name="F_SUB_0" Type="adapter::iec61131::arithmetic::AUI_SUB_2" x="-13500" y="-3466.67">
		</FB>
		<FB Name="E_DEMUX_0" Type="adapter::events::unidirectional::AUI_DEMUX_4" x="-12000" y="-3466.67">
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-16600" y="-2373.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_CTU_1" Type="adapter::events::unidirectional::AUI_CTU" x="-15000" y="-1333.33">
		</FB>
		<FB Name="F_SUB_1" Type="adapter::iec61131::arithmetic::AUI_SUB_2" x="-13500" y="-1333.33">
		</FB>
		<FB Name="E_DEMUX_1" Type="adapter::events::unidirectional::AUI_DEMUX_4" x="-12000" y="-1333.33">
		</FB>
		<FB Name="DigitalInput_CLK_I3" Type="logiBUS::io::DI::logiBUS_IE" x="-16600" y="-1300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="initval_1" Type="adapter::types::unidirectional::AUI::initval::initval_AUI" x="-15000" y="-2500">
			<Parameter Name="INIT_VAL" Value="1"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I4.IND" Destination="loop.RESET" dx1="3000"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="loop.START_S1" dx1="5773.33"/>
			<Connection Source="E_DEMUX_0.EO1" Destination="loop.S1_S2" dx1="986.67"/>
			<Connection Source="E_DEMUX_0.EO2" Destination="loop.S2_S3" dx1="953.33"/>
			<Connection Source="E_DEMUX_0.EO3" Destination="loop.S3_S4" dx1="920"/>
			<Connection Source="E_DEMUX_0.EO4" Destination="loop.S4_S5" dx1="886.67"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_CTU_0.CU" dx1="186.67"/>
			<Connection Source="DigitalInput_CLK_I3.IND" Destination="E_CTU_1.CU" dx1="253.33"/>
			<Connection Source="E_DEMUX_1.EO4" Destination="loop.S8_S1" dx1="753.33"/>
			<Connection Source="E_DEMUX_1.EO3" Destination="loop.S7_S8" dx1="786.67"/>
			<Connection Source="E_DEMUX_1.EO2" Destination="loop.S6_S7" dx1="820"/>
			<Connection Source="E_DEMUX_1.EO1" Destination="loop.S5_S6" dx1="853.33"/>
			<Connection Source="DigitalInput_CLK_I4.IND" Destination="E_CTU_1.R" dx1="1000"/>
			<Connection Source="DigitalInput_CLK_I4.IND" Destination="E_CTU_0.R" dx1="1306.67"/>
			<Connection Source="E_DEMUX_0.EO4" Destination="E_CTU_0.R" dx1="66.67" dx2="193.33" dy="406.67"/>
			<Connection Source="E_DEMUX_1.EO4" Destination="E_CTU_1.R" dx1="66.67" dx2="66.67" dy="266.67"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="loop.STATE_NR" Destination="AS_TO_AUDI.AS_IN" dx1="340"/>
			<Connection Source="AS_TO_AUDI.AUDI_OUT" Destination="Q_NumericValue_AUDI.u32NewValue" dx1="893.33"/>
			<Connection Source="loop.DO_S1" Destination="DigitalOutput_Q1.OUT" dx1="693.33"/>
			<Connection Source="loop.DO_S2" Destination="DigitalOutput_Q2.OUT" dx1="793.33"/>
			<Connection Source="loop.DO_S3" Destination="DigitalOutput_Q3.OUT" dx1="826.67"/>
			<Connection Source="loop.DO_S4" Destination="DigitalOutput_Q4.OUT" dx1="660"/>
			<Connection Source="loop.DO_S5" Destination="DigitalOutput_Q5.OUT" dx1="593.33"/>
			<Connection Source="loop.DO_S6" Destination="DigitalOutput_Q6.OUT" dx1="526.67"/>
			<Connection Source="loop.DO_S7" Destination="DigitalOutput_Q7.OUT" dx1="460"/>
			<Connection Source="loop.DO_S8" Destination="DigitalOutput_Q8.OUT" dx1="393.33"/>
			<Connection Source="E_CTU_0.CV" Destination="F_SUB_0.IN1" dx1="200"/>
			<Connection Source="initval_1.OUT" Destination="F_SUB_0.IN2" dx1="200"/>
			<Connection Source="F_SUB_0.OUT" Destination="E_DEMUX_0.K" dx1="200"/>
			<Connection Source="E_CTU_1.CV" Destination="F_SUB_1.IN1" dx1="200"/>
			<Connection Source="initval_1.OUT" Destination="F_SUB_1.IN2" dx1="200"/>
			<Connection Source="F_SUB_1.OUT" Destination="E_DEMUX_1.K" dx1="200"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
