<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_023_AX" Comment="Spiegelabfolge (3) - AX Variante">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-20" Remarks="AX Variante"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F2"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F3"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F7"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F8"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F9"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-2300" y="-500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="SoftKey_UP_F1" Type="isobus::UT::io::Softkey::Softkey_IXA" x="-7600" y="-500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
		</FB>
		<FB Name="AX_FB_SR_Ausfahren_Cyl_1" Type="adapter::iec61131::bistableElements::AX_FB_SR" x="-4300" y="-300"/>
		<FB Name="SoftKey_F2_DOWN" Type="isobus::UT::io::Softkey::Softkey_IXA" x="-7700" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F2"/>
		</FB>
		<Comment Comment="START-Knopf Ausfahren" x="-9500" y="-300" width="1373.33" height="366.67"/>
		<Comment Comment="Endlage Ausfahren_Cyl_1 &#10;" x="-9900" y="1000" width="1373.33" height="366.67"/>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="-2300" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="AX_FB_SR_Ausfahren_Cyl_2" Type="adapter::iec61131::bistableElements::AX_FB_SR" x="-4133.33" y="1366.67"/>
		<Comment Comment="Endlage Ausfahren_Cyl_2 &#10;" x="-9700" y="2500" width="1373.33" height="366.67"/>
		<FB Name="SoftKey_F3_DOWN" Type="isobus::UT::io::Softkey::Softkey_IXA" x="-7600" y="2333.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F3"/>
		</FB>
		<Comment Comment="Ausfahren_Cyl_1" x="-1100" y="-200" width="1373.33" height="366.67"/>
		<Comment Comment="Ausfahren_Cyl_2" x="-1200" y="1200" width="1373.33" height="366.67"/>
		<FB Name="SoftKey_F9_DOWN" Type="isobus::UT::io::Softkey::Softkey_IXA" x="-7600" y="6586.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F9"/>
		</FB>
		<FB Name="AX_FB_SR_Einfahren_Cyl_2" Type="adapter::iec61131::bistableElements::AX_FB_SR" x="-4300" y="3953.33"/>
		<FB Name="DigitalOutput_Q3" Type="logiBUS::io::DQ::logiBUS_QXA" x="-1800" y="3700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q3"/>
		</FB>
		<Comment Comment="START-Knopf Einfahren" x="-10100" y="3900" width="1373.33" height="366.67"/>
		<FB Name="DigitalOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QXA" x="-1500" y="5200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="SoftKey_F7_UP" Type="isobus::UT::io::Softkey::Softkey_IXA" x="-8000" y="3500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F7"/>
		</FB>
		<FB Name="AX_FB_SR_Einfahren_Cyl_1" Type="adapter::iec61131::bistableElements::AX_FB_SR" x="-4133.33" y="5620"/>
		<Comment Comment="Endlage Einfahren_Cyl_1  &#10;" x="-9800" y="6800" width="1373.33" height="366.67"/>
		<FB Name="SoftKey_F8_DOWN" Type="isobus::UT::io::Softkey::Softkey_IXA" x="-7700" y="5000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F8"/>
		</FB>
		<Comment Comment="Einfahren_Cyl_2" x="-200" y="4000" width="1373.33" height="366.67"/>
		<Comment Comment="Endlage Einfahren_Cyl_2  &#10;" x="-10100" y="5400" width="1373.33" height="366.67"/>
		<Comment Comment="Einfahren_Cyl_1 &#10;" x="-500" y="5600" width="1373.33" height="366.67"/>
		<FB Name="AX_SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-6400" y="1000"/>
		<FB Name="AX_SPLIT_3" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-6400" y="5400"/>
		<AdapterConnections>
			<Connection Source="SoftKey_UP_F1.IN" Destination="AX_FB_SR_Ausfahren_Cyl_1.SET1" dx1="1246.67"/>
			<Connection Source="AX_SPLIT_2.OUT1" Destination="AX_FB_SR_Ausfahren_Cyl_1.RESET" dx1="1246.67"/>
			<Connection Source="AX_FB_SR_Ausfahren_Cyl_1.Q1" Destination="DigitalOutput_Q1.OUT" dx1="760"/>
			<Connection Source="AX_FB_SR_Ausfahren_Cyl_2.Q1" Destination="DigitalOutput_Q2.OUT" dx1="460"/>
			<Connection Source="AX_SPLIT_2.OUT2" Destination="AX_FB_SR_Ausfahren_Cyl_2.SET1" dx1="1246.67"/>
			<Connection Source="SoftKey_F3_DOWN.IN" Destination="AX_FB_SR_Ausfahren_Cyl_2.RESET" dx1="1246.67"/>
			<Connection Source="AX_FB_SR_Einfahren_Cyl_2.Q1" Destination="DigitalOutput_Q3.OUT" dx1="760"/>
			<Connection Source="AX_SPLIT_3.OUT2" Destination="AX_FB_SR_Einfahren_Cyl_1.SET1" dx1="1246.67"/>
			<Connection Source="AX_FB_SR_Einfahren_Cyl_1.Q1" Destination="DigitalOutput_Q4.OUT" dx1="660"/>
			<Connection Source="SoftKey_F9_DOWN.IN" Destination="AX_FB_SR_Einfahren_Cyl_1.RESET" dx1="1246.67"/>
			<Connection Source="AX_SPLIT_3.OUT1" Destination="AX_FB_SR_Einfahren_Cyl_2.RESET" dx1="1246.67"/>
			<Connection Source="SoftKey_F7_UP.IN" Destination="AX_FB_SR_Einfahren_Cyl_2.SET1" dx1="1246.67"/>
			<Connection Source="SoftKey_F2_DOWN.IN" Destination="AX_SPLIT_2.IN" dx1="246.67"/>
			<Connection Source="SoftKey_F8_DOWN.IN" Destination="AX_SPLIT_3.IN" dx1="146.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
