<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_070c_AUI" Comment="WBSD auf UT ausgeben (Adapter Version)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-06-01" Remarks="WBSD mit Compound Scaling (Adapter Version)">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::TECU::DefaultPool_TECU_Numeric::NumberVariable_Wheel_based_machine_speed"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="IA_WBSD" Type="isobus::tecu::IA_WBSD" x="-1200" y="900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="CONV_AUI_AUDI" Type="adapter::conversion::unidirectional::AUI_TO_AUDI" x="300" y="1300">
		</FB>
		<FB Name="FIELDBUS_UDINT_TO_SIGNAL_SCALED" Type="logiBUS::signalprocessing::fieldbus::AUDI_FIELDBUS_UDINT_TO_SIGNAL_SCALED" x="1100" y="1200">
			<Parameter Name="SCALE" Value="LREAL#0.001"/>
			<Parameter Name="OFFSET" Value="DINT#0"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue_PHYSA_LREAL" x="3200" y="1400">
			<Parameter Name="stObj" Value="NumberVariable_Wheel_based_machine_speed"/>
		</FB>
		<EventConnections>
			<Connection Source="IA_WBSD.INITO" Destination="Q_NumericValue.INIT" dx1="66.67"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="IA_WBSD.SPEED" Destination="CONV_AUI_AUDI.AUI_IN" dx1="66.67"/>
			<Connection Source="CONV_AUI_AUDI.AUDI_OUT" Destination="FIELDBUS_UDINT_TO_SIGNAL_SCALED.IN" dx1="66.67"/>
			<Connection Source="FIELDBUS_UDINT_TO_SIGNAL_SCALED.OUT" Destination="Q_NumericValue.lrPhys" dx1="66.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
