<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_226_AX" Comment="Split-Bargraph: Sollwert-Eingabe treibt zwei nebeneinanderliegende Bargraphen als vorzeichenbehafteten Ausschlag">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-05" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::Dreieck::DefaultPool_Dreieck_BargraphSplit::Bargraph_Split_BargraphSplit"/>
		<Import declaration="Uebungen::const::UT::Dreieck::DefaultPool_Dreieck_Numeric::InputNumber_Sollwert_N"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Sollwert_N" Type="isobus::UT::io::NumericValue::NumericValue_PHYS" x="-6400" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="stObj" Value="InputNumber_Sollwert_N"/>
		</FB>
		<FB Name="SplitBar" Type="isobus::UT::Q::BargraphSplitFS" x="-2600" y="400">
			<Parameter Name="stObj" Value="Bargraph_Split_BargraphSplit"/>
		</FB>
		<EventConnections>
			<Connection Source="Sollwert_N.IND" Destination="SplitBar.REQ" dx1="633.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Sollwert_N.rPhys" Destination="SplitBar.rValue" dx1="1000"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
