<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_034b_AX" Comment="LONG_PRESS_HOLD-Eingang auf PWM Ausgang (Adapter Version) mit Terminal-Ausgabe">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-04-21" Remarks="Added terminal output for counter value">
	</VersionInfo>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_LONG_PRESS_HOLD"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="PWMOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QDA_PWM" x="6600" y="1300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="IE_SPEED_UP" Type="logiBUS::io::DI::logiBUS_IE" x="-2000" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_LONG_PRESS_HOLD"/>
		</FB>
		<FB Name="IE_SPEED_DOWN" Type="logiBUS::io::DI::logiBUS_IE" x="-2000" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_LONG_PRESS_HOLD"/>
		</FB>
		<FB Name="IE_STOP" Type="logiBUS::io::DI::logiBUS_IE" x="-2000" y="1800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="IE_FULL" Type="logiBUS::io::DI::logiBUS_IE" x="-2000" y="3000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="AUDI_CTUD" Type="adapter::events::unidirectional::AUDI_CTUD_UDINT" x="1000" y="1400">
		</FB>
		<FB Name="Q_NumericValue_AUDI" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="6600" y="2700">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<FB Name="AUDI_SPLIT_2" Type="adapter::events::unidirectional::AUDI_SPLIT_2" x="2900" y="2100">
		</FB>
		<FB Name="AUDI_TO_AD" Type="adapter::conversion::unidirectional::AUDI_TO_AD" x="4300" y="1800">
		</FB>
		<EventConnections>
			<Connection Source="IE_SPEED_DOWN.IND" Destination="AUDI_CTUD.CD" dx1="100"/>
			<Connection Source="IE_STOP.IND" Destination="AUDI_CTUD.R" dx1="100"/>
			<Connection Source="IE_FULL.IND" Destination="AUDI_CTUD.LD" dx1="753.33"/>
			<Connection Source="IE_SPEED_UP.IND" Destination="AUDI_CTUD.CU" dx1="1053.33"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="AUDI_CTUD.CV" Destination="AUDI_SPLIT_2.IN" dx1="453.33"/>
			<Connection Source="AUDI_SPLIT_2.OUT2" Destination="Q_NumericValue_AUDI.u32NewValue" dx1="1426.67"/>
			<Connection Source="AUDI_SPLIT_2.OUT1" Destination="AUDI_TO_AD.AUDI_IN" dx1="273.33"/>
			<Connection Source="AUDI_TO_AD.AD_OUT" Destination="PWMOutput_Q1.OUT" dx1="740"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
