<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_002a_AX" Comment="DigitalInput_I1/_I2 mit AND auf DigitalOutput_Q1, mit Plug and Socket">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-2100" y="400">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="800" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="AX_AND_2" Type="adapter::booleanOperators::AX_AND_2" x="-986.67" y="1220"/>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-2100" y="1513.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="QO" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<AdapterConnections>
			<Connection Source="AX_AND_2.OUT" Destination="DigitalOutput_Q1.OUT" dx1="366.67"/>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_AND_2.IN1" dx1="66.67"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AX_AND_2.IN2" dx1="66.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
