<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_000_AX" Comment="Einfache Addition">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-01-16" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="ADD_2" Type="adapter::iec61131::arithmetic::AI_ADD_2" x="-1500" y="3400">
		</FB>
		<FB Name="initval_AI" Type="adapter::types::unidirectional::AI::initval::initval_AI" x="-2800" y="3000">
			<Parameter Name="INIT_VAL" Value="INT#5"/>
		</FB>
		<FB Name="initval_AI_1" Type="adapter::types::unidirectional::AI::initval::initval_AI" x="-2800" y="3600">
			<Parameter Name="INIT_VAL" Value="INT#3"/>
		</FB>
		<AdapterConnections>
			<Connection Source="initval_AI.OUT" Destination="ADD_2.IN1" dx1="273.33"/>
			<Connection Source="initval_AI_1.OUT" Destination="ADD_2.IN2" dx1="273.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
