<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_202_AX" Comment="Interlock: ILOCK_BLOCK_PROTECT_AX (Verriegelung mit Schutzzeit via Adapter)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-19" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-4000" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-4000" y="900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="ILOCK_AX" Type="logiBUS::signalprocessing::interlock::ILOCK_BLOCK_PROTECT_AX" x="-2000" y="400">
			<Parameter Name="DT_PROTECT" Value="T#1s"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="1100" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="1100" y="100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="E_TimeOut" Type="iec61499::events::E_TimeOut" x="-100" y="1600">
		</FB>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="ILOCK_AX.UP_IN" dx1="200"/>
			<Connection Source="DigitalInput_I2.IN" Destination="ILOCK_AX.DOWN_IN" dx1="200"/>
			<Connection Source="ILOCK_AX.UP_OUT" Destination="DigitalOutput_Q1.OUT" dx1="200"/>
			<Connection Source="ILOCK_AX.DOWN_OUT" Destination="DigitalOutput_Q2.OUT" dx1="200"/>
			<Connection Source="ILOCK_AX.timeOut" Destination="E_TimeOut.TimeOutSocket" dx1="193.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
