<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_006a2b_AX" Comment="2x SR und T-Flip-Flop mit IXA">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-01-13" Remarks="initial API and implementation and/or initial documentation"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-700" y="-1200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-4600" y="-900">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-4600" y="100">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="AX_T_FF_SR_Q1" Type="adapter::bistableElements::AX_FB_RS_T_FF" x="-2800" y="-700"/>
		<FB Name="DigitalInput_CLK_I3" Type="logiBUS::io::DI::logiBUS_IXA" x="-5500" y="-2000">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<FB Name="AX_T_FF_SR_Q2" Type="adapter::bistableElements::AX_FB_RS_T_FF" x="-2900" y="300"/>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="-700" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<Comment Comment="Hausmeister-Aus (alles Aus mit einem Druck)" x="-4500" y="-2100" width="1000" height="400"/>
		<FB Name="AX_SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-4100" y="-1600"/>
		<AdapterConnections>
			<Connection Source="AX_T_FF_SR_Q1.Q1" Destination="DigitalOutput_Q1.OUT" dx1="673.33"/>
			<Connection Source="AX_T_FF_SR_Q2.Q1" Destination="DigitalOutput_Q2.OUT" dx1="720"/>
			<Connection Source="DigitalInput_CLK_I1.IN" Destination="AX_T_FF_SR_Q1.CLK" dx1="473.33"/>
			<Connection Source="DigitalInput_CLK_I2.IN" Destination="AX_T_FF_SR_Q2.CLK" dx1="426.67"/>
			<Connection Source="DigitalInput_CLK_I3.IN" Destination="AX_SPLIT_2.IN" dx1="173.33"/>
			<Connection Source="AX_SPLIT_2.OUT2" Destination="AX_T_FF_SR_Q2.RESET1" dx1="220"/>
			<Connection Source="AX_SPLIT_2.OUT1" Destination="AX_T_FF_SR_Q1.RESET1" dx1="273.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
