<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_211b_ALR" Comment="Standard IEC 61131-3 ADI_FB_CTU (Adapter Version, Vorwärtszähler, DINT) mit Terminal-Ausgabe (PHYS)">
	<Identification Standard="61131-3" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.2" Author="Franz Höpfinger" Date="2026-05-13" Remarks="Added ADI_DINT_TO_DI init block connected to PV"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.1" Author="Franz Höpfinger" Date="2026-04-21" Remarks="Added terminal output for counter value (PHYS)"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-21" Remarks="initial API and implementation (Adapter version)"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool_Numeric::OutputNumber_N3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="ADI_FB_CTU" Type="adapter::iec61131::counters::ADI_FB_CTU" x="0" y="0"/>
		<FB Name="ADI_DINT_TO_DI" Type="adapter::conversion::unidirectional::ADI_DINT_TO_DI" x="-1400" y="800">
			<Parameter Name="OUT" Value="DINT#5"/>
		</FB>
		<FB Name="Input_CU" Type="logiBUS::io::DI::logiBUS_IXA" x="-2500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="Input_R" Type="logiBUS::io::DI::logiBUS_IXA" x="-3100" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="Output_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="2500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="ADI_TO_ALR" Type="adapter::conversion::unidirectional::ADI_TO_ALR" x="1100" y="1400"/>
		<FB Name="Q_NumericValue_1" Type="isobus::UT::Q::Q_NumericValue_PHYSA_LREAL" x="2500" y="800">
			<Parameter Name="stObj" Value="OutputNumber_N3"/>
		</FB>
		<Comment Comment="hier sind negative Werte möglich ! " x="800" y="1800" width="1200" height="300"/>
		<Comment Comment="hier gegebenenfalls einen AX_D_FF einbauen, damit die Events reduziert werden. " x="1000" y="-700" width="1000" height="500"/>
		<EventConnections>
			<Connection Source="Input_R.INITO" Destination="ADI_DINT_TO_DI.REQ"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="Input_CU.IN" Destination="ADI_FB_CTU.CU" dx1="400"/>
			<Connection Source="Input_R.IN" Destination="ADI_FB_CTU.R" dx1="200"/>
			<Connection Source="ADI_FB_CTU.Q" Destination="Output_Q1.OUT" dx1="200"/>
			<Connection Source="ADI_FB_CTU.CV" Destination="ADI_TO_ALR.ADI_IN" dx1="173.33"/>
			<Connection Source="ADI_TO_ALR.ALR_OUT" Destination="Q_NumericValue_1.lrPhys" dx1="293.33"/>
			<Connection Source="ADI_DINT_TO_DI.ADI_OUT" Destination="ADI_FB_CTU.PV" dx1="226.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
