<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_089_AX" Comment="Beispiel für E_R_TRIG, mit Plug and Socket">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-09-10" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="2600" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-5500" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="AX_OR_2" Type="adapter::booleanOperators::AX_OR_2" x="-3800" y="-200">
		</FB>
		<FB Name="SPLIT_1" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-2900" y="-200">
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-5500" y="100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="AX_R_TRIG" Type="adapter::events::unidirectional::AX_R_TRIG" x="-1200" y="-300">
		</FB>
		<FB Name="AX_T_FF_Q1" Type="adapter::events::unidirectional::AX_T_FF" x="0" y="-300">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="2600" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="AX_T_FF_1_Q2" Type="adapter::events::unidirectional::AX_T_FF" x="-100" y="400">
		</FB>
		<FB Name="AX_E_SWITCH" Type="adapter::events::unidirectional::AX_E_SWITCH" x="-1200" y="400">
		</FB>
		<Comment Comment="R_TRIG schaltet nur wenn wirklich steigende Flanke" x="-1300" y="-700" width="1200" height="400"/>
		<Comment Comment="E_SWITCH schaltet auch, wenn anderweitig ein Event kommt. " x="-1200" y="1400" width="1200" height="400"/>
		<EventConnections>
			<Connection Source="AX_R_TRIG.EO" Destination="AX_T_FF_Q1.CLK"/>
			<Connection Source="AX_E_SWITCH.EO1" Destination="AX_T_FF_1_Q2.CLK" dx1="200"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_OR_2.IN1" dx1="646.67"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AX_OR_2.IN2" dx1="646.67"/>
			<Connection Source="AX_T_FF_Q1.Q" Destination="DigitalOutput_Q1.OUT" dx1="1840"/>
			<Connection Source="AX_T_FF_1_Q2.Q" Destination="DigitalOutput_Q2.OUT" dx1="1840"/>
			<Connection Source="AX_OR_2.OUT" Destination="SPLIT_1.IN"/>
			<Connection Source="SPLIT_1.OUT1" Destination="AX_R_TRIG.QI" dx1="473.33"/>
			<Connection Source="SPLIT_1.OUT2" Destination="AX_E_SWITCH.G" dx1="473.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
