<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_003e_AX" Comment="DigitalInput_I1-4 auf DigitalOutput_Q1-4 - flach mit Adapter mit Bypass (Druckumlaufventil)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23" Remarks="initial API and implementation and/or initial documentation"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q8"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-2000" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-5000" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="-2000" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-5000" y="100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="BYPASS_AX_1" Type="logiBUS::signalprocessing::bypass::BYPASS_AX_AX" x="-3400" y="-500"/>
		<FB Name="Bypass_Valve" Type="logiBUS::io::DQ::logiBUS_QXA" x="-2000" y="3000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q8"/>
		</FB>
		<FB Name="BYPASS_AX_2" Type="logiBUS::signalprocessing::bypass::BYPASS_AX_AX" x="-3400" y="500"/>
		<FB Name="DigitalOutput_Q3" Type="logiBUS::io::DQ::logiBUS_QXA" x="-2000" y="900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q3"/>
		</FB>
		<FB Name="DigitalInput_I3" Type="logiBUS::io::DI::logiBUS_IXA" x="-5000" y="1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<FB Name="BYPASS_AX_3" Type="logiBUS::signalprocessing::bypass::BYPASS_AX_AX" x="-3400" y="1500"/>
		<FB Name="DigitalOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QXA" x="-2000" y="1900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="DigitalInput_I4" Type="logiBUS::io::DI::logiBUS_IXA" x="-5000" y="2100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
		</FB>
		<FB Name="BYPASS_AX_4" Type="logiBUS::signalprocessing::bypass::BYPASS_AX_AX" x="-3400" y="2500"/>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="BYPASS_AX_1.IN" dx1="300"/>
			<Connection Source="BYPASS_AX_1.OUT" Destination="DigitalOutput_Q1.OUT" dx1="393.33"/>
			<Connection Source="DigitalInput_I2.IN" Destination="BYPASS_AX_2.IN" dx1="346.67"/>
			<Connection Source="BYPASS_AX_2.OUT" Destination="DigitalOutput_Q2.OUT" dx1="386.67"/>
			<Connection Source="DigitalInput_I3.IN" Destination="BYPASS_AX_3.IN" dx1="346.67"/>
			<Connection Source="BYPASS_AX_3.OUT" Destination="DigitalOutput_Q3.OUT" dx1="386.67"/>
			<Connection Source="DigitalInput_I4.IN" Destination="BYPASS_AX_4.IN" dx1="346.67"/>
			<Connection Source="BYPASS_AX_4.OUT" Destination="DigitalOutput_Q4.OUT" dx1="386.67"/>
			<Connection Source="BYPASS_AX_1.BY_OUT" Destination="BYPASS_AX_2.BY_IN" dx1="80" dx2="80" dy="293.33"/>
			<Connection Source="BYPASS_AX_2.BY_OUT" Destination="BYPASS_AX_3.BY_IN" dx1="80" dx2="80" dy="446.67"/>
			<Connection Source="BYPASS_AX_3.BY_OUT" Destination="BYPASS_AX_4.BY_IN" dx1="80" dx2="80" dy="493.33"/>
			<Connection Source="BYPASS_AX_4.BY_OUT" Destination="Bypass_Valve.OUT" dx1="153.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
