<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012m_AIS" Comment="String Input und Speichern NVS mit Subapp (AIS Adapter)">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0"/>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-24" Remarks="AIS adapter variant of Uebung_012m"/>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I1_STORE"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::InputString_S1"/>
	</CompilerInfo>
	<SubAppInterfaceList/>
	<SubAppNetwork>
		<SubApp Name="Uebung_012m_sub_AIS" Type="MyLib::sys::NVS_IN_AND_STORE_AIS" x="-3200" y="1600">
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="u16ObjId" Value="InputString_S1"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
