<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_011d_AUDI" Comment="Numeric Value Input I1 Durchschleifen auf N3 (Offset/Scale Effekt)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-04-14" Remarks="initial API and implementation and/or initial documentation">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::InputNumber_I1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N3"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="InputNumber_I1" Type="isobus::UT::io::NumericValue::NumericValue_IDA" x="-5000" y="600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="AD_TO_AUDI" Type="adapter::conversion::unidirectional::AD_TO_AUDI" x="-3100" y="1133.33">
		</FB>
		<FB Name="Q_NumericValue_AUDI" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="-1000" y="600">
			<Parameter Name="u16ObjId" Value="OutputNumber_N3"/>
		</FB>
		<Comment Comment=" Beispiel: I1-Eingabe 100000 → N3 zeigt 0.00, Eingabe 50000 → N3 zeigt -500.00." x="-4300" y="1900" width="4000" height="500"/>
		<AdapterConnections>
			<Connection Source="InputNumber_I1.IN" Destination="AD_TO_AUDI.AD_IN"/>
			<Connection Source="AD_TO_AUDI.AUDI_OUT" Destination="Q_NumericValue_AUDI.u32NewValue" dx1="640"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
