<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010a" Comment="SoftKey_F1/_F2 auf DigitalOutput_Q1/_Q2" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-1500" y="-700">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="SoftKey_F1" Type="IX" x="-4500" y="-800">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="SoftKey_F2" Type="IX" x="-4500" y="400">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" x="-1500" y="500">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_F1.IND" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="SoftKey_F2.IND" Destination="DigitalOutput_Q2.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="SoftKey_F1.IN" Destination="DigitalOutput_Q1.OUT" dx1="1200"/>
			<Connection Source="SoftKey_F2.IN" Destination="DigitalOutput_Q2.OUT" dx1="1200"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
