<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_006b" Comment="RS-Flip-Flop mit 2x IE" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="QX" x="-1466.67" y="-933.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I1_CLK" Type="IE" x="-4533.33" y="-933.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="DigitalInput_I2_CLK" Type="IE" x="-4533.33" y="266.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_RS" Type="E_RS" x="-2800" y="-733.33">
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DigitalInput_I1_CLK.INIT" dx1="1113.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I1_CLK.INITO" Destination="DigitalOutput_Q1.INIT"/>
			<Connection Source="INIT" Destination="DigitalInput_I2_CLK.INIT" dx1="1206.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="DigitalInput_I2_CLK.IND" Destination="E_RS.S" dx1="446.67" dx2="446.67" dy="0"/>
			<Connection Source="E_RS.EO" Destination="DigitalOutput_Q1.REQ" dx1="446.67" dx2="446.67" dy="0"/>
			<Connection Source="DigitalInput_I1_CLK.IND" Destination="E_RS.R"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_RS.Q" Destination="DigitalOutput_Q1.OUT" dx1="446.67" dx2="446.67" dy="0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
