<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="tastend" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2024-10-23">
	</VersionInfo>
	<CompilerInfo packageName="FBs::Uebungen::Uebung_103::subapp">
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="OUT" Type="AX"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="IN" Type="AX"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<AdapterConnections>
			<Connection Source="IN" Destination="OUT" dx1="3386.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
