<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="tastend_TON_5s" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2024-10-23">
	</VersionInfo>
	<CompilerInfo packageName="FBs::Uebungen::Uebung_103::subapp">
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="OUT" Type="AX"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="IN" Type="AX"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AX_X_TO_BOOL" Type="AX_X_TO_BOOL" x="-13700" y="-1200">
		</FB>
		<FB Name="AX_BOOL_TO_X" Type="AX_BOOL_TO_X" x="-9906.67" y="-1200">
		</FB>
		<FB Name="E_TON" Type="E_TON" x="-11600" y="-1200">
			<Parameter Name="PT" Value="t#5s"/>
		</FB>
		<EventConnections>
			<Connection Source="AX_X_TO_BOOL.CNF" Destination="E_TON.REQ"/>
			<Connection Source="E_TON.CNF" Destination="AX_BOOL_TO_X.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_TON.Q" Destination="AX_BOOL_TO_X.OUT"/>
			<Connection Source="AX_X_TO_BOOL.IN" Destination="E_TON.IN"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="IN" Destination="AX_X_TO_BOOL.AX_IN" dx1="2833.33"/>
			<Connection Source="AX_BOOL_TO_X.AX_OUT" Destination="OUT" dx1="7540"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
