<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Versuch_400" Comment="Versuch Array Summe">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Versuche">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SUM" Type="logiBUS::utils::dyn_arr::SUM" x="4000" y="1600">
		</FB>
		<FB Name="INIT_ARR_8_BYTE" Type="logiBUS::utils::generate::INIT_ARR_8_INT" x="0" y="2100">
			<Parameter Name="D1" Value="[44, 0, 5, 0, 7, 8, 0, 0]"/>
		</FB>
		<FB Name="GEN_INIT_ARR" Type="logiBUS::utils::generate::GEN_INIT_ARR" x="3900" y="2300">
		</FB>
		<FB Name="GET_AT_INDEX" Type="eclipse4diac::convert::GET_AT_INDEX" x="3700" y="3000">
			<Parameter Name="INDEX" Value="0"/>
		</FB>
		<FB Name="F_MOVE" Type="iec61131::selection::F_MOVE" x="6000" y="3200">
			<Attribute Name="DataType" Value="INT"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT_ARR_8_BYTE.INITO" Destination="SUM.REQ" dx1="380"/>
			<Connection Source="GET_AT_INDEX.CNF" Destination="F_MOVE.REQ" dx1="726.67"/>
			<Connection Source="INIT_ARR_8_BYTE.INITO" Destination="GEN_INIT_ARR.INIT" dx1="1480"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="INIT_ARR_8_BYTE.D1" Destination="SUM.A" dx1="266.67"/>
			<Connection Source="INIT_ARR_8_BYTE.D1" Destination="GEN_INIT_ARR.D1" dx1="806.67"/>
			<Connection Source="INIT_ARR_8_BYTE.D1" Destination="GET_AT_INDEX.IN_ARRAY" dx1="326.67"/>
			<Connection Source="GET_AT_INDEX.OUT" Destination="F_MOVE.IN" dx1="726.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
