"""Surgical fixes for two independent "Offene Punkte" items from
AUSGAENGE_EINGAENGE_POOL_PLAN.md, applied to the CURRENT DefaultPool.jop
(no full regenerate - see the plan's warning after the earlier revert incident):

1. List-row/header OutputText objects (JVS-ID 11010-11392, generated by
   build_diagnostic_pages.py) reference FontAttributes_24x32 (JVS-ID 23006)
   - the HOME menu's large font. Their own text-box Height is 18px, so the
   32px-tall glyphs of 24x32 don't fit. Repointed to FontAttributes_16x16
   (JVS-ID 23004). OutputText JVS-ID 11000 (the actual HOME title, also on
   23006) is deliberately left untouched - range starts at 11010.

2. Rectangle_BarTrack (FillAttributes_BarTrack, JVS-ID 25005, color
   0xAAAAAA/11184810) and Rectangle_BarThumb (FillAttributes_BarThumb,
   JVS-ID 25006, color 0xC0C0C0/12632256) are both mid-grey and barely
   distinguishable on the VT - the scroll thumb needs to visibly stand out
   against its track. Track becomes a light neutral grey matching the
   existing row-background color used elsewhere in the pool
   (0xE6E6E6/15132390), thumb becomes a clearly darker grey
   (0x606060/6316128).
"""
import io
import re

JOP_PATH = r"C:\git\fh\Krauternter\Ventilsteuerung\ISO-DesignerProjects\Workspace\DefaultPool\DefaultPool.jop"

OLD_ROW_FONT = 23006
NEW_ROW_FONT = 23004
ROW_TEXT_ID_MIN = 11010
ROW_TEXT_ID_MAX = 11392

TRACK_FILL_ID = 25005
THUMB_FILL_ID = 25006
NEW_TRACK_COLOR = "15132390"
NEW_THUMB_COLOR = "6316128"


def fix_row_fonts(text):
    pattern = re.compile(
        r'(<Object Class="COutputText"[^>]*JVS-ID="(\d+)">.*?<Objects>\s*<Object JVS-ID=")'
        r'(\d+)("/>\s*</Objects>\s*</Object>)',
        re.DOTALL,
    )

    count = 0

    def repl(m):
        nonlocal count
        oid = int(m.group(2))
        font = int(m.group(3))
        if ROW_TEXT_ID_MIN <= oid <= ROW_TEXT_ID_MAX and font == OLD_ROW_FONT:
            count += 1
            return f"{m.group(1)}{NEW_ROW_FONT}{m.group(4)}"
        return m.group(0)

    text = pattern.sub(repl, text)
    print(f"Repointed {count} row/header OutputText objects to FontAttributes_16x16 ({NEW_ROW_FONT}).")
    return text


def fix_bar_colors(text):
    def fix_fill(text, fill_id, new_color, label):
        block_pat = re.compile(
            r'(<Object Class="CFillStyle" JVS-ID="' + str(fill_id) + r'"[^>]*>.*?</Object>)',
            re.DOTALL,
        )
        m = block_pat.search(text)
        assert m, f"FillStyle {fill_id} not found"
        block = m.group(1)
        new_block = re.sub(
            r'(<Property Name="(?:Back|Fore)Color">\s*<Value>)\d+(</Value>)',
            r"\g<1>" + new_color + r"\g<2>",
            block,
        )
        n = len(re.findall(r'<Property Name="(?:Back|Fore)Color">', block))
        print(f"{label} (FillStyle {fill_id}): updated {n} color properties to {new_color}.")
        return text[: m.start()] + new_block + text[m.end():]

    text = fix_fill(text, TRACK_FILL_ID, NEW_TRACK_COLOR, "Rectangle_BarTrack")
    text = fix_fill(text, THUMB_FILL_ID, NEW_THUMB_COLOR, "Rectangle_BarThumb")
    return text


def main():
    with io.open(JOP_PATH, "r", encoding="utf-8", newline="") as f:
        text = f.read()
    assert "\r\n" in text

    text = fix_row_fonts(text)
    text = fix_bar_colors(text)

    with io.open(JOP_PATH, "w", encoding="utf-8", newline="") as f:
        f.write(text)
    print("Done.")


if __name__ == "__main__":
    main()
