<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Uebung_033" Comment="LED Strip Blinkende LED" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_DI" Type="Hutschienenmoped_XL_8_DI" x="-3273.33" y="-933.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="GLOBAL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="ID_NULL">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I1" Value="'Ventilsteuerung.functions.GREEN.BUTTON'"/>
			<Parameter Name="DigitalInput_I2" Value="'Ventilsteuerung.functions.YELLOW.BUTTON'"/>
			<Parameter Name="DigitalInput_I3" Value="'Ventilsteuerung.functions.RED.BUTTON'"/>
			<Parameter Name="DigitalInput_I4" Value="'Ventilsteuerung.functions.BLUE.BUTTON'"/>
			<Parameter Name="DigitalInput_I5" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I6" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I7" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="DigitalInput_I8" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_YELLOW" Type="Hutschienenmoped_XL_1_LED_strip" x="-3600" y="933.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_YELLOW"/>
			<Parameter Name="LED_5HZ" Value="'Ventilsteuerung.functions.YELLOW.LED'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_GREEN" Type="Hutschienenmoped_XL_1_LED_strip" x="-3600" y="133.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_GREEN"/>
			<Parameter Name="LED_5HZ" Value="'Ventilsteuerung.functions.GREEN.LED'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_RED" Type="Hutschienenmoped_XL_1_LED_strip" x="-3600" y="1733.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_RED"/>
			<Parameter Name="LED_5HZ" Value="'Ventilsteuerung.functions.RED.LED'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
		<FB Name="Hutschienenmoped_XL_1_LED_BLUE" Type="Hutschienenmoped_XL_1_LED_strip" x="-3600" y="2533.33">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u8SAMember" Value="Output_strip">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="u16ObjId" Value="LED_BLUE"/>
			<Parameter Name="LED_5HZ" Value="'Ventilsteuerung.functions.BLUE.LED'"/>
			<Parameter Name="LED_2HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_1HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_05HZ" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="LED_ON" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
		</FB>
	</SubAppNetwork>
</SubAppType>
