<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_033_sub" Comment="LED Strip Blinkende LED" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="LED" Type="QX" x="-1500" y="-700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="BUTTON" Type="IX" x="-4500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="BUTTON.IND" Destination="LED.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="BUTTON.IN" Destination="LED.OUT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
