<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_033_sub" Comment="LED Strip Blinkende LED" >
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="LED" Type="QX" x="-1500" y="-700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="BUTTON" Type="IX" x="-4500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="BUTTON.IND" Destination="LED.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="BUTTON.IN" Destination="LED.OUT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
