<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_033_sub" Comment="LED Strip Blinkende LED" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="LED" Type="QX" x="-1466.67" y="-833.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="BUTTON" Type="IX" x="-4533.33" y="-946.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="BUTTON.INITO" Destination="LED.INIT" dx1="1200"/>
			<Connection Source="BUTTON.IND" Destination="LED.REQ" dx1="1186.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="BUTTON.IN" Destination="LED.OUT" dx1="1186.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
