<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_033" Comment="LED Strip Blinkende LED" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GREEN" Type="Uebung_033_sub" x="-4533.33" y="-946.67">
		</SubApp>
		<SubApp Name="YELLOW" Type="Uebung_033_sub" x="-4533.33" y="-533.33">
		</SubApp>
		<SubApp Name="RED" Type="Uebung_033_sub" x="-4533.33" y="-133.33">
		</SubApp>
		<SubApp Name="BLUE" Type="Uebung_033_sub" x="-4533.33" y="266.67">
		</SubApp>
	</SubAppNetwork>
</SubAppType>
